### ISSUE TITLE
unable to update conda

### ISSUE THREAD

**Issue by randomgambit** [conda/conda#10007]
Hello there!

I have just installed the most recent Anaconda version (win 10 64bits) and I am now unable to update any package.

My `condarc` file contains my proxy settings. This used to work perfectly fine with the previous anaconda version.

```
proxy_servers:
  http: http://myproxy:8080
  https: https://myproxy:8080
```

But running `conda update conda` triggers an error

```
Collecting package metadata (current_repodata.json): failed
 urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None
```

What is the issue here?
Thanks!

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-74)

**Comment by EBenkler** [comment]
Not sure if it will help, but this might be an issue due to the way urllib3 handles the https prefix. For background see [pypa/pip/#9216](https://github.com/pypa/pip/issues/9216), where the solution is to use
`https: http://myproxy:8080` instead of `https: https://myproxy:8080` 

Maybe you also need to add `ssl_verify: False` to your .condarc

See also #9497

Please report back if you found a solution.
