### ISSUE TITLE
Autoclean

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1003]
There should be a config option to enable automatic cleaning of the pkgs directory.

**Comment by ThomasLecocq** [comment]
:+1: my pkgs folder is >4GB (installed Anaconda 1.7 and updated from there... )

**Comment by xgdgsc** [comment]
:+1:

**Comment by faceduck** [comment]
I second autosuggesting conda clean -p :)

**Comment by kalefranz** [comment]
It's rather expensive to scan the package cache and determine which packages are in use and which aren't.  What performance penalty would be an acceptable tradeoff to each and every `create` / `install` / `update` / `remove` operation if we implemented this?  20% increase in time?  10% increase in time?  None?

**Comment by michaelaye** [comment]
Isn't it true that `conda remove/install/create` are unlikely to create a scenario where packages become un-used? I guess `install` changes to `update` if the pkg is already there, but still, I would say one could constrain this to to `update`.

And I would be fine with setting in the conda config that I allow background removal of un-used packages, so that `conda update` says at the end, "Per your config unused packages will now be removed" and the process could do this in the background and return the prompt.

**Comment by douglasrizzo** [comment]
Hi all. I've updated the Python version of my `base` env from 3.7 to 3.8, but I saw that the `anaconda3/lib/python3.7` directory was still there, with 3.7 GB, while I no longer have a Python 3.7 environment under Anaconda. Since there is no autoclean function, is it safe to manually delete it?

**Comment by cassandralsmith** [comment]
Now I have over 13 GB of condo files mostly undeleted updated files.  I have tried conda clean -p that removed 2 GB.  I have tried removing and then reloading anaconda but same issue occurred.  Please advise.  Can't go on forever like this.
thanks,
