### ISSUE TITLE
Uninstalling miniconda3 from chocolatey fails to remove registry key for cmd autorun.

### ISSUE THREAD

**Issue by Todd-Fulton** [conda/conda#10110]
I ran into the issue of cmd always printing a message "The system cannot find the path specified", possibly to std err, when being started, which was causing other commands to fail.

I tracked it down to recently uninstalling miniconda3 installed with chocolatey which didn't remove a registry value for a cmd init script, presumably from conda init
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor\AutoRun="C:\tools\miniconda3\condabin\conda_hook.bat"`
the directory doesn't exist anymore, so every time I ran a command that spawns a cmd instance, it would respond with that message, and (pipenv in my case) would fail.

I had to search for the reverse of what the problem was (how to/not to run a command on cmd start up):
https://stackoverflow.com/questions/17404165/how-to-run-a-command-on-command-prompt-startup-in-windows

fyi, if anyone runs into this issue, just open regedit and empty that value for the registry key. It's basically the cmd equivalent of specifying the location of a .bashrc file, if you try to source a file on bash startup that doesn't exist, I'm sure it would spit up errors too.

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-134)

**Comment by ehatton** [comment]
I have also run into this problem recently . A colleague had recently uninstalled Anaconda following the [official instructions](https://docs.anaconda.com/anaconda/install/uninstall/) but this webpage does not explain anywhere how to reverse the shell initialization.

Due to the lingering registry key throwing an error, several critical processes calling cmd (completely unrelated to conda/python) mysteriously started failing, and it took hours to debug the problem.

I later found out about the command "conda init --reverse" which removes the shell changes without needing to manually edit the registry. It would be good if the uninstallation documentation could updated with details of this command.

Even better, perhaps an uninstaller script or exe could be provided which would remove Anaconda/Miniconda cleanly from the system (including all the Start menu items etc.).
