### ISSUE TITLE
How to set package priorities? 

### ISSUE THREAD

**Issue by jan-janssen** [conda/conda#10127]
I try to update my environment with:
```
~> conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: 


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.8.0              |           12_mkl          10 KB  conda-forge
    libcblas-3.8.0             |           12_mkl          10 KB  conda-forge
    liblapack-3.8.0            |           12_mkl          10 KB  conda-forge
    liblapacke-3.8.0           |           12_mkl          10 KB  conda-forge
    pandas-profiling-2.8.0     |             py_0         172 KB  conda-forge
    phonopy-2.7.1              |   py37h161383b_0         937 KB  conda-forge
    pyiron-0.2.17              |     pyh9f0ad1d_0         294 KB  conda-forge
    visions-0.4.6              |     pyh9f0ad1d_0          41 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.4 MB

The following packages will be UPDATED:

  phonopy                              2.6.0-py37h03ebfcd_1 --> 2.7.1-py37h161383b_0
  visions                                0.4.4-pyh9f0ad1d_0 --> 0.4.6-pyh9f0ad1d_0

The following packages will be DOWNGRADED:

  libblas                                      3.8.0-14_mkl --> 3.8.0-12_mkl
  libcblas                                     3.8.0-14_mkl --> 3.8.0-12_mkl
  liblapack                                    3.8.0-14_mkl --> 3.8.0-12_mkl
  liblapacke                                   3.8.0-14_mkl --> 3.8.0-12_mkl
  pandas-profiling                       2.8.0-pyh9f0ad1d_1 --> 2.8.0-py_0
  pyiron                                0.2.17-pyh9f0ad1d_1 --> 0.2.17-pyh9f0ad1d_0
```
I do not want these updates and it should report no updates necessary. The packages `pandas-profiling` and `pyiron` in their latest version, fix the dependencies to `visions` and `phonopy`: 

- https://github.com/conda-forge/pandas-profiling-feedstock/pull/29
- https://github.com/conda-forge/pyiron-feedstock/pull/31

Still conda prefers to downgrade `pandas-profiling` and `pyiron` to update `visions` and `phonopy` which is not what I want. Should not the the dependent package have the highest priority?

**Comment by chenghlee** [comment]
This "downgrade" is being triggered because the `pandas-profiling=2.8.0=pyh9f0ad1d_1` has a specific dependency requirement for `visions 0.4.4.*`, which is incompatible with your requested upgrade to visions 0.4.6. When you asked conda to upgrade visions, the solver had to find a build of pandas-profiling that was compatible with vision 0.4.6; in this case, `pandas-profiling=2.8.0=py_0` build, which specifies its `visions` requirement as `>=0.4.4`. Similarly, the `pyiron=0.2.17=pyh9f0ad1d_1` build requires `phonopy >=2.3.2,<2.7`, which is incompatible with the phonopy 2.7.1 upgrade you requested; the `pyiron=0.2.17=0.2.17-pyh9f0ad1d_0` simply requires `phonopy >=2.3.2`.

In both cases, the conda solver is doing exactly what it should, which is to ensure the specified requirements for all the packages in your environment are met. You will need to raise the issue with the respective feedstock maintainers as the whether the tighter constraints on the versions visions and phonopy are correct.

(As an aside, I put "downgrade" in quotes because conda is actually changing the versions of those packages; it's just selecting a different build of them.)

**Comment by jan-janssen** [comment]
@chenghlee thank you very much for your reply. As I indicated with the pull requests, I particularly updated the recipe for pandas-profiling and pyiron to prevent this downgrade. As pyiron depends on phonopy and pandas-profiling depends on visions it is important for me as well as the users of my software that the update of pyiron and pandas-profiling should have higher priority than the update of phonopy and visions.
