### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED on Linux

### ISSUE THREAD

**Issue by thu1911** [conda/conda#10146]
I can not use most of conda commands, including update, create, etc. The error is

```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/linux-64'

```

The info of conda is

```
active environment : base
    active env location : /home/myname/software/anaconda3
            shell level : 1
       user config file : /home/myname/.condarc
 populated config files : /home/myname/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.17
       base environment : /home/myname/software/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/myname/software/anaconda3/pkgs
                          /home/myname/.conda/pkgs
       envs directories : /home/myname/software/anaconda3/envs
                          /home/myname/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/3.10.0-514.16.1.el7.x86_64 centos/7.3.1611 glibc/2.17
                UID:GID : 1019:1003
             netrc file : None
           offline mode : False
```

**Comment by rayosborn** [comment]
This looks similar to #10111 on a Mac. There are also a couple of related questions on StackOverflow - https://stackoverflow.com/questions/63368800/condahttperror-http-000-connection-failed-in-unix and https://stackoverflow.com/questions/63053019/unable-to-download-or-update-anything-from-both-anaconda-and-pip-on-mac-os. There appears to be a serious issue that has affected a number of people, but it's still too intermittent to get the attention of the Conda developers, who I think assume that it is related to conflicts with environment variables. In my case, it wasn't - you can see the comments on #10111.

**Comment by s-zk** [comment]
In my case, add an option '--repodata-fn repodata.json' works for me. For example, 'conda install something --repodata-fn repodata.json'

**Comment by s-zk** [comment]
I did some debug work on this, when add flag '-vvv', a line shows some info: 
`DEBUG conda.core.subdir_data:_load(216): No local cache found for https://repo.anaconda.com/pkgs/main/noarch/current_repodata.json at /home/***/anaconda3/pkgs/cache/b35683e8.json`

Check conda/core/subdir_data.py file, line No.216, I found `current_repodata.json` comes from variable `self.self.url_w_repodata_fn`, which is a concat of `self.url_w_subdir` and `self.repodata_fn` (conda/core/subdir_data.py file, line 177). 

`self.repodata_fn` actually is 'repodata_fn' (line 162), which is imported from `..base.constants` (line 27). In conda/base/constants.py, `REPODATA_FN = 'repodata.json'` (conda/base/constants.py, line 151), so that should be fine. 

However, when I type `conda config --show`, it looks like this:

```
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
```

I still don't know how `current_repodata.json` was added, but according to [this](https://docs.conda.io/projects/conda/en/latest/commands/install.html#Channel%20Customization), we can use `--repodata-fn` to ask conda use `repodata.json` instead `current_repodata.json`, I made a try and it worked.

And you might still encounter errors if you are trying to install a very large package due to the package could not be downloaded within `remote_read_timeout_secs` seconds, or retry more than `remote_max_retries` times, or connecting cost more than `remote_connect_timeout_secs` seconds. Make sure these parameters are set well.

**Comment by iaradsouza1** [comment]
That HTTP error happened when I updated the conda with `conda update conda`. I tried all options discussed here but it only was solved when I downgraded the conda version (I'm using miniconda 4.8.2). 
- Download an older version miniconda at https://repo.anaconda.com/miniconda/
-  Install with the `-u` option to downgrade the current version

**Comment by turtle-27** [comment]
This is happening due to newer version of conda. Uninstall your current conda and install previous version of conda to fix this.
You can use this one: https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh

**Comment by Litchilitchy** [comment]
> If this can be of any help for anyone, I had a similar issue after updating conda from 4.7 to 4.9.2. I was behind a proxy. My https proxy server configuration was set to something starting by `https://...`. Changing it to `http://...` solved the issue.

Only this works for me, however I do not know what happens under the hood.
