### ISSUE TITLE
Miniconda .pkg installer creates .bash_profile owned by root (EUID), not regular user (RUID)

### ISSUE THREAD

**Issue by spapadim** [conda/conda#10221]
**Note**: issue observed on [current Miniconda3 MacOS pkg installer](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.pkg); if this the wrong issue tracker for this, my apologies (and I'd appreciate pointer to correct one). I suspect this is caused by how `conda init` is invoked by installer, but after 5min of perusing repo I admit defeat figuring out if installer is hosted here or not.

## Current Behavior
Installer creates `~/.bash_profile` owned by `root` (effective UID),  instead of the user that initiated the installation (real UID, i.e., owner of `~`).  This occurs if `~/.bash_profile` does not already exist, and the user chooses an installation location that requires elevated privileges by installer (e.g. `/opt`).

Other than the fact that this is a potential security risk, if the user then tries to re-install in a "regular" location (e.g., under `~/opt`), the installer will unexpectedly fail near the end with a generic error, which is apparently caused by file permission error when trying to append to `~/.bash_profile`.

### Steps to Reproduce
A. To create `~/.bash_profile` owned by `root`:

1. Run current Miniconda pkg installer on MacOS, with the following two conditions holding:
  * User has `bash` as default shell (did not test `zsh` but, unlike `~/.bash_profile`, MacOS _does_ install a skeleton `~/.zshrc` so, unless user has deleted that, problem _should_ not occur)
  * User does not have a `~/.bash_profile` (MacOS default user skeleton does not include one, so this is common)
  * User selects installation location that requires elevated privileges (e.g., "Install for all users")
1. Once installation is complete, a `.bash_profile` owned by `root` is created in the user's home dir.

B. To cause installer failure due to `root`-owned `~/.bash_profile`:

1. After above steps are complete, re-run installer but this time:
  * User selects installation location that does not require elevated privileges (e.g., "Install for me only")
1. Installation proceeds until the very end, at which point it fails with a generic error.

      Error message is generic, but it appears cause is file access error when appending to `~/.bash_profile`.
      If, however, `~/.bash_profile` is first `chown`ed to correct user, then installation succeeds.**Security note** Although I am _far_ from an expert, it seems this is more of an annoyance rather than a security risk (at least if user hasn't changed MacOS default file permissions mask): on test system, although `~/.bash_profile` was owned by `root`, it was world-readable but only root-writable (and, of course, not executable by anyone).

## Expected Behavior
Installer should create `~/.bash_profile` owned by real userid, rather than effective userid.

## Environment Information
Miniconda installation does not complete.  Problem was observed on both MacOS 10.12 and 10.15.

**Comment by shoemakerdr** [comment]
*DISCLAIMER*: I'm not a conda maintainer, but here's my (possibly ignorant) two-cents based on my experience with conda.

To me, `conda init` is more of a user-level configuration command. To my knowledge, only users who actually activate/use conda environments need to run `conda init`. With that, I think this could go one of a couple ways: 

1. The installer should only run `conda init` if it's doing a user-level installation.
2. The installer should revert to user-level privileges (real UID) when invoking `conda init` in the context of an "elevated privilege install".

The first one makes sense as long as you really buy into the whole conda-init-is-for-real-users-only deal. The second one would make sense in the scenario where you're an administrator of a multi-user conda install, and you want to `init` conda environment activation/deactivation for yourself. 

Definitely down to push up a PR, but I don't know if the Miniconda installer is in the scope of this repo, and I believe since that's where privileges are set, that's where the work is needed. Is this possibly something set in (conda/constructor)[https://github.com/conda/constructor]-- would need a maintainer to confirm.
