### ISSUE TITLE
https://github.com/conda/conda/issues/2256 should be re-opened

### ISSUE THREAD

**Issue by microlaser** [conda/conda#10240]
I was able to replicate the issue described in the closed bug report referenced above.  I am concerned because I checked and my high CPU is indeed correlated with the fact I am using OpenSSL 1.1.1.g.  I am concerned that this bug was closed with the solution to downgrade OpenSSL because this version contains a vital security patch.  Please see https://www.openssl.org/news/vulnerabilities-1.1.1.html

As a security-minded python programmer, I would like to see a real fix for the issue described in the referenced bug https://github.com/conda/conda/issues/2256

I realize this takes work, I am an experienced security guy and a novice python programmer, if I can help I would be glad to if someone can assign me a small doable task with this in mind.  I apologize in advance for being a novice, I am new to Git and python, I have only written bash scripts and PowerShell in the past and I am still learning.  If I can help I would be happy to.

**Comment by mingwandroid** [comment]
Just because an issue is closed it does not mean that you cannot leave comments in there. Closed is not permanent. If we agree with you then we will re-open it. Closing this one.

**Comment by mingwandroid** [comment]
>  I am concerned that this bug was closed with the solution to downgrade OpenSSL because this version contains a vital security patch

This is not the case. The person who gave this advice is not an Anaconda team member. This bug you've asked to re-open is ancient too and could not be reproduced.

Since it is so ancient, your issue with 1.1.1g is something different and you should probably rename this issue and provide all of the information that our issue template asked you for. Thanks. I'll re-open it in case you want to do that (though you can do it outside of me re-opening this!)
