### ISSUE TITLE
Using conda env from different minicondas installs

### ISSUE THREAD

**Issue by zbs** [conda/conda#10248]
My main conda environment directory is `foo`, which was created by a locally installed version of miniconda. There is a different directory, `bar`, whose environments were created by a different install of miniconda. I would like to add `bar` to my `.condarc`. Are there any foreseeable problems with mixing and matching the Miniconda installations that generated the environments living in my `.condarc`?

**Comment by kenodegard** [comment]
If I understand the question correctly, there's no problem with creating an environment using one installation of miniconda but accessing/using said environment using a different installation of miniconda. The only caveat is that the environment must be accessed as a prefixed environment, not as a named environment.

In the following examples assume `conda1` is the first installation and `conda2` is the second installation:

```bash
$ conda1 create -n foo ...

$ conda1 list -n foo
# packages in environment at /path/to/foo:
#
# Name                    Version                   Build  Channel
...

$ conda1 activate foo
(foo) $
```

```bash
$ conda2 list -p /path/to/foo
# packages in environment at /path/to/foo:
#
# Name                    Version                   Build  Channel
...

$ conda2 activate /path/to/foo
(foo) $
```

---

> environments living in my `.condarc`

Not sure what we mean by this since environments are not defined there.
