### ISSUE TITLE
Reopen 8565

### ISSUE THREAD

**Issue by steventartakovsky-vungle** [conda/conda#10287]
Please reopen https://github.com/conda/conda/issues/8565 as it has not been resolved.

**Comment by harry-fuyu** [comment]
I had the same problem and fixed it by deleting all exported paths and adding the following line to my .bashrc:
``` export PATH=/root/anaconda3/bin```
As suggested [here](https://stackoverflow.com/questions/59510865/unable-to-activate-existing-conda-environments), this error might be caused by repeatedly specifying the same path, which was what's happening in my original error-throwing .bashrc file.

**Comment by TitusCornelius** [comment]
great, thanks for that input @harry-fuyu: That totally solved it.

I had both modified the path to include the binaries and then a `conda activate base` that I added later. Removing the manual (redundant) PATH modification got rid of the bug for me. Strange thing is that an `echo $PATH` before removing it didn't actually show any duplication. Weird. Either way, this solved it.

I think the issue should be closed. #

**Comment by beeankha** [comment]
Closing this issue, as no further comments have been made on it (please re-open if this problem is persisting!)
