### ISSUE TITLE
Fatal Python error: initsite: Failed to import the site module

### ISSUE THREAD

**Issue by RizwanShaukat936** [conda/conda#10293]
Hi!  Read this; it's important.

This is an issue tracker for conda -- the package manager.  File feature requests
for conda here, as well as bug reports about something conda has messed up.

I  am facing this issue when I try to use conda or pip for doing some thing. 
`Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\Rizwan Shaukat\anaconda3\lib\site.py", line 579, in <module>
    main()
  File "C:\Users\Rizwan Shaukat\anaconda3\lib\site.py", line 566, in main
    known_paths = addsitepackages(known_paths)
  File "C:\Users\Rizwan Shaukat\anaconda3\lib\site.py", line 349, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\Users\Rizwan Shaukat\anaconda3\lib\site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\Rizwan Shaukat\anaconda3\lib\site.py", line 163, in addpackage
    for n, line in enumerate(f):
  File "C:\Users\Rizwan Shaukat\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 623: character maps to <undefined>`

it seems conda has crashed. please give me a solution.

**Comment by ganeshbhargav** [comment]
I am assuming that you are trying to run this command to install some libraries using conda/pip.
This error could occur due to another python version running on the same machine and the installation conda refers and the other python refers could lead to library mismatches internally.

The best solution is to uninstall all other versions of python and to do a clean install of anaconda.

The other solutions are :-
1) check your .bashrc file (if using ubuntu) and remove the PATH variables to other python versions and only keep the PATH variable for anaconda.
For example: Only keep this statement in bashrc : `export PATH="/home/ganesh/anaconda3/bin:$PATH"`

2) Run the python scripts using the specific python binary :-
    `/home/ganesh/Programs/anaconda3/bin/python3 file.py`

   and 

   `/usr/bin/python3 file.py
`
Hope this helps resolve the issue.
