### ISSUE TITLE
conda is not responding

### ISSUE THREAD

**Issue by rahul-art** [conda/conda#10391]
i am getting this error from last 1 week I search all the internet but nothing working because of this my datascience learning is just stuck please help 

```
rahul@linux:~$ conda
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: Unable to get the locale encoding
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007f8783c4d740 (most recent call first):
Aborted (core dumped)
```

**Comment by goanpeca** [comment]
Hi @rahul-art, thans for the report.

Could you please provide the information listed when creating a new bug report.

Specifically:



## Current Behavior



### Steps to Reproduce

```

```


## Expected Behavior



## Environment Information
<details open><summary><code>`conda info`</code></summary><p>


```

```
</p></details>


<details open><summary><code>`conda config --show-sources`</code></summary><p>


```

```
</p></details>


<details><summary><code>`conda list --show-channel-urls`</code></summary><p>


```

```
</p></details>

**Comment by kenodegard** [comment]
Closing since the poster did not respond with the requested details.
