### ISSUE TITLE
Our official package is totally dependent on conda release. We need Tensorflow2.4 now. So do you have some rough estimation when Tensorflow 2.4 is available on Conda environment ?

### ISSUE THREAD

**Issue by rajeev921** [conda/conda#10505]

**Comment by kenodegard** [comment]
While `defaults` does not offer Tensorflow 2.4, it is available via conda-forge (`conda search conda-forge::tensorflow=2.4`), I encourage using that version if still needed.

Otherwise, this is a packaging request (not an issue with the conda tooling itself) and should be directed to the
[Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)
where `conda` installer/package issues are addressed.
