### ISSUE TITLE
how-to-remove-conda-from-linux

### ISSUE THREAD

**Issue by issamhammadi19** [conda/conda#10523]
i tried to remove conda (not anaconda) with this command: conda uninstall conda it show me :

```
Collecting package metadata (repodata.json): done Solving environment: done
## Package Plan ##
  environment location: /home/issamhammadi/miniconda3
  removed specs:
    - conda
The following packages will be REMOVED:

  brotli-1.0.9-he6710b0_2   brunsli-0.1-h2531618_0   charls-2.1.0-he6710b0_2   conda-4.9.2-py38h06a4308_0   conda-package-handling-1.7.2-py38h03888b9_0   giflib-5.1.4-h14c3975_1  imagecodecs-2021.1.11-py38h581e88b_1   jxrlib-1.1-h7b6447c_2   lerc-2.2.1-h2531618_0   libaec-1.0.4-he6710b0_1   libdeflate-1.7-h27cfd23_5   libwebp-1.0.1-h8e7db2f_0   libzopfli-1.0.3-he6710b0_0   openjpeg-2.3.0-h05c96fa_1   zfp-0.5.5-h2531618_4
The following packages will be SUPERSEDED by a higher-priority channel:
  tifffile           pkgs/main/noarch::tifffile-2021.1.14-~ --> pkgs/main/linux-64::tifffile-2020.10.1-py38hdd07704_2
Proceed ([y]/n)? y
Preparing transaction: done Verifying transaction: failed
RemoveError: This operation will remove conda without replacing it with another version of conda.
```

plz help me hwo to delete conda completely

**Comment by giladmaya** [comment]
@issamhammadi19 Have you followed instructions from https://docs.anaconda.com/anaconda/install/uninstall/#uninstalling-anaconda?

**Comment by TidyData** [comment]
for me to remove miniconda, I just delete the folder with `rm -rf /home/issamhammadi/miniconda3`  
if you want to remove virtual environments `conda env remove -n NAMEOFVENV`  
you should clean out the `~/.conda/packages` if interested in saving space since won't be needing that anymore.
you should clean out the .bashrc so it doesn't add "conda" to the path anymore since it won't exist anymore
