### ISSUE TITLE
"FileNotFoundError:  No such file or directory" when creating an env.

### ISSUE THREAD

**Issue by markfrancis905** [conda/conda#1058]
Hello,

When trying to create an env, I get the following error:

```
[mark@mark-arch testEnvs]$ conda create -p ~/testEnvs/test1 python=2.7
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /home/mark/testEnvs/test1:

The following NEW packages will be INSTALLED:

    openssl:  1.0.1j-4 
    python:   2.7.9-1  
    readline: 6.2-2     (soft-link)
    sqlite:   3.8.4.1-0 (soft-link)
    system:   5.8-1     (soft-link)
    tk:       8.5.15-0  (soft-link)
    zlib:     1.2.7-0   (soft-link)

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the############################################                                                              |  57%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 387, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/plan.py", line 569, in execute_plan
    link(prefix, arg, index=index)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/plan.py", line 525, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/install.py", line 532, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode, instdir=instdir)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/install.py", line 254, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mark/testEnvs/test1/lib/libsqlite3.la'

[mark@mark-arch testEnvs]$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.4.1
     root environment : /opt/anaconda  (writable)
  default environment : /opt/anaconda
     envs directories : /opt/anaconda/envs
        package cache : /opt/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
```

A full purge and reinstall gives the same error.

Any insight and help on this error would be appreciated.

**Comment by druzzz** [comment]
Hi Mark,  I have the same problem as you had above.  I am a bit of a newbie.  Can you explain how you installed it from source?  did you just install sqlite3 from source.  how did you get it into your conda environment?  thanks

**Comment by markfrancis905** [comment]
From memory I had this issue when I used pip, but not when I used the git version.

Make sure you actually understand what's going on here. It's been a while since I have used conda but the basic idea is your installing a separate set of python files and pointing your linux environment variables to use them over your system installed ones.

If you show me your error I will see if I can help, but if it's not exactly the same as mine then you might be better opening another issue.

**Comment by druzzz** [comment]
Thanks for your response.  Well I am trying to create a new environment within anaconda, in which python 2.7 will be used as the interpreter rather than 3.4 which is installed in the general environment.

The error message I receive is pretty much the same as yours  as follows:



[timd@tom-bus ~]$ export PATH=/opt/anaconda/bin:$PATH
[timd@tom-bus ~]$ conda create -n python27 python=2.7
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/timd/.conda/envs/python27:

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-0     (soft-link)
    pip:        6.0.8-py27_0
    python:     2.7.9-2     
    readline:   6.2-2        (soft-link)
    setuptools: 14.0-py27_0 
    sqlite:     3.8.4.1-0    (soft-link)
    system:     5.8-1        (soft-link)
    tk:         8.5.15-0     (soft-link)
    zlib:       1.2.8-0      (soft-link)

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the             |  33%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/opt/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/install.py", line 545, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/install.py", line 254, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/timd/.conda/envs/python27/lib/libsqlite3.la'

**Comment by markfrancis905** [comment]
I can't remember how I fixed this I'm afraid.

Try installing the libsqllite3 package its after separately, or exclude it from the conda install if possible.

Obviously made sure your on the latest conda revision.

**Comment by asmeurer** [comment]
Does `conda install -f sqlite` fix it?

**Comment by asmeurer** [comment]
Was the space in the error message `FileNotFoundError: [Errno 2] No such file or directory: '/home/timd/.conda/envs/python27    /lib/libsqlite3.la'` (after `python27`) added by you?

**Comment by druzzz** [comment]
Your first comment seems to have done the trick. 

Regarding your second comment, yes the space was accidentally added by me.

thanks for the help

**Comment by asmeurer** [comment]
No idea what caused this. It likely has something to do with the fact that you both are using soft links.
