### ISSUE TITLE
Override channels with `conda env export`

### ISSUE THREAD

**Issue by jamesmyatt** [conda/conda#10587]
The `override-channels` behaviour in `conda env export` does not seem to be what is described.

The help/code says (https://github.com/conda/conda/blob/master/conda_env/cli/main_export.py#L43)

```python
    p.add_argument(
        "--override-channels",
        action="store_true",
        help="Do not include .condarc channels",
    )
```

Which is great: the export should list the channels actually used in the environment, rather than ones that are also in `.condarc`. This also mirrors the behaviour of this flag for `conda create|install|...` (See also https://github.com/conda/conda/issues/10498).

However, when I use this argument, I get the following error:

```raw
CommandArgumentError: At least one -c / --channel flag must be supplied when using --override-channels.
```

which makes it sound like the purpose of the flag is to ignore the channels used in the actual environment also (not just those in .condarc) and just use the flags from the command line arguments.

I think the most _direct_ fix of this issue would be to change the help text to something like "Only include channels specified as command line arguments".

However, this doesn't address the issue that it would be valuable to ensure that any `.condarc` channels are not included in the export unless one or more packages installed actually use the channel. How can this be achieved?

**Comment by edmundhenley-mo** [comment]
> **NOTE:** If this issue was closed prematurely, please leave a comment.

Hi @beeankha / @kenodegard - my *impression* from #11800 & activity upthread is that this issue may still be unresolved? And that your github-actions / github-project-automation bots may have been over-eager?

> If you would like this issue to remain open please:
> [snip totally reasonable request for commenter to do stuff to help you all prioritise!]

I encountered this in a corporate context ~3 months ago, and I've not yet done a MWE based on version of conda under my control / public channels.

For now am being lazy and just giving answers below based on my 1st encounter - do please say if you need a proper reproduction!

* OS: Linux
* conda version:
  * current: conda 23.7.4
  * when I encountered it: I assume (???) similar
* steps I took cf issue (no repro, just diff of the change I made when encountered, and not including output):
  * note in my case this was to avoid pull-through of a *different* conda config file higher up the [precedence](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html?highlight=precedence#searching-for-condarc) chain:  `/etc/conda/condarc`, not `~/.condarc` - but my take was that root cause *looked* related to this issue.
     * Similar to @jamesmyatt, I was expecting `conda env export` to only list the channels actually used by packages in the environment.

```diff
+ # Hack: override & specify channels, to ignore channels in /etc/conda/condarc
+ # * https://github.com/conda/conda/issues/10587
- conda env export > "$ENV_DIR"/environment_pinned.yml
+ conda env export --override-channels --channel conda-forge\
+       --channel nodefaults > "$ENV_DIR"/environment_pinned.yml
+  # Hack: remove the prefix specifying local path to conda env
+  # * https://github.com/conda/conda/issues/4339
+  # * https://github.com/conda/conda/issues/11114
+  sed --in-place 's|^prefix:.*$||' "$ENV_DIR"/environment_pinned.yml
```
