### ISSUE TITLE
conda list -e doesn't show pip packages

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#1063]
From here http://stackoverflow.com/questions/24664072/how-do-i-clone-a-conda-environment-from-one-python-release-to-another

I would expect that `conda list -e` was able to produce something with all the information needed to clone the environment (and be interpretable by `conda install --file <file>`). However it is ignoring the pip packages. I think that conda should learn to process pip dependencies along with the conda ones, ie:

```
$conda list -e
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
beautiful-soup=4.3.2=py27_0
django=1.7.1=py27_0
...#complicated binary conda dependencies
pip=1.5.6=py27_0
...
#output in the style of pip freeze
pip_deps{
django-app-namespace-template-loader==0.2
django-blog-zinnia==0.15
django-contrib-comments==1.5
django-mptt==0.6.1
django-tagging==0.3.4
django-xmlrpc==0.1.5
}
```

**Comment by scholer** [comment]
If `conda list` doesn't list pip packages, then what does the `--no-pip` optional argument imply?

I think, since there is a `--no-pip` optional argument for `conda list`, then people expect that when `--no-pip` is not specified, it will include pip-installed packages. If the `--no-pip` flag is some kind of legacy cruft, maybe add a quick note about it in the help message?
