### ISSUE TITLE
Conda upgrade issue 

### ISSUE THREAD

**Issue by Om4AI** [conda/conda#10660]
_**I have been trying to upgrade my conda version to the latest one, but getting following error:**_
1. some packages causing inconsistency

**_"conda update conda"_** is also giving error

**Comment by EBenkler** [comment]
Your description is insufficient. Please follow the contribution guidelines and provide all information required there and search the issues,. Otherwise you will probably not get the help you are hoping for. In your case, if you had searched for `conda update conda`, you would have found relevant issues that are already reported.

**Comment by jezdez** [comment]
We can't really help without the details as asked in the issue template. Feel free to create a new issue.
