### ISSUE TITLE
Solving environment does not seem to stop

### ISSUE THREAD

**Issue by sanyalab** [conda/conda#10666]
Hi,

I am working on CentOS 7. I am trying to run the "conda update conda" command. This is stuck at "Solving environment: ". Its been over 1.5 hours. I have searched other blogs and issues here on conda. All describe this same "Solving environment: " issue w.r.t. installing packages. I did not find any solution to this specific problem.

Is this because I have several environments available in anaconda? I do not want to delete the environments. It will be a mammoth task to reconstruct them. Please advice what to do.

Thanks

**Comment by mfansler** [comment]
If you have an Anaconda-installed **base** it's often bogged down by having **conda-forge** in your channels. Perhaps try

```bash
conda update -n base --override-channels -c defaults conda
```

**Comment by noam1023** [comment]
Hopefully same bug.

short: I am trying to install a package (pyodbc) in a conda installation. The installation hangs.
long: Using Azure HDInsight, I run Spark cluster (with Livy as front end). The installation (out of the box) of the cluster uses Conda 4.3 . 

To isolate the bug, I ssh'd to the machine, and did
conda update conda # 4.3 --> 4.8
conda activate py35  # existing env created by Azure(?)
conda install pyodbc --> hang

Because pyodbc needs also compilation of native code (so compile issue may interfere), I tried with another random package:

strace conda install vulkn
In the output file we can see a *blocking call to futex()*. Maybe it can hint one of the developers

link to pastebin: https://pastebin.com/mN0APxP8

OS: ubuntu 18.04
Conda: started with 4.3, upgraded to current (4.8)

**Comment by jucor** [comment]
Have you tried using mamba? It works amazingly, much faster solving, and it
will go you check whether the problem is one of unsatisfiable dependencies
or simply one of solving.

**Comment by noam1023** [comment]
Thanks for the reply! 
Trying to use mamba:  ( in the conda 4.3 , ubuntu 18.04 mentioned before)

conda config --add channels conda-forge 
conda install -y mamba 
  // don't get this far:    mamba install -y pyodbc 

If I add conda-forge, I get an error https://github.com/conda/conda/issues/10618 

If I don’t add , the mamba is not found

**Comment by jucor** [comment]
Ah yes, of course, you need a working conda to install mamba, sorry, I had
a brainlapse.

Did you try *not* adding conda-forge system-wide, then only  specifying it
via "-c conda-forge" as argument to the conda call when you install mamba ?
(I don't think that would help much, but worth a try)

**Comment by mfansler** [comment]
@jucor `conda-forge::mamba` would be better

**Comment by jucor** [comment]
Nice, thanks, I didn't know that syntax!

**Comment by wook2013** [comment]
I have meet the same problem and now there is another problem is that I can not stop solving environment by ctrl+c.  What is it going on and how colud I stop it ?

**Comment by sanyalab** [comment]
Use Brute force and it will stop (close terminal). Also do not update conda everytime it asks you too. In my experience this is an added headache for marginal benefit in speed and cost. Unless the tool you are using absolutely needs the new environment and is not compatible with any other release, I do not see the point. I have stuck to 4.9.2 and so far its serving my purpose. 

-Abhijit
