### ISSUE TITLE
bash still active after uninstalling anaconda 

### ISSUE THREAD

**Issue by kuateric** [conda/conda#11101]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

i uninstalled anaconda but the bash environment seems to be still activated. I cannot use pip as you can see here: 

```bat
$ which pip
/home/eric/.local/bin/pip
$ pip
bash: /home/eric/.local/bin/pip: /home/eric/sources/anaconda3/bin/python: Defekter Interpreter: no such file or directory 
```
How can i deactivate the conda bash environment ? 

thank you

**Comment by kenodegard** [comment]
This is mostly likely something that would be resolved by simply restarting your shell. Otherwise there may be remnants of the anaconda installation in your profile which you will need to manually address.

Unfortunately there are too many unknowns here that are entirely outside of the scope of the `conda` itself for us to help debug this issue.
