### ISSUE TITLE
'conda install gdal' on Windows

### ISSUE THREAD

**Issue by jscarbor** [conda/conda#1122]
Hi,

Posting here as recommended by the conda script. I can't install GDAL on Windows on a Google Compute Engine instance. Same result trying to do older versions of GDAL packages.

My command prompt, traceback, and conda info is below.

The exception is: WindowsError: [Error 5] Access is denied: 'C:\Anaconda\conda-meta\conda-3.7.0
-py27_0.json'

Thanks!

--James

```
C:\Anaconda>conda install gdal
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.8.3                |           py27_0         205 KB
    conda-env-2.0.1            |           py27_0          54 KB
    gdal-1.11.1                |       np19py27_0         9.1 MB
    numpy-1.9.1                |           py27_0        23.2 MB
    requests-2.5.1             |           py27_0         583 KB
    ------------------------------------------------------------
                                           Total:        33.1 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.0.1-py27_0
    gdal:      1.11.1-np19py27_0

The following packages will be UPDATED:

    conda:     3.7.0-py27_0 --> 3.8.3-py27_0
    numpy:     1.9.0-py27_0 --> 1.9.1-py27_0
    requests:  2.4.1-py27_0 --> 2.5.1-py27_0

Proceed ([y]/n)? y

Fetching packages ...
conda-3.8.3-py 100% |###############################| Time: 0:00:00 420.21 kB/s
conda-env-2.0. 100% |###############################| Time: 0:00:00 234.29 kB/s
gdal-1.11.1-np 100% |###############################| Time: 0:00:01   6.81 MB/s
numpy-1.9.1-py 100% |###############################| Time: 0:00:05   4.59 MB/s
requests-2.5.1 100% |###############################| Time: 0:00:02 279.49 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  33%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 387, in instal
l
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 587, in execute_actio
ns
    execute_plan(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 571, in execute_plan
    install.unlink(prefix, arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 589, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] Access is denied: 'C:\\Anaconda\\conda-meta\\conda-3.7.0
-py27_0.json'

C:\Anaconda>conda install gdal
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following NEW packages will be INSTALLED:

    conda-env: 2.0.1-py27_0
    gdal:      1.11.1-np19py27_0

The following packages will be UPDATED:

    conda:     3.7.0-py27_0 --> 3.8.3-py27_0
    numpy:     1.9.0-py27_0 --> 1.9.1-py27_0
    requests:  2.4.1-py27_0 --> 2.5.1-py27_0

Proceed ([y]/n)?

Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  33%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 387, in instal
l
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 587, in execute_actio
ns
    execute_plan(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 571, in execute_plan
    install.unlink(prefix, arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 589, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] Access is denied: 'C:\\Anaconda\\conda-meta\\conda-3.7.0
-py27_0.json'

C:\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False


C:\Anaconda>
```

**Comment by asmeurer** [comment]
How did you install Anaconda?

**Comment by jscarbor** [comment]
The conda installer for Windows. Nothing fancy. Then this was the first
package I tried to conda install.

I know gdal is funcky to get going with its binaries. Hence my use of
anaconda.

Let me know if you want me to try and run anything else or send more output.

--James
  Sent from my phone

On Feb 2, 2015 12:17 PM, "Aaron Meurer" <notifications@github.com> wrote:

How did you install Anaconda?

—
Reply to this email directly or view it on GitHub
<https://github.com/conda/conda/issues/1122#issuecomment-72529421>.

**Comment by ilanschnell** [comment]
To me it looks like you installed Anaconda as superuser, and now you are trying to install GDAL as a non-privileged user.

**Comment by jscarbor** [comment]
That is probably it. Or rather the MS Windows "User Account Control".

The day before yesterday I switched over to trying those Golhke UCI wheels,
had similar issues, and turning off UAC resolved that.

Note that my default named account is an 'administrator' account but is not
the administrator proper. It's not like I am changing how I log in from one
session to another.

I will fire up a new Google Compute Engine VM, disable UAC first off, start
fresh with Conda, and report back.

--James
>
>

**Comment by ilanschnell** [comment]
Hi James, any updates?  Otherwise, I would like to close the issue.  Thanks.

**Comment by jscarbor** [comment]
Confirmed:

**Fails:**
Privileged account, UAC on, install Anaconda 'All Users', UAC still on, conda install gdal - crashes
**Works:**
Privileged account, UAC on, install Anaconda 'All Users', turn UAC off, conda install gdal - completes
**Works:**
Privileged account, UAC on, install Anaconda 'Just Me', UAC still on, conda install gdal - completes

I'll let you determine if the issue is closed or not :-)

Thanks so much for clueing me in to the source of the problem!

--James

**Comment by hynekcer** [comment]
A better solution than breaking UAC is to run `conda install` as Administrator, if security is preferred: (Right click `cmd.exe` or `cmd.lnk`, select "Run as administrator". After running the necessary commands close this privileged command prompt. There are many more advanced methods how to ask for UAC and get a privileged command prompt.)

Maybe you can detect insufficient privileges in this case and raise the exception with a better message. (Run this from a privileged command prompt, click "Run as Administrator".?)

**Comment by rviger-usgs** [comment]
Having same problem as @jscarbor, except that I don't have acces to UAC settings in my corporate environment. I installed Anaconda as a privileged account on a local Win8 setup. 

Per @hynekcer, I ran `conda install gdal` with the same privileged account. I saw no complaints during install, but did not end up with a working installation. Looks like DLLs not getting loaded w/`import gdal`. Messages are posted below. Guessing that some path variable isn't properly set--I declined this option during install b/c I have other python and Anaconda environments on this platform I didn't want to disturb. I'm not quite sure where the DLLs are kept, so I haven't been able to try manually editing any environment variables.

As a short-term fix, I'm probably going to have to install as a non-privileged user because my office does not allow me to disable UAC. 

Any thoughts on fixing the install that I want to make available to "everybody" would be welcome!

__Messages when installing as privileged user__

c:\Anaconda64>scripts\conda install gdal
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment c:\Anaconda64:

The following NEW packages will be INSTALLED:

    conda-env: 2.1.3-py27_0
    gdal:      1.11.2-np19py27_0

The following packages will be UPDATED:

    conda:     3.7.0-py27_0 --> 3.10.0-py27_0
    numpy:     1.9.0-py27_0 --> 1.9.2-py27_0
    requests:  2.4.1-py27_0 --> 2.5.3-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%

c:\Anaconda64>python
Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1
500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Anaconda64\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "c:\Anaconda64\lib\site-packages\osgeo\__init__.py", line 32, in <module>

    _gdal = swig_import_helper()
  File "c:\Anaconda64\lib\site-packages\osgeo\__init__.py", line 28, in swig_imp
ort_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.
>>> import os
>>> os.environ['PATH']
'"C:\\Anaconda64;C:\\Anaconda64\\Scripts;E:\\software\\netCDF\\4.3.1.1-64\\bin;E
:\\software\\netCDF\\4.3.1.1-64\\\\lib;E:\\software\\netCDF\\4.3.1.1-64\\\\deps\
\shared\\bin;E:\\software\\netCDF\\4.3.1.1-64\\\\shared\\lib; C:\\Program Files\
\Java\\jdk1.7.0_51\\bin; C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32
\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ArcGIS\\arcexe9x\\bi
n;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files (x86)\\HDF_Group\\HDF5\\
1.8.13\\bin;C:\\Python27\\ArcGIS10.2; C:\\Anaconda;C:\\Anaconda\\Scripts";c:\\An
aconda64\\lib\\site-packages\\osgeo'
>>> os.environ['PYTHONPATH']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Anaconda64\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'PYTHONPATH'

__Initial messages when I tried to install as a non-privileged user:__
C:\Anaconda64>scripts\conda install gdal
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment C:\Anaconda64:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.10.0               |           py27_0         207 KB
    conda-env-2.1.3            |           py27_0          54 KB
    gdal-1.11.2                |       np19py27_0         358 KB
    numpy-1.9.2                |           py27_0        23.2 MB
    requests-2.5.3             |           py27_0         588 KB
    ------------------------------------------------------------
                                           Total:        24.4 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.1.3-py27_0
    gdal:      1.11.2-np19py27_0

The following packages will be UPDATED:

    conda:     3.7.0-py27_0 --> 3.10.0-py27_0
    numpy:     1.9.0-py27_0 --> 1.9.2-py27_0
    requests:  2.4.1-py27_0 --> 2.5.3-py27_0

Proceed ([y]/n)? y

Fetching packages ...
conda-3.10.0-p 100% |###############################| Time: 0:00:00  15.11 MB/s
conda-env-2.1. 100% |###############################| Time: 0:00:00  11.06 MB/s
gdal-1.11.2-np 100% |###############################| Time: 0:00:00  19.27 MB/s
numpy-1.9.2-py 100% |###############################| Time: 0:00:00  25.23 MB/s
requests-2.5.3 100% |###############################| Time: 0:00:00  21.49 MB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  33%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda64\scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda64\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda64\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Anaconda64\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda64\lib\site-packages\conda\cli\install.py", line 387, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda64\lib\site-packages\conda\plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "C:\Anaconda64\lib\site-packages\conda\plan.py", line 571, in execute_plan
    install.unlink(prefix, arg)
  File "C:\Anaconda64\lib\site-packages\conda\install.py", line 589, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] Access is denied: 'C:\\Anaconda64\\conda-meta\\conda-3.7.0-py27_0.json'


C:\Anaconda64>scripts\conda info
Current conda install:

             platform : win-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : C:\Anaconda64  (writable)
  default environment : C:\Anaconda64
     envs directories : C:\Anaconda64\envs
        package cache : C:\Anaconda64\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False

**Comment by jscarbor** [comment]
I reproduced @rviger-usgs's error on my Google Compute Engine Windows Server VM.

Did the anaconda installer exe as privileged account 'for all' and let it append the path.

Right clicked on 'Anaconda Command Prompt' and 'Ran as Administrator' per @hynekcer. Executed 'conda install gdal' to no complaints.

Yet 'import gdal' subsequently fails in the same privileged command prompt session and a regular run of the 'Anaconda Command Prompt'. Fails to import _gdal.py.

I have no solution... just confirming the specific issue trying to work within UAC.

--James

**Comment by vickyting0910** [comment]
Same problem here, and I have tested all methods I can google. My machine is in Windows7 64bit. 
Finally, GDAL works, even though I am not exactly sure which step is the key. Here are the steps from my last attempt. 
1. remove Anaconda, all python packages and GDAL related files, including osgeo4w, gdal-111-1500-x64-core and GDAL-1.11.2-cp27-none-win_amd64.whl etc. 
2. install Anaconda and Microsoft Visual C++ 2008 Service Pack 1 vcredist_x64.exe, based on
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/cGhArND_2T8
3. use unofficial Windows Binaries to install GDAL
http://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal

**Comment by jscarbor** [comment]
Here is the install batch file I ended up writing. As @vickyting0910 says there are some binaries that GDAL needs. This particular customer was traveling to install our product (imageseg.com) in a facility in Togo (Africa) with shaky internet so she needed everything on a DVD. I ended up not using Anaconda for this special install. But the GDAL peculiarities may be helpful.

Also using the Gohlke distros. Note still hand emaciating UAC (@hynekcer).

--James

```batch
@echo.
@echo Be sure to first disable User Account Control
@echo   Control Panel--System and Security--Change User Account Control settings--
@echo   Never Notify
@echo.
@echo Control-C to cancel this script
@pause
:: Visual C++ 2008 updates
vcredist_x64.exe
:: Python itself
python-2.7.9.amd64.msi /qb+ ALLUSERS=1 ADDLOCAL=ALL,PrependPath
:: Python packages
C:\Python27\Scripts\pip install numpy-1.9.1+mkl-cp27-none-win_amd64.whl
C:\Python27\Scripts\pip install scipy-0.15.1-cp27-none-win_amd64.whl
C:\Python27\Scripts\pip install Pillow-2.7.0-cp27-none-win_amd64.whl
C:\Python27\Scripts\pip install PySide-1.2.2-cp27-none-win_amd64.whl
C:\Python27\Scripts\pip install GDAL-1.11.1-cp27-none-win_amd64.whl
:: Required for GDAL
copy FileGDBAPI.dll C:\Python27
@echo.
@echo Copying BIS to local drive
xcopy ..\bis C:\bis /EIQ
call shortcut.bat
@echo.
@echo Launching BIS
cd \bis
C:\Python27\python.exe gui.py
@echo.
@pause
```

**Comment by kheuton** [comment]
Hey all, still getting the same import errors mentioned above when trying to install gdal with conda (even as an adminstrator). What I did to get it working was:

`conda remove gdal`
Download the unofficial windows binary: http://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal
Then install gdal with that:
`pip install GDAL‑1.11.3‑cp27‑none‑win_amd64.whl`

Unfortunately, fiona doesn't work for me even once gdal is working, but that is a separate issue.
