### ISSUE TITLE
Add issue template for experimental solver rollout

### ISSUE THREAD

**Issue by jezdez** [conda/conda#11232]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

To have a feedback channel for the users that try out our experimental libmamba solver, we need to add an additional issue template that caters to this topic specifically and that is easy to spot in the issue template select on https://github.com/conda/conda/issues/new/choose.

### Why is this needed

By narrowing the issue template to ask for questions related to the libmamba solver, we're making sure we're getting all the details needed to be able to reproduce possible hard to debug scenarios with the experimental solver.

### What should happen?

- add a new issue template based on the bug report template
- ask to share extra output such as:
  - uploading environment.yml files
  - uploading log file produced by the solver
  - any terminal output that can be copied over that would allow us to see what happens
  - the result of the same run of conda but with increased verbosity `-vvv` (and mention that this may take longer since the libsolv backend write a LOT of log output)
- provide a freeform text area for additional context

### Additional Context

@jaimergp @LtDan33 Do you have other ideas how we could ask for as much data reasonable that would put us in a better position to debug the solver?

**Comment by jaimergp** [comment]
> any terminal output that can be copied over that would allow us to see what happens

We need `conda list`, `conda info` and `conda config`, for sure, as well as the command the used. This will be in the logs too, but just in case the logs are malformed for whatever reason.

> the result of the same run of conda but with increased verbosity -vvv (and mention that this may take longer since the libsolv backend write a LOT of log output)

I would also ask for the output of the classic solver. They could fill a "what should have happened" section, where they can paste such an output.

> provide a freeform text area for additional context

Sometimes the report won't have a "problem" per se but a different expected behaviour. Wording should cover those cases as well (not buggy, but _different_).
