### ISSUE TITLE
What's the minimum version of Python that Conda supports for new versions?

### ISSUE THREAD

**Issue by 3tilley** [conda/conda#11357]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Has Python 3.6 support been officially dropped for conda? I would like to add OpenTelemetry support but it requires Python >=3.7. The [setup.py](https://github.com/conda/conda/blob/master/setup.py#L10) says Python 3.6 is supported, but [this](https://github.com/conda/conda/issues/11096#issuecomment-1011440219) suggests it's only 3.7.

Which is the case? If it is Python 3.7 only, can I open a PR to update setup.py?

**Comment by kenodegard** [comment]
@3tilley Sorry for the confusion, I mistakenly stated in the [linked comment](https://github.com/conda/conda/issues/11096#issuecomment-1011440219) that Python 3.6 was dropped in 4.10.0, only **Python < 3.6** was dropped at that time.

However, since we are seeking to follow Python's support schedule we will no longer be supporting Python 3.6. We will formalize this in the upcoming [4.13.0 release](https://github.com/conda/conda/issues/11358).

**Comment by 3tilley** [comment]
Thanks!

Is there any interest in OpenTelemetry for Conda?
