### ISSUE TITLE
Add `no_proxy` support if using `proxy_servers`

### ISSUE THREAD

**Issue by jonashaag** [conda/conda#11411]
### What happened?

I have a `.condarc` like this:

```
proxy_servers:
  http: http://myproxy
```

I want to exclude some domains from proxying. There does not seem to be a way.

Attempt 1: Using `no_proxy=blah conda ...` does not make any difference because Conda passes its own list of proxies to `requests`, disabling `requests`' environment variable checking.

Attempt 2: Using

```
proxy_servers:
  http: http://myproxy
  no_proxy: blah  # or no: blah
```

also doesn't work because it's passed to `requests` in an inappropriate way as well.

It would be nice if Conda supported a way to selectively disable proxies.

NB: It works if don't use `proxy_servers` in the first place and only use environment variables because then `requests` will properly deal with all things proxy.

### Decision

We will go forward with exposing `no_proxy` (and `all_proxy`) in `.condarc` (per [this comment](https://github.com/conda/conda/issues/11411#issuecomment-1109530884))

**Comment by kenodegard** [comment]
Yup, since `conda` supports setting proxies via the `.condarc` [this implicitly disables requests' environment variable handling](https://docs.python-requests.org/en/latest/user/advanced/#:~:text=When%20the%20proxies%20configuration%20is%20not%20overridden%20per%20request%20as%20shown%20above%2C%20Requests%20relies%20on%20the%20proxy%20configuration%20defined%20by%20standard%20environment%20variables%20http_proxy%2C%20https_proxy%2C%20no_proxy%2C%20and%20all_proxy.):

> When the proxies configuration is not overridden per request as shown above, Requests relies on the proxy configuration defined by standard environment variables `http_proxy`, `https_proxy`, `no_proxy`, and `all_proxy`.

So we should consider (1) exposing `no_proxy` (and `all_proxy`) and/or (2) augmenting `proxy_servers` from `.condarc` with any environment variables that may be defined. I see potential problems with doing the second option since this could very well break current users' setups so it's probably safest to only do the first option.

**Comment by jonashaag** [comment]
Re (2), do you think exposing `no_proxy` and `all_proxy` only could be a problem? I guess nobody uses the `no://` or `all://` protocols with Conda...

**Comment by kenodegard** [comment]
Yeah, I think it'll be surprising to some users (and could potentially do the wrong thing) if conda started to understand `NO_PROXY` and `ALL_PROXY` env vars. Especially if we have users that have a proxy configured for non-conda stuff and a different proxy for conda stuff.

I also think it would be a weird inconsistency if conda ignores `HTTP_PROXY` and `HTTPS_PROXY` env vars but picks up `NO_PROXY` and `ALL_PROXY` env vars. I do think we'd want an all-or-nothing approach.

Separate thought, does the `NO_PROXY` env var work if we do not define `proxy_servers` and instead defined `HTTP_PROXY` and `HTTPS_PROXY` env vars? If that does work then I definitely think we should only go with the first option.

**Comment by jonashaag** [comment]
> Separate thought, does the `NO_PROXY` env var work if we do not define `proxy_servers` and instead defined `HTTP_PROXY` and `HTTPS_PROXY` env vars? If that does work then I definitely think we should only go with the first option.

Yes that's working correctly because in that case Conda delegates all proxy setup to `requests`.

**Comment by jonashaag** [comment]
I agree with option (1).

**Comment by jonashaag** [comment]
I'm assuming this is still an issue?
