### ISSUE TITLE
Downloading packages fails if existing packages need to be updated

### ISSUE THREAD

**Issue by DaanAcohen** [conda/conda#11458]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I have ran this code:

`conda install --download-only grpcio=1.35.0`

This caused an error message.

> CondaExitZero: Package caches prepared. UnlinkLinkTransaction cancelled with --download-only option

I hope this can be fixed soon. [I have been recommended on stackoverflow to report a bug ](https://stackoverflow.com/a/72141709/1987258) about this.

**Comment by beeankha** [comment]
Hi @DaanAcohen , thanks for filing this issue. The reason you are getting the `CondaExitZero` message is because the process is terminating prior to unlinking and linking packages into the prefix; technically this is indicating that everything was successful. Are your package caches not populated as expected? (the package caches should be found either in what's listed in the `package cache` section of your `conda info` output, or whichever dir you have specified in your `.condarc` file via the `pkgs_dirs` entry)
