### ISSUE TITLE
Illegal instruction when installing Miniconda3 on Raspberry Pi OS Lite 64-bit

### ISSUE THREAD

**Issue by KoenT-SS** [conda/conda#11486]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I tried to install the latest Miniconda3 on a Raspberry Pi 4, and got an "Illegal instruction" error message:

1. Downloaded the latest Miniconda3:
`wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-aarch64.sh`
2. Verified the hash of the file, which was correct:
`sha256sum Miniconda3-py39_4.11.0-Linux-aarch64.sh`
2. Ran the installation script (and accepted the confirmation steps):
`bash Miniconda3-py39_4.11.0-Linux-aarch64.sh`
4. Then got this:
```
[/home/pi/miniconda3] >>>
PREFIX=/home/pi/miniconda3
Unpacking payload ...
Miniconda3-py39_4.11.0-Linux-aarch64.sh: line 417:  1679 Illegal instruction     "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs
```

Info from running `uname -a` on the Raspberry Pi:
`Linux kttestpi3 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`

Expected behavior:
The installation completes successfully, without errors.

### Conda info

```shell
(can't execute this, as the installation failed)
```

### Conda config

```shell
(can't execute this, as the installation failed)
```

### Conda list

```shell
(can't execute this, as the installation failed)
```

**Comment by beeankha** [comment]
Hi @KoenT-SS , thanks for filing this issue. We currently no longer build installers for this architecture, however, there are two things you could try:

1. Use the old installer (`http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh`) and then upgrade `conda` once it's installed

2. Try the `linux-aarch64` installer [here](https://github.com/conda-forge/miniforge#download) (keep in mind that this is the `conda-forge` miniforge installer and not supported by Anaconda, Inc.)

In the meantime, I'm adding this to our [`Unsupported OS: Raspberry Pi 4` epic](https://github.com/conda/conda/issues/11395) since this is a frequently reported issue.

**Comment by KoenT-SS** [comment]
Hi @beeankha,
too bad there is no official support from Anaconda for Raspberry Pi OS 64-bit on the Pi 4 at the moment.
I had in the meantime indeed found out about the conda-forge Miniforge installer, and that worked for me.
I didn't try the first option you mentioned.

**Comment by beeankha** [comment]
@KoenT-SS I'm glad that the second option worked for you; since this is a duplicate issue and it's been added to the epic mentioned above, I'll go ahead and close this out. The problem you reported will be discussed along with the other Raspberry Pi 4 issues that are on that larger ticket.

**Comment by r-a-i** [comment]
I just ran into this on a RaspberryPi Zero 2 W. 
Too bad, this is unsupported. I'm curious, if this is a "frequently reported issue", why don't we just fix it?
