### ISSUE TITLE
Add colored terminal output to conda

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11495]
### What is the idea?

Considering that many other CLI tools have adopted some sort of colored output for better user experience, I believe the time has come for conda to make its output more colorful too. When complete, this feature request will have laid the foundational work for this more colorful future to become a reality.

Here are some questions we need to answer:
- Are we going to rely on a third party library or create our own?
- If we rely on a third party library, which one are we going to use and why?
- How are we going to ensure that future contributors use colors correctly? Should we write a style guide?
- Have we taken into account issues surrounding accessibility (e.g. color-blindness, screen readers)?

### Why is this needed

Effective use of not only colors but of text emphasis and de-emphasis can create user experiences which are fun and lead to being able to better read the content displayed. Colors should not only be added because of flair (also important!) but also because we want to be nice to our users by providing a compelling command line experience.

Additionally, colors help reflect that `conda` is a modern tool keep up with modern trends. Failure to do so may indicate to our users they are using an antiquated product, or worse yet using a product whose developers do not place importance on user experience.

### What should happen?

Here are some assorted user stories 

As a conda developer, I want a clearly defined set of rules for making the outputs of my commands more colorful and engaging, so that I can create the best user experiences possible.

As a conda user, I want the output of conda commands to be easy to read, so that I can quickly find the most important information when I need to know what's going on, or when I want to debug something.

As a conda user with color-blindness, I want to know that conda will always choose appropriate color schemes, so I can continue reading the outputs of commands. _We will also ensure that colors are optional with appropriate configurations._

**Comment by jezdez** [comment]
I'm in favor of this, as long as we allow disabling it for CI runs (maybe automatically when the `CI` env var is discovered?) and via a general command line flag `--no-color`.

Regarding how to do this, we should probably rely on a library like [colorama](https://pypi.org/project/colorama/) which works cross-platform, has been installed [a lot](https://pepy.tech/project/colorama) and is available both on the `defaults` and `conda-forge` channels.

I'm not in favor of adding more complex systems that among other things do colors (like rich) to conda since we're currently trying to reduce the maintenance surface instead increasing it.

**Comment by jezdez** [comment]
> I'm in favor of this, as long as we allow disabling it for CI runs (maybe automatically when the `CI` env var is discovered?) and via a general command line flag `--no-color`.
> 
> Regarding how to do this, we should probably rely on a library like [colorama](https://pypi.org/project/colorama/) which works cross-platform, has been installed [a lot](https://pepy.tech/project/colorama) and is available both on the `defaults` and `conda-forge` channels.
> 
> I'm not in favor of adding more complex systems that among other things do colors (like rich) to conda since we're currently trying to reduce the maintenance surface instead increasing it.

A ~year has passed, and we've made tremendous progress on removing dependencies and resorting to direct dependencies instead of vendored code. I think we should restart the initiative to use colored output and generally improve user experience based on the projects described above. https://clig.dev in particular is a treasure trove.
