### ISSUE TITLE
TensorFlow conflict with matplotlib

### ISSUE THREAD

**Issue by livecat-ai** [conda/conda#11502]
There seems to be conflict issue between tensorflow 2.6 and matplotlib in the latest release of miniconda on windows11.

conda 4.12.0
python 3.9.12
tensorflow 2.6.0

>>> conda install matplotlib.
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

**Comment by beeankha** [comment]
Hi @livecat-ai , thank you for filing this issue! Due to the contents of this ticket being off-topic for this repo, we ask that you please file a new one in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) (it is the place for `conda` installer/package manager issues) if you are still encountering this problem.
