### ISSUE TITLE
python package should require pip

### ISSUE THREAD

**Issue by minrk** [conda/conda#1152]
I don't think it should be possible to get a conda environment with Python and without pip. This is a source of confusion, where people set up an env, pip install a few things, and realize (or don't) that pip is still associated with the system Python.

It is increasingly rare these days to have any Python installation without pip. It should be a safe assumption that if you have Python in an environment, pip is there, too.

**Comment by asmeurer** [comment]
Unfortunately, there's a technical reason we can't do this, which is that older versions of conda do not support circular dependencies (since pip also depends on python), and since conda itself depends on python, this makes it impossible to update older versions of conda if this change is made (we did make this change for a little bit a while back, and ran into this problem). 

The only solution I can think of is to package pip with python, but not make the conda package a dependency (possibly also making pip itself an empty package for backwards compatibility, or just leaving it be, since conda will ignore packages with duplicate files).

**Comment by minrk** [comment]
With ensurepip in Python 2.7.9 and 3.4, I think it makes sense to include pip in the Python package.

**Comment by aldanor** [comment]
@minrk #1154

**Comment by minrk** [comment]
Thanks!

**Comment by bbirand** [comment]
Should I be installing the `ensurepip` package on conda then? I'm having trouble running `pyvenv`, which gives me this error:

Error: Command '['/Users/myuser/tmp/ve/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

The `ensurepip` package is not installed, and it doesn't seem to be installable with conda??

**Comment by makmanalp** [comment]
Same issue as @bbirand here. This reminds me of the whole discussion here: https://bugs.launchpad.net/debian/+source/python3.4/+bug/1290847

**Comment by matanster** [comment]
So with the latest anaconda, is pip installed by anaconda or not?!
