### ISSUE TITLE
--no-deps flag is not honored when installing

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#1161]
This is not the expected behavior.

``` console
$ conda install --no-deps -c javascript mocha
Fetching package metadata: ......
Solving package specifications:
Error: Could not find some dependencies for mocha: iojs

You can search for this package on Binstar with

    binstar search -t conda iojs

You may need to install the Binstar command line client with

    conda install binstar
```

**Comment by asmeurer** [comment]
The reason it still has to go through the resolve module is so that python versions match up.

**Comment by tswicegood** [comment]
@asmeurer not sure I understand.  I'm not installing Python into that environment.  I can't imagine a scenario where someone would type `conda install --no-deps foo` and expect a failed install based on being unable to find a dependency from `foo`, which is what happened here.

**Comment by asmeurer** [comment]
Sorry for being terse. I was mostly writing that to remind myself.

When you do `conda install --no-deps package`, conda still has to use the resolve module because in general, there are many versions of the same package and even many instances of the latest version (different builds for different versions of Python is the most common, especially since conda automatically takes into account the version of Python already installed in the environment). This means that if the resolve module fails, then installation will fail. Two ways the resolve module can fail are if dependencies can't be found, and if the dependencies are unsatisfiable.

Probably the right thing to do here is to somehow ignore the missing dependencies in the resolve module. I don't know how easy that will be to do, though. 

Another thing that ought to work would be to install the exact version you want, like `conda install --no-deps -c jacascript mocha=2.1.0=0`. It looks like it doesn't, though, so I'll have to take a look at why that is.

**Comment by asmeurer** [comment]
Ah, it looks like the installation from explicit specs (`mocha=2.1.0=0`) intentionally fails if dependencies can't be found, I guess because it wants to fall back to the more advanced resolve logic that can find versions without missing dependencies. 

I think the only viable workarounds for you now are to either add a channel with iojs (or upload iojs to `javascript`), or to download the file and install it from a tarball.

**Comment by tswicegood** [comment]
@asmeurer but isn't this a bug in the resolver?  Shouldn't installing with `--no-deps` turn off all dependency checking?  Based on the argument I would have assumed that all dependency checking was turned off.

**Comment by frol** [comment]
I agree with @tswicegood , `--no-deps` shouldn't fail because of dependencies. If you think it still must fail, please, rename it to `--no-install-but-check-deps` or whatever, but don't confuse users...

**Comment by kalefranz** [comment]
--no-deps integration tests added and passing.
