### ISSUE TITLE
Wrap libmamba solver in plugin API

### ISSUE THREAD

**Issue by jezdez** [conda/conda#11639]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Following the libmamba solver gaining stable status, we need to wrap the libmamba solver into a plugin hook, following CEP 2.

### Why is this needed?

To be able to ship libmamba solver as a plugin.

### Additional Context

This is a requirement: https://github.com/conda/conda/pull/11435

**Comment by jaimergp** [comment]
> I have some question around this issue, which will probably get addressed in the PR, but posting it here as well so I don't forget.

We want existing users to transition seamlessly from experimental to non-experimental, so:

- What happens if they use a plugin-ready conda with an older conda-libmamba-solver? 
- What about the opposite, a plugin-ready conda-libmamba-solver with an older conda?
- Essentially, we need to decide between dependency metadata restrictions or a transition compatibility layer with deprecation warnings.

**Comment by travishathaway** [comment]
We have just merged https://github.com/conda/conda/pull/11889, and I am currently working with @beeankha to merge the plugins feature branch.

**Comment by jezdez** [comment]
Closed via #11993.
