### ISSUE TITLE
legacy-install-failure ta-lib python

### ISSUE THREAD

**Issue by BLOCO01** [conda/conda#11669]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

 note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ta-lib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

### Additional Context

não consigo instalar!! estou usando o python3.9 e ta dando erro

**Comment by jaimergp** [comment]
What command are you running? This error is happening while running `pip` (which in turns seems to be calling other tools to build `ta-lib`?), not `conda` itself. Is it from an `environment.yml` file?

I've checked `ta-lib` on PyPI and [they only distribute source tarballs](https://pypi.org/project/TA-Lib/#files), so that seems to be the problem (missing Cython dependency or something?). Anyway, fortunately for you, the package is also [available on `conda-forge`](https://anaconda.org/conda-forge/ta-lib), so you can also get it installed on your environment with:

```
$ conda install -c conda-forge ta-lib
```
