### ISSUE TITLE
--clone root doesn't discard packages that depend on conda

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1190]
--clone root discards conda, but not packages that depend on conda.

**Comment by rnelsonchem** [comment]
If you do `conda list --export -n root > root_pkgs`, you get a package list that contains conda and its dependent packages. If you try to create a environment with that file, e.g. `conda create -n testenv --file root_pkgs`, conda throws an error about installing conda in the root environment. Would it make more sense if the create command simply ignored conda-based packages. It could throw a little "Skipping package..." error, so folks know that it is being skipped. This might be tricky for new users, as evidenced by our conversation in the user support forum.

**Comment by asmeurer** [comment]
Yeah, export ought to discard conda too, at least optionally.

**Comment by rnelsonchem** [comment]
How important is it for future reproducibility that people know the version
of conda being used? Maybe not at all since it is just acting as a package
manager...? But if it is important for any reason, I would think that a
different solution might be necessary (i.e. not to discard that information
from `list`), rather than having the users shoot themselves in the foot
accidentally.

**Comment by asmeurer** [comment]
For export it could just comment out the conda lines, so that you can still see what versions were installed.

**Comment by robodendron** [comment]
May I ask what the progress is on this?

**Comment by ijstokes** [comment]
@mcg1969 another test case to see if the new `--clone` plays more nicely/intelligently with this kind of scenario.

**Comment by cequencer** [comment]
I have a slightly different question.  

> Can I update conda only within my_conda_env to be a higher version than the root conda?

The reason why I ask this question is because I do not have privileged access to update the root conda, therefore everything has to resort to user_conda_enviornment.  I never had to address this issue until now, because my root conda is version 4.3.22 and it contains a bug that is resolved with conda upgrade.  Sorry for hijacking this thread as I couldn't find the answer I am looking for multiple internet search attempts.
