### ISSUE TITLE
can has try_update and rollback_update functions?

### ISSUE THREAD

**Issue by showkeyjar** [conda/conda#12011]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

every time update conda env, it will meet problem, and some time it can not be fixed.

so I'm wondering: 

would you please develop a function that can be try update some package, 

if run or test failed, We can rollback to old env.

### Why is this needed?

because it break envs so many times when update.
if we can try, and then we can roll back, there is no problems any more.

### What should happen?

when try update, it'll create a copy of env for backup,  and when update, it copy back the backup.

**Comment by travishathaway** [comment]
Hi @showkeyjar,

I have good news for you. I believe the feature that you want already exists. It's called "revisions", and here's how it works.

Suppose I create and activate a new environment with the following commands:

```
$ conda create -n my-env python pandas
$ conda activate my-env
```

I now have a new environment activated with python and pandas. But, let's now suppose that I want to also install the bokeh library. I will do that with this command:

```
$ conda install bokeh
```

But, I am not happy with this library and would like to remove it from my environment. Instead of uninstalling it with `conda remove` I can actually just revert my environment to the initial revision. Here's what that looks like:

First, I can list the revisions with this command:

```
(my-env) $ conda list --revisions
2022-10-25 10:26:14  (rev 0)
    +blas-1.0 (defaults/osx-64)
    +bottleneck-1.3.5 (defaults/osx-64)
    +bzip2-1.0.8 (defaults/osx-64)
    +ca-certificates-2022.07.19 (defaults/osx-64)
    +certifi-2022.9.24 (defaults/osx-64)
    +intel-openmp-2021.4.0 (defaults/osx-64)
    +libcxx-14.0.6 (defaults/osx-64)
    +libffi-3.3 (defaults/osx-64)
    +mkl-2021.4.0 (defaults/osx-64)
    +mkl-service-2.4.0 (defaults/osx-64)
    +mkl_fft-1.3.1 (defaults/osx-64)
    +mkl_random-1.2.2 (defaults/osx-64)
    +ncurses-6.3 (defaults/osx-64)
    +numexpr-2.8.3 (defaults/osx-64)
    +numpy-1.23.3 (defaults/osx-64)
    +numpy-base-1.23.3 (defaults/osx-64)
    +openssl-1.1.1q (defaults/osx-64)
    +packaging-21.3 (defaults/noarch)
    +pandas-1.4.4 (defaults/osx-64)
    +pip-22.2.2 (defaults/osx-64)
    +pyparsing-3.0.9 (defaults/osx-64)
    +python-3.10.6 (defaults/osx-64)
    +python-dateutil-2.8.2 (defaults/noarch)
    +pytz-2022.1 (defaults/osx-64)
    +readline-8.2 (defaults/osx-64)
    +setuptools-63.4.1 (defaults/osx-64)
    +six-1.16.0 (defaults/noarch)
    +sqlite-3.39.3 (defaults/osx-64)
    +tk-8.6.12 (defaults/osx-64)
    +tzdata-2022e (defaults/noarch)
    +wheel-0.37.1 (defaults/noarch)
    +xz-5.2.6 (defaults/osx-64)
    +zlib-1.2.13 (defaults/osx-64)

2022-10-25 10:27:11  (rev 1)
    +bokeh-2.4.3 (defaults/osx-64)
    +freetype-2.11.0 (defaults/osx-64)
    +giflib-5.2.1 (defaults/osx-64)
    +jinja2-3.0.3 (defaults/noarch)
    +jpeg-9e (defaults/osx-64)
    +lcms2-2.12 (defaults/osx-64)
    +lerc-3.0 (defaults/osx-64)
    +libdeflate-1.8 (defaults/osx-64)
    +libpng-1.6.37 (defaults/osx-64)
    +libtiff-4.4.0 (defaults/osx-64)
    +libwebp-1.2.4 (defaults/osx-64)
    +libwebp-base-1.2.4 (defaults/osx-64)
    +lz4-c-1.9.3 (defaults/osx-64)
    +markupsafe-2.1.1 (defaults/osx-64)
    +pillow-9.2.0 (defaults/osx-64)
    +pyyaml-6.0 (defaults/osx-64)
    +tornado-6.2 (defaults/osx-64)
    +typing_extensions-4.3.0 (defaults/osx-64)
    +yaml-0.2.5 (defaults/osx-64)
    +zstd-1.5.2 (defaults/osx-64)
```

Above are the two revisions I have for that environment so far. To revert to the first one, I run the following command:

```
conda install --rev 0
```

This takes me back to the way environment was initially set up.

I hope that answers your question. I apologize if I misunderstood what you were asking for as I had a little difficulty reading your original post.

**Comment by showkeyjar** [comment]
@travishathaway  good! I'll try this way.
