### ISSUE TITLE
Conda not pulling the latest build from the `mosdef-gomc` package

### ISSUE THREAD

**Issue by bc118** [conda/conda#12089]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

****`Conda`** not pulling the latest build from the `mosdef-gomc` package** 

When building the `mosdef-gomc` package via `conda` (conda install -c conda-forge mosdef-gomc) it is not pulling the latest build from the conda-forge feedstock (https://github.com/conda-forge/mosdef-gomc-feedstock/blob/main/recipe/meta.yaml), which is build number 2.  It is still pulling number 0.

However, I believe the conda-forge feedstock is correct because when it is built with mamba, it works correctly and pulls build 2. 

If this is an issue with `conda` can you fix it, or maybe provided more information on what the error is and what could be causing it?

Here are the `mosdef-gomc` packages pulled from `conda` and `mamba`, from the `conda` or `mamba` list command:
`conda`: `mosdef-gomc    conda-forge/noarch::mosdef-gomc-1.0.0-pyhd8ed1ab_0 None`
`mamba`: `mosdef-gomc        1.0.0       pyhd8ed1ab_2  conda-forge`

- MoSDeF=GOMC : https://mosdef-gomc.readthedocs.io/en/latest/index.html and https://github.com/GOMC-WSU/MoSDeF-GOMC

**Comment by travishathaway** [comment]
Hi @bc118,

Thanks for filing this bug report. I am wondering if you are still having these issues as I was unable to recreate the bug myself.

Here's what I did:

```bash
conda create -n issue-12089 -c conda-forge mosdef-gomc

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    # snip, snip
    mosdef-gomc-1.0.0          |     pyhd8ed1ab_2         174 KB  conda-forge
    # snip, snip
```

It  looks like the build number two is being fetched.

Please let me know if this is still an issue for you, or how I could better recreate it.

**Comment by bc118** [comment]
Hey.  Yeah when I run the commands below:

```
conda create --name test python=3.9
conda activate test
conda install -c conda-forge mosdef-gomc
```

It is still building the 0 version

`mosdef-gomc               1.0.0              pyhd8ed1ab_0    conda-forge`

**Comment by travishathaway** [comment]
Hi @bc118,

Thanks for the extra information. I was able to recreate the bug reported. Here's what I noticed:

1. When you attempt to install `mosdef-gomc` with `python>=3.9` you get the `_0` build number
2. When you attempt to install `mosdef-gomc` with `python=3.8` you get the `_2` build number (the one you want)

As a temporary work around, I would suggest using Python 3.8 for now. I'm still unsure whether this actually represents a bug in the way the default solver in conda works or whether this has something to do with how the package was built.

Regardless, I have categorized this as a being a https://github.com/conda/conda/labels/solver issue, but I cannot not promise when this will be address by the conda core developers. In any case, please keep an eye on this issue for further updates.

**Comment by Krande** [comment]
Hi, 

we are seeing the same bug with the [occt](https://github.com/conda-forge/occt-feedstock) package

In `occt` we recently updated to use build numbers to separate our build variants `all=200+` and `novtk=100+`.

Running `conda create -c conda-forge -n occt-env occt` pulls the lower build number

`occt               conda-forge/win-64::occt-7.7.1-novtk_hdfb195f_101`

While `mamba create -c conda-forge -n occt-env occt` results in the expected

`occt                              7.7.1  all_h13609b4_201`


Our build number priority was intentional to that the `novtk` package is an _opt in_ variant not the default as it would potential break a lot of downstream packages. 

However, with conda not properly resolving the build numbers we are starting to see downstream packages failing in conda forge due they are pulling a lower build number by default :(

* [IfcOpenShell](https://github.com/conda-forge/ifcopenshell-feedstock/pull/27)


Any help on this would be greatly appreciated!

Best Regards
Kristoffer

**Comment by travishathaway** [comment]
Hi @Krande,

Please see the comment on this issue:

- https://github.com/conda/conda/issues/12640#issuecomment-1540259737

There's a fix there and I believe it's related to what you're experiencing.
