### ISSUE TITLE
Slow `test_notices_appear_once_when_running_decorated_commands` test

### ISSUE THREAD

**Issue by jezdez** [conda/conda#12092]
### What happened?

Seems like the [test_notices_appear_once_when_running_decorated_commands](https://github.com/conda/conda/blob/9d51b702b41f47b6b53686a0ba2d013218dd5c71/tests/cli/test_main_notices.py#L236-L278) test is slow, e.g. [in this run with ~217 seconds](https://github.com/conda/conda/actions/runs/3448472489/jobs/5755526559#step:7:514). Wondering if the mock isn't working and it's timing out or something.

/cc @travishathaway

**Comment by travishathaway** [comment]
@jezdez, I think the culprit here is the follow test fixture (the slowdown is happening in the setup of the test):

https://github.com/conda/conda/blob/ebc563d740c0ec2edc22f605c5a03e757eed6004/tests/conftest.py#L32

You'll see that this fixture calls `conda-build` under the covers. I'm thinking this is the source of the slowdown.

@kenodegard , I remember you and I had worked on this. Originally, I had proposed simply building this ahead of time and then storing the build artifacts in the test folder as a `tar.bz2` file. Do you think this strategy is worth revisiting?

**Comment by travishathaway** [comment]
@jezdez , I've got a pull request ready for this now:

- https://github.com/conda/conda/pull/12142
