### ISSUE TITLE
Plugin code executed in core modules should have extra error handling

### ISSUE THREAD

**Issue by mbargull** [conda/conda#12149]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

With the new plugin system being used in `conda.core.index`, we could run into problematic scenarios in case of buggy plugins. In the future, if some package which registers itself as a plugin is installed, its code can bring `conda install`/`conda remove` etc. down. Meaning if a plugin (or a combination of plugins) cause some errors, they effectively can't be uninstalled with the same `conda` installation:

Two scenarios:

1. If some arbitrary error is thrown in `core.index._supplement_index_with_system` via `context.plugin_manager.get_hook_results("virtual_packages")`, it is currently not caught early and thus breaks `core.index.get_reduced_index`.
2. If two identically named virtual packages are created by the same or multiple plugins, this currently throws an uncaught `PluginError` which again breaks `core.index.get_reduced_index`.

Since `core.index.get_reduced_index` is a core functionality used from `core.solve`, a breakage there makes any package modifications impossible, esp. including removal of the hypothetical error-producing plugin package.

### Conda Info

```shell
Source as of conda=22.11.0
```

### Tasks

- [x] #12460
- [x] #12748
- [x] #12660

**Comment by travishathaway** [comment]
This issue came up in a separate pull request:

- https://github.com/conda/conda/pull/12712#discussion_r1206369287

I did little work exploring how we may be able to disable plugins and came across these helpful methods on the PluginManager object:

- https://pluggy.readthedocs.io/en/stable/#blocking

@jezdez is suggested that we simply go with a `--no-plugins` flag for all commands. Using this would allow users to regain operation of a broken install command. I endorse this approach 😎.

**Comment by jezdez** [comment]
Closing since this was done.
