### ISSUE TITLE
conda activate base env instead of current env

### ISSUE THREAD

**Issue by anki-code** [conda/conda#12215]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

If you activate env in conda and run new instance of the shell the env will be `base` instead of the current env in the new instance of the shell.

How to repeat this in xonsh:
```xsh
# zsh
pip install 'xonsh[full]'
conda init xonsh
conda create -n "env1" python=3.10 xonsh

xonsh
$CONDA_DEFAULT_ENV
# 'base'

conda activate env1
$CONDA_DEFAULT_ENV
# 'env1'

xonsh  # run new instance of xonsh
$CONDA_DEFAULT_ENV
# 'base'            # EXPECTED: 'env1'
```

#### Where is the issue in the code

The issue is in this line that common for all shells:

https://github.com/conda/conda/blob/f356172ccbb38c7aef0a925de165c671af387657/conda/activate.py#L162-L162

For xonsh the command should be like this:

```xsh
conda activate @(__xonsh__.env.get("CONDA_DEFAULT_ENV", "base"))
```

#### Possible fix

Disable auto activate base and use `postamble` to get `CONDA_DEFAULT_ENV` for every shell:

https://github.com/conda/conda/blob/f356172ccbb38c7aef0a925de165c671af387657/conda/activate.py#L161-L165

#### Workaround 1 - disable auto activate base

```xsh
# zsh
export CONDA_AUTO_ACTIVATE_BASE=false

xonsh
conda activate env1
$CONDA_DEFAULT_ENV
# 'env1'
xonsh
$CONDA_DEFAULT_ENV
# 'env1'  # AS EXPECTED
```

#### Workaround 2 - dirty fix

And the dirty fix is to replace the line in `~/.xonshrc` from:

https://github.com/conda/conda/blob/f356172ccbb38c7aef0a925de165c671af387657/conda/core/initialize.py#L1143

To:

```xsh
__xonsh__.execer.exec($("{conda_exe}" "shell.xonsh" "hook").replace("activate base", 'activate @(__xonsh__.env.get("CONDA_DEFAULT_ENV", "base"))'),
```

### Versions

```shell
conda version : 22.11.1
xonsh 0.13.4
```

**Comment by travishathaway** [comment]
Hi @anki-code,

Thanks for submitting this bug report. I would argue that always starting with the base environment is the expected behavior. Can you point to anywhere in the documentation that would seem to contradict this? If so, please share it here.

Otherwise, if this is behavior you would like to see changed, I would encourage you to instead categorize this as a feature request.

Please let me know if you have any questions or concerns.

**Comment by travishathaway** [comment]
Hi @anki-code,

I discussed this with some of my colleagues, and we decided it would be best to close this issue. We believe the expected behavior should always be to open the base environment in new shells regardless of how it is nested.

We are still grateful for this request and hope not having this feature does not negatively impact you too much.
