### ISSUE TITLE
conda doesn't report packages being installed from tarball

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1224]
I do a `conda install /path/to/foo-pkg-1.1.0-123_hash.tar.bz` and conda gives me a list of all the things it is going to do like normal *except* for showing me that it is going to install `foo-pkg` version 1.1.0 (and a hint as to whether this will upgrade, downgrade, or just be new).  Knowing that the command is, in fact, going to install `foo-pkg`, and whether this is going to replace an existing version of `foo-pkg`, seems like the most important piece of information it could provide.

Not providing that information seems pretty weird to me.  Is there a reason that is the behavior, or is this a bug?

**Comment by asmeurer** [comment]
Sounds like it is an unintended consequence of how tarball installs work (it first installs the dependencies, and then the tarball). We should make the output less confusing.

**Comment by ijstokes** [comment]
ping! @ilanschnell is this addressed by some of the changes you did around handling tarball-based package install a few weeks ago?

**Comment by ilanschnell** [comment]
Installing tarballs directly like this is quite different from the usual process, because it doesn't involve the resolver at all.  It is basically skipping all those steps and does a brain dead install of whatever tarball you give conda.  However, I have added recently that existing versions of the package get removed before (we talked about this).
