### ISSUE TITLE
Latest Miniconda Version fails installation if being installed to a path with >128 characters.

### ISSUE THREAD

**Issue by DanaBCooper** [conda/conda#12250]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi - I started encountering an issue when installing the newest version of Miniconda to different locations on a Linux system (tested on both RHEL8 and Ubuntu22). Certain paths would work, and others would not. I started minimally testing by running `source <conda_installation>/bin/activate` which would Fail with the following error (in some locations)
```
line 12, in <module>
 ERROR:create_buildenv.py:    from conda.cli import main
 ERROR:create_buildenv.py:ModuleNotFoundError: No module named 'conda'
```

The reason for this error was that the version of Python being used by `<installation>/bin/conda` was my default, system Python and not the Python version included in the conda installation.

I eventually realised that the installation would only fail on paths > 128 characters. I believe this is due to [this check](https://github.com/conda/conda/blob/60e11b4f1859874c1cb1a3ae324e599e0867a086/conda/core/portability.py#L221) which would replace the shebang specifying the Conda python installation with a generic `/usr/bin/env`. The default python picked up would be my system python, which did not contain the conda module and thus the above error message would be triggered.

Older versions of conda did not have this problem, even on large file systems. This is because of [this](https://github.com/conda/conda/commit/c6ead1bfaf14f6d5274cc05272212b95d55bac27#diff-acee32cda24b4ea1fda4839b5249f2dfebab40933d91d79a389aa99f18b15ec3L4) which removed the addition of the system prefix to path, when activating (`etc/profile.d/conda.sh` being called by `bin/activate`). This meant the above error wouldn't occur - conda would still pick up the correct Python version, because it was first on the Path.

I think a possible solution is simply restoring the `_add_sys_prefix_to_path()` method, though I am not aware why that was removed and it is likely not that simple.

Minimal Replication Instructions:
- Download https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
- Install to a folder with >128 characters, I ran `bash Miniconda3-latest-Linux-x86_64.sh -b -p <install_location>`
- Run `source <install_location>/bin/activate`

Please let me know if there are any issues / changes required with this bug report.

### Conda Info

```shell
The version being installed is https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

This bug relates to the installation of conda, and as such the configuration of my conda installation is not relevant.
```

### Conda Config

```shell
This bug relates to the installation of conda, and as such the configuration of my conda installation is not relevant.
```

### Conda list

```shell
This bug relates to the installation of conda, and as such the configuration of my conda installation is not relevant.
```

**Comment by jezdez** [comment]
Hi @DanaBCooper thanks for opening this ticket and providing a wonderfully detailed issue. We'll get back to you as soon as possible while we're looking into what we can do about this. The prefix injection issue has come up in a number of other subtle ways.

**Comment by TheAssassin** [comment]
I believe I'm affected by the same problem. Once the path becomes too long (e.g., in some automated CI environment), conda unexpectedly(!) just changes the shebang for some arbitrary value (`/usr/bin/env python`), which is not logged and not documented anywhere.

This is due to the workaround introduced to "fix" https://github.com/conda/conda/issues/977.

I'd rather have `conda` refuse to work entirely if that problem happens, as this current setup gives the user a really a bad experience. I mean, after all, `/usr/bin/env python` *cannot* work in a standard scenario. I could live with this workaround if there was a very, very bold warning in the log that this workaround would be needed, because that at least significantly speeds up debugging.

It took me so many hours (almost a whole day!) to figure out what causes this exception and after finding out `conda` is to blame, why it behaved like that...

Also, for the record, all Linux kernels > 5.1 support a 255 limit for shebangs, so the limit should really be raised. Python could parse the output of `platform.release()` to figure out which limit applies.
