### ISSUE TITLE
conda update with proxy repeatedly prompts for username and password without success

### ISSUE THREAD

**Issue by dlrice** [conda/conda#1227]
If I am accessing http/s through a proxy and attempt to update I start a cycle of username/password prompts:

```
$ conda update conda
Fetching package metadata: 
https proxy username: <username>

https proxy username: Password:
https proxy username: Password:
https proxy username: Password:
```

Here is what my ~/.condarc looks like:

```
channels:
 - defaults

 proxy_servers:
  http: <proxy>
  https: <proxy>
```

If I put my username and password directly into the .condarc file then `conda update conda` works though I would prefer to not to do this as I am on a shared filed system. If you need any more information I am very happy to supply this. Thanks!

**Comment by asmeurer** [comment]
Does your username or password have any special characters that would have to be quoted in a url?

**Comment by dlrice** [comment]
No, there are no characters outside of the set dictated in the URL RFC:

>Thus, only alphanumerics, the special characters "$-_.+!*'(),", and reserved characters used for their reserved purposes may be used unencoded within a URL. [RFC1738](http://www.faqs.org/rfcs/rfc1738.html)

**Comment by patrick984** [comment]
Hi, I have been having the same problem and I believe I have found the source of the issue. I did some digging in `conda/fetch.py` and found that it appears the function `get_proxy_username_and_pass` (which prompts the user) is being called multiple times at the same time. I then found this line (245):

    with concurrent.futures.ThreadPoolExecutor(10) as executor: 

I changed the 10 to a 1 and everything worked!

My guess is that a bunch of threads are trying to fetch the package index, and are all failing and prompting the user for proxy details at the same time.

**Comment by asmeurer** [comment]
Yep, that looks right. Thoughts on how to fix this?

**Comment by asmeurer** [comment]
Maybe the proxy retry logic should be refactored to raise an exception (currently it just calls the function again), so that the code with the ThreadPoolExecutor can catch the exception and cancel and restart all threads.

**Comment by patrick984** [comment]
I had another look at this and I believe it can be fixed by adding a synchronisation lock on the `handle_proxy_407` function. This would resolve the issue of multiple threads attempting simultaneous access to the relevant shared objects (`session.proxies` & user input).

However this then raises the issue of what if the user makes a typo. Currently, because `get_proxy_username_and_pass` is memoized and requests doesn't appear to distinguish between no credentials and bad credentials, conda will just retry the same username/password until your account gets locked out.

To get around this you have to check the credentials are valid before letting the other threads run again and add a method to signal `get_proxy_username_and_pass` not to use cached credentials.

Here is a working example: [fetch.diff](https://gist.github.com/patrick984/31261b15e0d912583e2f#file-fetch-diff)

I added an immediate check of the credentials within `handle_proxy_407` and 2 state variables: 
 - **attempts:** and integer which is incremented on authentication failure and passed as a second argument to `get_proxy_username_and_pass` to invalidate the cached values.
 - **authenticated:** a boolean flag to prevent the other threads needlessly re-checking the credentials.

Not sure if this is the most elegant solution but it does appear to work.

**Comment by holongate** [comment]
Hi all,

Is this something that will be fixed someday?
No attempt to incorporate the suggestion from @patrick984 has been made after mostly 18 months...
Nobody appears to care having passwords in the clear in .condarc?
With all the IT guys inside corporates mad about security, its time for Continuum Analytics to grow some spine and get serious about security if they want to still be relevant.
For now we have been forced to move away from conda just because of this bug. Sad.

Hope this will revive some interest in security and concerns of corp users.

**Comment by AlexS12** [comment]
I agree with @holongate. More or less the same problem in my company. In my opinion, it is essential to fix this bug in order to get a good acceptance of this product in companies storing passwords in txt files is not an option.

**Comment by kalefranz** [comment]
Now tracking with #5220.
