### ISSUE TITLE
Conda takes 100% CPU after install

### ISSUE THREAD

**Issue by wenzhenl** [conda/conda#12283]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

After install conda, the CPU gets up to 100%, and after `rm -rf miniconda3`, the CPU dropped. I reinstalled it again, same issue happened.

system:  SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

I installed https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

**Comment by dholth** [comment]
Can you give us more information about your system? For example, does "top" show Python using up the CPU?

**Comment by wenzhenl** [comment]
Hi, the top shows there were multiple processes started by cmd conda with the latest miniconda version, each taking about 15% of CPU, almost immediately after installing conda, the CPU went to 100%.

I removed the latest version and switched to use a previous version of ~2022/07, it’s currently working well.

note I’m working with a vps with limited memory also, 1gb RAM, so I’m also getting oom issue when creating env with the yaml, so I have to install pkg one by one.

**Comment by dholth** [comment]
You might be able to reduce memory usage by setting `default_threads` to 1 https://docs.conda.io/projects/conda/en/latest/configuration.html

**Comment by wenzhenl** [comment]
Thanks, I’ll try it for the memory issue. But I think there indeed some issue with the latest version, I followed the default install instructions, immediately after I allow conda init, CPU is spiking to 100%. The old version solved the problem for me.

**Comment by gh-andre** [comment]
I ran into this issue as well with a `t2.micro` instance, which has 1GB of RAM. Trying something like `conda create --name abc pytest` would put the VM into an unresponsive state, to the point that it won't respond to Ctrl-C and the only way to get the VM back is to kill user's session. In my case it chewed through 2/3 of my AWS CPU credits until I realized it was pounding the CPU.

Looking more into this, it turns out Conda is a bit of a memory hog and requires about 1GB of RAM on its own, so `t2.micro` went into heavy memory swapping, causing all of the above. I didn't expect this much memory requirement from an environment management utility, so it caught me off-guard.

Updating instance size to `t2.small`, which has 2GB of RAM, worked around the problem, but needing 1GB for the primary app and 2GB for the environment management utility does not sound like a good reason to pay extra for a 2GB VM. I wish Conda would be more RAM-friendly by default.
