### ISSUE TITLE
Packages with underscore get double entry in `conda list`

### ISSUE THREAD

**Issue by bjonen** [conda/conda#1237]
When installing a package `foo_bar` into a conda environment, the package comes up in `conda list` as both `foo_bar` and `foo-bar`. 

The bld.bat is standard: 

```
"%PYTHON%" setup.py install
if errorlevel 1 exit 1
```

The setup.py is standard too: 

```
import os
from setuptools import setup, find_packages

pcknm = 'foo_bar'
packages = [pcknm] + [os.path.join(pcknm, sub) for sub in find_packages(pcknm)]
setup(
    name=pcknm,
    version='0.1',
    packages=packages,
)
```

conda list returns something like this

```
foo-bar             0.1                       <pip>
foo_bar               v0.02                    py27_0    file:///c|/Miniconda/conda-bld/win-64/foo_bar-v0.02-py27_0.tar.bz2
```

**Comment by asmeurer** [comment]
Looks like pip converts underscores to dashes.

**Comment by bjonen** [comment]
But the package is installed via conda... not sure where pip comes in...

**Comment by asmeurer** [comment]
`conda list` calls `pip list` to get a list of pip packages. In this case, pip sees the Python package (because the pip metadata is part of the conda package), and converts the underscores to dashes, so conda lists it as a separate package.

Maybe it should be smarter about this. I'm not sure if it's fixable, though.

**Comment by bjonen** [comment]
So I guess the problem is to recover the original package name from `pip list` which apparently calls `safe_name` from setuptools (see http://stackoverflow.com/a/19131777/2146052). I guess you are right then, that this is impossible. Very unfortunate because it is really confusing to have two entries in `conda list` after installing a package. For me the takeaway is to avoid underscores in package names. 

Another reference: 
http://stackoverflow.com/a/16388350/2146052

**Comment by asmeurer** [comment]
Probably the best we can do is to somehow make the output of `conda list` less confusing. This is not the first time that someone has been confused by the apparent "duplication" of packages caused by the merging of conda packages and `pip list`. For instance, if you `setup.py develop` a package that is also installed by conda (e.g., conda itself), it will appear in the output twice (regardless if the name has dashes or underscores or not). Also https://github.com/conda/conda/issues/1097 is related. 

Maybe we should list pip packages and conda packages in different rows.

**Comment by kalefranz** [comment]
`conda list` no longer subprocesses to pip.  This issue can be closed.
