### ISSUE TITLE
Command-line auto-completion for conda commands

### ISSUE THREAD

**Issue by gro1m** [conda/conda#12408]
### What is the idea?

Auto-completion on the command line for conda commands, especially when using descriptive environment names, it would be helpful to be able to auto-complete the environment name, i.e. when activating an environment.

### Why is this needed?

Speeds about development and allows for easier interaction with conda commands.

### What should happen?

Auto-completion of commands. From a user perspective, allows to type commands more quickly and doing less errors.

**Comment by kenodegard** [comment]
@gro1m Unfortunately, we are unlikely to expand on conda's shell completion in the near term due to efforts underway to rethink how the shell interfaces work (e.g., https://github.com/conda/conda/issues/12451). In the meantime, we recommend checking out other projects like [fig](https://fig.io/) that can augment/replace your shell completion.
