### ISSUE TITLE
Make always_yes: true the default?

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1244]
@srossross and @ilanschnell and I were discussing this the other day. Should we make `alway_yes: true` the default, i.e., conda will not prompt you with yes/no if you want to install a package, unless you explicitly configure always_yes to no? You would still be able to use `--dry-run` to see what would happen without doing it.

The option is very annoying to me personally. always_yes was one of the first things I implemented when I started working on conda and is always the first thing I configure on any new machine that I install conda on. But my experiences shouldn't necessarily be a guide toward understanding the experiences of the typical conda user. I very rarely see people, when I do see them use conda, choose the no option. I do perhaps often see people check what conda will do before choosing yes, although this may just be because the question itself suggests that they need to do this.

**Comment by mrocklin** [comment]
I personally prefer always yes though I think that you're right that we should be aware that naive users may have a different opinion.  As someone further down the naive spectrum I'm still quite happy with always yes

**Comment by tswicegood** [comment]
:+1: -- only thing I would caution against is changing the behavior for existing users without a prompt (ironic, I know).  How about this?

* On new installs, create a `.condarc` that explicitly sets it to true (if I remember the inheritance correctly, this could be done at the system config level instead of user as user would override).
* On existing installs, detect that it hasn't been set and prompt the user explaining that the behavior has changed and ask what they would like to set.

**Comment by pzwang** [comment]
+1 to Travis's suggestion about detecting existing installations, but silently making it the default for new installations.

I do want to make sure that we acknowledge the last sentence in what @asmeurer observed, though: people use it as a chance to review what's about to be done.  I've found myself doing that on occasion, although I'm not sure I'd miss it if it were gone.  Is there any way to service both of these needs?  (The answer may very well be no...)  For instance, prompt the user if more than 4-5 packages need to get updated, or if the download size exceeds a certain amount, etc.

**Comment by ccordoba12** [comment]
FWIW, I always review what conda plans to install.

Besides, asking the user is also the default for apt-get and yum.

**Comment by bkreider** [comment]
-1.  Echoing ccordoba12, it's the default for apt-get and yum.  I always run all three of those package managers first and then inspect what will change before installing.  

If ctrl-C actually worked without leaving conda in an unknown state, it might not matter as much.

**Comment by srossross** [comment]
Our target audience should be `pip` users as well and as a pip user I find it very annoying.

**Comment by ilanschnell** [comment]
-1.  Mainly because people are used to the current behavior.  You can already set `always_yes: True` in your `~/.condarc` file, if you find the default behavior annoying.

@srossross Also our target should *not* be `pip` users.  Our target should be Anaconda users!  Some Anaconda users are also `pip` users, but the majority of Anaconda users are people who are new to Python (and certainly new to Python packaging).

**Comment by kalefranz** [comment]
Our target audience should be users.  `pip`, `yum`, `apt-get`, `packman`, `brew`, `gem`, `npm`, `cargo`, `maven`, `cpan`, and on and on
