### ISSUE TITLE
Miniconda install script refused to run when being piped into bash

### ISSUE THREAD

**Issue by raymond-u** [conda/conda#12477]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Miniconda install script has this piece of code:

```bash
if ! echo "$0" | grep '\.sh$' > /dev/null; then
  printf 'Please run using "bash"/"dash"/"sh"/"zsh", but not "." or "source".\n' >&2
  return 1
fi
```

Any installation via a pipe would fail. (Say, `curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | bash`. In this case, the result of `echo "$0"` would be `bash`.)

Also, it would actually throw a error when we didn't pass this check if running in sh. `sh: line 16: return: can only return from a function or sourced script`

**Comment by travishathaway** [comment]
Hi @raymond-u,

Thanks for filing this bug report. This isn't actually the correct place for this type of issue. I would instead file this as a feature request over at the [conda constructor](https://github.com/conda/constructor) project. Conda constructor is the tool that is used to generate the actual installers.

I can't promise that this will get accepted though. In the meantime, you might want to check out this website: https://conda.sh/ . I think it kind of does what you want.

Because this project isn't the appropriate place for this issue I will be closing it and labeling it as https://github.com/conda/conda/labels/off-topic .
