### ISSUE TITLE
leaked semaphore objects warning 

### ISSUE THREAD

**Issue by zepang** [conda/conda#12567]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

## env
platform: MacOS ventura M1
conda version: 23.3.1
python version: 3.8.16 or 3.9.16

## issue
warning message(python 3.9 also has the same warning message): 

```
/Users/xxx/anaconda3/envs/py38/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
(py38) 
```

I searched for some issues where it is mentioned that this issue has been fixed, however, I found that there is still this warning message

**Comment by travishathaway** [comment]
Hi @zepang,

Thanks for submitting this issue. Before we proceed, we need to collect some important information. Which conda command were you running when you saw this warning? Also, can you please add the information requested by the new issue form so that we can debug this properly?

We need the output from the following commands to debug appropriately (please update the description of this issue with that information):

```
conda info
```

```
conda config --show-sources
```

```
conda list --show-channel-urls
```
