### ISSUE TITLE
R does not respect virtual environment

### ISSUE THREAD

**Issue by FvD** [conda/conda#1258]
When I start R within a conda virtual environment it does not access the correct package library. 

In an environment called "my-env" I do the following:

1. Install R (the r channel already added to conda config)

      `(my-env)~ $ conda install r`

2. Start R

     `(my-env)~ $ R`

3. Check paths 
```
> system.file()
 [1] "/usr/lib/R/library/base"

 > path.package()
 [1] "/usr/lib/R/library/stats"                               "/usr/lib/R/library/graphics"                           
 [3] "/usr/lib/R/library/grDevices"                           "/usr/lib/R/library/utils"                              
[... etc]
```

This is not what I expected, especially since the R library exists inside the virtual environment:

    /home/frans/anaconda/envs/my-env/lib/R/library

I am doing something wrong (Perhaps I need to call R in a different way from within the virtual enviroment) or is this an issue with conda?

**Comment by asmeurer** [comment]
Is `my-env` the same as `sip-crs`? 

Can you verify with `type R` in the terminal that `R` is coming from that environment?

**Comment by FvD** [comment]
Yes! (I thought to make the example generic in the bugreport, but missed
a few I see).

**Comment by asmeurer** [comment]
What about `type R`?

**Comment by FvD** [comment]
```
(my-env)~ $ type R
    R is /home/frans/anaconda/envs/my-env/bin/R
    R is /usr/bin/R
```

**Comment by asmeurer** [comment]
I don't understand what that means. I suspect your problems is that you are running the `/usr/bin/R` instead of the one in the environment. What shell do you use?

**Comment by FvD** [comment]
I ran the R binary from the anaconda/envs folder and since then I cannot repeat the problem anymore. Packages within the environment follow the expected path:
```
> path.package()
[1] "/home/frans/anaconda/envs/my-env/lib/R/library/stats"    
[2] "/home/frans/anaconda/envs/my-env/lib/R/library/graphics" 
[etc]
```
I use the zsh shell, but it seems that this was a user problem, and not shell-related.

**Comment by asmeurer** [comment]
Oh, I think I see what happened. I didn't notice that you started off by conda installing R. The way both bash and zsh work is that when you type a command, like `R`, it searches the paths in `PATH` one by one until it finds it, and then it caches the location (this is called "hashing" in shell terminology), so that when you type it again, it doesn't have to search the `PATH` again, it just runs it. 

What probably happened was you started R before you conda installed it, which loaded and hashed the one in `/usr/bin`. Then you conda installed it, but the shell still had `R` hashed to `/usr/bin/R`. 

When you run `source activate`, it automatically runs `hash -r` in bash and `rehash` in zsh to clear the hashed commands, so it will find things in the new path on the PATH, but there is no way to do this when a `conda install` is run (the command has to be run inside the shell itself, meaning either you have to type it yourself or source a file that does it). 

This is a relatively rare gotcha, since it will only happen if you activate an environment (or just use the root environment), run a command from somewhere else, then conda install it and try to run it again without running `source activate` or `source deactivate`. But it's worth knowing about. `type command_name` will always tell you exactly what is being run (this is better than `which command_name`, which ignores hashed commands and searches the `PATH` directly), and `hash -r ` (in bash) or `rehash` (in zsh) will reset the hash so that you get the right thing. Or you can just run `source activate`, as it does this as well.

**Comment by FvD** [comment]
Thank you for that explanation!

**Comment by kerrywatson1** [comment]
Added to conda docs troubleshooting page PR#100.

**Comment by jolespin** [comment]
Just to be clear.  To get everything to work perfectly when using R w/ conda in a virtual env.  You must `conda create -n r-conda -c r r-essentials` to create the environment; then run `R` w/o activating the environment to get cache correct; then proceed as normal?

**Comment by mingwandroid** [comment]
You need to activate the conda env so that your shell finds the correct R in that env.

**Comment by jolespin** [comment]
Activate the R env first, and then call R?

**Comment by mingwandroid** [comment]
Yeah.

**Comment by jolespin** [comment]
If did the reverse (i.e. `~/anaconda/envs/r-conda/bin/R` and then `source activate r-conda`), what happens and how can I fix it?  Sorry for all the questions.

**Comment by mingwandroid** [comment]
Nothing bad, I'd close my terminal window and start another just to get a clean slate.
