### ISSUE TITLE
Miniconda3-latest-Linux-x86_64.sh: line 352: conda.exe: cannot execute: required file not found

### ISSUE THREAD

**Issue by vareille** [conda/conda#12585]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Alpine linux 3.17 - Python 3.11
I launched in my home folder:
bash Miniconda3-latest-Linux-x86_64.sh

and after confirming the location it say::

Miniconda3-latest-Linux-x86_64.sh: line 352: /home/minipc/miniconda3/conda.exe: cannot execute: required file not found

(but strangely the file conda.exe exists)

**Comment by travishathaway** [comment]
Hi @vareille,

The miniconda install will not work on Alpine Linux out of the box. Instead, use `continuumio/miniconda3:22.11.1-alpine`. This is an image we manage and know works with Alpine Linux.

To update your version of conda to the latest, simply run `conda update conda --yes`.

Hope this helps. I'm going to be closing this issue now because it's actually considered off topic for this repository. This issue queue is specifically for the conda tool itself and not the Miniconda installer.

**Comment by vareille** [comment]
thanks for the info
