### ISSUE TITLE
Environment variable set to a non-existent path in multiple conda environments

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [conda/conda#12590]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have written a detailed problem description here (believing the issue being related to VSCode or Python/Packages):
https://stackoverflow.com/questions/75926017/os-environssl-cert-file-stores-a-path-to-a-non-existing-file-in-visual-studi

After all the described steps I finally resinstalled MiniConda, which resolved my issue. 

### Conda Info

```shell
As mentioned above, now I have reinstalled conda. However, I initially posted the issue on the vscode repo, where a lot of info was collected. The complete thread can be found here:
https://github.com/microsoft/vscode/issues/179447
```

### Additional Context

After a clean reinstall, creating a new environment and installing only the `minio` package the environment variable is not set anymore and everything is working as expected.

**Comment by travishathaway** [comment]
Hi @TheRealRolandDeschain,

Thanks for filing this issue and providing a couple links with further information.

I want to let you know that it is definitely possible for packages to set their own environment variables upon environment activation. An example of this can be seen in the `gdal` package (this is the "activate" shell script for that package https://github.com/AnacondaRecipes/gdal-feedstock/blob/master/recipe/scripts/activate.sh)

This can be further customized by creating your own "activate" and "deactivate" scripts within your environment.

With all that being said, I am doubtful that this issue represents a problem with conda itself. The only environment variables that the application sets begin with `CONDA_*` or `_CE_*`.  That is why I think it is best to close this issue for now as I do not think it truly represents a bug with conda considering the myriad of ways that these environment variables can be set and the fact that conda itself never modifies the environment variable in question.

If you disagree and can provide more evidence pointing to `conda` itself being the problem, I invite you to keep this conversation going and re-open the issue. Otherwise, I am happy that you have found a solution to your problem and thank you for taking the time to gather so much information for this.

**Comment by TheRealRolandDeschain** [comment]
Hi, thanks for the information. Honestly, I still have no idea what the root cause for the issue was, as seen above I initially considered the problem on my side, one of the python packages and Visual Studio Code. 

I just wanted to leave this here as a "FYI" in case someone encounters a similar issue so closing the ticket is fine for me  :).
