### ISSUE TITLE
Research adding sphinx autodoc to project documentation

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12614]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

We would like to make the conda code more discoverable, so that developers have a better idea of how to use it.

### Why is this needed?

As we open our code with more and more plugin hooks, it will be important to provide plugin authors with a good experience surrounding code documentation. This sort of documentation is also widely provide amongst many other open-source projects.

### What should happen?

- [ ] Install/enable to the [autodoc plugin for sphinx ](https://www.sphinx-doc.org/en/master/tutorial/automatic-doc-generation.html)
- [ ] Make a first pass to generate documentation from existing doc strings; see what shows up well and what doesn't (I'm guessing it won't look super pretty the first time it's run 😅)
- [ ] Based on first runs with sphinx autodoc, come up with a plan to begin documenting the code. Something to consider:
  - What's our documentation style? (e.g. [Google](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), [NumPy](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy), or [Sphinx](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html))
  - What should document at a minimum? (identify important modules, classes, functions, etc.)

If more work is needed after this initial research (there most likely will be), create new issues to finish this work.

**Comment by jezdez** [comment]
Thanks for filing this!

To simplify the first task, it would be worth using https://github.com/readthedocs/sphinx-autoapi for this instead of Sphinx' built-in autodoc extension.

sphinx-autoapi does most of what we need, but doesn't need to import the actual code during the documentation build and relies on parsing the source code instead. This is often much better, since importing the conda source code during the build time requires satisfying any accidental import-time side effects.
