### ISSUE TITLE
Miniconda3 Python 3.10 Install x86-64-bit bash TypeError

### ISSUE THREAD

**Issue by PowersPope** [conda/conda#12826]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

My friend was trying to install miniconda3 on MacOS. After activating conda, she ran `conda init`. However, there was an error that she experienced in `/home/<user>/miniconda3/lib/python3.10/subprocess.py` on line 1985 (I believe, this was at work). 

The error was a TypeError. 

The function `memorywise(self._input)` gave an error that it needed byte, but got str. I had to go and change that line in subprocess.py to `memorywise(bytes(self._input, "utf-8"))` to get `conda init` to function correctly. Don't know if this was a one off on her computer only or this is a common problem. I thought I would create an Issue and let people know how to fix it if they have a problem. Sorry I don't have more information about her system. 

I believe `conda --version` after `conda init` was 23.3.1.

**Comment by travishathaway** [comment]
Hi @PowersPope,

Thanks for submitting this issue. The file you changed was in the core of Python, so I would not recommend this as a sustainable solution for others going forward.

If you run into this again (hopefully the odds of that are very low), I would recommend reporting a more detailed error report to the https://github.com/conda/constructor repository. This is this repository that hold the code responsible for creating these installers.

In the meantime, I will be closing this issue because I do not believe it is relevant to this repository.
