### ISSUE TITLE
Any way to initialize conda for bash shell without having a home directory?

### ISSUE THREAD

**Issue by JohannesWiesner** [conda/conda#12858]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I wonder if there's any way to initialize conda for my bash shell if I don't have a home directory and therefore no `.bashrc`, `.bash_profile`, etc., files?

### Why is this needed?

This is needed because I need a way to activate a conda environment inside a Docker container that is being run using `-u $(id -u):$(id -g)`. In my institution, we don't get root-rights for our machines. The only way to make sure that I am being able to modify/delete files that were created using container processes is to pass my host's user and group id to the container. That however leads to a user "inside the container" that has no home directory. Therefore there are no files that `conda init` could write to. 

### What should happen?

Offer another ("global") method to initialize conda for a bash shell that does not depend on files in a user's home directory. 

### Additional Context

I already opened a [Stackoverflow thread](https://stackoverflow.com/questions/76638472/interactively-run-docker-image-as-a-non-root-user-with-already-activated-conda-e) for this.

**Comment by JohannesWiesner** [comment]
It seems that [this thread (and possibly this specific answer)](https://github.com/conda/conda/issues/10297#issuecomment-713644821) is related?

**Comment by travishathaway** [comment]
Hi @JohannesWiesner,

Thanks for submitting this. I took a look at your Stack Overflow post and was wondering if using the miniconda3 container might help you out: https://hub.docker.com/r/continuumio/miniconda3

I'm not sure if it will handle the user and group IDs like you want though.

But, if all you want to is activate conda without writing anything to your .bashrc file, then this should do the trick:

```bash
eval "$(/root/miniconda3/bin/conda shell.bash hook)"
```

It's similar to the answer you linked to except there's no writing a temporary file.

Finally, considering that the answer above provides a sufficient workaround, I don't believe this feature request will be implemented any time soon, but I will gladly leave this issue open so that you and others can discuss.

**Comment by JohannesWiesner** [comment]
> Thanks for submitting this. I took a look at your Stack Overflow post and was wondering if using the miniconda3 container might help you out: https://hub.docker.com/r/continuumio/miniconda3

This probably won't help as the neurodocker project aims to create custom Dockerfiles. But thanks for the line of code, much appreciated! :)
