### ISSUE TITLE
In light of PEP668, It's time to reconsider --user / .local

### ISSUE THREAD

**Issue by pgunn** [conda/conda#12940]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

In #6018, this was opened as a bug. I am opening this as a feature request, in light of recent discussions in the Python community that recognise that virtualenvs and conda have changed how people use python in practice, and that having environments interact less with each other is desirable.

PEP668: https://peps.python.org/pep-0668/

This proposal is to:
A) Add a config option to conda, defaulting to true, enabling "conda_isolated" behaviour, defined below. When false, everything will behave as it does currently
B) Have `pip install --user` fail with an error message noting that use of `install --user` is not supported, telling users just to use `pip install`, which will install into their current environment directories as it normally would
C) Have conda set the PYTHONNOUSERSITE environment variable to tell python not to put the ~/.local/ module install path that `install --user` populates into the library search path. This means conda environments would only use packages from the conda environment (whether installed with conda or pip in nonlocal mode) for found packages, avoiding issues like 6018, and eliminating needs for user workarounds

Anyone who wants the current behaviour, which would become legacy behaviour, can keep it by setting conda_isolated to false. I'm not sure why they would want that, but it'd be nice not to break their workflows. But it'd be good to have better default behaviour, and I think with PEP668 the broader Python community has recognised that.

### Why is this needed?

The current defaults are surprising and have have fallen away from what users expect

### What should happen?

Python in a conda environment should not be disrupted by packages installed in a user's .local

**Comment by travishathaway** [comment]
Hi @pgunn,

Thanks for taking the time to submit this thought provoking feature request. Below are some of my thoughts...

One way this could be implemented is by having the default "state" file read as follows:

```
{"env_vars": {"PYTHONNOUSERSITE": "1"}}
```

This essentially does the same thing as running the following command:

```
conda env config vars set PYTHONNOUSERSITE=1
```

I'm not sure we would want to make this the default though. At first, this would be introduced as an opt-in feature and only later would we consider making it a default.

Regarding the behavior with `pip install --user`, I'm not sure this would be possible to control via a conda installation.

In the meantime, there is a workaround for this and that is using the command I showed above. We will leave this thread open so that others can join this discussion and voice their opinion about this feature request.

**Comment by pgunn** [comment]
Happy to start the discussion with conda; I think the broader python community is starting to talk on issues like this and that's pretty healthy.

**Comment by jezdez** [comment]
For the record, we have #12245 tracking PEP 668 already. Closing as duplicate.

**Comment by pgunn** [comment]
@jezdez This is chasing a different implication of PEP668, and should be reopened.

**Comment by jezdez** [comment]
@pgunn I apologize for the brevity earlier, what I should have written:

This is too small of a deviation from the plans described in #12245 to track in a separate ticket. Could you please add your proposal to the other ticket, to prevent competing conversations about locking conda environments like this?

You're absolutely right that `~/.local` is a liability to fully locked environments, and we should take the opportunity of introducing the locked mode for the base environment to consider adding a feature that you described above.

**Comment by pgunn** [comment]
@jezdez Ah. I  disagree with the primary direction of #12245 ; I at least don't think it's trying to solve the same problem (keeping conda environments from being interfered with from a legacy package install mechanism that can still bite users in the butt, versus stop pip from working under conda for some reason).

I'd really rather avoid the issue I'm trying to raise from being lumped in to the (incomprehensible, in my view) issue there.

**Comment by pgunn** [comment]
@jezdez Please reconsider the closure of this feature request. I do not intend to comment on or support that other ticket. It has nothing to do with this feature request, even though it references the same PEP.

**Comment by jezdez** [comment]
Hey @pgunn, as already stated on Matrix, I closed this as a duplicate given my analysis as an issue sorter for the conda project. We're following a process that can be reviewed [here](https://github.com/conda/conda/blob/main/HOW_WE_USE_GITHUB.md).

My analysis is based on the commonality with a [different feature request](12245) that is about improving the user experience when using pip with the conda base environment. Your feature request equally tries to improve the user experience, when users accidentally pip install packages into their user site directory. I would suggest basically to have different levels of "isolation", that you're suggesting. One of which is locking the base environment, one other being about the user site directory.

I haven't left a comment related to that in the ticket, which made the reason for closing as a duplicate probably less clear for you, which I'm sorry for.

Generally speaking, when trying to think about how these features could be implemented in a way that doesn't create a lot of churn for users, basically have as little disruption as possible, it's better to implement them together instead of separately.

You may of course disagree with that analysis, but I would encourage you to reflect on my reasons above. Finally, a closed duplicate doesn't imply that it's denied. Thanks for contributing to conda and bringing #6018 back to our attention!
