### ISSUE TITLE
Miniconda3 macOS Apple M1 64-bit pkg latest installation bug

### ISSUE THREAD

**Issue by ttimbers** [conda/conda#13027]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I tried to install conda on my new M2 mac via the latest link (`https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.pkg`) it said that the software was incompatible with my computer... but when I followed the link to "[Other installer links](https://docs.conda.io/en/latest/miniconda-other-installer-links.html)" on the miniconda install page and installed the latest version named by the version number it worked... version that worked was `https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-MacOSX-arm64.pkg`

These are supposed to be the same installer binary (the sha indicates this) but there is some difference as I can reproduce this over and over.

**Comment by travishathaway** [comment]
Hi @ttimbers,

Thanks for reporting this. I will reach out to the team responsible for building this installer to see if they have also seen this issue.

**Comment by jezdez** [comment]
@travishathaway Please make sure to point the ticket author to the correct repository as this issue is a problem in the miniconda installer and not the conda package manager, this repo is not the correct place to file an issue.

@ttimbers Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) instead.
