### ISSUE TITLE
Missing metadata for RPM Conda repo

### ISSUE THREAD

**Issue by artanokhov** [conda/conda#13042]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I followed instruction from https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html
So, I've tried to run 
```
rpm --import https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc && \
    echo [conda] >> /etc/yum.repos.d/conda.repo && \
    echo name=Conda >> /etc/yum.repos.d/conda.repo && \
    echo baseurl=https://repo.anaconda.com/pkgs/misc/rpmrepo/conda >> /etc/yum.repos.d/conda.repo && \
    echo enabled=1 >> /etc/yum.repos.d/conda.repo && \
    echo gpgcheck=1 >> /etc/yum.repos.d/conda.repo && \
    echo gpgkey=https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc >> /etc/yum.repos.d/conda.repo && \
    echo priority=1 >> /etc/yum.repos.d/conda.repo && \
    dnf install -y conda && \
    yum clean all && \
    rm -rf /var/cache/yum
```

it throws following errors:
```
[2023-08-28T13:26:03.903Z] [ INFO ] run: #8 235.0 Errors during downloading metadata for repository 'conda':

[2023-08-28T13:26:03.903Z] [ INFO ] run: #8 235.0   - Status code: 404 for https://repo.anaconda.com/pkgs/misc/rpmrepo/conda/repodata/2b909a47952374f264ada873eadce5aa532d19d000d44125d67c1ee0c6967198-filelists.xml.gz (IP: 10.217.247.236)

[2023-08-28T13:26:03.903Z] [ INFO ] run: #8 235.0   - Status code: 404 for https://repo.anaconda.com/pkgs/misc/rpmrepo/conda/repodata/47fc34cf9e290b7b90d56bed4aef6ece43858edf963744db18bdd0e6ec98ddb1-primary.xml.gz (IP: 10.217.247.236)
```
Seems like missed files with metainformation 
https://repo.anaconda.com/pkgs/misc/rpmrepo/conda/repodata/47fc34cf9e290b7b90d56bed4aef6ece43858edf963744db18bdd0e6ec98ddb1-primary.xml.gz
https://repo.anaconda.com/pkgs/misc/rpmrepo/conda/repodata/2b909a47952374f264ada873eadce5aa532d19d000d44125d67c1ee0c6967198-filelists.xml.gz

**Comment by cvquesty** [comment]
Let me second this.  I've got a CI failing since I can't use this repo.  

`dnf check-update
Updating Subscription Management repositories.
Conda Package Repository for Install           3.5 kB/s | 896  B     00:00
Errors during downloading metadata for repository 'Conda':
  - Status code: 404 for https://repo.anaconda.com/pkgs/misc/rpmrepo/conda/repodata/2b909a47952374f264ada873eadce5aa532d19d000d44125d67c1ee0c6967198-filelists.xml.gz (IP: 104.16.130.3)
  - Status code: 404 for https://repo.anaconda.com/pkgs/misc/rpmrepo/conda/repodata/47fc34cf9e290b7b90d56bed4aef6ece43858edf963744db18bdd0e6ec98ddb1-primary.xml.gz (IP: 104.16.130.3)
Error: Failed to download metadata for repo 'Conda': Yum repo downloading error: Downloading error(s): repodata/47fc34cf9e290b7b90d56bed4aef6ece43858edf963744db18bdd0e6ec98ddb1-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/2b909a47952374f264ada873eadce5aa532d19d000d44125d67c1ee0c6967198-filelists.xml.gz - Cannot download, all mirrors were already tried without success`

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager and not the packages that Anaconda Inc is distributing. Thank you for understanding!

**Comment by cvquesty** [comment]
Umm... I'm letting you know that YOUR TOOL isn't working.  Seems to me to be something you'd like to open a ticket on since it affects your entire REPO
