### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels

### ISSUE THREAD

**Issue by Char-CN** [conda/conda#13060]
### What is the idea?

I want to install scorecardpy==0.1.9.2, but I find that this package does not exist. How should I install it? I read the official documentation of conda, but I couldn't find a way to install it locally.

![image](https://github.com/conda/conda/assets/4012897/8fb60cf4-5043-480a-8648-b9f79da1f259)

![image](https://github.com/conda/conda/assets/4012897/5a1d2604-08d1-4a12-a34b-bfe6b31768e3)

**Comment by kenodegard** [comment]
@Char-CN not all packages that can be installed from PyPI via pip are also packaged for conda. The `defaults` channel only offers a collection of the most popular packages (and their dependencies). `conda-forge` offers even more packages but even then still depends on volunteer interest and effort.

You have three options here:

1. Create a conda environment and use pip to install scorecardpy. This comes with various risks since conda and pip do not communicate so if you go this route is is recommended to use conda first to install as much as possible and to only use pip at the very end to install the missing packages.
    ```bash
    ```
3.
