### ISSUE TITLE
Why there is no "Add Miniconda3 to my/system PATH environment variable" like option in installer if selected to install for all users?

### ISSUE THREAD

**Issue by wohenbushuang** [conda/conda#13077]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I remember that when last time (one or two years ago) I installed miniconda, there is an option such as "Add Miniconda3 to my PATH environment variable", so I can call `conda` command in Windows prompt if I checked the option. This is quite convenient.

Today I found the option is gone in the 23.5.2 installer, and I have to modify the PATH environment variable manually.

### Why is this needed?

Add the option back please

**Comment by wohenbushuang** [comment]
Sorry for my confusing description. I retried and found that the option indeed exists if I select to install for `just me`.
The similar option is missing if I select to install for `all users`, which is I used to. So I wonder that why there is no similar option to add miniconda3 to system PATH environment variable if installed for all users is selected?

![2023-09-11 224821](https://github.com/conda/conda/assets/15613184/92eaf3d1-52f8-418f-9193-990543e411ac)

**Comment by travishathaway** [comment]
@wohenbushuang,

Thanks for clarifying. I did some digging around and found out that this was done on purpose to deal with a security vulnerability. You can read more about why that was done here:

- https://github.com/conda/constructor/pull/584

I'm going to close this issue now because this actually isn't the correct repository to raise such inquiries. Please redirect further requests to the [constructor](https://github.com/conda/constructor project). Although, I doubt this feature will be added back anytime soon because of the vulnerability.
