### ISSUE TITLE
Exporting SAT solver inputs

### ISSUE THREAD

**Issue by JellePiepenbrock** [conda/conda#13096]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

It is my impression that Conda uses a SAT solver in some of the steps. Would it be possible to export these SAT problems? What would be the best place in the code to try to do it?

### Why is this needed?

I'd like to be able to analyze the kind of SAT problems that are generated in various package management settings.

### What should happen?

The only thing I'm asking for is an informed pointer by the Conda developers to either 1.) an existing feature that exports the SAT problems or 2.) a spot in the code that looks well positioned to implement this myself.

**Comment by travishathaway** [comment]
Hi @JellePiepenbrock,

Thanks for submitting this request and for your curiosity about how the SAT solver works. I dug around the code a little, and I think this class may give you what you want:

- https://github.com/conda/conda/blob/fb7775e936cdc1e9996d31662ad1c0c356bd9b1f/conda/common/logic.py#L48-L56

I apologize if that's not correct. My experience with this part of the code is limited.

If I was you, I would setup a development environment (more information about that here: https://docs.conda.io/projects/conda/en/stable/dev-guide/development-environment.html) and begin setting `breakpoint()`s to figure out what's going on in there.

You might also want to check out this project: https://github.com/conda/pycosat because it handles the low-level work of solving the SAT problem.

I'm not sure if we will implement this feature as you've requested it because there are not very many people currently demanding it. Hopefully this helps you get going in the right direction though. Feel free to experiment yourself to see what you can come up with 😄.

**Comment by JellePiepenbrock** [comment]
Thank you, that pointer is all I needed!
