### ISSUE TITLE
Conda 23.10.0 installs some packages in [environment]/site-packages in stead of [environment]/Lib/site-packages

### ISSUE THREAD

**Issue by wimiko** [conda/conda#13376]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I create a new environment from a .yml description on windows, one of the packages is installed in [environment]/site-packages in stead of  [environment]/**Lib/**site-packages. This path is not in sys.path, so it can't be found.
The package concerned comes from an internal conda channel.

Reverting to 23.9.0 solves the issue

It seems similar to this very old ticket: https://github.com/conda/conda/issues/6333

### Conda Info

```shell
active environment : xxx
    active env location : C:\Users\xxx\Miniconda3\envs\xxx
            shell level : 3
       user config file : C:\Users\yyy\.condarc
 populated config files : C:\Users\yyy\.condarc
          conda version : 23.10.0
    conda-build version : not installed
         python version : 3.9.18.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\yyy\Miniconda3  (writable)
      conda av data dir : C:\Users\yyy\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\yyy\Miniconda3\pkgs
                          C:\Users\yyy\.conda\pkgs
                          C:\Users\yyy\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\yyy\Miniconda3\envs
                          C:\Users\yyy\.conda\envs
                          C:\Users\yyy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.9.18 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\yyy\.condarc <==
ssl_verify: False
```

**Comment by travishathaway** [comment]
Hi @wimiko,

Thanks for filing this issue. Unfortunately, without having access to this internal package, it makes it very hard for us to recreate and therefore debug.

If this is a widespread issue, then hopefully other users will also begin commenting here. Otherwise, I would urge you to go back to the problematic package and try to find anything in it that may be causing this behavior. If you are able, it would also be very helpful to have as much information about this package as possible.

It also very interesting that downgrading your conda version resolves the issue. The one big change that we implemented in the `23.10.0` release was upgrading our solver to us the `libmamba` solver. If you want to upgrade to `23.10.0` again, you could experiment with disabling this solver by running `conda config --set solver classic`. This will revert to the original solver. I would be very interested to see if that resolves the issue. If it does, please report back.

**Comment by jaimergp** [comment]
See #13412 for some possible explanations @wimiko

**Comment by jaimergp** [comment]
This was fixed with the release of conda-libmamba-solver 24.11.0, which has libmamba v2 compatibility.
