### ISSUE TITLE
Error while installing pytorch-mutex, ffmpeg using conda

### ISSUE THREAD

**Issue by 9e0** [conda/conda#13404]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi Team,

I am getting below error:
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2>
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2>

when running:
conda install pytorch-mutex -c pytorch
conda install ffmpeg -c pytorch

Thanks in advance

**Comment by travishathaway** [comment]
Hi @9e0,

Thanks for filing this issue. To help, we will need a little more information from you:

- Does this only happen for the pytorch channel?
- Can you please copy and paste the output of: `conda install pytorch-mutex -c pytorch -v -v -v`?

**Comment by travishathaway** [comment]
Hi @9e0,

It looks like the traffic is being blocked by something called Zscaler. It looks like Zscaler is probably some sort of VPN/Firewall, so I'm guess this is being blocked as a false positive.

Therefore, in order to resolve this, you will need to talk with your network administrators or whoever manages this VPN/Firewall. Because there is nothing more we can do to help you, I will now be closing this issue.
