### ISSUE TITLE
Conda multiple libpng versions

### ISSUE THREAD

**Issue by cel4** [conda/conda#1345]
I have a conda environment with all `anaconda` packages. Recently, I explored the idea to install the `IRKernel` in my environment:

`conda install -c r r-irkernel`

```
The following NEW packages will be INSTALLED:

    r-irkernel: 0.3-r3.1.3_0

The following packages will be UPDATED:

    libpng:     1.5.13-1 --> 1.6.17-0
```

Updating `libpng` is problematic for me, since it would break all packages that are still linked to the old `libpng` library.

Is there any workaround for that? Can I somehow keep multiple `libpng` versions around?

**Comment by ccordoba12** [comment]
The best way to avoid messing with your root environment is to create a new one, and installl the `IRKernel` there.

You can do that with this command:

    conda create -n test-r -c r r-irkernel

Then to activate/deactivate your environment, please use

    source activate test-r
    source deactivate

**Comment by asmeurer** [comment]
You can also force individual packages to not be upgraded by pinning them (see http://conda.pydata.org/docs/faq.html?highlight=pinning#updating-packages-in-the-root-environment).

**Comment by cel4** [comment]
@ccordoba12, thanks for your solution, but I don't think this would work. The kernel is installed directly into the specific environment. If I understand correctly, installing it into `test-r` only makes it available in `test-r` which does not help much.

@asmeurer, but pinning wouldn't work either, would it? conda packages are statically linked to a specific version - if I have just one `libpng` version, either `r` or `matplotlib` will work but never both.

**Comment by ccordoba12** [comment]
@cel4, well, other than what @asmeurer suggested, you don't have other alternatives.

Why doesn't help to have things in a separate environment for you?

**Comment by asmeurer** [comment]
Are you having specific issues with one or the other breaking with one version of libpng? If so, we probably just need to update matplotlib to link against the newer libpng.

**Comment by asmeurer** [comment]
To answer your question, there's no way for conda to install multiple versions of the same package. This wouldn't really work anyway, because the two packages share some files (specifically`lib/libpng.[so/dylib]`, which is a symlink to the versioned library). You could copy the older libraries into your environment manually.

**Comment by asmeurer** [comment]
Ah, I see now that matplotlib does indeed link against libpng15, so installing the newer version makes the library not found (at least on OS X).

**Comment by asmeurer** [comment]
I'll have to think of how conda ought to be handling things like this (if at all). For now, I think the simplest solution will be for me to rebuild libpng 1.6 with the 1.5 libraries included in the package. @ilanschnell any other suggestions?

**Comment by ilanschnell** [comment]
This is really a packaging issue (as supposed to a conda issue).  I will look into updating libpng to the latest version for the next Anaconda release.

**Comment by cel4** [comment]
@ccordoba12, No that is not really an option for me. I would not be able to switch between `R` and `ipython` kernels then. This is actually why I try to install `ir-kernel` in the first place.

@ilanschnell, @asmeurer I agree that in my case this can be solved by repackaging. But I think there's also a fundamental problem here: Different library versions lead to some packages silently blocking each other. `conda` happily updates without realizing that the update will break things.

**Comment by ccordoba12** [comment]
@cel4, I see, so you want all Python packages you already have in your root environment to be available when using Python kernels.

Well, you can install them too in your `test-r` environment without wasting disk space. conda only makes (hard) symlinks between the place where your packages are located and a directory inside `test-r` (`site-packages` for Python packages). That's how package installation works in conda for all packages :-)

The thing is conda environments are precisely designed to let you try different versions of the same library, or a combination of different versions of different libraries. That's why I (also) closed the issue initially ;-)

**Comment by asmeurer** [comment]
The fact that conda doesn't look at the dependencies of already installed packages when installing is a [known issue](https://github.com/conda/conda/issues/454). If that worked then conda would disallow installing both (actually, in this specific case, the libpng version restriction is not specified in the r-base package, so it would just use the older libpng and break R). 

The real issue here is that there's no way to install both libpng versions at once. I'm not sure if it's something that conda should try to solve or if it should always be solved from the packaging side.

**Comment by asmeurer** [comment]
@ccordoba12 does have a point in that with a bit of configuration, you can make IPython look in multiple environments for its kernels, so that you can have your Python packages in one environment and your R packages in another. This won't work so easily if you use rpy2, though, as it links against libR. A simpler workaround in your instance, until I fix the libpng package, would be to copy the libpng15.[so/dylib] file into your lib directory.

**Comment by asmeurer** [comment]
https://github.com/conda/conda/issues/611 is very closely related to this one.

**Comment by Wakeupbuddy** [comment]
I met the same issue. My current solution is updating libpng to 16, but keep both libpng15.so.15 and libpng16.so.16 files under ~/anaconda/lib/, so those libararies depending on libpng15 won't complains.

**Comment by kalefranz** [comment]
Resolving libpng and other core dependencies is the goal of current CDT work.  We will not be installing multiple versions of the same package within a single conda environment.
