### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

### ISSUE THREAD

**Issue by eklavya-eg** [conda/conda#13619]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Any miniconda command not working   
   
   
    conda --help
  File "C:\ProgramData\miniconda3\Lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\ProgramData\miniconda3\Lib\site-packages\OpenSSL\SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "C:\ProgramData\miniconda3\Lib\site-packages\OpenSSL\crypto.py", line 1616, in <module>
    class X509StoreFlags:
  File "C:\ProgramData\miniconda3\Lib\site-packages\OpenSSL\crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

### Conda Info

 File "C:\ProgramData\miniconda3\Lib\site-packages\OpenSSL\crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

### Conda Config

 File "C:\ProgramData\miniconda3\Lib\site-packages\OpenSSL\crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

### Conda list

 File "C:\ProgramData\miniconda3\Lib\site-packages\OpenSSL\crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

### Additional Context

![Screenshot 2024-02-23 021218](https://github.com/conda/conda/assets/129644400/b82f298a-f282-4e63-977b-fdc35db74903)

**Comment by travishathaway** [comment]
Hi @eklavya-eg,

At this point, I would recommend reinstalling conda. I looks like your install has become corrupted.

**Comment by buraketmen** [comment]
Installing `pyopenssl==24.0.0` fixed the same problem for me.

**Comment by travishathaway** [comment]
@buraketmen,

Just curious, how were you able to do that if none of the conda commands were working for you? 🤔 Did you use `pip`?

**Comment by buraketmen** [comment]
> @buraketmen,
> 
> Just curious, how were you able to do that if none of the conda commands were working for you? 🤔 Did you use `pip`?

I actually encountered `'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'` error not due to conda but because of the new version of cryptography (42.0.5). And yes,  I resolved it by installing `pyopenssl==24.0.0` using pip.

**Comment by eklavya-eg** [comment]
hi @travishathaway 

I copied all envs to save and then reinstalled it, then again pasted all envs to newly installed conda

**Comment by eklavya-eg** [comment]
> > @buraketmen,
> > Just curious, how were you able to do that if none of the conda commands were working for you? 🤔 Did you use `pip`?
> 
> I actually encountered `'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'` error not due to conda but because of the new version of cryptography (42.0.5). And yes, I resolved it by installing `pyopenssl==24.0.0` using pip.

yes

**Comment by ianchanning** [comment]
I hit this and it was because I was moving between different conda environments but running `pip install` (because the package I need to use was not in conda).

However the pip inside the conda enironment was not using the conda pip: https://stackoverflow.com/a/56889729/327074

So the package that I installed with pip was installed somewhere separately to `pyopenssl`.

Then once I finally got the correct pip using `python -m pip install ...`, I had to just run `conda install pyopenssl`.

**Comment by jfly** [comment]
> Installing `pyopenssl==24.0.0` fixed the same problem for me.

This works, but kind bad advice, because without context, it makes it sound like there are problems with newer versions of pyopenssl, and that's not true. Better advice would be `pyOpenSSL >= 23.2.0`. Pinning packages (especially security related packages!) is never a good idea if it can be avoided.

For folks curious about the breakage:

- `cryptography` 42.0.0 removed this `X509_V_FLAG_NOTIFY_POLICY` flag: https://github.com/pyca/cryptography/commit/654dccb8e9d26f4b95e19831f976fc53bef98544
- `pyOpenSSL` 23.2.0 stopped referencing this `X509_V_FLAG_NOTIFY_POLICY` flag: https://github.com/pyca/pyopenssl/commit/d788a4f1ee2cfe0642ea9e0533bb840077a88ca6

So, you'll only run into this issue if you're running `cryptography >= 42.0.0`, and `pyOpenSSL < 23.2.0`

**Comment by valkiriaaquatica** [comment]
Same error here, in this case using ansible-inventory . Solved also installing with pip pyopenssl==24.0.0

**Comment by cpb-cbb** [comment]
![Image](https://github.com/user-attachments/assets/21786801-3f89-4b04-8674-b3f70450b76f)
I have updated the version of openssl to
"Successfully installed pyOpenSSL-24.2.1"
but the problem not solved

**Comment by ReimarBauer** [comment]
seems openssl 3.4.0 is not compatible to 44.0.0 and a pinning < 44.0.0 there is missing.

**Comment by qianweijiujiu** [comment]
> As [@jfly](https://github.com/jfly) mentioned below, installing `pyopenssl >= 23.2.0` can fix the problem.

Thx it really works.
