### ISSUE TITLE
SHA256 Mismatch for Miniconda3-latest-Linux-x86_64.sh

### ISSUE THREAD

**Issue by harris2001** [conda/conda#13630]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I just checked the sum for the Miniconda3-latest-Linux-x86_64.sh and I get a mismatch with the hash listed at https://docs.anaconda.com/free/miniconda/. Could you please check the integrity of the file.
For reference:
* Listed Hash: c9ae82568e9665b1105117b4b1e499607d2a920f0aea6f94410e417a0eff1b9c
* My Hash: b978856ec3c826eb495b60e3fffe621f670c101150ebcbdeede4f961f22dc438

**Comment by kenodegard** [comment]
Looks like an error in updating the docs page, looking at the archives (see https://repo.anaconda.com/miniconda/) the hash you have is correct

cc @kathatherine

**Comment by kathatherine** [comment]
Thank you for bringing this to our attention! The docs for this latest release did not get merged in at the same time as the installer release itself, which is why there was a difference in the hashes for the latest installers. The docs are now properly up to date and the hashes match repo.anaconda.com/miniconda. We'll review our release timeline to avoid this happening again.
