### ISSUE TITLE
"'python' has unsatisfiable dependencies" when creating environment

### ISSUE THREAD

**Issue by pitrou** [conda/conda#1365]
I'm trying to create a conda env from a custom-built Python 3.5 that I uploaded to my binstar channel:

```
$ conda create -c antoine -n 35 python=3.5
Fetching package metadata: ..........
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|################################################################################################################################| 100%


Hint: 'python' has unsatisfiable dependencies (see 'conda info python')

$ conda info python | \grep "python 3.5"
python 3.5.0a1.dev1 1_dev_dbg
python 3.5.0a4.dev1 3_dev
python 3.5.0a4.dev1 3_dev_dbg
python 3.5.0b2.dev1 4
```

**Comment by asmeurer** [comment]
The reason to look at  `conda info python` is to see the dependencies of `python`.

**Comment by asmeurer** [comment]
Ah, I see what's happening here. `conda info python` wouldn't have helped. conda has some special logic that injects `pip` as a dependency of Python (this has to be done in conda itself for backwards compatibility, because older versions of conda crash on circular dependencies). There's no Python 3.5 build of pip, so it fails. You could have deduced this by adding the `--alt-hint` flag. 

The simplest fix is to create `pip` Python 3.5 package. If your Python 3.5 already includes pip you can just create an empty package.

**Comment by pitrou** [comment]
> The simplest fix is to create pip Python 3.5 package.

Hmm... but how do I do that, if I can't create a Python 3.5 environment?

**Comment by pitrou** [comment]
And, yes, recent Python versions are able to install pip on their own (although I don't remember if they do so by default).

**Comment by asmeurer** [comment]
I thought they did unless you configure with `--with-ensurepip=no`. 

Probably the easiest way to bootstrap is to create an empty package, even if you later create a real pip package. Just create a meta.yaml (no build script), and don't include any build dependencies, only run dependencies. Or use `conda metapackage pip 7.0.3 --dependencies 'python 3.5*'`. 

Once you have that it should be possible to create an actual pip package. You'll need to be careful though, since conda doesn't include files that are part of build dependencies, so you might have to use `always_include_files` to build future versions. 

It's kind of a mess. You may want to just stick with including pip as part of the Python package and having a dummy pip package.

**Comment by pitrou** [comment]
Thanks, I'll try the dummy package.

**Comment by pitrou** [comment]
It works!
(well, mostly, because of this Python bug: http://bugs.python.org/issue24418 ... but it doesn't matter until I need an actual pip executable :-))

**Comment by asmeurer** [comment]
Huh. The use `python -E` probably has the reverse of the intended effect by ignoring `PYTHONNOUSERSITE`.

**Comment by pbethke** [comment]
I have the same problem, albeit on windows. I just cant seem to build an empty pip package. I just created an info folder with an empty ```files``` file, empty ```requires``` and ```no_softlink``` and ```index.json``` and ```meta``` with what I think is the correct data. Can you just send me a dummy package?

**Comment by asmeurer** [comment]
Does `conda metapackage` work to create a dummy package (as described above)?

**Comment by vmuriart** [comment]
@pitrou try to use `conda metapackage pip 7.0.3 --dependencies "python 3.5*"` with the double quotation marks instead of the single ones

**Comment by pelson** [comment]
Same problem here. The automatic pip thing is quite annoying in some situations. Any way to disable it   (esp. within a recipe)?

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1577

**Comment by pelson** [comment]
What timing... thanks @asmeurer

**Comment by mcg1969** [comment]
Let's close this to avoid confusion. Now that there is a Python 3.5 version of pip, and now that we can disable automatic pip injection, this is no longer active.
