### ISSUE TITLE
Add "activate in the Command list of "conda -h"

### ISSUE THREAD

**Issue by masasakano** [conda/conda#13668]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

`conda -h` outputs the list of the available COMAND. However the list does not include "activate", which is one of the most essential commands of `conda` in my understanding.  It shoud be included.

### Why is this needed?

That is the command an absolute beginner of `conda` would search for in their first use or after a long absence (as I did!).

### What should happen?

The output of `conda -h` should include `activate`.

**Comment by travishathaway** [comment]
Hi @masasakano,

Thanks for filing this. I am happy to let you know that this has been added to conda as of version 23.11.0. Please see the release notes for more information:

- https://github.com/conda/conda/releases/tag/23.11.0

I imagine you are not seeing this because you are using a version of conda that is older than this. I would recommend updating to the latest version.

I would encourage you to close this issue if there are no further actions for us to take 😄.

**Comment by masasakano** [comment]
Thank you for pointing it (and I apogogise I missed it…)! I have confirmed it and am now closing the issue.
