### ISSUE TITLE
why is conda loading another libffi?

### ISSUE THREAD

**Issue by nullhook** [conda/conda#13727]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

why do I see two flavors of libffi loaded when running a script? and why does conda loads it's own libffi?

`/usr/lib/libffi.dylib`
`/opt/homebrew/Caskroom/miniconda/base/envs/xxx/lib/libffi.8.dylib`

**Comment by travishathaway** [comment]
@nullhook,

Could you provide more information about this script? Otherwise, it will be hard for us to provide an exact answer.

More generally, conda does attempt to create environments that are separate from system dependencies, so the fact that it is using it's own libffi is expected. The fact that the system one is present would be more concerning.

**Comment by nullhook** [comment]
sure. i'll see if i can create a small reproducible.

another question, why does python binaries provided from conda does not link to Python.framework?
