### ISSUE TITLE
Clang binding

### ISSUE THREAD

**Issue by TDaltonC** [conda/conda#1383]
I've been using conda for my managing a bunch of python environments and it has saved me a huge amount of time. But now I need a python environment where python is bound to Clang instead of GCC.

I managed to hack together a bash script that adds an alternative version of python to my PATH.  I run that when I activate the source I want to use, but is there a way to handle this just inside of conda?
Is that possible? If so how? If not, is it on the development horizon?

**Comment by asmeurer** [comment]
Is this just a matter of swapping out one Python for the other? If so, I think you just need to build a conda package for you clang Python.

**Comment by stuarteberg** [comment]
>But now I need a python environment where python is bound to Clang instead of GCC.

I'm not sure exactly what you mean by this.  You mean a version of Python that was compiled by clang instead of gcc?  I can't think of a situation in which that would be useful, but I'm genuinely curious to know what your use-case is.

**Comment by TDaltonC** [comment]
I'm asking on behalf of a friend (he's shy) who works in a lab that has a "clang everything" rule so that they know exactly what they'll get when they move code across environments, and the debug reports are the same. He says that the robots (he works on reach and grasp movements) can be extremely finicky in surprising ways. I'll ask him if he has a good example of where this was really important. 

You might like this: http://sayspy.blogspot.com/2009/08/compiling-python-using-clang.html

**Comment by venachescu** [comment]
Hey, shy friend here, I'm sure my use-case(s) are pretty atypical and specific so I'll try to explain. 

We have a code base for our robots, simulations ML-stuff and other tools which used to be almost entirely in C, but things are being added in C++. All this stuff needs to compile and link on a couple different platforms including some real time OSes. We keep certain compiled libraries centrally and then link against them at compile time, so that these are stable, debugged and no surprises when they're running the bigger robots.

In the past it's been GCC across the board (and still is for the most part), but for a number of reasons we're trying to move everything to clang. Now as far as I know, linking C libraries compiled in GCC or clang should really be fine, but not so much for C++. However, we really don't want any surprises when it comes to real time / robot control stuff so everything should be compiled and linked with the same toolchain (for each OS).

Anyway, for now my dirty hack updating the path works to use conda python when I need it and I keep the generic python compiled with clang for the tools I'm building in python that'll be used with the robots. But it seems that clang will only become more popular since it's default on Mac and there's some nice API and low level stuff that will catch on with IDEs I imagine. A little example - if you're using the YouCompleteMe engine for semantic code completion it crashes immediately when the python it finds is complied with gcc.

(Disclaimer: I might be totally mistaken about something - but from tinkering around for a few days I think it makes sense)

**Comment by stuarteberg** [comment]
As you point out, it shouldn't matter what compiler you used to build a C library, and it's only C++ that causes trouble.

The crash you mentioned sounds strange.  I still can't figure out why it should matter which compiler you used to build `libpython.dylib`.  It seems more likely that you are using two different *versions* of `libpython.dylib`.  If you build the `YouCompleteMe` stuff against `libpython.X.dylib` and then switch to using `libpython.Y.dylib` at runtime, you may end up with symbol mismatches.

Anyway, if you really need to start building clang versions of every package you use, I guess your only option (as mentioned above), is to start building your own packages using clang.  You'll have to write your own recipes and upload the resulting packages to binstar and somehow uniquely identify them so that you always get the version when you want.  (The "uniquely identify" part is a little tricky. You could give your packages unique names, or maybe special version numbers like 2.7.10.99, or possibly create a conda 'feature' called "clang".)

**Comment by kalefranz** [comment]
> possibly create a conda 'feature' called "clang"

That's one solution.  Or just isolate your packages in your own channel(s) and confine conda to that/those channel(s).
