### ISSUE TITLE
Conda should be able to create environments for other platforms (than its own)

### ISSUE THREAD

**Issue by penenkel** [conda/conda#1386]
ATM `conda create` creates environments based on the platform of the conda installation (i.e. what is displayed as platform if you call `conda info`. Usually that is all one ever needs, because what use is an environment if it can not run on your system. There are IMHO exactly two exceptions to that: 
 1) win-64 systems can run win-32 binaries (I'm not certain if this only applies to Windows)
 2) if one uses conda to create custom "(portable) python installations" that are to be shipped to other systems. 
With regards to case 1): Most systems nowadays are 64bit (at least the Windows ones), unfortunately there are still quite a lot of legacy software products that are 32bit, which by means that any interaction with them from python requires a 32bit python.

While one certainly can install conda 64 and 32 parallel and then create the desired environment with the matching conda, this is IHMO kind of unsatisfying, as one has two (mini)conda installations to maintain and only one can be active (i.e. first on PATH) at a time.

I propose adding flag to `conda create` that allows specifying the target platform. This would also require to separate/subdivide the `/pkgs` folder according to platform.

**Comment by asmeurer** [comment]
Right now, the way we've told people to manage this is to install a separate Miniconda for the platform they are interested in (at least for the 32-, 64-bit issue). I'm not sure if it's worth the complexity that would be added to conda to make things work the way you say. A lot of places in the code assume there is a single platform, and that that platform matches `sys.platform`. And as you note, there is also the assumption that there only needs to be one package cache, one index, etc. 

Regarding use-case 2, that might not really work in general anyway, since conda packages in general cannot be relocated once they are installed, because hard-coded paths in files are replaced with the install prefix at install time. 

At any rate, the use-case 1 seems legitimate, but I don't really see the value of allowing to install packages for a completely different operating system.

**Comment by denfromufa** [comment]
+1 on supporting both win32 & win64 in conda environments. this is possible with virtualenv.

**Comment by bheklilr** [comment]
+1 on this from me too.  I'm currently trying to get Python 2.7 win-32 set up in Miniconda3 win-64 so that I can have wxPython 2.8 installed from another source.  I need this particular version of wxPython, and the DLLs the application interacts with are 32 bit, so I'm locked in to that environment.  It's quite a pain to have to install Miniconda2 win-32 just for this case, and be locked in to 32 bit for all environments created under that version of conda.  I'll be looking into the virtualenv approach as mentioned by @denfromufa, but it's just not very ideal in my situation.

**Comment by kalefranz** [comment]
In later versions of conda 4.3, both `subdir` and `subdirs` are accepted as configuration parameters.  For one-off commands, use `CONDA_SUBDIR` and `CONDA_SUBDIRS` environment variables.

This configuration isn't documented just yet.  We've still got some user-facing API to lock down before we make it 100% official.
