### ISSUE TITLE
The error report "CondaError: Run 'conda init' before 'conda activate'" is misleading, solution proposed

### ISSUE THREAD

**Issue by olympus-terminal** [conda/conda#13998]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This error message pops up when conda is not initialized, but the suggestion for action (i.e., Run 'conda init' before 'conda activate' ) is not helpful because that is only a temporary fix for the user. From reading other users' issues on this error, what would be more helpful is to suggest a permanent fix for the user.

What should be reported is a recommendation to re-source the environment with the conda init block, because if that doesn't work, then the init block needs to be integrated into the env startup protocol (and not entered as user input in an interactive interface).

**Comment by travishathaway** [comment]
@olympus-terminal,

I don't understand why you think that `conda init` is only a temporary fix. You only need to run `conda init` once so that it can edit the applicable shell configuration file. On subsequent shell runs, this will not need to be done again and `conda activate` can be directly called.

Is there a better way we could explain that?

**Comment by jimpickrellgit** [comment]
"conda init" doesn't work.  So it is not a solution.  It doesn't work once.  It doesn't work twice.  It doesnt work.

I am on Colab and have installed conda successfully (according to the prompts it gives me)

**Comment by jaimergp** [comment]
Jupyter doesn't really give you access to a shell. It's just executing subprocesses for you. You can't use other environments in condacolab 1.x, only `base` (read the [Shortcomings section](https://github.com/conda-incubator/condacolab/tree/0.1.x?tab=readme-ov-file#shortcomings)). And you can't change your Python version either so that's going to be a no-no. So yes, this is not a bug in `conda`, but a limitation of `condacolab`, which if anything should be addressed there.

**Comment by Getiann** [comment]
`source activate` maybe can solve this
