### ISSUE TITLE
What's the license for conda/miniconda?

### ISSUE THREAD

**Issue by franktoffel** [conda/conda#1407]
@JJ and I were having a chit chat regarding the license of conda and we found the text to be maybe unclear since it says the following:

https://github.com/conda/conda/blob/master/LICENSE.txt#L4

To my understanding conda is licensed under BSD terms as it is properly written in the docs and below that line. But since we are not lawyers we have doubts about the final "legal" interpretation of it.

**Comment by JJ** [comment]
In fact, it does look like that's the exact text of the BSD 3-clause
license http://opensource.org/licenses/BSD-3-Clause
So the contradiction is right there, I'm afraid.

**Comment by asmeurer** [comment]
That's right, Continuum maintains the copyright in the license. This is how open source licenses generally work. I have neither the knowledge nor the time to really explain this well, since I am not a lawyer. Hence what I say below may be wrong, and SHOULD NOT BE TAKEN AS LEGAL ADVICE. 

My basic understanding is that, under US law, copyright is automatically assigned to any work as soon as it is created. That work may then be licensed for others to use by the copyright holder by whatever terms the holder wants. The BSD open source license is one such set of terms. It allows almost completely unrestricted use of the work, basically subject to the terms listed in the license (such as the requirement to maintain the copyright and disclaimer text in derivative works). 

It is also possible to completely remove the copyright of a work, which puts it in the public domain, but this is generally frowned upon for a few legal reasons (e.g., it is not clear if US law even allows works to be irrevocably placed in the public domain, and the concept of public domain does not even exist in some countries). It's much smarter to license the work under a license like the BSD license. This protects the copyright holder (in this case, Continuum Analytics) with the disclaimer. This has the intended effect of putting the thing in the public domain, namely, other people can reuse the source code basically however they want, but it also limits the copyright holder's liability with the disclaimer, and the copyright notice rules maintain attribution.  But you can see for instance that conda includes versioneer, which has been put in the public domain.

You can spend a lot of time learning about this stuff, and sometimes there are no straight answers because things have to be tested in courts, but at the end of the day, practically, you should just license your code with a [common open source license](http://choosealicense.com/), as they have been written by lawyers who have thought a lot more about these things than you have. 

As an aside, Miniconda itself, as well as Anaconda (the installers) have a separate license, which is displayed when you run them.

**Comment by racinmat** [comment]
So, the question is, what is the license for miniconda? I understand that conda itself is FOSS, but miniconda (nor anaconda) are not, right?
I know anaconda has commercial license. But how about miniconda? Is it free for commercial usage, or not?
