### ISSUE TITLE
Can't install Anaconda

### ISSUE THREAD

**Issue by Haffa1995** [conda/conda#14299]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

Try to install anaconda. However , keeps failing. The last step.

### Additional Context

![Image](https://github.com/user-attachments/assets/33a86ba4-a4e1-4615-a420-b12bab821c2d)

**Comment by travishathaway** [comment]
Thank you for filing this issue! Unfortunately, this is off-topic for this repo because it is related to an Anaconda product.
If you are encountering issues with Anaconda products or services, you have several options for receiving community
support:

- [Anaconda community forums](https://community.anaconda.cloud)
- [Anaconda issue tracker on GitHub](https://github.com/ContinuumIO/anaconda-issues/issues)
