### ISSUE TITLE
Conda update not working properly sometimes.

### ISSUE THREAD

**Issue by M2ATrail** [conda/conda#14324]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

This seems similar to this but not exactly the same since this isn't conda.
Post:
curious why conda update duckdb isn't updating mine from 1.1.1 to 1.1.2 even though you seem to have added it to channel.
![Image](https://github.com/user-attachments/assets/f8ce6474-2a3d-4d78-8bef-050bbaf2c096)

here's the verbose output
https://paste.pythondiscord.com/5CAW7AN4F2WVOTBLSAL7G3IISQ

interesting enough, conda update --all recognizes it.
![Image](https://github.com/user-attachments/assets/a48c7aca-5696-46bc-abe3-ded8cc29743b)

installed conda from miniforge3

**Comment by travishathaway** [comment]
@M2ATrail,

When you run `conda update <package-name>` it will attempt to just update that single package. If there is another dependency in the environment that is preventing it from being updated it will not be update to its latest version because it will not be able to provide a valid resolution for all the dependencies.

In your case, the dependency preventing `duckdb` from updating to its latest version (`1.1.2`) is `python-duckdb`. `duckdb=1.1.2` requires you to have `python-duckdb >=1.1.2,<1.1.3.0a0` installed, but you have `python-duckdb=1.1.1` installed. Because you only have `python-duckdb=1.1.1` installed, the dependency solver will not be able to produce an answer that includes `duckdb=1.1.2`.

You've already discovered how to overcome this by using `conda update --all`, but another way to solve this would be to simply include `python-duckdb` in the update command:

```
conda update duckdb python-duckdb
```

This will attempt to update both packages and will be able to find a solution that includes the latest version of `duckdb`.

I hope that makes sense. Please let me know if you have any questions.

**Comment by M2ATrail** [comment]
@travishathaway 
Thanks, that does make sense and I thought about it, but when you install duckdb it installs both duckdb and python-duckdb so I assumed both are done together.

I'd also say, it would make sense to receive a message that says "hey this needs x and y dependencies, do you want to update?"
having that directly would make more sense.

is there a way to group packages together? to recommend it to duckdb people.

**Comment by travishathaway** [comment]
@M2ATrail,

There exists within conda the idea of a "metapackage", which is a collection multiple packages. It is not widely used though as far as I know.

This would be a question to bring up with those responsible for packaging duckdb.

**Comment by M2ATrail** [comment]
Alright thanks, I'll be recommending this to them and adding feature request I guess for that.
