### ISSUE TITLE
Resolve code makes incorrect usage of "features" vs. "track_features"

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#1471]
Having `features` set does not seem to stop upgrading when a newer version without the feature is not present.

    $ conda --version
    conda 3.15.1

**Comment by asmeurer** [comment]
I think it shouldn't. What package are you seeing this with?

**Comment by jakirkham** [comment]
I have a copy of `scipy` here ( https://anaconda.org/jakirkham/scipy ) built with `openblas` as a feature. Code for the recipes can be found here ( https://github.com/jakirkham/nanshe-build/tree/2bb6ee274062938cd741c02dd5c342c518ee64f4 ). Sorry its going through an update.

**Comment by jakirkham** [comment]
Also, I am seeing this issue when building, as well. However, I suspect it is the same bug causing this issue.

**Comment by jakirkham** [comment]
So to help narrow this down a bit. This problem was not present in `conda`'s `3.15.0` release, but is present in `3.15.1`.

**Comment by asmeurer** [comment]
Can you verify that by downgrading conda? There were no changes in conda that should affect this. I suspect rather that the state of the repositories changed.

**Comment by jakirkham** [comment]
Sorry, I can't. I thought I could, but it didn't seem to solve it completely.

**Comment by asmeurer** [comment]
I see now. There are actually two issues here:

- If you run `conda create -n test -c jakirkham scipy openblas`, it chooses the wrong version of scipy. This is caused by https://github.com/conda/conda/issues/1338, and was already reported at https://github.com/conda/conda/issues/1334.

- If you run `conda create -n test -c jakirkham openblas` and then `conda install -n test -c jakirkham scipy`, it doesn't install scipy. That's because it only looks at the track_features for packages specified in the install (for the installed packages it looks at the features, not the track_features, which is wrong). 

The second issue should not be hard to fix. The first is dependent on #1338. Maybe I should disable the "fast" algorithm when there are features. That would solve this specific problem, but not all problems.

**Comment by asmeurer** [comment]
Since the first point is already a duplicate, I'm going to retitle this issue for the second point.

**Comment by jakirkham** [comment]
I see. Sorry to duplicate.

**Comment by asmeurer** [comment]
That's fine. I wouldn't have found the second issue without this report.

**Comment by gqmelo** [comment]
Hey, I was taking a look at some issues and found this one. About the second point cited by you I made an attempt to fix it on this PR https://github.com/conda/conda/pull/1421.

**Comment by jakirkham** [comment]
@gqmelo, thanks for this. Let me take a look at it tomorrow and see how it goes.

**Comment by asmeurer** [comment]
That PR was merged and the other issue is a dupe of https://github.com/conda/conda/issues/1334 and https://github.com/conda/conda/issues/1338, so closing.
