### ISSUE TITLE
--dependencies-only flag for development

### ISSUE THREAD

**Issue by naught101** [conda/conda#1543]
It'd be nice to have a `conda install -dependencies-only` flag. This would install all of the dependencies of the required package, but not the package itself. This would be useful when developing a package - it would allow you to install all of the required packages in one fell swoop.

**Comment by asmeurer** [comment]
I agree. It would be basically the opposite of `--no-deps`.

**Comment by asmeurer** [comment]
Even so, it's pretty easy to achieve the same thing with `conda install package; conda remove package`.

**Comment by damianavila** [comment]
easy but feels like hacky....

**Comment by filmackay** [comment]
+1 - this is a common scenario when wanting to automate unit tests prior to creating a package. Don't want to go through the whole conda build unnecessarily (and could fail, but I want my unit tests to fail).

**Comment by jhprinz** [comment]
@benbovy Is there progress on this? It seems that #3500 works already but no decision has been made whether this feature will become part of conda. 

I would like to use it to setup the development environment easily and for testing as well.

**Comment by benbovy** [comment]
I'm still waiting for some feedback or review on this.

It does work, although currently a (major) limitation is that we can't set specific versions for the dependencies, which is I actually need to easily create multiple dev/test envs for a given package.

**Comment by jhprinz** [comment]
> It does work, although currently a (major) limitation is that we can't set specific versions for the dependencies, which is I actually need to easily create multiple dev/test envs for a given package.

maybe then you need to change the option to be 

```
--add-dependencies-from-package [packagename]
```

which will circumvent the whole installation process and only add the requirements to the install string. This way you can just add more constraints and be more flexible in building envs. Say your package `foo` requires `xyz>=1.0` and you want to test with later versions you run
```
conda install --add-dependencies-from-package foo  xyz=1.1
```
which should act something like
```
conda install xyz>=1.0  xyz=1.1
```
(not that this syntax works but that is what I think would be nice)

This would also be useful if you want to update all dependencies when developing. 

In my case -- just setting up an environment for testing -- it would be nice to have some option in conda-build instead that creates a suitable environment to execute, test or develop in. Conda-build used to not clean up its testing enviroment `_test` which I used to run nose tests a while ago. Having only this step as a single option with a name of the environment would be useful.

I imagine the case where the test branch needs additional packages then installing from an existing build is not enough. Probably the origin why it _feels_ hacky.
```
conda build --only-create-test-environment mytest path-to-recipe 
```

**Comment by kalefranz** [comment]
I think the use case might fit better with conda-build's already-built capabilities too.  @benbovy if we implemented something like what @jhprinz suggests in conda-build, would that cover your use case?

CC @msarahan

**Comment by benbovy** [comment]
@kalefranz although I rarely use conda-build and I've not used it so far for setting up development environments, to me it feels a bit hacky to use a "tool for *building* conda packages" to actually just *install* packages in a new development environment. In my case -- create and submit PRs -- I don't need a recipe to build a conda package. Using `conda install package; conda remove package` would be easier than downloading or writing a recipe.

I actually like @jhprinz's suggestion of having a `--add-dependencies-from-package PACKAGE` option (maybe with a more succinct name like `--deps-from PACKAGE` ?). I can update #3500 to implement that option if needed.

**Comment by msarahan** [comment]
If meta.yaml is involved, then conda build is the right way. If only run
time deps are involved, I agree with Benoit.

All this said, I do wonder if the conda develop command (part of conda
build) is what is needed here.

**Comment by benbovy** [comment]
@msarahan Yes, the following would be nice in my case:

```
$ conda create -n devenv --deps-from package
$ conda develop -n devenv ./package_repo

**Comment by msarahan** [comment]
I guess what I meant was it would be neat if conda develop could (optionally) create new envs for you - and that the way to get development environments would be to use conda-build's conda develop command, and cut the conda create step entirely.  I don't think that this is the way it is right now, but it seems like the right way to do things eventually.

```
conda develop -n devenv ./package_repo
```

would create the environment if it didn't already exist - otherwise, it would ensure that the dependencies were up to date, potentially adding new ones or even removing ones removed from the package.  The removal is of course contentious, but might be the best way to ensure that you have a good, known-working recipe, since previously installed packages would allow things to run, even if they were no longer listed in the recipe.

Opinions?

**Comment by benbovy** [comment]
Indeed, it would be nice to run conda develop only. However, I don't kown how we can get from `./package_repo` all the information needed to setup the environment (i.e., dependencies, channels) when no meta.yml is involved. A possible solution is to set it explicitly (as well as additional constraints on the versions of the packages to install) as new options of conda develop, but then it would probably end up adding a lot of conda create/install features to conda develop. Maybe I miss easier solutions (as my knowledge of conda and conda-build logic is quite limited)?

**Comment by jhprinz** [comment]
>  @msarahan  it would be neat if conda develop could (optionally) create new envs for you 

I think I expected `conda develop` to work in the way you want it to: Install and/or update packages so that you can _develop_ on your package. If that is not the case it would definitely be a good option.

I will not cover my two usecases though: 

1. I usually have a github repo I am working on that is also build into a conda package. What is (kind of) annoying is that once in a while a test on travis fails because some packages were updated (without me noticing) and I need to update my conda environment again. 

    So for this I would like some `conda build` option to update the current environment  to the latest packages matching the specifications in `meta.yml`. I think it would be useful if `conda build` would check this when building or even disallow building when your current packages do not represent what would be installed from just using `meta.yml`. All of this should work in the current environment and I assume `conda build` would be the right place to put this functionality
2. I actually need a clean environment to run tests (on travis) that has all the dependencies and at best also all the dependencies in the `test` section of `meta.yml`. I realize that the cleaner way would be to run all the tests when building and put these into the `test` section but for travis CI we decided to run these separately after the build is done. Then use the freshly build package, install it and run the tests. For these we need to recreate the test environment a second time. I assume this would be very easy to implement since conda build can already do that.

The earlier proposed `--deps-from PACKAGE` would still be nice and make sense for `conda install` or `conda update` to provide similar functionality, but it is more a convenience for cases where you know a packages dependencies are complete in providing a certain range of packages. When developing this can be helpful but it is not really what you want. It still requires a package to already exists that needs the packages you want. 

If I understand correctly then these cases are a little different from what @benbovy needs ?!

**Comment by benbovy** [comment]
I guess that the main difference from @jhprinz's usecases is that the packages I'd like to contribute are available as conda packages but they don't include any conda recipe in their github repo (the recipes are maintained either in the Continuum's anaconda-recipes repo or as separate conda-forge feedstocks).

Moreover, when I'm working on a pull request, I often prefer to run unit tests locally on multiple environments (e.g., py27, py35) before committing and pushing my commits, even if these tests will be run again automatically with CI. This way I avoid pushing too much commits like "fix tests with py27"...

It would indeed be neat if we could use `conda develop` to automatically create all these environments (at least one command for one environment), though it doesn't seem straightforward as the information needed to setup these environments is usually written in `meta.yml` (which is not directly available here) and/or in files like `.travis.yml`. A solution would be to explicitly provide that information as `conda develop` options, but IMO it feels a bit like copy/pasting the features of `conda create/install` to `conda develop`.

In the case explained here, I don't mind using the two commands `conda create; conda develop` to setup one environment, instead of just `conda develop`. The `--deps-from PACKAGE` option would avoid writing `conda create; conda remove; conda develop`.

**Comment by tjader** [comment]
It would also be useful if the command would work when multiple packages are specified.
That is, if `packageA` requires `packageB` and `packageC` and the line 
`conda install --dependencies-only packageA packageB` is run, then only `packageC` would be installed.

This behavior would be useful in a CI environment where the tests are run on heads of `packageA` and `packageB`, and not the released package.
