### ISSUE TITLE
Optional dependencies for conda packages

### ISSUE THREAD

**Issue by groutr** [conda/conda#1696]
A proposal for optional dependencies in conda packages.  Implementation of this would be relatively simple.

The proposal consists of adding a new section requirements so that it could look like

``` yaml
package:
  name: my_package
  version: 1.0.0

requirements:
  build:
    - python
  run:
    - python
  optional:
    - nice_package1
    - nice_package2
```

At the end of a conda install process, it would simply inform the user that for extra features, consider installing the list of packages in the optional section (and list them on the commandline).

``` stdout
<... snip ... >
The following packages will be INSTALLED:

    my_package: 1.0.0

Proceed ([y]/n)? y

Fetching packages ...
my_package 100% |####################################################################################| Time: 0:00:10   3.77 MB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################################################| 100%

The following packages can be installed to enable extra features in my_package:
nice_package1
nice_package2
```

Further, an option could be added to conda install to attempt to install optional dependencies as well.  It would then simply add the list of optional packages to the list of packages to install before calling the dependency solver.
So something like

```
conda install my_package --install-optional
```

would be synonymous with

```
conda install my_package nice_package1 nice_package2
```

**Comment by moorepants** [comment]
+1

**Comment by ccordoba12** [comment]
@groutr, what about something like

    run:
      - pyqt5 or pyqt

?

I think we're going to need this for packages that support both `pyqt` and `pyqt5`. Precedence will be given to the first dep.

**Comment by jdreaver** [comment]
I think it would be cool to put a reason for the dependency too:

```yaml
optional:
  nice_package1: "adds this cool feature"
  nice_package2: "adds another neat feature"
```

This would result in:

```
The following packages can be installed to enable extra features in my_package:
nice_package1: adds this cool feature
nice_package2: adds another neat feature
```

**Comment by jbednar** [comment]
+10

I was about to create an issue asking for precisely this feature, but found that there was already this request.  

Right now, conda packages include lots of "requirements" that are not at all required, which makes it very difficult to put together a minimal installation.  E.g. the matplotlib package "requires" pyqt, which is problematic in many installations because of its licensing, even though it will run just fine without pyqt (unless your own application itself requires Qt).  A more extreme example is Python itself, which currently requires readline in conda, presumably because it was linked against the readline library when building.  Readline also has license issues, as many people do not want to give the appearance (even if not true) of being virally tainted with GPL.  In my own HoloViews library we have similar issues -- HoloViews truly *requires* only Numpy and Param, but we set up conda to install Matplotlib and Bokeh plus IPython Notebook, which most (but not all!) users will want.  Right now we can only say that all users will have those add-ons, or that all users will have to explicitly install them if they want them, with no middle ground of installing them by default but allowing them to be overriden.

So, I'm all for conda installing useful packages by default, but please can we have a way to suppress them when we explicitly decide we don't want them?  E.g. ``conda install --omit-optional``, once people set up their packages to declare optional dependencies as proposed by @groutr or @ccordoba12  above? 

There might even be three categories:  required (hard dependencies), suggested (installed unless conda is told otherwise), and optional (installed only by explicit request, but suggested upon installation as proposed by @jdreaver).  That seems like it would cover what's needed...

**Comment by groutr** [comment]
@jbednar, this seem similar to what Debian and Redhat do with their package manager where packages can have different types of dependency relationships (with the depends, recommends, suggests, enhances categories).  The original idea was alert users to packages that would provide extra features for the installed package.  I was trying to avoid putting extra work on the dependency solver if possible.  Having different levels of dependencies might need a deeper discussion if it involves modifying the dependency resolution.

**Comment by groutr** [comment]
@jdreaver, that would be very beneficial too.

**Comment by jbednar** [comment]
@groutr, it would be worth having someone deeply involved in conda to think about whether there are issues with the dependency solver, but I don't *think* there would be.  I.e. the current relationships would all continue just as they are, except that for certain packages people could add additional optional ones, and some of the existing ones could be downgraded to suggestions (which could reveal gaps in other packages' declared dependencies, but if so those were always problems with the other packages, not the one actually being changed here).  I think this approach could actually significantly simplify the dependency solver's job -- if packages had a lean list of genuine core dependencies, instead of the broad kitchen-sink list of everything related to each package that they have now, then finding a valid set of installable packages to fill all required dependencies would get easier.  Same logic as before, easier problem.

**Comment by jbednar** [comment]
In any case I think we really need to solve the problem, so that we can ship customers an installation with only those packages actually required, so that they can verify the software licenses involved are only those they can agree to.

**Comment by mcg1969** [comment]
It's not clear to me that the dependency solver is affected in any way here. After all, an optional package is not a dependency!

But what if we looked at it from another perspective. Instead of organizing this in terms of optional _dependencies_, let a package have a list of optional _capabilities_. (I would say "feature" but unfortunately we use that term in other ways.) Associated with each capability is a set of dependencies that make it functional.

**Comment by mcg1969** [comment]
OK, blast it, I'm going to call this "features" because that's the right name for it. We'll figure out the disambiguation later. Regarding this proposal:
```
optional:
  nice_package1: "adds this cool feature"
  nice_package2: "adds another neat feature"
```
What if "cool feature" requires two *different* dependencies to obtain? I would suggest something like this instead:
```
optional:
  nice_feature1: 
    - description: "adds this cool feature"
    - requires:
        - package1
        - package2
  nice_feature2: 
    - description: "adds another neat feature"
    - requires:
        - package1
        - package3
```

**Comment by mcg1969** [comment]
Command line syntax for the above:
```
conda install package0+nice_feature1+nice_feature2
```
translates to
```
conda install package0 package1 package package3
```

**Comment by mcg1969** [comment]
One issue with all of this is that the passive way that options are handled. That is, we are assuming that the package somehow _figures out_ that `nice_feature1` is enabled simply because `package1` and `package2` have been installed. There is no mechanism here for _telling_ the package what options have been selected.

**Comment by jdreaver** [comment]
Great suggestions @mcg1969! 

A lot of packages dynamically enable features requiring other packages by wrapping imports in a `try` block, and just ignoring the module if there is an `ImportError`. However, I bet quite a few packages would need to be recompiled based on different optional packages, especially if the optional packages are C dependencies. The conda build farm could probably build a few variations of each package based on optional dependencies, but only if the number of options is not too large.

It would be cool if Python packages descriptions had explicit and uniform support for optional dependencies, but unfortunately that isn't the case.

**Comment by groutr** [comment]
@jdreaver https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by jbednar** [comment]
@groutr, I don't think my group ever got those extra features to be recognized for setuptools in our packages, but they must be working for someone!  In any case, they *are* working for pip -- e.g. "pip install ipython[notebook]" (which installs extra packages not installed with just "pip install ipython".   I think that's effectively what Michael is proposing for conda, and I agreed that it would be very useful.

However, pip (and setuptools?) optional packages are about providing extra packages that are *not* installed by default, and thus they address category "optional" in my proposal above.  At least for the projects I am involved in, it's much more urgent to move some of what conda currently considers "dependencies" into a different category "suggested".  The key here is that the default behavior of conda would not change for our currently supported packages -- by default, exactly the same packages would get installed whether the dependencies were listed as suggested or required.  But if given a special flag, conda would then install only the hard dependencies, not the suggested ones.  

I think this approach is distinct from and complementary to support for extra "optional" explicitly specified packages.  E.g. current conda users might be alarmed if they suddenly find all their useful tools disappearing in a new release, because we no longer consider them hard dependencies, so that they now have to explicitly install each one.  Instead, we can keep installing everything we think is useful or supported, just as we do now, but simply provide some mechanism for people to tell conda to install only the *core* or *required* dependencies.

**Comment by jbednar** [comment]
@jdreaver, yes, some of these optional packages do require recompilation -- e.g. my example of Python with and without the readline support, which I believe requires linking it against a readline replacement library (non-GPL), and thus having an entirely separate binary.  There might be a combinatorial explosion of binaries required if there are multiple such C-library options, with every possible combination of included library needing a new compiled version.   So we probably could realistically only support optional C libraries in a very few cases, such as the very important readline case.  But I would think that most such optional libraries are simply things that pure Python code wraps in "try: except:", i.e. uses if it's there, ignores it otherwise.  I would hope that keeping track of those would be straightforward.

**Comment by JanSchulz** [comment]
See also https://github.com/conda/conda/issues/793 for some discusion how this could be solved: https://github.com/conda/conda/issues/793

**Comment by kalefranz** [comment]
Optional constrained dependencies are part of conda 4.4.

**Comment by jakirkham** [comment]
Are there some docs where we can read up on how this works? Also curious how this would impact `conda-build` recipes.

**Comment by kalefranz** [comment]
> Are there some docs where we can read up on how this works?

Not yet.  We haven't even released 4.4 yet.

> Also curious how this would impact conda-build recipes.

@msarahan just merged the sister conda-build PR.  https://github.com/conda/conda-build/pull/2001

**Comment by kalefranz** [comment]
The only change is that you can add a field

```
requirements:
  run_constrained:
    - package 1.0.*
    - another-package >=2
```

which doesn't require that those packages be installed in the prefix, but if they are, it constrains the versions.

**Comment by jbednar** [comment]
So there is no option that can be passed to conda that will install the "run_constrained" packages, e.g. "conda install --optional"?  I was hoping we could list packages specifically relevant to this one, but not strictly required, so that users can automatically install them if they wish without knowing their names.

**Comment by jakirkham** [comment]
Did this go in the docs yet?
