### ISSUE TITLE
conda on Windows should use the windows network stack for proxy settings

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda#1708]
In windows, every application that connects over the internet goes through the Windows networking stack.  The proxy server settings are set in a central location in windows under 

Start → Control Panel → Network and Internet → Internet Options → Connections → LAN Settings

conda should use the same central location to use the proxy server and not require users to manually add proxy information to .condarc

**Comment by PeterDSteinberg** [comment]
@JeremyEnns @csoja It looks like we need to access these values via the windows registry in pywin32.  I don't know if I'm the right person to work on this one.  I haven't used windows since 2012 and don't think I have a windows VM now.  

See the ReadRegistryValue function on [this pywin32 help page](http://code.activestate.com/recipes/528896-simplest-registry-io/).  I think that's what we need to do.

**Comment by groutr** [comment]
I would suggest reading the registry using Python's standard library instead of introducing another dependency.

**Comment by PeterDSteinberg** [comment]
I am seeing in requests 2.8.1 that on windows requests is already respecting the settings for HTTP_PROXY in Start → Control Panel → Network and Internet → Internet Options → Connections → LAN Settings.  Could the problem observed here just be the result of an out-of-date requests module.  We are not ensuring the version of requests that is installed it seems.

**Comment by PeterDSteinberg** [comment]
@csoja I think this issue is that same as this one on conda build: [https://github.com/conda/conda-build/issues/550](https://github.com/conda/conda-build/issues/550) (out of date requests without proxy support)

The recent versions of requests respect the settings in 

Start → Control Panel → Network and Internet → Internet Options → Connections → LAN Settings

just like the HTTP_PROXY.

**Comment by kalefranz** [comment]
All recent versions of conda are now also forcing recent versions of requests.
