### ISSUE TITLE
Bogus scp package fails builds on win64

### ISSUE THREAD

**Issue by remram44** [conda/conda#1743]
What the hell is this? https://anaconda.org/anaconda/scp

An abandoned package in official channels, with only win-64 builds? This is definitely not the PyPI package of same name (which is version 0.10.2), what is it?

Please remove traps from your repository.

**Comment by msarahan** [comment]
Hi, I'm sorry you perceive this as a trap.  This is the PuTTy PSCP.exe program, repackaged.  That information is in the recipe, but it doesn't seem to show up with ```conda info scp```, nor at the link you provided.

I use this on Windows to avoid having to install scp separately (it is used in our internal build process.)

What would be a better way to name this?  I named it scp because that is the functionality it provides, as a Windows stand-in for (existing) scp on other platforms.  Would it be better to leave the package name as pscp?  I would still rename the binary inside to scp, so that the build scripts "just work."

**Comment by remram44** [comment]
How comes it has exactly 0 downloads? Is it really needed? This is definitely going to conflict with scp, and the fact that it is brought in only for one platform made this especially painful to debug.

If this is an internal tool, couldn't you name it something unique, like scp-exe-internal-conda-build, or better yet, not add it to the registry at all? Or at least not to the default channels people use?

Renaming to a correct descriptive name like pscp would be a minimum, but does it really need to be there?

**Comment by msarahan** [comment]
> How comes it has exactly 0 downloads?

It is new, and I have probably been the only one using it.  I probably installed it prior to it being made public.  Thus, 0 downloads (nothing depends on it, and my one install to get things working came from our internal test server).

> Is it really needed?

It saves me from having to install a development environment.  My setup consists of installing miniconda, then installing a metapackage that brings in (this) scp, and many other utilities for packaging on windows (gnuwin32, git_windows, Putty's plink as ssh - another one I will probably have to rename) In that, it is very convenient.  Not strictly necessary, but I think it builds nicely towards conda as a self-contained CI bootstrapping tool.

> This is definitely going to conflict with scp (which has been on Conda for nearly two years at pypi/scp, btw...

This was my bad.  I did not do my homework.  There was no scp in our anaconda recipes, and I did not look at conda-recipes.

> is the pypi repository is even official?

I'll have to get back to you on that.  I don't know.

> If this is an internal tool, couldn't you name it something unique, like scp-exe-internal-conda-build, or better yet, not add it to the registry at all?

This need not be an internal tool.  I made a package because I thought other people might find it useful.  I don't know how you came across it.  I would like to.  I'm very sorry that you found it sinister.

> with its broken patch package

This is fixed: https://github.com/ContinuumIO/anaconda-issues/issues/424 was available as patch-2.5.0.  @groutr cleaned up the recipe later (patch-2.5.9-0), but it was broken by not including the manifest, accidentally (this was the issue where patch required elevation).  Patch-2.5.9-1 has the manifest, and should work.  It has been available on win-64 for 2 weeks or so.  Sorry it took us time to fix this.  Our internal build systems have been Python 2, and now that other people are building with Python 3 core environments, we're having to go back and address some issues like this.

> the random failures unlinking the _test environment

Please link me to an issue, I'd like to investigate and make sure that we are following up on this.

> the non-functional envs

This was fixed by your PR (thanks).  Sorry it took so long for us to merge.  Conda and our whole system on Windows has not had the attention it deserves for some time.  We are working hard to change that (I'm proud of #1727), and I hope you'll see the fruits of our efforts in new releases soon.  Many of these unfortunately will not be ready in time for the coming Anaconda 2.4 release.

> does it really need to be there?

This is a subjective question.  If it makes it easier to set up CI on AppVeyor, or for anyone else to set up a Windows build build environment for even one person other than me, then I think it is a good thing.

I'm sorry you've had issues with Conda lately.  We are working hard to improve it, and we especially appreciate users like you who have contributed to improving the tools.  Please keep pointing out issues, and we'll do our best to resolve them in a timely manner.  Windows issues in particular are my responsibility.  Please ping me directly.

**Comment by remram44** [comment]
> I made a package because I thought other people might find it useful. I don't know how you came across it. I would like to. I'm very sorry that you found it sinister.

I'm using the actual scp module ([pypi](https://pypi.python.org/pypi/scp)), which works fine everywhere except on win-64 where it pulls yours instead and fail miserably. I had to change my dependencies to `scp !=0.65` to avoid it, since I don't know of a way to restrict the dependency to some channel (e.g. "not anaconda").

**Comment by msarahan** [comment]
The scp package has been removed.  I hope this causes you no further trouble.  A pscp package is available, should you ever need this functionality.  Please close this issue if it has been resolved.

**Comment by remram44** [comment]
Awesome! Thank you very much!

I will close this issue as requested.
