### ISSUE TITLE
Document inequality specs can't handle build numbers

### ISSUE THREAD

**Issue by ahmadia** [conda/conda#1750]
If I want to specify `foo >= 0.1.2-3`, where `-3` is it's build number, this isn't currently possible.  Is this a desired feature?  Regardless, we should document that this isn't currently possible.

**Comment by mcg1969** [comment]
When implementing my pruning pass I was tempted to refactor the VersionSpec object a bit. The result would allow for build numbers in inequalities as well as more flexible "or" constraints. I'm pretty sure the parsing pass will have to be careful here. For instance, I don't think `>= 0.1.2-3` will work, because the splits happen on whitespace. (After all, what if some package with a weird version convention uses a dash?) So it might have to be `>= 0.1.2 3`, as non-intuitive as that may seem.

**Comment by mcg1969** [comment]
In any case, if an opportunity presents itself I can work on a VersionSpec replacement and the changes to the parsing code. It would simplify my pruning code a bit but I must confess the savings now would be somewhat minor. But I would defer to the team on prioritizing such a thing.

**Comment by kalefranz** [comment]
In conda 4.4, you would specify this as

    conda search 'foo>=0.1.2[build_number=3]'

or

    conda search "foo[version='>=0.1.2', build_number=3]"
