### ISSUE TITLE
cloning leaves out the pinning

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#1769]
I just cloned an numpy 1.9.\* pinned environment like so:

``` bash
$ conda create -n py35clone --clone py35
Fetching package metadata: ....
src_prefix: '/usr/local/python3/miniconda/envs/py35'
dst_prefix: '/usr/local/python3/miniconda/envs/py35clone'
Packages: 41
Files: 3994
Linking packages ...
[      COMPLETE      ]|#########################################################################| 100%
#
# To activate this environment, use:
# $ source activate py35clone
#
# To deactivate this environment, use:
# $ source deactivate
#
```

but the pinned file was not copied over. System: OSX 10.10.5

**Comment by megies** [comment]
Can confirm, just wanted to report the same.

**Comment by megies** [comment]
Any comments by the devs/maintainers? Is this considered a feature? For me, pinning is essential to usage of anaconda envs and thus should be a part of making an exact clone (especially since #1967 has kept breaking my envs frequently for months with numpy updates not making sure that all packages compiled against numpy were still compatible).

**Comment by michaelaye** [comment]
I would say that cloning currently is not reliable, at least I cannot rely on it so I prefer to do things by hand for now. Even using a package list file, I don't get consistent envs, see #2315 and #2316
