### ISSUE TITLE
conflicting hints should be more exhaustive.

### ISSUE THREAD

**Issue by Carreau** [conda/conda#1776]
When upgrading to python 3.5, 
instead of showing all the list of package that conflict with python 3.5 conda show only 1. 
which take a long time, for a user to decide for this package and re-try.

```
$ conda update --all python=3.5
Fetching package metadata: ....
Solving package specifications: ....................................................................................................................................................................................................................................................................................................................................
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]#############| 100%


Hint: the following packages conflict with each other:
  - beautiful-soup
  - python 3.5*

Use 'conda info beautiful-soup' etc. to see the dependencies for each package.

(start at line 1 again, with numba, then libdynd-python, ...etc)
```

it would be nice to have : 

```
Hint: the following packages group conflict with each other:
  - python 3.5*
conflict with:
  - numba
  - beautiful-soup
  - libdyn-python
  - ... 
```

**Comment by msarahan** [comment]
@mcg1969 is this something you are familiar with in Conda?  Any ideas on feasiblity/ease of implementation?

**Comment by Carreau** [comment]
My guess is it's around [here](https://github.com/conda/conda/blob/74f2909046495d3f3982301f1f833aa8deddbd5a/conda/resolve.py#L910-L941), and that you do not want the `minimal_unsatisfiable_subset`

**Comment by mcg1969** [comment]
I definitely see the challenge here. In my pruning PR, I deliberately punted if I encountered an unsatisfiable hint. That's because generating hints is actually not easy _in general_. However, there were some cases where I felt a couple of heuristics would give us good results. For instance, I think it would be feasible to print out a list of all packages that are failing on at least one dependency.

**Comment by asmeurer** [comment]
The hint generating code is already there, and works fairly well (but if you can figure out other ways to generate "hints", that's great too). For me, when I did this (update to Python 3.5), it wasn't that big of a deal because any package that didn't have a Python 3.5 version I rebuilt anyway, so doing it in multiple steps didn't save a ton of time. It used to generate all possible hints, but that was slow, but there is a faster algorithm in place now, so maybe it can go back to generating all hints (at least optionally). The hint generation basically bisects solve2, so the faster that it is, the faster that it will be. I'm unsure how to modify the [bisection algorithm](https://github.com/conda/conda/blob/74f2909046495d3f3982301f1f833aa8deddbd5a/conda/logic.py#L631-L737) to give all possible minimal unsatisfiable subsets. 

Good luck!
