### ISSUE TITLE
The anaconda metapackage should not pull from other channels

### ISSUE THREAD

**Issue by mcg1969** [conda/conda#1781]
See this issue here: https://github.com/conda/conda/issues/1778

This is fixed in master already, however, it was caused by the following confluence of factors:
1. The user has additional channels enabled besides the default.
2. Those channels contain packages with the same name as found in the main channel and included in the anaconda metapackage.
3. Those packages have additional dependencies not present in anaconda.
4. Those dependencies are not added to the search list, because anaconda links to _exact builds_ (strictness=3), and the current tagged releases of conda do not add lower-level dependencies in such cases. This is fixed in master, but has been purposefully left unfixed because it degraded performance.

The selling point of the anaconda metapackage is that it points to a set of curated and _tested_ packages. If a user shadows those packages with his own channel, then he's no longer getting the packages that anaconda is certifying, and we should not be unintentionally endorsing those alternate builds.

My contention, therefore, is that anaconda should _only_ refer to the exact packages supplied in the main channel, not identically named versions of packages found in other channels.

**Comment by marscher** [comment]
"anaconda" meta-package should refer to the main channel - makes total sense to me. Do you intend not to release this fix, because it hurts performance? I'm experiencing a lot of trouble with conda recently, because of this issue (have a custom channel shadowing for instance boost with a newer version), so it would be really helpful if you release it anyway and fix the performance regression in the version after.

**Comment by mcg1969** [comment]
No fix has been developed... This is just a discussion at this point, and I am not a core conda developer. So I appreciate the feedback! Indeed, as I thought about it more, I realized that the shadowing problem is not unique to Anaconda. I do think that at the very least, a warning should be given if a dependency is pulled from a "newer", unintended channel.

**Comment by mcg1969** [comment]
@marscher, if you're referring to fix  https://github.com/conda/conda/issues/1778, that has already been merged into master and will be pushed out with the next release. That should fix the more serious issues with shadowing. But it will still be the case that `conda install anaconda` will install packages that the Anaconda developers themselves did not intend. That's the purpose of this discussion here; to discuss what should be done to prevent or warn against that.

**Comment by ijstokes** [comment]
I think there are a few considerations here:

* dependency specifications should have the option of saying from which channel they expect a specific package to come from, rather than "from whatever set of channels you happen to have setup"

* dependency specifications should provide a mechanism to state exactly *or* optionally which channels should be part of the package search (and those channels themselves can be specified either explicitly with a full URL or partially with just a channel name).

Here is an example showing off both these ideas in a format that is **not** currently valid conda JSON:

```json
channels:
    - anaconda
    - r
    - http://anaconda.org/ijstokes

requirements:
  build:
    - python
    - setuptools
    - anaconda/numpy
  run:
    - python
    - anaconda/numpy
```

With an option for "exclusivity" of channels by using `exclusive_channels:` instead of `channels`, meaning **only** that listed set of channels will be considered (ignore `.condarc` and any `defaults`).

**Comment by goanpeca** [comment]
@ijstokes I am :+1:^:100: 

for:
```
  build:
    - python
    - setuptools
    - anaconda/numpy
  run:
    - python
    - anaconda/numpy
```

I really find weird that conda takes all the packages in all channels and dumps them together when matching specs....

**Comment by goanpeca** [comment]
Conda should have a `--strict` flag or something so that if a package is found in several channels then it should complain, cause how does conda know which one should it use?

**Comment by ijstokes** [comment]
@goanpeca as they say in France *"moi aussi"*

**Comment by mcg1969** [comment]
I would actually go further. I think that it should *not be permitted* for Package A to depend on a version of Package B that occurs "higher up" in the channel list, without *explicit assent* from the user. That can take the form of a flag, like `--allow-shadowing`, or a warning followed by a `Y/N` confirmation at the command line.

**Comment by goanpeca** [comment]
:+1:

**Comment by bkreider** [comment]
> I would actually go further. I think that it should not be permitted for Package A to depend on a version of Package B that occurs "higher up" in the channel list, without explicit assent from the user.

+1.  I like the ability to slipstream packages that 0.1% of the time when it is actually needed, but it's so dangerous it shouldn't happen automatically.  

> or a warning followed by a Y/N confirmation at the command line.

I'll match you and raise.  I would go further and not allow confirmation on the command line, because most people just hit Y, because they have an actual task they need to work on and just want it to work.  Our job is to remove cognitive load from people.  Maybe the question/warning is "Refusing to shadow .... Please set --allow-shadowing if you want to replace the specified file.  continue? [Y/N]"
