### ISSUE TITLE
Error in installing packages on Anaconda

### ISSUE THREAD

**Issue by collawolley** [conda/conda#1790]
Hi, I uninstall my old Anaconda and installed the latest anaconda. unfortunately, I have not been able to install my preferred package. an attempt at installing gensim and scikit-learns gave many errors:
i.e. ensuring that c\users\anaconda\library\bin is on your user path environment variable
"" was expected at this time
error: error: post-link failed for : conda-env-2.4.4-py27_1

I am using windows 7, 64 bit. and this is the content of my user path variable: C:\Users\user\Anaconda2;C:\Users\user\Anaconda2\Scripts;C:\Users\user\Anaconda2\Library\bin;C:\Users\user\Anaconda\Library\bin

I will appreciate any help.

Thanks
Colla

**Comment by msarahan** [comment]
This issue should be fixed.  The relevant fixed packages were:

python-2.7.10-4.
python-3.4.3-4
python-3.5.0-3

conda-env-2.4.4 (build 2)
menuinst-1.2.2

The fix is that the conda-env post-link script has been removed.  It has been replaced by a modified Lib/site.py file in each Python installation, plus a library_bin.pth file in each Python installation.  The combination of these lead to Library/bin being added to os.environ["PATH"] for any Python process.  Any programs you install that end up in Library/bin (for example, patch) will still not be on PATH for older installations.  You can either modify PATH to add Library/bin yourself, or uninstall and reinstall using a new installer (Anaconda >= 2.4.0; Miniconda >= 3.18)

I'm closing this issue, but please reopen it if you are still having issues.
