### ISSUE TITLE
Issues with Conda-Env 2.4.4 

### ISSUE THREAD

**Issue by somubasu** [conda/conda#1792]
When trying to install numpy getting the following:

The following NEW packages will be INSTALLED:

    conda-env: 2.4.4-py35_1

Proceed ([y]/n)?

Linking packages ...
not was unexpected at this time.                                         |   0%
Error: Error: post-link failed for: conda-env-2.4.4-py35_1

The same is there if trying to install PIP as well.

**Comment by msarahan** [comment]
Sorry, this is a known issue: conda env build 1 tried to introduce a post-link script to add Library/bin to PATH for users, so that Matplotlib and spyder in particular could resolve their DLL dependencies.  That post-link script has an error on Python 2.7.  https://github.com/ContinuumIO/anaconda-issues/issues/509

The fix right now is to manually remove the .conda-env-post-link.bat script from (your install folder)\Scripts and force installation of an older build of conda-env, any time you use Conda:

```conda install scikit-image conda-env=2.4.2```

If you do not force the older version of conda env, it gets updated automatically and causes this issue again.

We are working on testing a better fix not involving the post link script, and hope to release this later today.

**Comment by msarahan** [comment]
This issue should be fixed.  The relevant fixed packages were:

python-2.7.10-4.
python-3.4.3-4
python-3.5.0-3

conda-env-2.4.4 (build 2)
menuinst-1.2.2

The fix is that the conda-env post-link script has been removed.  It has been replaced by a modified Lib/site.py file in each Python installation, plus a library_bin.pth file in each Python installation.  The combination of these lead to Library/bin being added to os.environ["PATH"] for any Python process.  Any programs you install that end up in Library/bin (for example, patch) will still not be on PATH for older installations.  You can either modify PATH to add Library/bin yourself, or uninstall and reinstall using a new installer (Anaconda >= 2.4.0; Miniconda >= 3.18)

I'm closing this issue, but please reopen it if you are still having issues.

**Comment by j9ac9k** [comment]
Chiming in to confirm that things are fixed with a fresh install of Miniconda

conda update python attempted to downgrade my python version to python-3.5.0-1, however 

conda update conda-env 

followed by

conda update menuinst did the trick.

Thanks.

**Comment by msarahan** [comment]
Thanks for the report.  That may help us solve the unsatisfiable dependency issues some people are having.
