### ISSUE TITLE
repodata.json in Channel and Package Metadata are out of Sync/Differ

### ISSUE THREAD

**Issue by jhoare** [conda/conda#1797]
I have noticed that the metadata, specifcally regarding package dependencies, for some particular packages in the channel repodata.json differs from the metadata in the 'info/index.json'  file that is in the package. Two examples I have encountered are the 'pip' packagte, and the 'matplotlib' package. 

What this means is the dependency tree that is built when online (which uses the channel repodata.json) will differ when running offline, which (I believe) uses the index.json within packages. I believe this is the cause of several other bugs which are posted (selection that I quickly found): #1768, #1660 

So it appears that the metadata is being updated in the repodata.json on the official conda channel, but the packages are not being rebuilt with the newer, updated metadata. 

Here's an example, of the 'pip' package: 

From the repodata.json file at: https://repo.continuum.io/pkgs/free/linux-64/repodata.json

```
"pip-7.1.2-py27_0.tar.bz2": {
  "build": "py27_0",
  "build_number": 0,
  "date": "2015-08-24",
  "depends": [
    "python 2.7*",
    "setuptools",
    "wheel"
  ],
  "license": "MIT",
  "md5": "71c111b98dfa27bb8d8a727a604ff0b2",
  "name": "pip",
  "requires": [],
  "size": 1434745,
  "version": "7.1.2"
},
```

And here is the index.json file: 

```
{
  "arch": "x86_64",
  "build": "py27_0",
  "build_number": 0,
  "depends": [
    "python 2.7*",
    "setuptools",
    "wheel 0.24.0"
  ],
  "license": "MIT",
  "name": "pip",
  "platform": "linux",
  "requires": [
    "python 2.7",
    "setuptools 18.1",
    "wheel 0.24.0"
  ],
  "subdir": "linux-64",
  "ucs": 4,
  "version": "7.1.2"
}
```

You'll see that the requirements are different, the repodata.json states only that pip requires on wheel, but the index.json file in the actual pip package requires wheel version 0.24.0. 

Matplotlib has a similar issue where the requirements have differing version number requirements (freetype 2.5.2 is required by the index.json while the repodata.json claims 2.5.*)

So, I believe this bug is related to conda, but is really an issue of the packages that are maintained in the official conda channel.

**Comment by frol** [comment]
I hit the same issue. How on earth could this happen?! I have tried to use `conda index` on my local packages cache with pip-7.1.2 and the resulting `repodata.json` is correct!

**Comment by oliparcol** [comment]
I had the same issue. I think the problem is more on anaconda side than directly related to conda: https://groups.google.com/a/continuum.io/forum/m/#!topic/anaconda/5GsiFhl4zt8

**Comment by mnazbro** [comment]
This problem is definitely related to Continuum's repo rather than Conda itself

**Comment by jhoare** [comment]
Is there a more appropriate place to file this bug?

**Comment by msarahan** [comment]
Pinging @ilanschnell

**Comment by ilanschnell** [comment]
Well, `repodata.json` should be the true source of truth, and I thought that when being in offline mode, the cached version of `repodata.json` (in `<root>/pkgs/cache/*.json`) were used.

The reason for this discrepancy (`info/index.json` in conda packages vs. `repodata.json`) has historical reasons, as the system which builds packages for the default conda repo (`repo.continuum.io`) used to create `repodata.json` independent of the content of the conda packages.

**Comment by mcg1969** [comment]
I consider this a feature not a bug. I think there are going to be a variety of situations where the metadata needs correction but rebuilding is impractical or otherwise unnecessary. The conda channel developer ought to have the prerogative to made adjustments to their `repodata.json` file to suit.

That's not to say that this approach is without challenges, and indeed we encountered one such challenge today with 3.19.2---which is why we skipped right to 3.19.3 :-)

**Comment by mcg1969** [comment]
In fact we just merged this PR today to handle situations where the package metadata is incomplete or out of date: https://github.com/conda/conda/pull/2107

**Comment by frol** [comment]
@ilanschnell @groutr @mcg1969 @msarahan 

May I ask you NEVER update `repodata.json` "manually"? Today this thing is broken in another place: python package in the online `repodata.json` requires `openssl=1.0.2g`, while the package includes `openssl=1.0.2d` (`d` instead of `g`) dependency. The "funny" part here is that instead of an error message I got a crash in conda 4.0.5:

```
$ conda create -n test --offline --unknown python
Fetching package metadata: 
Solving package specifications: .
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/usr/local/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    update_deps=args.update_deps)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/plan.py", line 413, in install_actions
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 875, in install
    pkgs = self.solve(specs, len0=len0, returnall=returnall)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 909, in solve
    dists, new_specs = self.get_dists(specs)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 399, in get_dists
    specs, removes, optional, features = self.verify_specs(specs)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 391, in verify_specs
    bad_deps.extend(self.invalid_chains(ms, filter))
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 359, in invalid_chains
    return chains_(spec)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
...
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 351, in chains_
    if spec.name == top or self.valid(spec, filter):
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 299, in valid
    return v_(spec)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 287, in v_
    return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fn_(spec)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 290, in v_ms_
    return ms.optional or any(v_fn_(fn) for fn in self.find_matches(ms))
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 553, in find_matches
    ms = MatchSpec(ms)
RuntimeError: maximum recursion depth exceeded
```

NOTE: you will get the crash only if you do **NOT** have openssl=1.0.2d in your local cache.

**Comment by mcg1969** [comment]
I'm afraid the utility of updating the metadata outweighs the costs.

The cause of this crash however has been fixed in master.

**Comment by mcg1969** [comment]
OpenSSL in particular is important to update on the fly, because of its security implications.

**Comment by msarahan** [comment]
but surely we should never pin openssl so specifically?

**Comment by mcg1969** [comment]
I could see relaxing this to `>=`, indeed.

**Comment by frol** [comment]
> I'm afraid the utility of updating the metadata outweighs the costs.

Can you update the package included metadata also then?

**Comment by mcg1969** [comment]
Yes. We've talked about updating the packages on the server to incorporate any of these metadata hotfixes. I don't think that will prevent most of the issues people are seeing; with the exception of `conda index` (a known issue), `conda` trusts `repodata.json` over anything found in the `.tar.bz2.` files. 

But that still leaves the situation where the copies of packages that are already downloaded will have metadata that differs from what is in the cloud. _That's_ the real issue here that we have to be careful with, and why we don't want to update metadata _too_ often.

**Comment by mcg1969** [comment]
Instances where metadata hotfixes are the only solution:
- Package `A-1.0-0.tar.bz2` depends on package `B` (no version qualifier). Package `B-2.0-0.tar.bz2` is released, and it is discovered that it causes this particular `A` to break. The first thing we need to do is create a new version or build of `A` that either fixes the problem or includes a constraint `B <2.0`. But we still need to retroactively update the metadata for build `0` to include the constraint `B <2.0`. Otherwise, when `B` is updated for other reasons, `A` will break.
- Package `B 1.0.1` is discovered to have a critical security vulnerability and must be *removed* from the repository. This breaks any package that has a hardcoded dependency on `B 1.0.1`, so the metadata needs to be corrected (and presumably, the packages re-tested against `B 1.0.2`).

**Comment by frol** [comment]
> But that still leaves the situation where the copies of packages that are already downloaded will have metadata that differs from what is in the cloud.

It is even WORSE now! The downloaded and **installed** packages cannot be installed again in the offline mode due to the fact that "correct" dependencies are available *only* online.

**Comment by mcg1969** [comment]
Can you offer a specific example of your problem? In fact, you ought to have cached copies of the downloaded `repodata.json` files alongside the cached copies of the downloaded packages.

**Comment by mcg1969** [comment]
Again, we acknowledge that `conda index` is not working properly, because it is not incorporating this cached metadata. But if there are other instances where `conda` is favoring the package metadata over the `repodata.json` data, those are bugs that need to be corrected as well.

**Comment by frol** [comment]
@mcg1969 As I have shown above, `conda create` doesn't seem to take those cached `repodata.json` into account.

**Comment by mcg1969** [comment]
Thanks @frol, I'll take a look. If you can get to it before I can, can you try adding `--use-index-cache` to your command to see if that fixes it?

**Comment by mcg1969** [comment]
Actually, @frol, I can reproduce the traceback above rather easily here, but it's actually not caused by the metadata differences.

**Comment by mcg1969** [comment]
The traceback itself seems to be caused by the `--unknown` flag in particular. I get a "packages missing" error if I remove it. On the other hand, if I use `--use-index-cache` instead of `--offline`, I get a successful result. I'm afraid I'm not sufficiently familiar with the purpose of the `unknown` flag, nor do I understand the full consequences of the `offline` flag. I think I will file separate issue however since it doesn't seem to be a function of the metadata conflict.

**Comment by frol** [comment]
@mcg1969 `--use-index-cache` doesn't help. The reason I think the issue is related to the metadata difference is that when I have `openssl=1.0.2d` in my local cache, `conda create` in the offline mode installs it (instead of a newer `g` one).

**Comment by mcg1969** [comment]
It wouldn't surprise me if the metadata differences exercise the bug. And if your cache has different packages than mine it would explain why our behavior differs. But I can reproduce the traceback without it as well, and that needs to be fixed regardless of the issues with metadata.

**Comment by frol** [comment]
Hmm, `--use-index-cache` instead of `--offline --unknown` seems to solve the issue for me!

**Comment by mcg1969** [comment]
Oh, good. But I don't see why `offline` should behave differently. And what is `unknown` supposed to accomplish for you?

**Comment by frol** [comment]
It seems that `--use-index-cache` is not a very old command (or I missed it somehow) and we have been using `--offline` + `--unknown` for over a year now (solving ocasional inconsistences in repodata vs local packages metadata). The goal I tried to achieve is being able to create conda envs at a "boot step" in my Docker containers while it is assumed that I have all necessary packages in cache, and I wanted to avoid unnecessary (and, in case of lack of the Internet connection, impossible) fecthing online repodata.json.

P.S. It would be probably nice to mention `--use-index-cache` in the documentation to the `--offline` since the former is probably what most users would like to use instead of `--offline`.

**Comment by mcg1969** [comment]
Agreed re: the documentation. However, it looks like `--use-index-cache` still *tries* to go online for some reason---perhaps it does so for channels that are not in the cache yet.

**Comment by kalefranz** [comment]
Now fixed.
