### ISSUE TITLE
Conda install --no-deps takes a very long time

### ISSUE THREAD

**Issue by srossross** [conda/conda#1814]
"Solving package specifications" takes about a minute or two when I have explicitly stated `--no-deps`

```
Fetching package metadata: ........
Solving package specifications: ...........
```

**Comment by srossross** [comment]
Any comment here?

**Comment by mcg1969** [comment]
Because on your [related issue](https://github.com/conda/conda/issues/1919), I spent some time understanding exactly what effect `--no-deps` has.

The way it is currently implemented, the first thing that `conda` does is compute the full solution *as if that flag was not specified.* Then it filters out all of the dependencies from the install solution. So this means that `--no-deps` isn't going to speed things up at all.
