### ISSUE TITLE
Conda should not update itself so much

### ISSUE THREAD

**Issue by bryevdv** [conda/conda#1830]
This behavior is undesirable and I have seen other people complain about it as well:

```
bryan@0199-bryanv (git:master) ~/work/bokeh/examples/charts/file $ conda install tornado
Remote site alias https://api.anaconda.org does not exist in the config file
Fetching package metadata: ..............
Solving package specifications: ..................
Package plan for installation in environment /Users/bryan/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.18.5               |           py34_0         179 KB

The following packages will be UPDATED:

    conda: 3.18.3-py34_0 --> 3.18.5-py34_0

Proceed ([y]/n)? 
```

What I want to know is that there is no new  version of tornado, not have to deduce that by noticing that it instead is going to update conda without my asking.

**Comment by groutr** [comment]
I agree that this is undesirable behavior.

**Comment by jseabold** [comment]
Is there some way to avoid conda from updating itself? pip, for example, will just warn you that you are not using the latest version.

**Comment by mingwandroid** [comment]
In `~/.condarc` add:
`auto_update_conda: false`

**Comment by jseabold** [comment]
Ah, thanks. Any discussions on making that the default behavior?

**Comment by mingwandroid** [comment]
I wouldn't have thought that was the desirable default behavior.

**Comment by jseabold** [comment]
The premise of this issue is that it is undesirable.

If conda were a bit more stable, I would think it more desirable, because upgrading can usually fix some show-stopping issues. OTOH, upgrading conda has broken previously working things for me on more than one occasion.

Maybe it's just down to a personal preference, but I prefer the `pip` method of letting the user decide.

**Comment by mingwandroid** [comment]
This is a decision for @kalefranz, there are important pros and cons either way.

**Comment by kalefranz** [comment]
It's been the default behavior for a while. At least now there's a way to stop it. With the pros and cons either way, we need to be deliberate and careful if/when we change it. In general this is a great discussion because I haven't fully thought through what that even looks like. 

Also, this exact issue is one of the reasons we're starting a conda canary program with 4.2.0.

**Comment by jseabold** [comment]
Oh excited to hear about conda canary. I wrote an e-mail after my last upgrade experience partly to ask about just such a thing IIUC but never sent it. Any links to discussions?

**Comment by kalefranz** [comment]
Conda canary blog post
https://www.continuum.io/blog/developer-blog/what-conda-canary
