### ISSUE TITLE
Relocatable conda environments

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1845]
I had a good conversation with @airnandez from CNRS IN2P3 French supercomputing center.  They are big Anaconda fans, but are blocked in some areas in their ability to use it because of how software gets provisioned onto their cluster.  They need to create the conda environments in one file system with a path prefix `/a/b` then move to `/c/d` on the "deployed" system.  There is some good discussion about this issue in #361 and @airnandez and I came up with some observations about `--clone` and `conda create` that make me feel like it should be feasible to package up an environment in a way that it can be relocated via some intermediate mechanics.

**Comment by ijstokes** [comment]
@kalefranz giving you a mention on this since I see this as a high impact low effort low risk new feature for conda.

**Comment by kalefranz** [comment]
I didn't read all of #361, but the big obvious elephant in the room is the inability to properly handle post-install scripts (of which, I'd note, the wakari deploy system severely and serially abuses).

It would be awesome if we could do this, but it will take a LOT of thought to get right.  We have to consider both windows AND unix. If people have implementation ideas, feel free to leave them in this thread...

**Comment by ijstokes** [comment]
@eriknw has written a script that partially does this.

In thinking about it, `conda create --clone` effectively "relocates" an environment, without the removal of the original.  But that could easily be added in, I think.

**Comment by mcg1969** [comment]
I like the idea of using the `clone` functionality to pull this off. I'm not convinced it is possible to "relocate" the environment in-place, particularly if there are post-install scripts. But a copy & delete seems reasonable.

**Comment by ijstokes** [comment]
It seems to me that Conda (or at least some part of the Anaconda installer) already has all the mechanics required to get the paths correct in all the necessary places for an arbitrary installation location.  This makes me think there could even be some way to "fix" the paths of an Anaconda installation if someone were to do:

```
mv /Users/jsmith/anaconda /opt/Anaconda40
```

**Comment by kalefranz** [comment]
Actually, that's a really good point. `conda fix $PREFIX` or something like that. All the machinery is already there. Just have to hack in at the right place.

**Comment by airnandez** [comment]
That is good news. I would be happy to know more about this and help testing this feature.

We are distributing a [binary version](https://github.com/airnandez/lsst-cvmfs) of the software framework for the [Large Synoptic Survey Telescope](http://lsst.org), which uses Anaconda (currently, `conda v4.0.8`). For some users, it would be really helpful to be able to relocate this binary package to their preferred location in their own computers. This is currently not possible because we don't know how to easily and reliably relocate Anaconda. If this relocation is now possible, that's great news and it would be very helpful.

I would add that in our particular case, we are mainly interested in providing a mechanism for the end user to relocate a **read only** copy of Anaconda. Neither the original Anaconda nor the relocated one is meant to be modified in any way by the end user, but if that's also possible (for instance for adding or upgrading a package via the `conda` command) it would be great.

Any guidance for testing this feature would be appreciated.

**Comment by alexbw** [comment]
Any progress here? We're interested in packaging up an anaconda install and then tarring and scping it to a server with a different path to use it.

**Comment by ijstokes** [comment]
@kalefranz you asked for implementation ideas: I'm only being a little bit funny, but:

```
perl -p -i -e 's#/old/path#/new/path#g; `grep -rl /old/path /old/path`
```

**Comment by kalefranz** [comment]
I didn't realize until just now that #3097 had (currently) 51 up votes.  While this issue is technically older, I'd rather leave #3097 as the open issue.  Google probably likes it better.

**Comment by kynan** [comment]
I think this is the more relevant issue @kalefranz
