### ISSUE TITLE
Fallback procedure to add to conda's repertoire 

### ISSUE THREAD

**Issue by rsvp** [conda/conda#1865]
If a package is pip-installable, why would it be unavailable on conda? For example: **boto3** which is slowly replacing _boto_ heavily used for Amazon AWS. 

Currently conda suggests a search on anaconda.org -- however, to use an offered package from a random user poses security risk for code such as boto3 which transmits credentials. 

What would the difficulty be in having conda call pip internally for package installation, so that the client does not have to set up a virtualenv environment. Also it is not clear whether one should use pip within a conda environment without breaking its infrastructure. 

Once explained, I would be most happy to update the documentation, or modify the exception case when a package is not within conda's reach. This must be a frustration or FAQ for many.

**Comment by rmcgibbo** [comment]
- There's no big problem with `pip`-installing into your conda environment.
- It's also pretty straightforward to make your own conda packages -- this is why so many of them are on anaconda.org. Most of this is done automatically for you with `conda skeleton`.
- Many pip packages [don't accurately declare](https://mail.python.org/pipermail/distutils-sig/2015-October/027161.html) their build and runtime dependencies, which makes it impossible to directly translate packages from PyPI into conda packages without double checking everything.

**Comment by frol** [comment]
> There's no big problem with pip-installing into your conda environment.

The problem is that you cannot write a recipe with the dependencies from pip. For example, I have a project that depends on `boto3`, in this case I cannot use conda recipe & conda-build, and I cannot upload my package on Anaconda.org, unless I also package boto3 (or find it in someones repo, but then you must hope that that package won't get broken or deleted in future...).

> It's also pretty straightforward to make your own conda packages...

I support @rsvp's opinion. I've been with Conda for around a year now and it is really frustrating that instead of easy and straightforward:

```bash
$ conda install boto3
```

@rmcgibbo Don't you think that `conda install` is more straight than building a package "from scratch"?

You have to bump your head over a heap of bugs in conda-build (I've hit dozens), anaconda-client (binstar, anaconda-server - fortunatelly, they stopped renaming this package for now), and then maintain your packages... [Don't even try to submit a package to conda-recipes](https://github.com/conda/conda-recipes/pulls) (95 PRs are there already, and even simple package-upgrade PRs get stuck in there).

> Many pip packages don't accurately declare their build and runtime dependencies, which makes it impossible to directly translate packages from PyPI into conda packages without double checking everything.

If pip can manage the badly declared dependencies, so can conda do also! So it is a bad argument. There are only a couple of projects with really messed up dependencies and build process (numpy, scipy, sklearn, ...), but 99% of Python packages are plain, and in the worst case you may pass dependencies right after the package name, e.g. `conda install boto3+botocore,jmespath`, or even give up on auto-installing the dependencies, but just list them afterwards, so user can just copy the list and install & freeze them himself.

**Comment by rmcgibbo** [comment]
There are a lot of technical differences between pip and conda that make this challenging. But fortunately, conda is open source, so the sky is the limit if you want to fork conda and improve the pypi (or cran, or cpan) interoperability.

**Comment by rsvp** [comment]
@frol focusing just on a particular package, like **boto3**: how does one can "petition" to get inclusion into conda (with the dependencies carefully curated)? Who are the curators, and how are they directed contacted?

@rmcgibbo Open source for conda is good, however, I do not believe that modifying the code will change the behind-the-scenes human *curation* selection process.

**Comment by frol** [comment]
@rsvp From my understanding, the most close to the official packages repo is [conda-recipes github repo](https://github.com/conda/conda-recipes). I do pull-requests there (e.g. [PR #399](https://github.com/conda/conda-recipes/pull/399), [PR #490](https://github.com/conda/conda-recipes/pull/490)), but even a merged package doesn't automatically go into anaconda.org official repo. You may ask somebody there, so they add it to the 'magic list'.

**Comment by rmcgibbo** [comment]
I believe they use their own internal system for their recipes which is not directly coupled to the `conda/conda-recipes` github repo.

OTOH there are a number of community-driven recipe repositories like https://github.com/omnia-md/conda-recipes, https://conda-forge.github.io/, https://github.com/ioos/conda-recipes that maintain recipes and the build infastructure to automatically build packages and upload them to anaconda.org.

**Comment by frol** [comment]
@rmcgibbo It is just like saying "Oh, Debian is great, but if you need the package, please, go and build it yourself, or install Ubuntu, or you can always mix the packages from their repos". For me, the solution of missing packages in Debian/Ubuntu was found in Arch Linux (Gentoo is also great), where it is hard to find something that isn't there. Now, conda is Debian/Ubuntu, and pip is Gentoo. With pip, you can even install packages right from a git repo, or a zip archive.

At Salford Systems, we have to maintain [49 open-source packages](http://anaconda.org/salford_systems/) (though we try to contribute back as much as possible), which otherwise could have been in the main repo.

**Comment by rmcgibbo** [comment]
Don't get me wrong, I'm all for getting more packages in the main repos. But last time I checked, I wasn't paying Continuum (a for-profit company) a dime for all the services they provide. So it's great to say "hey it would be nice if you could add <package x> to the default channels", but you can't reasonably demand anything more than that unless you want to pay, or do it yourself.

**Comment by frol** [comment]
@rmcgibbo I don't demand either, I have pointed out that we have been working on conda infrastructure for a year already, and contributed as much as we can, but your first reply was so much protective, so I thought that you don't like the idea at all.

**Comment by kalefranz** [comment]
from https://github.com/conda/conda/issues/931#issuecomment-284102860

> There was a brief period of time where conda actually did fall back to pip, and that change was quickly reverted. (This was several years ago.) The fallback behavior has some pretty disastrous unintended consequences.

> At this point, what's more possible would be for conda to directly install wheels from PyPI. If there's community interest in that, I'd encourage discussion directly exactly toward that feature in a new issue.
