### ISSUE TITLE
Pyplot crashes in windows 10 powershell

### ISSUE THREAD

**Issue by mountaindust** [conda/conda#1870]
I'm running Python 3.5.0, Anaconda 2.4.0 (64-bit) on Windows 10. All packages are up to date as of 11/29/2015 4:55pm EST.

To reproduce:
1. Open Windows PowerShell.
2. Start ipython
3. Enter: "import matplotlib.pyplot as plt". A message appears: "Qt: Untested Windows version 10.0 detected!
4. Enter: "plt.plot([1,2,3]). (Out line shows a matplotlib.lines.Line2D object)
5. Enter: "plt.show()". A window appears with the plot as expected. However, wait a few seconds (less than a minute typically), and a popup window will appear saying that Python has stopped responding. Ipython then crashes, closing the plot window and dumping you back to the command prompt.

This problem is NOT reproduced using the Anaconda Prompt or IPython from the start menu. When a regular command prompt is used, you get the same problem.

**Comment by msarahan** [comment]
This is happening because some other Qt version is getting picked up before Anaconda's.  Neither the Anaconda prompt nor IPython from the start menu have issues because they are prepending entries to PATH for their processes.  This is done when activating environments, so any activated environment should also not have issues.

For the root environment, you have two options:
1. Hack (root installation)/Lib/site.py (see https://groups.google.com/a/continuum.io/forum/#!searchin/anaconda/pyqt$20dll$20error/anaconda/vcY-P7MBwo0/hQByFQsNAwAJ)
2. Move the Anaconda paths in your system PATH environment variable earlier.

1 is much less invasive.  This change has been made in our source code, but the package hasn't been released yet.

By the way: a clear indicator that some other Qt is getting picked up is the Windows 10 warning.  That was making our tests fail, and we have disabled it.  Seeing that message absolutely means "this is the wrong Qt dll."

**Comment by mountaindust** [comment]
Awesome! That was exactly it, and option 1 does the trick. Just like the original post in that thread you linked to, it seems to be my MiKTeX 2.9 installation that occurs first in the PATH, causing the problem.

Thanks!!
