### ISSUE TITLE
Administrative channel_alias is not working

### ISSUE THREAD

**Issue by tanweihou** [conda/conda#1911]
I refer to issue #906
I have setup a private repo and wanted to set `channel_alias` to this repo.
Unfortunately it's not working.
When I tried to search something using conda, I got this error message.

```
Fetching package metadata: Error: Could not find anaconda.org user admin
```

The admin's `.condarc` is shown as below and I tested it without user's `.condarc`

```
allow_other_channels: false
channel_alias: https://my.repo/
channels:
  - admin
```

**Comment by dhirschfeld** [comment]
I'm that I'm also seeing the behaviour....

**Comment by bkreider** [comment]
You don't need to use channel alias for that.  Channel alias is only used when you don't fully specify the channel.  You can fully specify the channel doing:  https://my.repo/admin in the "channels" key.  

Also, you will want to use "default_channels": http://conda.pydata.org/docs/install/central.html#default-channels-default-channels

So i recommend something like this, because if you ever create a ~/.condarc with channels, "defaults" is added automatically and it will expand to the public repos.  It's good practice to re-assign the "defaults" shortcut if you never want to hit the public repos.

```
channel_alias: https://my.repo/
channels:
  - defaults

default_channels:
  - https://my.repo/admin
```

And run `anaconda config --set url "http://myrepo"`.

**Comment by tanweihou** [comment]
Hi, thanks for your suggestion, unfortunately it did not work for me
My repo is actually just a directory in my server.
```
channel_alias: file:///my/repo/

channels:
    - defaults

default_channels:
    - file:///my/repo/conda-channel/admin

show_channel_urls: True

create_default_packages:
    - ipython
```
Anyway, here is my own solution
Users could still bypass it if they have their own `.condarc`, but they do not have write access on Python distribution
It works, but not that pretty :/ 
```
allow_other_channels: false
channels:
  -  file:///my.repo/

create_default_packages:
    - ipython
```

**Comment by kalefranz** [comment]
No longer relevant post 4.2.
