### ISSUE TITLE
Conda install --no-deps does not install the correct package

### ISSUE THREAD

**Issue by srossross** [conda/conda#1919]
```
[localhost] local: conda create --yes -p ./static -c https://conda.anaconda.org/t/bi-TOKEN/channel/dev --no-deps binstar-server
Fetching package metadata: ........
Solving package specifications: ...............................
Package plan for installation in environment /home/ec2-user/deploy/static:

The following NEW packages will be INSTALLED:

    binstar-server: 2.11.3-0

Linking packages ...
[      COMPLETE      ]|#################################################################################################################################################| 100%
#
```

```
(deploy)[ec2-user@anaconda-jumpbox deploy]$ conda search  -c https://conda.anaconda.org/t/TOKEN/binstar/channel/dev  binstar-server
Fetching package metadata: ........
binstar-server               2.0.5                    py27_0  binstar         
                             2.1.3                    py27_2  binstar         
...
                          .  2.11.2                        0  binstar         
                             2.11.2                        4  binstar         
                          .  2.11.3                        0  binstar         
                             2.12.0                        0  binstar         
```

**Comment by srossross** [comment]
Why is 2.11.3 being installed and not 2.12.0?

**Comment by ilanschnell** [comment]
Have you tried being more explicit?
```
conda create --yes -p ./static -c ... --no-deps binstar-server=2.12.0
```
Conda used to always choose the latest version, when no version is specified, but something must have changed.  We've seen this wired behavior in other places also.

**Comment by srossross** [comment]
@ilanschnell this is not possible for us. This affects our automated installs.

**Comment by ilanschnell** [comment]
Hmm, then we need to prioritize the problem in conda.

**Comment by ilanschnell** [comment]
CC @mcg1969

**Comment by mcg1969** [comment]
My guess is that this does indeed have something to do with my pruning pass: specifically, `2.12.0` is being removed from consideration because it has some sort of dependency conflict with the current environment. Obviously the `--no-deps` flag implies some sort of override for this behavior so we should be bypassing the pruning pass in such cases. 

I need to confirm my suspicion is correct, however. If someone can make it possible for me to access this channel, that will help. Alternatively (or more quickly), if someone can send me the `json` data for the package, I can take a look and see if there are obvious dependency issues.

I'm going to check independently if the `--no-deps` disables/skips the pruning pass. It should, regardless of whether that is the issue here.

**Comment by mcg1969** [comment]
Yes, I think that's what is happening. The `--no-deps` argument actually does a *full solve* for `conda install binstar-server`, *then* it drops the dependencies. Therefore it will only install the latest version of the package that has a valid solution. What version of `binstar-server` is selected if you drop the `--no-deps` argument?

**Comment by mcg1969** [comment]
This doesn't explain why choosing the version number explicitly `binstar-server=2.12.0` works. (Or does it? Can we reconfirm this?) If there was a dependency issue, that should result in an unsatisfiable specification error.

**Comment by mcg1969** [comment]
In order to study this I need access to this repo. @srossross, can you give that to me?

**Comment by csoja** [comment]
@mcg1969 you should have an invitation now.

On Tue, Dec 22, 2015 at 12:14 PM, Michael C. Grant <notifications@github.com
> wrote:

> In order to study this I need access to this repo. @srossross
> <https://github.com/srossross>, can you give that to me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1919#issuecomment-166693992>.
>



-- 
*Crystal Soja*
*Anaconda Distribution Product Manager*

**Comment by mcg1969** [comment]
Oh, I'm sorry. I meant access to the binstar-server conda channel.

**Comment by mcg1969** [comment]
My guess was correct: the reason 2.12.0 was not being selected was because it has missing dependencies; for instance, `flask-wtf==0.8.4`. The `binstar` channel has this dependency, but `binstar\channel\dev` does not.

I verified this by dropping `--no-deps`. And the following command allowed me to install version `2.12.0`, which lives only in the `dev` channel:
```
conda create -n test -c binstar -c binstar/channel/dev binstar-server=2.12.0
```

The fact is that `--no-deps` *still requires dependencies to be satisfiable*, even though it doesn't install them. In fact, when the `--no-deps` argument is supplied, `conda` generates a full solution as if `--no-deps` isn't there, then it drops the dependencies from the install plan.

At first I thought that this is clearly incorrect behavior. After all, a user specifying `--no-deps` is presumably aware that installing a package without its dependencies will produce an unusable installation. There is tacit acknowledgement that the user is about to break things.

On the other hand, whether the user realizes it or not, s/he *is* expecting conda to resolve the dependencies *to the extent that it can*. For instance, I would suggest that the user would consider it to be conda's fault if it installed a Python 2.x package in a Python 3.x environment or vice versa. If `--no-deps` truly ignored dependencies, it could sometimes do just that.

So clearly, `--no-deps` is problematic, and it's not clear to me what the solution is here.

**Comment by mcg1969** [comment]
The good news, by the way, is that this doesn't affect the main channel, because all of the dependencies are present there.

**Comment by mjuric** [comment]
@mcg1969 I'm seeing a similar problem, where `conda` doesn't select the most recent available version. However, I think in my case all the dependencies do exist on the channel, so this looks like a solver bug.

I have the following on the channel:
```
[mjuric@lsst-dev ~]$ conda search lsst-sims --full-name
Fetching package metadata: ......
lsst-sims                    master_gac1855abae.0125    ac1855abae_0  http://research.majuric.org/conda/xxx/linux-64/
                             master.20150626170402.post157    ac1855abae_0  http://research.majuric.org/conda/xxx/linux-64/
                             master.20150928224422.post8    c2d9827e8b_0  http://research.majuric.org/conda/xxx/linux-64/
                             master.20150928224422.post46    c2d9827e8b_0  http://research.majuric.org/conda/xxx/linux-64/
```

Testing by comparing `conda.resolve.normalized_version()`-s of all of these confirms that `master.20150928224422.post46` is the highest version. However, I get:
```
[mjuric@lsst-dev ~/public_html/conda]$ conda --debug install lsst-sims
DEBUG:conda.fetch:channel_urls=('http://research.majuric.org/conda/xxx/linux-64/', 'http://research.majuric.org/conda/xxx/noarch/', 'https://repo.continuum.io/pkgs/free/linux-64/', 'https://repo.continuum.io/pkgs/free/noarch/', 'https://repo.continuum.io/pkgs/pro/linux-64/', 'https://repo.continuum.io/pkgs/pro/noarch/')

...[snip]...

Package plan for installation in environment /ssd/mjuric/projects/lsst_packaging_conda/miniconda:
....
    lsst-sims:                     master.20150626170402.post157-ac1855abae_0
....

Proceed ([y]/n)?
```
when I try to install `lsst-sims`. When I specify the version explicitly, it works:
```
[mjuric@lsst-dev ~]$ conda --debug install lsst-sims=master.20150928224422.post46
Fetching package metadata: ......
....
    lsst-sims:                     master.20150928224422.post46-c2d9827e8b_0
...
Proceed ([y]/n)? n
```
(so I don't think it's an issue with missing dependencies).

The channel in question is public -- see http://research.majuric.org/conda/xxx for the channel.
The full outputs of the above commands is at https://gist.github.com/mjuric/b59eedfbf2198c07d78f

PS: Do let me know if there's anything else I can try or provide you with to make debugging easier; happy to help!

**Comment by mjuric** [comment]
Also (though I'm not sure if this is at all related), the solver is very slow on this particular channel, even though most dependencies are of the '==' kind. We right now have to clear the channel of old versions every time we put out a new one.

**Comment by mcg1969** [comment]
Try adding the exact version number to your update command and see what happens.

**Comment by mcg1969** [comment]
@mjuric, sorry, I see you did that.

**Comment by mcg1969** [comment]
@mjuric, this is indeed a different issue, and likely related to the version string ordering. Can you file a separate issue?

**Comment by kalefranz** [comment]
Recently added extra integration tests to the 4.3.x branch for the `--no-deps` flag.  It works correctly now.
