### ISSUE TITLE
Inconsistent match spec processing

### ISSUE THREAD

**Issue by ivan-kalev** [conda/conda#1922]
1.

```
conda install "numpy ==1.8"
conda install "numpy  =1.8"
```

both versions work as expected.

2.

```
conda install "numpy ==1.8.*"
conda install "numpy  =1.8.*"
```

only the second version works.

3.

```
conda install "numpy 1.8.*"
```

returns `Error: Invalid package specification: numpy 1.8.*` on the command line, but works in `meta.yaml`.

(3) is probably fine, but (2) looks suspicious.

**Comment by mcg1969** [comment]
Looking at the internals here, this is due to the way `conda` attempts to merge two different types of version specs. 

The double-equal `==` specs are interpreted "pip-style", and pip-style specs do not support asterisk wildcards. If you want to select the latest `1.8` version in this manner, you should use something like this: `numpy >=1.8,<1.9`

The single-equal `=` spec is interpreted using a newer conda convention that does allow for wildcards. So `numpy =1.8.*` is indeed equivalent to `numpy >=1.8,<1.9` in this case.

What is interesting is that *internally*, `numpy =1.8.*` is converted to `numpy 1.8.*`. So there's nothing internally that would prevent `conda` from supporting option (3). It blocks during the pattern matching.

**Comment by kalefranz** [comment]
conda install "numpy ==1.8.*"

is indeed invalid, because `==` means an *exact* version match, which isn't compatible with a wildcard or range.

    conda install "numpy 1.8.*"

is fine as of conda 4.4.
