### ISSUE TITLE
installing new env python3.5:  site-packages still points to python 2.7

### ISSUE THREAD

**Issue by gaming-hacker** [conda/conda#1931]
why in python3.5 still point to 2.7 site-packges?

python 2.7 no issues,  installed python 3.5 with 

conda create --name python3 python=3
The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0     
    pip:        7.1.2-py35_0 
    python:     3.5.1-0      
    readline:   6.2-2        
    setuptools: 19.1.1-py35_0
    sqlite:     3.8.4.1-1    
    tk:         8.5.18-0     
    wheel:      0.26.0-py35_1
    xz:         5.0.5-0      
    zlib:       1.2.8-0      
Proceed ([y]/n)? y

conda list crashes 
# packages in environment at /Users/me/anaconda/envs/python3:
#
Failed to import the site module
Traceback (most recent call last):
  File "/Users/glen/anaconda/lib/python2.7/site-packages/site.py", line 75, in <module>
    __boot()
  File "/Users/me/anaconda/lib/python2.7/site-packages/site.py", line 23, in __boot
    loader.load_module('site')

it should be point here
/Users/me/anaconda/envs/python3/lib/python3.5/site-packages

**Comment by ilanschnell** [comment]
Do you have the `PYTHONPATH` or `PYTHONHOME` environment variables set?

**Comment by gaming-hacker** [comment]
yes i have it set to 
PYTHONPATH=${HOME}/anaconda/lib/python2.7/site-packages:\
${HOMEBREW_PREFIX}/lib/python2.7/site-packages

so homebrew doesn't override anaconda packages, where is the script that sets the env?

**Comment by ilanschnell** [comment]
There is no need to set `PYTHONPATH` or `PYTHONHOME` when using anaconda.  Unsetting `PYTHONPATH` will fix the problem.

**Comment by gaming-hacker** [comment]
incorrect, otherwise homebrew will stomp on on the env

**Comment by msarahan** [comment]
To explain this just a bit more:

PYTHONPATH is for putting your modules in a place so that python knows how to find them.  Some people use it to keep all their one-off scripts in one place, and import them.

PYTHONPATH causes problems when it includes packages that Anaconda or any other Python distribution you have installed on your system also includes.  Modules are found in PYTHONPATH first, before they get found in that distribution's site-packages folder.  You end up with the wrong version imported, and things break.

Many, many people (like you) put site-packages in PYTHONPATH to try to force a particular package to get picked up.  That generally breaks things in unpredictable ways.  It is best to, like Ilan says, unset PYTHONPATH, unless you are completely certain that you will be importing ONLY your code, and not any installed packages from anywhere.  It's safer to simply unset PYTHONPATH.

Each Python process creates its search path on startup.  You can see this with 

```import sys; print(sys.path)```  

If you have PYTHONPATH set, you'll see that its entries appear at the beginning of sys.path - this is why modules in the first folder clobber others.  If you don't have PYTHONPATH set, then nothing else gets in the way - only the site-packages folder local to the current python interpreter will get found.

This is completely separate from which python interpreter gets found.  PATH is the environment variable that determines that.  Conda's activate script takes care of setting PATH so that the desired interpreter in your env gets found.
