### ISSUE TITLE
Workflow for installing conda in development mode

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#2110]
Not quite sure what the right way of doing this is. Removing `conda` appears to be disallowed (makes sense). Can I simply `pip install -e .` from the `conda` repo and safely overwrite everything or is there a better way?

**Comment by msarahan** [comment]
I don't know of a truly simple way of doing this.  I actually dread working on Conda because it is so easy to get mixed up.  I hope we can fix this by making Conda more independent of the root environment into which it is installed.  Here's what I do:

1. Install a separate miniconda installation, just in case things go wrong (or work with a docker image or VM)
2. ```conda install setuptools``` (because it's not installed by default and conda needs it to install itself
3. manually delete the site-packages/conda folder and site-packages conda-3.xx.x egg info file (or else you might get the release version overriding your dev version.)
4. ```pip install -e .``` in the conda folder

Note that shell scripts do not get updated like Python files do with ```pip install -e .```  If you're tweaking shell scripts, you need to re-run ```pip install -e .``` to have conda "see" the updates.  You  should see output when running ```pip install -e .``` that it is copying the shell scripts.  You should be suspicious if you change the shell scripts, run ```pip install -e .``` and do not see the scripts mentioned.  It will not mention them if they haven't changed.

All of this could be automated pretty well with a Docker image, I think, so that you could develop on your machine, and never have to worry about an installation on your local machine.  I'll chew on that.

Any other suggestions welcome.

**Comment by mcg1969** [comment]
This is one of those times where my limited experience with standard Python development practices comes in handy. I probably don't know what I'm missing.

I tend to develop right in the source directory. I have a Jupyter notebook that I use test out individual routines, with key modules loaded in cell 1 and either a call to `api.get_index()` or code to load `tests/index.json`. When I need to run the commands from the shell, I just substitute `python conda/cli/main.py` for `conda`.

Every once in awhile, I find myself confused by Python's path resolution behavior. Usually, just the fact that I'm sitting in the conda source directory is enough to ensure I'm getting the right version of the files. Other times, I have to set PYTHONPATH. But occasionally, even that isn't enough, and what I do is manually rename the installed `conda` package directory to, say, `conda2`, so I can be sure Python doesn't find it. I usually don't forget to move it back.

**Comment by mcg1969** [comment]
I recently learned that I can use `api.get_index(platform='linux-64')` (for instance) to debug metadata from other OS's besides the one I'm in...

**Comment by kalefranz** [comment]
> I tend to develop right in the source directory.

![image](https://cloud.githubusercontent.com/assets/1418419/13691013/e3ba8130-e6fa-11e5-872d-87f9b33aaf66.png)

**Comment by kalefranz** [comment]
I confess to using `pip install -e .`.  But I also do dev work within python virtualenvs sometimes.  Works fine for conda code itself.

On my long backlog is making conda as much as possible play nice with virtualenv.

**Comment by kalefranz** [comment]
Going to close this to remove it from the open board. No reason discussion can't continue though.
