### ISSUE TITLE
conda create requires admin access on Windows in a multiuser installation

### ISSUE THREAD

**Issue by eugenschindler** [conda/conda#2136]
We are running Minoconda on a server machine for multiple users.
Miniconda is installed in C:\Miniconda3.
I set the permissions of the C:\Miniconda3 folder (and subfolders) such that all users have write access. Also explicitly for C:\Miniconda3\envs.
When doing a conda create -n p35 anaconda python=3.5 (also tried with python=2 and python=3), the system asks for admin rights for the executable pythonw.exe. This happens at the end, when all packages are downloaded and some linking needs to be done.
So users cannot create their own environments (so I am assuming that some temporary files are created or other files are written to other locations.
Would it be possible to make it so that users can create their own environments without needing an administrator password?

**Comment by groutr** [comment]
The only thing I can think of is conda possibly trying to write menu shortcuts.
@msarahan would know more.

**Comment by msarahan** [comment]
Yes, this is for installing menu shortcuts.  Shortcuts for all users requires admin elevation.  There's no way around that.

You could create a file called ".nonadmin" in your C:\Miniconda3 folder.  That will trick the menu installation to happen for only the current user.  Any menus created for environments thereafter will be local to that single user.

This is a really fragile way to operate, though.  You will have major permission issues if more than one person tries to use conda at once, and if people are using an environment when someone else changes it, then again, you'll get permissions errors and an upredictable broken final state.

DIsk space is cheap.  I would strongly advise you to give everyone their own miniconda installation.  If you need to preserve bandwidth, I would recommend caching packages to a local proxy as people download them, and have your many installed minicondas all go look for packages at the proxy rather than directly on the internet.

**Comment by eugenschindler** [comment]
Thanks! That information is definitely helpful. Would it be possible to skip making the shortcuts as our main use case is to use "activate <envname>" instead of the shortcuts in the Windows start menu.

**Comment by msarahan** [comment]
There's two approaches that might work:

1. remove menuinst from the root installation.  This one will be fragile - other things may try to install it again as a dependency.
2. create environments with a leading underscore in their name (_env_name).  These will skip menu installation.

We would like to make a flag or something to disable menu installation, but that's not there yet.

**Comment by eugenschindler** [comment]
Thanks again for your quick and useful replies!
Shall I make an issue for the mentioned flag or does it already exist (a quick search for something like that in the issues suggests that this is not so)?

**Comment by msarahan** [comment]
Please do. I think there may be one already, but can't track it down now. We can close duplicates later.

**Comment by eugenschindler** [comment]
Thanks. Done so under #2144 and also linked it with related issues that I could find.

**Comment by wesm** [comment]
Ran into this today

![IMG_20191001_144227](https://user-images.githubusercontent.com/329591/65994883-efecb300-e459-11e9-83df-330faec14850.jpg)

Is this expected behavior? On conda 4.7.10

**Comment by msarahan** [comment]
Yes, as described above, menuinst tries to install shortcuts for all users based on the root installation.  Conda has this flag you can use (from the help):

`  --no-shortcuts        Don't install start menu shortcuts`

**Comment by wesm** [comment]
Thanks
