### ISSUE TITLE
Remove locking completely

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2196]
I would suggest removing the locking of conda entirely, because it causes more problems, than it solves.  Users just have to be careful not to run multiple instances of conda at once, but even if they do things will work most of the time.  There are only few cases were the file locks are doing a useful job.  Moreover, conda has been designed in a way that most commands can be interrupted and resumed later.  I was never a fan of these locks, because of the additional complexity they added.

**Comment by pzwang** [comment]
I'm -1 against removing them completely based on the arguments above.  If we can believe we completely understand the "few cases" where file locks are doing a useful job, then we should either narrow down the locking behavior to just those cases, or otherwise guard against them or warn the user.

We can be overly cautious; we don't have to be perfect.  But what we *can't* do is create situations where things "mysteriously" work or don't work.  That erodes user confidence in the tool in a deep and subtle way that is very, very hard to earn back.

Would you rather have a slow car that just works *all of the time*, or a super fast car that randomly breaks down on the highway, when the sun strikes it at a particular angle, when a certain song comes on the radio, etc.?  For a tool that people rely on, predictability is the single biggest feature.

**Comment by kalefranz** [comment]
Conda does *a lot* of locking right now. I'm in favor of conservatively and intelligently scaling it back over time.

For example, the whole package cache directory is locked for every download.  A logical next step would be just to lock the destination path for the current download.

All of this is on my radar, and scaling this back will happen over time as I run across these things.
