### ISSUE TITLE
Version ordering for string suffixes is unintutive

### ISSUE THREAD

**Issue by cel4** [conda/conda#2300]
Please consider changing the version ordering for added strings. I find it very unintuitive that `2.1.1.bioconda` < `2.1.1`, whereas `2.1.1.1` > `2.1.1`

Found here:
```
Package plan for installation in environment /Users/ch/miniconda/envs/sb35:

The following NEW packages will be INSTALLED:

    gnuplot: 5.0.3-3

The following packages will be DOWNGRADED:

    libgd:   2.1.1-0 --> 2.1.1.bioconda-0
```

**Comment by mcg1969** [comment]
@ukoethe, care to comment? I think you have some history with the VersionOrder spec.

According to the comments, this is very deliberate behavior. Text suffixes are treated as prerelease versions. The exception is the string "post".
```
    * Release versions contain only integers, e.g. '1.0', '2.3.5'.
    * Pre-release versions use additional letters such as 'a' or 'rc',
      for example '1.0a1', '1.2.beta3', '2.3.5rc3'.
    * Development versions are indicated by the string 'dev',
      for example '1.0dev42', '2.3.5.dev12'.
    * Post-release versions are indicated by the string 'post',
      for example '1.0post1', '2.3.5.post2'.
```
So what you want to do here is `2.1.1post.bioconda`:
```
>>> VersionOrder('2.1.1post.bioconda') < VersionOrder('2.1.1')
False
>>> VersionOrder('2.1.1post.bioconda') < VersionOrder('2.1.2')
True
```

**Comment by ukoethe** [comment]
Conda's version ordering closely follows the Python versioning standard https://www.python.org/dev/peps/pep-0440/. It is not 100% identical (because conda must support other languages beyond Python), but is the best compromise I could come up with. 

Regarding your problem: an important recommendation is "version self-consistency". In your case, this means that the number of numeric version components should never change. So you should rename `2.1.1` into `2.1.1.0`. Then, appending a tag will never change the ordering.
