### ISSUE TITLE
MKL installed with libgfortran=1.0 despite nomkl

### ISSUE THREAD

**Issue by jseabold** [conda/conda#2340]
I've narrowed down why mkl keeps getting installed for me.

environment.yml

```
name: foobar
dependencies:
- python=3.4
- libgfortran
- nomkl
- numpy=1.10.4
```

If I change to `libgfortran=1.0` mkl gets installed. Can't see why.

**Comment by jseabold** [comment]
Using conda 4.0.5 and calling

`conda create env -f environment.yml`

**Comment by mcg1969** [comment]
The `nomkl` version of `numpy 1.10.4` requires `libgfortran 3.0`, so installing the wrong version of `libgfortran` forces conda to select a different version of `numpy`.

**Comment by jseabold** [comment]
Why did it select a `mkl` variant?

Is there any way to give a graceful failure and informative error message? This took a line by line trimming of my `environment.yml` to figure out.

**Comment by jseabold** [comment]
Also, is there any way for me to diagnose this using conda?

**Comment by mcg1969** [comment]
> Why did it select a mkl variant?

That version is compatible with your constraints. Features are not hard requirements---they instruct conda to install as many packages _as possible_ with the requested feature.

> Is there any way to give a graceful failure and informative error message?

Well, it shouldn't fail. It's a correct solution to the specs given.

But it is indeed a long-standing problem that `conda` needs to provide better hints when arriving at a "suboptimal" solution, like a downgrade etc. It turns out that generating _informative_ hints is quite difficult.

**Comment by mcg1969** [comment]
I did manage to do this:
```
[mcgrant@centos6 ~]$ conda create -n test python=3.4 libgfortran=1.0 nomkl numpy=1.10.4=py34_nomkl_1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
  - numpy 1.10.4 py34_nomkl_1 -> libgfortran 3.0
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.
```
Even this doesn't look good, because it should be listing the `libgfortran=1.0` spec in the as well. 

My general trick is this: if `conda` is not installing the package you *think* it should be installing, use the `=version=build_string` hint to force conda to focus just on that package, and that will usually spit out a hint.

**Comment by jseabold** [comment]
I can imagine. Thanks for the hints. That's helpful. I've just learned to [avoid pinning to build strings altogether](https://groups.google.com/a/continuum.io/forum/#!topic/conda/laFDA84qQLs), so it is nice to know I can use them for this.

As a comment, avoiding mkl has become a really big headache for me. Doing a lot of packaging work, a 300 MB download on a 6-10 MiB/s internet connection over and over is brutal. I suppose I could download the package everywhere I'm doing builds and put it in a local index, but I try to just use nomkl everywhere.

**Comment by jseabold** [comment]
Also, I guess it's not clear to me why mkl and nomkl aren't a conflict. If they were, it seems like this could have generated a path to the conflict.

**Comment by mcg1969** [comment]
MKL is actually not a feature anymore--it is the default.
