### ISSUE TITLE
Command line arguments should require latest version (`=latest` version spec)

### ISSUE THREAD

**Issue by dsludwig** [conda/conda#2505]
When a user types: `conda install packagename` or `conda update packagename`, the expectation is that the latest version of `packagename` will be installed. If the latest version is not installable (e.g. it has unsatisfiable dependencies), but there is an earlier version which is installable, the older version will be silently selected.

e.g. https://github.com/Anaconda-Platform/support/issues/26 (not quite the same issue, but it may have been detected more easily)

The packages specified on the command line should be constrained to _equal_ the latest version found by conda, or there should be a way that users can specify that they would like this behavior (i.e. `conda install packagename=latest`).

cc @mcg1969 @srossross

**Comment by mcg1969** [comment]
@dsludwig, we will not be changing the current default behavior, which is to install the latest version of the package *that is compatible with the installed package set*.

But we can find a way to implement the `=latest` option or similar so that the latest version *regardless of compatibility* can be requested.

**Comment by mcg1969** [comment]
For recordkeeping: it turns out that the problem that motivated this issue filing was some weird behavior caused by an older version of conda (3.19). It does _not_ prioritize the command line packages over the other installed packages. This prioritization was added in one of the 4.0 releases; and tests with 4.0.5 confirm that the specific problem does not occur in that case.

Thus while an `=latest` version or equivalent remains desirable, the issue that prompted its request has been resolved.

**Comment by dsludwig** [comment]
> there should be a way that users can specify that they would like this behavior (i.e. conda install packagename=latest).

**Comment by kalefranz** [comment]
@mcg1969 Probably best to assign this to you for the moment.  At least to help implement the guts of it.  Basically I'd like `VersionOrder`/`VersionSpec` to support two "aliases," one for `latest` and one for `current` which would order as `latest - 1`.  I think this is actually your idea that we've discussed before.
