### ISSUE TITLE
conda install widgetsnbextension doesn't copy files to share folder

### ISSUE THREAD

**Issue by wikiped** [conda/conda#2551]
After doing:

    conda skeleton pypi widgetsnbextension
    conda build widgetsnbextension

Conda succeeds producing `.tar.bz2` file.

How after installing it with:

    conda install widgetsnbextension
    
Trying to activate it with:

    jupyter nbextension enable --py widgetsnbextension
    
Fails with error:

    Enabling notebook extension jupyter-js-widgets/extension...
          - Validating: problems found:
            - require?  X jupyter-js-widgets/extension
            
The reason for this is that conda did not copy `jupyter` folder from the egg file to `share` folder of environment directory.
After manually copying the above activation works fine.

Content of `widgetsnbextension-1.2.3-py2.7.egg` in `.tar.bz2` file produced by `conda`:

    .\EGG-INFO\
        .\...
    .\share\
        .\jupyter\
            .\...
    .\widgetsnbextension\
        .\...
    
Expected contend of `Anaconda\env\env_name` folder:
    
    .\...
    .\share
        .\jupyter\
            .\...
    .\...
    

My question is:

Should `conda` be able to copy those files automatically like `pip` does?

Or is there something else that should be done with recipes files to ensure these files are copied?

Thanks

P.S.

`conda --version`
`4.0.6`

**Comment by mcg1969** [comment]
This is a problem with how conda-build _builds_ the package, not with how it is installed. After all, a `conda` package is really just a compressed archive that is extracted: if the files are in the wrong place after extraction, that's because they were _put_ in the wrong place during the build.

And it might even be an issue with the `widgetsnbextension` package configuration not respecting the `sys.prefix` properly. 

Either way, this actually isn't the best forum for the issue, which focuses on the base `conda` package and its package and environment management capabilities. It might be best to re-file this over in the [conda-build issues tracker](https://github.com/conda/conda-build/issues).

**Comment by wikiped** [comment]
I did suspect that `conda-build` might be a better place to ask but wasn't sure. Anyway, thanks for the advice - will file it there.
