### ISSUE TITLE
conda install --force implies --no-deps

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#2568]
This is a (breaking) change in behaviour  in 4.0.7. These two options should be connected the other way around (--no-deps implies --force), because there are use cases for --force with dependencies (for example an equivalent to update-or-install).

It is not very nice to have to update my scripts to check whether a particular package was installed first (and then call update) so as to restore the old behaviour, especially considering that it takes a few extra seconds.

**Comment by Zaharid** [comment]
In fact, because conda update has the same behaviour,  and conda update for some reason doesn't pull the dependencies of the force-installed package, the closest thing to update-or-install I see is:

conda install <package> --force
conda install <package>

which is quite likely to have many corner cases.

**Comment by mcg1969** [comment]
According to the [update history](https://github.com/conda/conda/blame/master/conda/cli/install.py#L272), `force` has implied `no_deps` since January 2014. 

However, what we do know is that the dependency solver in conda 4.x has undergone a significant overhaul. This has not been without pain, caused potentially breaking changes for some people's automations. This may be related to what you are encountering.

Unfortunately, this was necessary because the 3.x solver did not consider the entire environment when installing and updating packages. Thus `conda` could _break_ environments by allowing incompatible packages to be installed. The goal with 4.x is to ensure that the only way for `conda` to break an environment in this manner is with explicit approval from the user, through the use of `--force` option.

We do have an outstanding issue involving the interaction of `--force` and `--no-deps` in this regime.
