### ISSUE TITLE
Code smell in moving files to trash

### ISSUE THREAD

**Issue by msarahan** [conda/conda#2579]
I ran across this while debugging a conda build issue: https://github.com/conda/conda/blob/master/conda/install.py#L964-L965

wherein we basically create a tmp folder, like

c:\users\frank\miniconda\conda-bld\tmp4326jklasdf

Then append

..\long\other\path\to\conda-bld

to it.  So we toss the random dir we just added.  I have no idea why we don't just use the random dir.  I'll put in a PR if you agree this doesn't make sense.  Otherwise, I'd like to be enlightened.

**Comment by mcg1969** [comment]
cc: @mingwandroid

**Comment by mingwandroid** [comment]
Definitely a bit smelly that. I should've spotted it when I was in that area recently. The original code dates back to September last year, and it looks like an oversight to me.

**Comment by mingwandroid** [comment]
so the '..' is actually indicative of using move_to_trash in a way that wasn't anticipated (the folder you trash *not* being a sub-folder of the root prefix).

it's potentially a bad security exploit too, if you get a few '..'s you can get up to the root of the system and start writing files into /usr/lib, for example.

I'm fixing the '..' now, but also keeping the mkdtemp since otherwise we'll run into failures to put things in trash since there's already a folder with the same name in there.

**Comment by msarahan** [comment]
@mingwandroid took out the trash in #2587 - closing this.
