### ISSUE TITLE
constructor does not work with master

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2589]
Using `conda version: 4.0.7.dev432+5503970`, and having the following channels in `construct.yaml`:
```
channels:
  - http://repo.continuum.io/pkgs/free/
  - https://conda.anaconda.org/ilan

specs:
  - python
  - grin
  - sample
```
I get the traceback:
```
Traceback (most recent call last):
  File "/Users/ilan/python/bin/constructor", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/ilan/constructor/bin/constructor", line 6, in <module>
    sys.exit(main())
  File "/Users/ilan/constructor/constructor/main.py", line 146, in main
    verbose=opts.verbose)
  File "/Users/ilan/constructor/constructor/main.py", line 84, in main_build
    create(info)
  File "/Users/ilan/constructor/constructor/shar.py", line 97, in create
    t.add(join(info['_download_dir'], fn), 'pkgs/' + fn)
  File "/Users/ilan/python/lib/python2.7/tarfile.py", line 2006, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/Users/ilan/python/lib/python2.7/tarfile.py", line 1878, in gettarinfo
    statres = os.lstat(name)
OSError: [Errno 2] No such file or directory: '/Users/ilan/.conda/constructor/osx-64/ilan::sample-0.6.0-xyz.tar.bz2'
```
To solve this problem, I suggest that `conda.fetch.fetch_index` should have an optional argument `dist_as_key`, where the default is `False`.  The resulting index has the following keys:
  * dist_as_index=False   filename as key, e.g. `sample-0.6.0-0.tar.bz2`
  * dist_as_index=True    distribution as index key, e.g. `ilan::sample-0.6.0-0.tar.bz2`

When the function is called within conda, it can always we called using `dist_as_index=True`.
In this way, the function will behave in the old way for existing code which uses it.

CC @mcg1969

**Comment by mcg1969** [comment]
Looking at this one now.

**Comment by mcg1969** [comment]
I have to be honest, I'm not inclined to make the change suggested here. After all, `fetch_index` has been changed for entirely legitimate reasons; because using the filename as the index key fails when multiple channels have packages with the same name. I claim that you're basically asking `fetch_index` to stay broken by default, and have an optional keyword argument `fix_bug=False`.

It seems to me that the sensible thing to do here is to modify constructor so that it stops relying on the dictionary keys in the way it does. I'm happy to submit a constructor PR to accomplish this. It seems to me this is not going to be the last time that `conda` changes will force changes in `constructor`.

@kalefranz, what do you think? If I am outvoted here, so be it.

**Comment by kalefranz** [comment]
Have we resolved this now?

**Comment by kalefranz** [comment]
Fixed with https://github.com/conda/constructor/pull/26
