### ISSUE TITLE
conda update fails - Access is denied: 'C:\\Anaconda2\\Library/imports'

### ISSUE THREAD

**Issue by cgryan** [conda/conda#2608]
'conda update anaconda' fails with an error:
WindowsError: [Error 5] Access is denied: 'C:\Anaconda2\Library/imports'
Despite having admin privs, I can't seem to get this dir to behave. Aint Windows wonderful ...
Any suggestions?

Recommended traceback/info follows:

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 634, in link

  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: 'C:\Anaconda2\Library/imports'

[Anaconda2] >conda info
Current conda install:

```
         platform : win-64
    conda version : 4.0.8
```

  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by steamelephant** [comment]
I have the same problem but with 

- `conda update conda`
- user install
- python 3

My conda info is:
                                                                                                                                     
platform : win-64                                                                                                  
conda version : 4.1.0                                                                                             
conda-build version : 1.20.0                                                                                                 
python version : 3.5.1.final.0                                                                                        
requests version : 2.9.1                                                                                                
root environment : C:\Users\xxxxxx\Anaconda3  (writable)                                                         
default environment : C:\Users\xxxxxx\Anaconda3                                                                        
envs directories : C:\Users\xxxxxx\Anaconda3\envs                                                                      package cache : C:\Users\xxxxxx\Anaconda3\pkgs                                                                       channel URLs : https://repo.continuum.io/pkgs/free/win-64/                                                                             https://repo.continuum.io/pkgs/free/noarch/                                                                             https://repo.continuum.io/pkgs/pro/win-64/                                                                              https://repo.continuum.io/pkgs/pro/noarch/                                                                
config file : None                                                                                                
is foreign system : False 

The failure happens when   copying  
'C:\\Users\\xxxxxx\\Anaconda3\\pkgs\\menuinst-1.4.1-py35_0.tmp' -> 'C:\\Users\\xxxxxx\\Anaconda3\\pkgs\\menuinst-1.4.1-py35_0'

**Comment by kalefranz** [comment]
`conda update conda`

We've fixed a lot of problems with permissions, especially in conda 4.3.
