### ISSUE TITLE
Make conda pip functional again please

### ISSUE THREAD

**Issue by NervenCid** [conda/conda#2738]
Hello:

I tried install conda via pip 

pip install conda

I used : conda update conda

but its not working

I tried miniconda distro but some code that works with official python is not working with anaconda Python (i have problems with tkinter)

Please help

**Comment by kalefranz** [comment]
Yes, that could very much happen someday.  This would be a conda 5.x timeframe feature though.  Also note that we're removing `conda init` right now in 4.2 because it's broken anyway.  See https://github.com/conda/conda/pull/2750

I appreciate the feature request. I'm going to close the ticket right now.  It's just not technically possible in the near-term, but longer term it would be nice to make this happen.
