### ISSUE TITLE
conda list misses pip-installed wheels

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2754]
As of conda 4.1, `conda list` no longer captures python packages that were pip-installed and were installed from wheels.

https://www.python.org/dev/peps/pep-0427/#id14

CC @ilanschnell

**Comment by kalefranz** [comment]
This is actually a real issue now because the large majority of packages on PyPI are distributed as sdists, and now on install, pip force-compiles sdists to wheels, then installs those wheels.

How about we use something like this:

    import pkgutil
    packages = [p[1] for p in pkgutil.iter_modules()]

**Comment by ilanschnell** [comment]
The problem is that from whatever `pkgutil.iter_modules()` returns, it is hard to tell whether or nor the installed package is a conda package or not.  The point of the new `conda.egginfo` module, part from not having to call out to `pip`, is that conda knows which `.egg-info` files are "untracked" (not part of any conda package).  I think the best solution is to extend `conda.egginfo` to handle these new meta-data files also.

**Comment by ilanschnell** [comment]
Voila https://github.com/conda/conda/pull/2870/files
There is almost no risk to merging this, and it would be awesome to see this in the conda 4.1.4 release!
