### ISSUE TITLE
weird priority interaction

### ISSUE THREAD

**Issue by bkreider** [conda/conda#2790]
I ran into an unexpected issue when installing binstar-server.  

1.  setup .condarc for installing our software:
```
channels:
  - https://conda.anaconda.org/t/$TOKEN/anaconda-server/
  - https://conda.anaconda.org/t/$TOKEN/binstar/
  - defaults 
```

2.  conda install binstar-server binstar-static
3.  conda install -y supervisor    # downgrades supervisord and binstar-server to a very old version
4.  conda remove supervisor     # removes binstar-server as well

Should channel priority respect already installed packages that are from a lower priority channel rather then downgrading them?  I suspect that the lower priority supervisor (3.1.3) gets installed because it is a hard dependency when asking for binstar-server.  Then when asking just for supervisor, 3.0b2 gets installed, because it is on the highest priority channel and it downgrades everything.

I don't think people want to downgrade a package in this manner most of the time.  They still need to be able to do it if they REALLY want to.  But i don't see why that would be the normal case.

@kalefranz

**Comment by mcg1969** [comment]
Actually, the channel priority for these orphan packages was indeed initially set to the highest level. But it turns out that this has the interesting consequence of making it *extremely* difficult to upgrade that package. After all, since the channel is not in the channel list, it will never see any additional versions appearing in that channel. And because of channel priority, conda will endeavor to keep that package no matter how much the packages are being upgraded in other channel.

It's an easy flip for us to make, but let me be clear: we're going to see support requests for *exactly the opposite problem* if we do.

I suspect the proper solution is neither of these options, but rather something like the ability to pin a package to a particular channel.

**Comment by mcg1969** [comment]
Ignore everything I just said. I misread the problem. Hang on

**Comment by mcg1969** [comment]
I think we should provide the facility to pin packages to particular channels. But no, I think channel priority has to be respected even across updates. Perhaps the dependencies for `supervisor` need to be changed so that this doesn't happen?

**Comment by mcg1969** [comment]
That said, I am away from my desk and frankly can't investigate in depth. Can you give @kalefranz and a full breakdown here? That is:
- Which channels does `binstar-server` live in? And if it lives in more than one, which versions are in which channels?
- Which channels does `supervisor` live in? And if it lives in more than one, which versions are in which channels?
- What are the *exact* dependency specifications here that are involved in this process? Specifically: you mention a "hard dependency" that supervisor has on binstar-server. What is that dependency? And is it correct? Can it be relaxed?

**Comment by mcg1969** [comment]
Yeah, from what I'm seeing in our company chat, the real problem here is that `supervisor`'s dependencies are too strict.

**Comment by kalefranz** [comment]
Sounds like it was resolved in flowdock
