### ISSUE TITLE
Anaconda.org over capacity

### ISSUE THREAD

**Issue by tomkinsc** [conda/conda#2816]
We had an automated test on Travis fail today while installing a conda package, because the anaconda.org server was at capacity:

`Fetching package metadata .......Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://conda.anaconda.org/bioconda/linux-64/repodata.json.bz2: https://conda.anaconda.org/bioconda/linux-64/`

This has happened a few times now. Is anaconda.org is rate-limited by account/channel, or are the limits global? Is there any sort of CDN in front of the servers hosting packages? Is there a time of day that's best for running automated tests that depend on conda packages?

**Comment by kalefranz** [comment]
> Is anaconda.org is rate-limited by account/channel, or are the limits global?

Not at a level any normal user or CI system should hit.

> Is there any sort of CDN in front of the servers hosting packages?

Yes, but packages aren't the problem here.  It's the repodata.json file, which in most cases is generated dynamically.

The Anaconda Cloud team is definitely aware of the problem and working on resolving it asap.  I've also created a ticket for them to consider setting up a status page, something like through statuspage.io for example.

**Comment by kalefranz** [comment]
Closing this issue because it's really not even something conda itself can affect.  I've definitely been working with the anaconda.org team directly though.

**Comment by tomkinsc** [comment]
Thanks, Kale. Is there a better channel for these sorts of questions/reports?

**Comment by kalefranz** [comment]
Yes, and I was looking for it to just move this issue, but I can never remember exactly where it is.
