### ISSUE TITLE
Can't update conda from v1.7.1 due to "No packages found matching: conda-env"

### ISSUE THREAD

**Issue by bscipio** [conda/conda#2822]
Testing with  fresh install of Miniconda-1.6.0.
```
 % conda update conda
No packages found matching: conda-env >=2.5.0

 % conda install conda-env
Error: No packages found matching: conda-env >=2.5.0

% conda -V
conda 1.7.1

% conda info
 Current conda install:
              platform : linux-64
 conda command version : 1.7.1
        root directory : /home/brian/sandbox/anaconda/miniconda16
       default prefix : /home/brian/sandbox/anaconda/miniconda16
          channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None`
```

`% conda search conda`
does return various verisons of conda-env, including 2.5.0,  and conda

Also attempted with anaconda 1.7 with similiar conda-env error.

Are older conda version upgrade paths to current version supported?

**I'd like to avoid fresh installs of anaconda, if possible, due to various packages being deprecated version to version.**  

_I Probably should have upgraded earlier..._

Thanks!

**Comment by mcg1969** [comment]
bscipio, sorry for the delay in responding, but to be honest, we wanted to think hard about whether or not there is anything we could do for you. I certainly understand the desire not to have to reinstall anaconda, but I just don't see that it will be possible to upgrade conda within this environment.

Here's an alternative approach that I would like to encourage you to consider:

1. Install a fresh installation of Miniconda in a _separate directory_ from this one. Make sure your PATH is set so that this is the active installation.
2. Do a `conda update --all` to get conda in particular up to date. In fact, I recommend making sure you have at least conda 4.1.3 for this one, because it incorporates some important fixes here.
3. Then do `conda create -n miniconda16 --clone /home/brian/sandbox/anaconda/miniconda16`.

Crossing our fingers, what this should do is create a new environment with all of the same packages, _except_ for conda. You should be able to do `source activate miniconda16` and get access to those programs.

**Comment by bscipio** [comment]
Thank you for your reply! This appears to be working pretty good

I have a few minor notes and follow up questions.

Using miniconda 3.7, with conda updated to 4.1.3
After Step 3:  (actually cloned miniconda  1.9 in this example )
```
conda create -n miniconda19 --clone /home/brian/sandbox/anaconda/miniconda19```
...
No psutil available.
To proceed, please conda install psutil
```
Naturally I did `conda install psutil`
So it might be worth doing the psutil install prior to step 3.

**Questions**

- How can I make this new environment, miniconda19, my default or root environment?
Is this the recommended way?
`export PATH=/home/brian/sandbox/anaconda/miniconda37/envs/miniconda19/bin:$PATH`

- Can one replace/update the root environment with another (miniconda19 in my example)?

Thanks again!

Ref:
[How to change default Anaconda python environment](https://stackoverflow.com/questions/28436769/how-to-change-default-anaconda-python-environment)
[CEP 1: Replacing root environment with default environment](https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment)

**Comment by mcg1969** [comment]
There is not going to be a way to make this environment your _root_ environment. Indeed, that's part of the point here, you need to keep your _root_ environment, the one that contains `conda` itself, to remain as up-to-date as possible. This is also an argument for keeping your root argument _minimal_, with just enough packages to keep `conda` running, and do all of your experimentation in child environments. That CEP you referenced is an attempt to enforce this strictly by giving conda its own environment.

If you want to make sure that your preferred environment is selected upon startup, then you can probably include `source activate miniconda19` in your `.bashrc` and/or `.bash_profile` files.

**Comment by bscipio** [comment]
Thank you the explanation!   That will work fine.    We've been avoiding multiple environments in an effort to keep it simple (we have several users wanting to use the same environment), but this sounds perfectly fine, and easier to upgrade in future.
