### ISSUE TITLE
conda install --force implies --no-deps

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2928]
From `conda install -h` (version 4.1.5):
```
  -f, --force           Force install (even when package already installed),
                        implies --no-deps.
```
I don't know when it was added that `--force` also implies `--no-deps`, but this is not how it used to be.  What `conda install -f` used to do is simply install the package (with it's dependencies) but re-extract and possibly re-download the package.

**Comment by mcg1969** [comment]
Take it up with Aaron: https://github.com/conda/conda/commit/45b3cbd2bb9790d2917f5e6043132c2baff39b1e

**Comment by ijstokes** [comment]
I don't have time to dig it up, but this has caught me out and I think I've reported some of the PLS-violating implications of this policy.

**Comment by ijstokes** [comment]
Found it: #1878

**Comment by mingwandroid** [comment]
While we're talking about PLS and installation of dependencies, can anyone think up a good reason why installing from a tarball doesn't also install dependencies? I get that you may need to supply some channels, but that is better than installing things that don't work.

**Comment by mcg1969** [comment]
I was wrong. It's not 2.5 years old. It's over 3 years old, and it has been there ever since `--no-deps` was added. Here's the commit, from @ilanschnell:
https://github.com/conda/conda/commit/e3936b4e7f670c59bf3a5e380f8c9e02237062bf

**Comment by mcg1969** [comment]
My suggestions:

1. create a new option, `--force-extract` (maybe `--force-fetch` as well), that implements the re-extraction functionality but otherwise behaves the same as `conda` without the `--force` option.
2. change the behavior of tarball installation to extract the tarball metadata so its dependencies can indeed be taken into account.
3. make extra, extra sure `--no-deps` is working before deploying #2.

**Comment by mcg1969** [comment]
What I'd really like to do is reduce the number of reasons to use `--force` at all. I want `--force` to come with a strong implication that it may break your environment. 

If we're recommending the use of `--force` for _other_ reasons, such as ensuring the package is re-extracted, we're diluting the strength of that message.

On the flip-side, the fact that we can install tarballs without checking dependencies, and without using `--force`, _also_ dilutes that message. Because we _can_ break environments that way. So that's a vote for changing that behavior.

**Comment by kalefranz** [comment]
![tumblr_inline_npvaq2arbl1rujkbp_500](https://cloud.githubusercontent.com/assets/1418419/16501341/a1c80104-3ece-11e6-9358-7c8ca439b80f.gif)

**Comment by mcg1969** [comment]
From #1878

> If I do `conda install -f jupyter` then I want to force-install all the dependency packages specified the jupyter meta-package.

@ilanschnell, @ijstokes: I know this has come up many times, that somehow `conda install --force` should pull all dependencies, too. But when I fully think through the ramifications of this I find I simply can't get to a satisfactory conclusion.

For instance, `jupyter` depends on `python`. Which Python do I choose? Do I query the environment to see what version it's using? Or what if a package is built for multiple NumPy versions; should I query the environment to figure out which version of NumPy I should prefer? Either way I'm not _really_ ignoring the environment, which goes against the `--force` flag. I should be picking Python 3.5 and NumPy 1.11 every time unless an alternative is added right there on the command line.

But let's set that aside, and say the rule is: pretend the environment is empty. What if the packages I ask for are _still_ internally inconsistent? Should conda cough up an `Unsatisfiable` exception? But isn't `--force` basically supposed to always work? 

Perhaps the rule is: if it's satisfiable, make it so; but if not, just do the "best you can" in some sense. What exactly is that sense? Perhaps it should just pick the latest versions of the requested packages, and the latest versions of their dependencies, and so on. There will be a lot of tiebreaking to do, I'm guessing.

I think the desire for `--force-but-with-dependencies-too` simply doesn't have a well-defined specification. If someone can spec out all of these corner cases then we could put something like it on the roadmap. But since `--force` has behaved this way for over three years, I think we need a new name. Maybe `--force` `--ignore-installed`.

**Comment by ilanschnell** [comment]
Thanks for the detailed explanations @mcg1969.
I didn't realize that the current behavior has been around for 2.5 years.  I guess it is best the leave it like that.  Also, this is more consistent with `conda install <path to conda package>`, which also ignores dependencies.
