### ISSUE TITLE
python executable should not get symlinked from anaconda environment to package cache

### ISSUE THREAD

**Issue by dfeich** [conda/conda#2966]
We have the central installation as well as our work areas on a central shared filesystem which does not allow hardlinks. We got failures for importing modules in conda environments which installed an updated python executable into the user's local package cache.

Following up, I discovered that the python executable in the created conda environment was installed by symlinking to the newly installed python in the package cache:

```
$ ls -l ~/.conda/envs/pytest/bin/python2.7

lrwxr-xr-x 1 feichtinger unx-ait 78 Jul  2 09:12 .conda/envs/pytest/bin/python2.7 -> .conda/envs/.pkgs/python-2.7.12-0/bin/python2.7
```

Since python dereferences argv0 by which it gets called, the sys.prefix which determines the module search path, ends up relative to the physical location of the python in the package cache.

```
$ ~/.conda/envs/pytest/bin/python2.7 < <(echo 'import sys; print sys.prefix; print sys.exec_prefix')

~/.conda/envs/.pkgs/python-2.7.12-0
~/.conda/envs/.pkgs/python-2.7.12-0
```

But the sys.prefix should be relative to the environment (to the symlink's path), otherwise it cannot pick up the site-packages, etc. of that environment. For hardlinks this all works, but where hardlinks are not possible, I think the python executable should be copied to the conda environment location and not symlinked (same as is done in virtualenv).

Is there any solution already available besides copying the executable to the symlink's location manually? 

Many thanks,
Derek

**Comment by mcg1969** [comment]
You could add
```
allow_softlinks: false
```
in your `.condarc`; that should prevent soft linking. Unfortunately there's currently no way to disable that for all users in one place.

**Comment by mcg1969** [comment]
@kalefranz, I'm thinking we need to either remove symbolic linking from the package cache altogether, or change `allow_softlinks` to default to `False`. What happens if the package cache is corrupted or removed? Or a package from one channel has to overwrite a package from another channel? Suddenly the environments that link to it will be corrupted.

**Comment by dfeich** [comment]
I think the symlinks still have a big worth, because they allow to save a lot of space. This may not be important on the ever growing local disks, but on a shared filesystem the home directories of users often need to be limited. The symlinks allow for minimal environments where most of the links will point to the centrally installed packages, some links point to the users own package cache with newly downloaded packages.

Sure, the drawback is tha these environments are not truly well isolated, and messing with the package cache could make some of them unusable. But I still think that the symlinks have their value.

The situation can be repaired if one makes a simple exception for the installation of python itself. If I e.g. just copy the pkg-cache python to the symlinks location:
```
(pytest)$ ls -l pytest/bin/python2.7 
lrwxr-xr-x 1 feichtinger unx-ait 78 Jul  2 09:12 pytest/bin/python2.7 -> ~/.conda/envs/.pkgs/python-2.7.12-0/bin/python2.7

(pytest)$ rm pytest/bin/python2.7

(pytest)$ cp ~/.conda/envs/.pkgs/python-2.7.12-0/bin/python2.7 pytest/bin/python2.7
```
Now the environment works fine for me.

For the moment I will recommend our users to do this copying manually as a fast workaround. But I think it would be great if conda would implement this exception for the python binary, because it would make the symlink option work nicely.

Best regards,
Derek

**Comment by mcg1969** [comment]
I recognize that symlinks are valuable, but in my view, their fragility demands that we offer them only to users to assent to their risks. I'm not saying we should get rid of them, only that users or the sysadmin explicitly ask for them. 

Regardless, your suggested change is a good one.

I do think that, as part of our overall goals to fully support centrally administered installations, we could eliminate the fragility issue. For instance, when a package is sym-linked for the first time, we could mark its package cache directory as "locked" so that it cannot be accidentally removed. We could implement a conservative reference counting scheme that counts the number of environments that have symlinked to that package, and allow it to be removed only when the count is zero.

**Comment by dfeich** [comment]
The reference counting proposal sounds great. This would provide most of the resilience that hardlinks give. It's probably easy to do for a user's local package cache. For the central package cache it might be more challenging, because it is not writable for normal users. So the information of local user envs pointing at the central package cache would need to be stored in a file/dir/DB which allows user writing but without allowing users to mess which each others entries. A directory with settings like /tmp on a typical unix filesystems with one file per user could make sense.

Thanks to all you guys for providing anaconda. It is a great environment!

**Comment by mingwandroid** [comment]
I ran into a problem during `conda-build`'s test phase caused by this symlinking.

I 'fixed' it with the following:

https://github.com/conda/conda/blob/master/conda/utils.py#L450-L469

Cheers!
