### ISSUE TITLE
Conda install should work with git repo (like pip install)

### ISSUE THREAD

**Issue by teoliphant** [conda/conda#306]
Conda install should be able to take a git, hg, subversion, or other repository.

It should: 
- run conda build on the repo URL (with no option to upload)
- install the resulting package

conda build URL should:
- download the directory
- if a recipe is found at the directory, then conda normal build is then run
- If a setup.py file is found in the top-level directory, then create a package from the setup.py file (see conda build setup.py)

**Comment by kalefranz** [comment]
I recently closed the "conda should install sdists" feature ticket that I wrote myself.  I proposed the same mechanism as above.  At this point, I'm much more on board with conda installing wheels (especially since conda-build is now outputting wheels).

I also feel like turning `conda install` into an implicit `conda build` crosses over the line into "too much magic" territory.
