### ISSUE TITLE
Conda env removes default kernelspec without replacing it

### ISSUE THREAD

**Issue by michaelpacer** [conda/conda#3094]
Notebooks with the kernel "`python3`" cannot be opened with the conda env kernelspec manager (`nb_conda_kernels` version `1.0.3`). This seems to be because nb_conda_kernels removes the default kernelspec but does not put anything to replace it. 

A solution would be for the kernelspec corresponding to the Root env to reuse this key rather than following the naming scheme for other envs. 

Alternately, it could not remove the default kernelspec. 

The result looks like the following image

<img width="696" alt="screenshot 2016-07-16 13 49 43" src="https://cloud.githubusercontent.com/assets/2482408/16896558/32641852-4b5d-11e6-9459-aab55fcd52a8.png">

**Comment by michaelpacer** [comment]
@pzwang, @carreau, @minrk, @kalefranz

**Comment by michaelpacer** [comment]
In the Jupyter `kernelspec` search process, we 

1. Lookup available `kernelspec`s by exact match with the notebook `kernelspec`'s name (using dictionary key call)
2. If none, grab all the `kernelspec`s whose language matches the `notebook` `kernelspec`'s language
     1. If there is only one match, use it and display nothing (only put a message in the console log)
     2. If multiple matches, trigger the `"spec_not_found.Kernel"` event and display a dropdown list of the matching `kernelspec` names available on the system

**Comment by minrk** [comment]
Further detail: Since the default kernelspec will have the name 'python2' or 'python3', and conda env kernels all have names like 'python [root]', this dialog will be shown for any notebook created without the conda env KernelSpecManager to anyone with at least one conda env.  Users who only have a root env will trigger the single-match logic above, and everything will be fine. It's also true in the other direction: anyone not using this extension who has more than one Python kernel will see this dialog when opening a notebook written by someone who has this extension.

**Comment by takluyver** [comment]
We also have a very vague plan to integrate a notion of environments into the default kernelspec system. We postponed this because:

1. It's not clear what model to use - there can be multiple kernels available in one environment, multiple environments available with the same type of kernel, and kernels that don't really match a specific environment.
2. We want this to be generic for different environment systems. Just for Python there's conda, virtualenv and pyenv, and no doubt other languages have their own similar tools. It's also not clear where the line is - do we try to handle docker containers as part of this too?

This hasn't got any less challenging, but if Anaconda feels the need to push environments into the existing kernelspec mechanism, maybe we need to try to work these issues out and produce a more general mechanism.

**Comment by damianavila** [comment]
I put some explanations in the mailing list [here](https://groups.google.com/d/msg/jupyter/jfPC-ROO_XY/sDu3eRbOAgAJ) and [here](https://groups.google.com/d/msg/jupyter/qE6fCyXe6fs/IpxGTDDNAgAJ).

And what @minrk decribes, it complements the info I provided there...

>This hasn't got any less challenging, but if Anaconda feels the need to push environments into the existing kernelspec mechanism, maybe we need to try to work these issues out and produce a more general mechanism.

You raised very well the complexities... now looking into this using the Jupyter dev glasses, I don't know if we want to introduce that complexity and push for a general mechanism... Now as a conda user and CIO dev... I would love to see something naively integrated. How I reconcile my two faces :wink:

In any case, for this specific issue, in nb_conda_kernels we need to deal better with users working with pre-existing ipynb. Pinging @bollwyvl and @stephenakearns.

**Comment by minrk** [comment]
Using the same default kernel name that IPython uses for the root env is probably the simplest solution in the immediate term.

We can also tweak the language in our dialog to sound less like something went wrong. More like "we found multiple kernels for this notebook, but we aren't sure which one you want, so here's a list"

Yet another solution on our side would be to work a bit harder to guess which kernel to use, e.g. Pick the language-matching kernel with the same major version and highest total version, alphabetically first in case of exact version tie. Right now we punt to dialog at the first sign of ambiguity.

**Comment by damianavila** [comment]
>Using the same default kernel name that IPython uses for the root env is probably the simplest solution in the immediate term.

Probably...

>We can also tweak the language in our dialog to sound less like something went wrong. More like "we found multiple kernels for this notebook, but we aren't sure which one you want, so here's a list"

Yes... that would be better.

>Yet another solution on our side would be to work a bit harder to guess which kernel to use, e.g. Pick the language-matching kernel with the same major version and highest total version, alphabetically first in case of exact version tie. Right now we punt to dialog at the first sign of ambiguity.

And that would be really great!!

**Comment by jasongrout** [comment]
> Yet another solution on our side would be to work a bit harder to guess which kernel to use

I like having the choice when there is any ambiguity.

**Comment by dancosta** [comment]
I just want to let register, in searchable words,  that this issue is related to the problem of having the **Python [Root]** as the kernel to a new jupyter notebook. I don't recall what was the conda version I was using before I updated to version 4.1.11. 
My intention is to let people searching for this to know that there is an Open issue addressing the problem.

**Comment by bollwyvl** [comment]
@dancosta We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing! @michaelpacer sorry for the delay!

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166

**Comment by dancosta** [comment]
Thanks @bollwyvl for the reply, I've updated and now I got "Python [default]" as the kernel name, instead of the Python 3 that used to be.

**Comment by damianavila** [comment]
> Thanks @bollwyvl for the reply, I've updated and now I got "Python [default]" as the kernel name, instead of the Python 3 that used to be.

That's expected, that `python [default]` use Jupyter's default kernel name ('python2' or 'python3') for the current env... so you are safe to use that one.
Every `Python 3` notebook will be opened as a `python [default]` one and if you share a notebook with this kernel in it with someone without `nb_conda_kernels` they will be able to open it and they will see the `Python 3` name.

**Comment by dancosta** [comment]
Thank you @damianavila for the explanation. That's great to know!
