### ISSUE TITLE
Improve conda clean --packages

### ISSUE THREAD

**Issue by frol** [conda/conda#3177]
I do understand that there is a [TODO comment in the source code](https://github.com/conda/conda/blob/ebc6a353d6d141f0b2e15e03b0d4cad469f3c957/conda/cli/main_clean.py#L260-L261), but `conda clean --packages` assumes that all conda environments are either hard-linked or completely copied, and completely ignores the fact that packages can be also symlinked.

I hit the issue that old python packages are not get cleaned due to the hard links inside the packages (just like the TODO comment mentioned above warned us), and reading the code and searching the internet I came across only [one discussion on Continuum Google Groups](https://groups.google.com/a/continuum.io/forum/#!topic/conda/NANWcX64dIA), so I figured that it might be worthwhile to create an issue for this.

**Comment by willsALMANJ** [comment]
I discovered a third somewhat minor issue with the way `conda clean` works right now. Here is a summary of the issues with `conda clean` that I am aware of:

1. It breaks symlinked packages because it just checks hard links (this is the issue noted above).
2. It does not clean packages that contain multiple hard links to the same file in the package because it just checks for any file with a hard link count greater than one (this is issue #7597).
3. It erroneously cleans metadata-only packages like blas and numpy because they have no files that get hard linked (this is the third issue that I am adding to the list).
