### ISSUE TITLE
Conda does not seem to handle basic auth

### ISSUE THREAD

**Issue by srossross** [conda/conda#323]
Works:

`TOKEN=7365616e-74727462-556a-451e-834e-ba48884bd12b`

`curl https://$TOKEN@conda.binstar.org/wakari/osx-64/repodata.json`

Fails:
```
conda install -c 'https://$TOKEN@conda.binstar.org/wakari' wakari-file-xfer-app
Error: failed to fetch repo data from https://7365616e-74727462-556a-
451e-834e-ba48884bd12b@conda.binstar.org/wakari/osx-64/
```

**Comment by joewalnes** [comment]
Is there any plan to add basic auth to conda channels? It seems it's supported in proxies, but not the end channel.

**Comment by joewalnes** [comment]
Hello Conda team

I'd really like this functionality as I need to put authentication in place in front of `http[s]://` channels. 

Proposal: allow channels to include `user:pass` style directives in `condarc`.

Example condarc:

```yaml
channels:
  - http://user:pass@some.custom/channel
```

This is consistent with how it's done for proxy_servers: https://github.com/conda/conda/blob/2e6e70f3d79507348bdeabde26e916edb3466f3f/tests/condarc#L19

Seeing as Conda now depends on the requests library (which it didn't when this issue was first opened), this should be a relatively straightforward change.

I am happy to implement and send a PR, if the Conda team is happy with the proposal. I'll also include `ftp://` authentication for consistency. Please let me know if you'd like this change made and I'll get it done.

**Comment by asmeurer** [comment]
I think that should already work, since user:pass is a standard part of urls.

**Comment by joewalnes** [comment]
ok, it seems it works :smile:

**Comment by jehturner** [comment]
This does not work for me (as in the last 3 posts, using Anaconda 4.2.0):
```
> conda create -n test -c "http://username:password@astroconda.gemini.edu/channel" package_name

Fetching package metadata ...........CondaHTTPError: HTTP Error: HTTPError: 401 Client Error: Authorization Required for url: http://astroconda.gemini.edu/channel/linux-64/repodata.json: http://astroconda.gemini.edu/channel/linux-64/
```

But this **does** work normally:
```
curl "http://username:password@astroconda.gemini.edu/channel/linux-64/repodata.json"
```

Could this be a regression or am I just doing something stupid? Thanks!

**Comment by kalefranz** [comment]
@jehturner Please update conda with `conda update conda`. If you're still having problems, please file a new bug report.  https://github.com/conda/conda/issues/new

**Comment by jehturner** [comment]
Thanks a lot @kalefranz. It seems to be working now with conda 4.3.4 (apart from some complaints about "noarch"). Next time I'll try that first, rather than just using the latest anaconda release (which has conda 4.2.9, the non-working version in the above example)...
