### ISSUE TITLE
Bogus comments in `conda config`

### ISSUE THREAD

**Issue by pitrou** [conda/conda#3272]
```
>conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'numba'
--add channels 'antoine'
--add channels 'conda-canary'   # highest priority
```

yet:
```
>conda update --all
Fetching package metadata ...Uncaught backoff with errno 2
Uncaught backoff with errno 2
......
Solving package specifications: ..........

Package plan for installation in environment C:\Miniconda3:

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:     4.2.1-py35_0 conda-canary --> 4.1.11-py35_0
    conda-env: 2.6.0-0      conda-canary --> 2.5.2-py35_0

Proceed ([y]/n)?
```

**Comment by HugoTian** [comment]
For the first one , I think @kalefranz added that --add and priority stuff


 if key == "channels" and q in (0, numitems-1):
                        print("--add", key, repr(item),
                              "  # lowest priority" if q == 0 else "  # highest priority")
                    else:
                        print("--add", key, repr(item))

Moreover I think conda config --show will give better output for config

**Comment by HugoTian** [comment]
For the second one, please see [here](https://github.com/conda/conda/blob/master/conda/utils.py#367), which is added by @kalefranz 

It use log.error to show the uncatched error

**Comment by kalefranz** [comment]
The second helped me find a bug. It was fixed in 4.2.2.  The first is probably a result of pulling 4.2.2.  I pulled it because it broke conda-build and I didn't want to mess up people's CI. I've been working today on a better testing of conda and conda-build together (non-trivial given they're in different repos).

**Comment by kalefranz** [comment]
Actually, I'm not sure what's going on with the first.  With conda 4.2.1 installed, can you give me the output of `conda config --show-sources`?

**Comment by kalefranz** [comment]
@HugoTian, as I'm guessing @pitrou knows, errno 2 is ENOENT, meaning the path doesn't exist.  In 4.2.2+, all file removal (along with the `rm_rf` function) use `utils.backoff_unlink`, which takes care of a race condition that results in this warning.

**Comment by HugoTian** [comment]
For the first one, I double checked the behaviour of old version

for conda config --get channels, in 3.x , and 4.0.x , the output like below:

--add channels 'defaults'
--add channels 'conda-forge'
--add channels 'tianzhang1000'

The reason for this format is stated in the comments:

     # Use repr so that it can be pasted back in to conda config --add
                    print("--add", key, repr(item))

Now in conda 4.1 and 4,2, we add " # highest priority " stuff

**Comment by kalefranz** [comment]
Yeah, see https://github.com/conda/conda/blob/master/conda/cli/main_config.py#L318

                # Note, since conda config --add prepends, these are printed in
                # the reverse order so that entering them in this order will
                # recreate the same file

That's the historical comment.  In 4.1, I added the lowest/highest priority indicators to the printout since it was potentially confusing.

In 4.2, we've made the deliberate decision to change the behavior of `--add` to append rather than prepend.  It's a safer default for the more naive user.  There are also both `--append` and `--prepend` options to be more explicit.

**Comment by pitrou** [comment]
@kalefranz, with conda 4.2.1, the output looks saner:
```
c:\>conda config --get channels
--add channels 'conda-canary'   # lowest priority
--add channels 'antoine'
--add channels 'numba'
--add channels 'defaults'   # highest priority

c:\>conda config --show-sources
> cmd_line
debug: False
json: False
```
