### ISSUE TITLE
Choosing whether to upgrade primary (non-dependency) package

### ISSUE THREAD

**Issue by lukeyeager** [conda/conda#3360]
Pip's default is to only upgrade when necessary (but can be overridden with `--upgrade`):

``` sh
pip install 'itsdangerous==0.21'  # installs 0.21
pip install 'itsdangerous>=0.21'  # reports "Requirement already satisfied (use --upgrade to upgrade)"
```

Conda's default is to upgrade whenever possible:

``` sh
conda install 'itsdangerous==0.21'  # installs 0.21
conda install 'itsdangerous>=0.21'  # installs 0.24
```

Is there any way to opt out of that upgrade? There's not a `--no-upgrade` flag and the `--no-upgrade-deps` command doesn't have an effect here.

**Comment by minrk** [comment]
I'm finding that I would love this for Binder.

In Binder, we do installation in two stages:

1. Binder itself sets up a base environment with functional defaults (working Python, Jupyter, IPython, etc.)
2. users can provide an `environment.yml` to specify dependencies for their code.

We do the installation with (approximately):

- conda env update -n root -f base-environment.yml
- conda env update -n root -f user-environment.yml

*Usually*, an environment.yml used on Binder only contains the dependencies to run the code (e.g. pandas, etc.), and not the dependencies to run the application (IPython/Jupyter/etc.). However, if you have a repo of notebooks for general use, such as a tutorial, it is logical to provide an environment.yml that includes everything needed to run the notebooks, e.g. including `notebook` itself. However, including that information means that the `notebook` package will get updated on every install, rather than using the already-present version in the base environment.

There's a perverse incentive now, because users get the best experience *not* specifying dependencies like `notebook` and building environment.yml files specifically for Binder, which is the opposite of what we want to encourage.

What we really want for Binder is to get pip-style behavior, where already-satisfied dependencies present in the user's `environment.yml` are not upgraded. What is the best way to go about this? It would be extra super awesome if this resulted in a fast check with no network requests if a given environment already satisfies all of the dependencies in an environment file.

**Comment by kalefranz** [comment]
There is now a `--freeze-installed` flag.  While the functionality is in the conda 4.5 code, I don't think we actually got the flag exposed until conda 4.6.  You can get a preview release of conda 4.6 with

    conda config --add channels conda-canary
    conda update conda

Does `--freeze-installed` cover your use case?

**Comment by lukeyeager** [comment]
@kalefranz from the name of the flag, it sounds like it should cover this use case, yes.

I don't actually have a need for this feature anymore (this was for an old project), so I'm not set up to test the new feature. From my point of view, you can close this issue. Might want to double-check with @minrk that he's happy, too.

**Comment by kalefranz** [comment]
I've started an issue to track behavior changes we might want to make in a far-off conda 5.0 release, and making the (new in conda 4.6) `-S` / `--satisfied-skip-solve` the default behavior is on the list.  See https://github.com/conda/conda/issues/7394

**Comment by minrk** [comment]
@kalefranz that sounds great! Thanks for working on it. I tested it out it gets *almost* to what I want, which is:

- if requirements are fully satisfied, skip solve (-S does this nicely)
- if *some* requirements are fully satisfied, do not upgrade them (neither -S nor --freeze-installed do this)

For example:

```
$ conda create -yn test simplejson=3.14  # 3.15 is latest
$ conda install --dry-run -S -n test simplejson
# All requested packages already installed. (yay!)
$ conda install --dry-run -S -n test simplejson ujson
The following NEW packages will be INSTALLED:

    ujson:      1.35-py36_0   conda-forge

The following packages will be UPDATED: (oops)

    simplejson: 3.14.0-py36_0 conda-forge --> 3.15.0-py36_0 conda-forge
```

simplejson should *not* be updated because it is already satisfied.

In this context, `conda install --freeze-installed ujson` executes precisely the transaction I want to occur, but there doesn't seem to be away to get the `-S` behavior on a subset of packages if there are any transactions to execute. Alternately, `--freeze-installed` doesn't freeze the packages on the list that are already installed. That's what I'm after. Essentially, I want to change the interpretation of the presence of 'simplejson' in the package list to "ensure it is installed" from "install the latest available satisfying version".

For Binder, I also need these behaviors on `conda env update`, not just `conda install`. Maybe config options are enough for that, but at least the CLI options don't seem to be exposed there.
