### ISSUE TITLE
conda updates dependencies

### ISSUE THREAD

**Issue by bkreider** [conda/conda#337]
Conda updates all dependencies even if they are already satisfied.  This is definitely a problem for developers when pulling from a channel that has continuous builds and they want to just update one package.

**Comment by hhuuggoo** [comment]
well - how about this - is  there a way to install, but have it do the minimal thing?  only update what needs to be updated to satisfy dependencies?

**Comment by asmeurer** [comment]
There isn't (that's what this issue is for).

The best workaround is to use the pinned feature to pin the packages you don't want to be updated. Alternately, if you are dealing with your own packages, you can specify all the dependencies exactly in your recipe, so that all the versions are exactly where you want them to be.

**Comment by pzwang** [comment]
No, I think this is a bigger issue than just foisting a thing on users that they need to pin packages.  conda should do one of two things:

1. install the minimum number of things to satisfy the specified package install/update request
2. install/update everything that the package depends on to their latest versions.

I think mode 1 should be the new default behavior, and mode 2 should be achieved with a `--alldeps` flag or something.

People generally want stability.  This is especially true when people are using these tools to do real work and run production code.

**Comment by asmeurer** [comment]
I meant that more as a way to solve this with the current situation. I know that this should be done, but it's not completely trivial to do (but I think I know how), as I noted above. 

I disagree that it should be the default, though. I like the current behavior where conda updates everything. But let's be sure to have a huge bikeshed discussion about this, though, because it's very important.

**Comment by teoliphant** [comment]
I agree with Peter.   We should make #1 the default.   The current behavior is not suited to an important, but often silent user base --- the enterprise user.

**Comment by ijstokes** [comment]
OK, so I don't think this is bike-shedding.  I think this is really important, as @hhuuggoo has flagged in an email.  I would say that both behaviors are desirable, and I understand how this is complicated because of the SAT solver.  I think we need to go with PLS here, rather than "best design".  What is going to be the least surprising behavior?  There are 3 ways a (potentially) new conda package can be installed into an env:

1. `conda install foo`
2. `conda update foo`
3. `conda install foo=X.Y`

In all cases, the user *just wants `foo`* (and possibly with some specific version).  The problem we have is that if they previously installed `bar`, then this `conda` operation may make `bar` not work.  And they will have no clue, since we don't try to keep all previously installed packages working with satisfied deps at any given time (aside: and most users have no idea that this trap exists).

So what does `conda` need to do?  Satisfy dependencies for `foo`, in any way that will allow the "best" `foo` that it finds to run properly.  The user doesn't care, so I would say that `conda` doesn't *need* to care either.  The fact that it does care (i.e. currently only has one opinion on this matter) is an outcome of the SAT solver implementation.

The advantage of doing a "minimal" set of package updates is that other packages like `bar` that might be broken by doing a "maximal" update of `foo` dependencies to the latest version, *may* be saved from such a fate.  That, to me, is certainly a lot less surprising than discovering a few days or weeks later that `bar` is mysteriously broken.

Performance-wise, this could save a stack of downloads and installs.

Administratively, it means the ground is changing under your feet in a production environment in a way that is qualitatively scary. (the quantitative part is the risk of `bar` being broken)

Counter arguments:

1. `bar` still may be broken, and you wouldn't know.  I thought there was something like `conda verify` that could warn you about this, but it doesn't look like that exists.  Presumably it would be pretty easy to implement?

2. You might be expecting to get `foo` along with all the latest and greatest dependencies, and you don't.  Or maybe the developers of `foo` would expect that if you just did a `conda install foo` today, you would get `foo` along with the latest and greatest dependencies.

Having outlined it thus, I tend towards the view that `--minimal` should *become* the default, and `--maximal` should be available as an option, and that perhaps we should stage the transition between these two modes *once* it is actually implemented (assuming that is possible!)

**Comment by teoliphant** [comment]
Excellent discussion, Ian!   Agreed!  Can we implement --minimal.

**Comment by asmeurer** [comment]
> bar still may be broken, and you wouldn't know. I thought there was something like conda verify that could warn you about this, but it doesn't look like that exists. Presumably it would be pretty easy to implement?

Broken how? What would conda verify do?

> You might be expecting to get foo along with all the latest and greatest dependencies, and you don't. Or maybe the developers of foo would expect that if you just did a conda install foo today, you would get foo along with the latest and greatest dependencies.

Exactly. Developers are only going to test their stuff against the most recent version(s). If someone only does `conda update ipython` (e.g.) and the IPython developers eventually stop supporting some old version of pyzmq (e.g.), then unless we know enough about this to put it in the version restrictions for the `ipython` package, people who have had ipython for a long time and have the old pyzmq dependency will eventually have a broken system. 

Again, I do appreciate that this is a useful behavior (although I would like for @teoliphant to weigh in on its priority, since it could be some work to implement, and I am working on other things too). I just disagree that it should be the default. Of course, we can add command line switches and .condarc options to change things.

**Comment by hhuuggoo** [comment]
It's primarily open source developers that test their stuff against most recent versions.  Enterprise developers want to test their stuff against whatever current version the company is on.

**Comment by bkreider** [comment]
> Broken how? What would conda verify do?

AFAIK, conda doesn't care about the state of your system on disk.  It only cares about the current transaction.  So you can install conflicts as long as you do it in two different conda "transactions".  (at least this was true).  For example, if you installed ipython and then later installed an incompatible version of pyzmq (pretend it is 0.0.1), you wouldn't know you broke ipython.  

> does conda update ipython (e.g.) and the IPython developers eventually stop supporting some old version of pyzmq (e.g.), then unless we know enough about this to put it in the version restrictions for the ipython package

Isn't this accepting failure for the whole system?  Our ipython conda package needs to know it's dependencies.  Otherwise, we might not even have the latest pyzmq as a conda package and it would still break in a way not detectable by conda.

**Comment by bkreider** [comment]
> AFAIK, conda doesn't care about the state of your system on disk. It only cares about the current transaction. So you can install conflicts as long as you do it in two different conda "transactions". (at least this was true). For example, if you installed ipython and then later installed an incompatible version of pyzmq (pretend it is 0.0.1), you wouldn't know you broke ipython. 

Since tone doesn't come across short comments:  this isn't meant to be a value judgement against conda.  We have actively chosen to implement conda in this simpler manner.  I wanted to remind others of this detail.  Something like rpm has a local database of state and will prevent you from installing things that conflict with previously installed packages.

**Comment by ijstokes** [comment]
> What would conda verify do?

Check that all dependencies for all installed packages are still satisfied.

**Comment by asmeurer** [comment]
@ijstokes the solution that I would implement would still use the SAT solver. It would just change the constraints to prefer existing versions for dependencies rather than preferring the newest possible version. But for instance, if you install a package and that package says in the metadata that it requires a newer version of a dependency than what is installed, it would still update it, because it has to to be satisfiable.

Actually, what would be the preferred situation here, "for the enterprise"? To update the dependency all they way when it has to, or to update it as little as possible. For instance, say we have the following packages

A: 1.0 (depends on B >= 1.0)
A: 2.0 (depends on B >= 2.0)
B: 1.0
B: 2.0
B: 3.0

and we have A 1.0 and B 1.0 installed, and want to update A to 2.0. Should this install B 2.0 or B 3.0?

**Comment by openvest** [comment]
I very much appreciate this thread.  I tend to agree with Peter that the
"least surprising" or --minimal is better from my standpoint.  As to
developers wanting the latest....I'm using AS to install production code at
JPM and offer some thoughts:

1.  I recently went through my py-conda_requires.txt DOWNGRADING all
package versions to match exactly what is found in Anaconda 2.0.1 .  That
and only that Anaconda release is  a  "SEAL" approved component at JPM.
Sure, we'll get newer anaconda releases similarly approved in the system
but there will be an absolute requirement that packages not approved will
not be allowed into "production".   BTW: anaconda is a developers salvation
here because there is a menu of 150+ packages to choose from without
jumping through the security hoops we face.

2. I currently deploy by dealing with all of the versioning in QA and UAT
(pre-production) environments and a final requirements file is deployed
(--no-deps) with the exact version and build that was tested.

3. Aaron's B2.0 or B3.0 question above.  B2.0 is preferred.  B3.0 is more
likely to have it's own dependencies that will want to upgrade C3.0.

conda anticipates my needs and get's 90% of what I expect.  I have,
however, always regarded the over-agressive updates of conda as something
that I have to explain away.  Most people have no idea of pinning which I
consider an advanced management feature.  More common case is updating one
package and setting off an avalanche of apparently unrelated updates.

Truth be told. As AS is better understood, this will be less of a
"production" problem since we can have AS configurations that only contain
security scanned and "SEAL" (or similar) approved packages.

--
Phil

**Comment by hhuuggoo** [comment]
Yea - I think updating as little as possible isn't really important - but maybe others should chime in.  For me it's generally binary, either I'm in scope with approved packages, or I go ahead and upgrade.  If possible some information about the min version reqed when updating would be nice - though if this is hard that's definitely a distant second.  The most important case I think is when no deps really need to get updated, but they do anyways

**Comment by asmeurer** [comment]
@openvest thanks for your input. If only Anaconda 2.1 is SEAL approved, then you can put the `anaconda` metapackage in your requirements, and that will force all versions to be at those versions. I would also agree that if packages are not approved then they shouldn't be put in the AS in the first place.

**Comment by jangerritharms** [comment]
Personally I would also consider the minimal option the better one. I am responsible to keep the software running in our research group and everytime people would like to update one package, all packages are updated which will break most of the scripts and will result in many angry emails in my inbox. Thus I would also prefer stability over the current "update everything" solution.

**Comment by ilanschnell** [comment]
@jangerritharms can you give an example of updating a package which "updates everything"?  Note that only the dependencies of the package you are updating are updated, not all installed packages.  So this is quite different from `conda update --all`.

**Comment by jangerritharms** [comment]
@ilanschnell Yes sorry for being so unclear, indeed what are meant are all dependent pacakges. Say I have an environment with pyzmq=2.2.0, zeromq=2.2.0, ipython=2.4.1 and spyder=2.3.2. If I then do: 
<code>conda update spyder</code>
then I will also get pyzmq=14.5, ipython=3.0.0 and zeromq 4.04.
Much of the code I use depends on zeromq=2.* however. So it would be much easier if there was an option that only updates spyder and necessary updates but not unnecessary and if that option would be the default.

**Comment by hhuuggoo** [comment]
@jangerritharms in your case, you can just use pinned packages - http://continuum.io/blog/advanced-conda-part-1.  It will prevent that package from ever being updated
