### ISSUE TITLE
Package variation that does not include dependencies

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3418]
We have had multiple requests for `rpy2` in an environment where R is provided outside of the Anaconda ecosystem: i.e. the system owners have installed it by some other means: from source, from installers, from yum/apt.  But they want the Conda version of `rpy2` and they want it to pick up and work with their pre-existing R.

This is a reasonable request, but one which is not easily handled today.  I believe (though haven't tested it) that this can be achieved by one of:

    conda install --nodeps -c r rpy2
    conda install /path/to/rpy2-conda-package.tar.bz2

But this puts things in a funny state: it leaves you with a Conda environment that has installed packages whose dependencies are not satisfied.  There are (I believe) all sorts of ways a future Conda operation will then try to satisfy those deps or get confused about the state of things, when really what we want is to say "this is just how its supposed to be" -- and if `rpy2` doesn't work because some ancient version of R is installed, or it isn't installed at all, well, that we can live with: Anaconda and Conda did its best to do what the user requested.

`rpy2` is just one example of this behavior, but it is a concrete one so I've decided to focus on it.

We have an active client engagement where we are in exactly this situation.

**Comment by kalefranz** [comment]
We've talked about solving this with "shadow" packages.  As a work-around, could you try building an empty R package, and then putting that channel as your highest priority channel in your channels list?

**Comment by mingwandroid** [comment]
I'm not sure how frequently or well such a mixed-ecosystem setup will work with binary packages.

How did `rpy2` work out? Which OS was used?

**Comment by kalefranz** [comment]
Yeah as Ray sort of hinted at, no guarantees that something like that will work, even with the shadow package.  Could work on some systems/OSes, and not on others.

**Comment by csoja** [comment]
After further team discussion, this seems like asking for numpy or scipy that use the system python (or whatever python the user has installed) instead of Anaconda python.  The number of possible "gotchas" here are extensive - and it is not clear we could get to a point where it was "guaranteed" to work.  It seems for these types of cases, a version of rpy2 may need to be built for the particular customer use case.

**Comment by ijstokes** [comment]
@csoja and @kalefranz I get it.  The answer for people who want things done this way is going to be something like:

1. Mirror `rpy2` from PyPI into Anaconda Repository
2. Install R however you like onto your system(s).
3. Install the build chain on each system.
4. `pip install rpy2` pulling the package from Anaconda Repository

Or alternate approach from step 3 onwards:

3. Install the build chain onto one representative system
4. `conda skeleton pypi rpy2` (pointing it to Anaconda Repository PyPI mirror)
5. `conda build rpy2`
6. `conda upload /path/to/package`
7. On all systems that require it, `conda install -c localr rpy2

Works for me!  Let me know if you have any comments or thoughts on this workflow I've proposed, because I will need to pass this on to a customer who has this setup.

**Comment by csoja** [comment]
@mingwandroid since you've built rpy2, do you have any comments on Ian's approaches for rpy2?

**Comment by mingwandroid** [comment]
> 1. Mirror rpy2 from PyPI into Anaconda Repository
@ijstokes, can you list the exact command(s) for that?

I don't think `conda-build` can/should be used to build software outside of the conda ecosystem. I expect there are too many assumptions made in the codebases for conda and conda-build for that to work (@msarahan, @kalefranz, your thoughts please?), so for Linux and macOS, I would go with the first approach.

On Windows, our package applies a lot of patches that I had to write: https://github.com/mingwandroid/conda-recipes/tree/master/python/rpy2 (note, the first patch *isn't* for Windows but is *probably* fixed in 2.8.3). I've no idea how anyone who builds rpy2 for Windows does it without these fixes. One thing to note is that we use mingw-w64 GCC 5.4 while Rtools uses (its own build of) GCC 4.9.3 so this may be a reason why some of my patches are necessary (but I don't think it is).

The internet is full of tales of woe regarding rpy2 on Windows: http://stackoverflow.com/questions/14882477/rpy2-install-on-windows-7. It is one of the trickier packages I've built (since it involves both MSVC and GCC DLLs) and IMHO on that OS the only sensible course of action is `conda install -c r rpy2`, anything else will be a support nightmare.

If, in this instance, the customer wants to build it against a different (e.g. official) release of R for Windows and wants a conda package for that then it would be a fairly lengthy task, in the order of a week.

As an aside, I would like to get to the bottom of what's missing that they won't use all of our stuff.
