### ISSUE TITLE
Activating Python 3.5 fails in Windows Shells

### ISSUE THREAD

**Issue by illuzioner** [conda/conda#3511]
I followed the instructions here: http://conda.pydata.org/docs/py2or3.html  to install Python 3.5 into my existing Anaconda2 Python 2.7 installation.

I executed this command in PowerShell (PS) on Windows 7: 
conda create -n python35 python=3.5 anaconda 
and things seemed to install okay.  It hung on installation in PowerShell ISE.

However, nothing seems to happen in PS when I execute: 
activate python35

Executing "python --version" says

Python 2.7.11 :: Anaconda 4.0.0 (64-bit)
However, when I navigate to the newly created python35 directory and execute ".\python --version", I get

Python 3.5.2 :: Anaconda 4.1.1 (64-bit)
Everything outside this directory still identifies as Python 2.7. So, how DO I use change Anaconda to use Python 3.5?

If I do this in a cmd window instead of PowerShell, in that window only the environment seems to change. Is that intentional?

It seems Anaconda/Conda do not work reliably in PowerShell, even though it is a much more useful shell than the simplistic cmd window.

Seems there are several conflicting things going on. In my start menu I have "IPython (python35)" which brings up a cmd window with python 3.5. I also have "Anaconda Navigator (python35)" which opens the Navigator, and opens Jupyter notebooks in Python 2.7, NOT 3.5. There is no option to change the kernel when I do this. Finally, I have "Jupyter Notebook (python35)" which opens Jupyter. When I open a notebook, it says: "I couldn't find a kernel matching Python 2. Please select a kernel:"  At THAT point, I can change the kernel to Python 3.5.  Activating 3.5 in a cmd window doesn't change this.

I far prefer PowerShell since it has similar power to Unix and resizeable windows, but that aside, there seems to be something wrong with Anaconda in PowerShell.

**Comment by njalerikson** [comment]
Significant work was just completed ( #3175 ) that refactored all of the activate/deactivate code. Currently only the CMD activate/deactivate codes are known to work 100% correctly (and is actually part of the unittesting) with the new update but the update includes the groundwork/preliminary support for PowerShell/Cygwin/MinGW/MSYS and also Ubuntu on Windows (hello Windows 10).

Since this ticket was opened before PowerShell started to receive support I think this should be closed until further work and testing can be done.

**Comment by kalefranz** [comment]
Powershell support will be tracked via #626
