### ISSUE TITLE
Allow activating multiple environments

### ISSUE THREAD

**Issue by abretaud** [conda/conda#3580]
Hi,
I'm trying to configure conda to use it on a computing cluster with command line access for multiple users (~300 accounts).
The idea is that we will provide to users some preinstalled conda environments that they can use as they need.

Some people will want to activate several of these environments to perform their compute task. The problem is that the `activate` script calls `deactivate` before doing the activation job, so users can only have 1 environment loaded.

I know that activating multiple environments could be a problem as some incompatibility could arise depending on the packages installed in each env. But in our case, in many situations, it would work perfectly well (and if it's not, users would be able to take care of it).

So I'm wondering if you think this feature could be added to conda somehow? Maybe with a special option for the activate script, and a modification to deactivate to allow it to deactivate _all_ the loaded env.
I can work on a PR if you are ok with the idea.

The other option would be to force them to adopt the proper conda way (they create their own environments), but it would make the transition too hard for most of them...

**Comment by groutr** [comment]
So, if I understand correctly, you're proposing that it be possible to activate more than one environment at a time by removing the deactivate step from the activate script.  Then you would add an option to deactivate that would allow it to deactivate all the previously activated environments.  Is that right?

Activating an environment prepends that environment's directories to PATH.  Thus activating two environments at the same time in the same terminal session is somewhat ambigous.  Which environment should have precedence?  Since we can't be ambigous about what environment is active, one environment can be active in a session at a time.

Each user should be able to activate a conda environment for each terminal session they have open.  Each terminal session has its own shell environment. For example, on my linux system, if I want to activate two conda environments, I need to open two terminal sessions.  Since each terminal session has its own shell environment, I can activate a different conda environment in each session without any problems.  There are no conda environments the need to be deactivated.

When using preinstalled environments, it might be a good idea to ensure somehow that users don't change the preinstalled conda environment.  One problem that can arise is when a user upgrades packages that breaks another users's code.  This is one of the several problems that conda environments solve very well.

I would, of course, highly encourage you to educate your users about conda environments.  Environments are pretty powerful and a little knowledge goes a long way.

If I've misunderstood your post, please let me know.  I think the above information should help you.

**Comment by kalefranz** [comment]
This issue relates to #2502, and I'd encourage you to weigh in there. @pzwang has proposed the ability to "stack" envs, pretty much as you've described. I consider #2502 a first step toward that.

Also, implementing #2502 would resolve https://github.com/conda/conda/issues/3411, which often happens in cluster environments.

**Comment by abretaud** [comment]
> So, if I understand correctly, you're proposing that it be possible to activate more than one environment at a time by removing the deactivate step from the activate script. Then you would add an option to deactivate that would allow it to deactivate all the previously activated environments. Is that right?

Yep, that's it

> Activating an environment prepends that environment's directories to PATH. Thus activating two environments at the same time in the same terminal session is somewhat ambigous. Which environment should have precedence? Since we can't be ambigous about what environment is active, one environment can be active in a session at a time.

Precedence would depend on the order or activation, ie each new env gets its path prepended to PATH. That's how it works currently on our cluster with simple bash scripts, and it works not so bad for most of the softs we use.

> Each user should be able to activate a conda environment for each terminal session they have open. Each terminal session has its own shell environment. For example, on my linux system, if I want to activate two conda environments, I need to open two terminal sessions. Since each terminal session has its own shell environment, I can activate a different conda environment in each session without any problems. There are no conda environments the need to be deactivated.

Hum, yes, no problem in having multiple shells with specific activated env. Our use case is that user want to run as a job a big pipeline that uses many different software, that are womewhat unrelated. A script like this:
```

#!/bin/bash
source activate softA
source activate softB
source activate softC
source activate softD

my_huge_pipeline.sh|py|pl|... --that uses --internally the -4 softs
```

> When using preinstalled environments, it might be a good idea to ensure somehow that users don't change the preinstalled conda environment. One problem that can arise is when a user upgrades packages that breaks another users's code. This is one of the several problems that conda environments solve very well.

I *think* it's not a big problem if we don't give write permissions to users for the system-wide conda, and let them create their own environments (if they need to) in their /home:

```
conda create -p /home/my_env softA softB
source activate /home/my_env
```

> I would, of course, highly encourage you to educate your users about conda environments. Environments are pretty powerful and a little knowledge goes a long way.

Yes, I agree, but that will take a looong time I think... Most of our users are not power users.

@kalefranz right, #2502 looks like a good first step, but still a little bit different as here I'd like to stack multiple envs.

**Comment by groutr** [comment]
@abretaud I think I understand your use case a little better now.  AFAIK, what you are proposing should technically work.

**Comment by mingwandroid** [comment]
My opinion is: Having a few envs for certain specific purposes is fine. Those purposes are:

    1. To store only conda in order to simplify conda's code.
    2. To store the root/Administrator installed, read only packages that everyone can use.
    3. To store the user's customizations of that env.

Making this arbitrarily cascadable would be really confusing and difficult to manage and communicate. We'd also run out of PATH on Windows quite quickly.

**Comment by njalerikson** [comment]
Actually, a change like this would start morphing Conda into something more akin to lmod.

An interesting concept with potential.

I would personally want a solution like this to have a broader understanding of what kinds of environments are being activated. That way if say the first/base environment activated is Python 3.5, any subsequent activations will ensure that the Python versions match (to an extent). This should eliminate the most obvious dangers.

In conjunction with the suggested boolean variable `stack_envs` from #2502, I would suggest something like a boolean variable `deactivate_on_activate`. I'm sure these variables are self explanatory in the scope of this discussion.

**Comment by thoth291** [comment]
Basically, in peoples mind, there are 3 types of environments:
- the main python environment
- additional packages environment
- additional binary/lib environment

So each environment can be treated as source for python, source for packages (using site packages environment), source for bin/libs.

Let's assume we have
- EnvA
  - binA
  - PythonA
  - PkgA1
  - PkgA2
- EnvB
  - binB
- EnvC
  - binC
  - PythonC
  - PkgC1
  - PkgC2

So I would suggest extending the activation logic to something like this:
```bash
activate EnvA
activate -p EnvB
activate -b EnvC
```
Would setup something like this:
- Env
  - binC:binA
  - PythonA
  - PkgA1
  - PkgA2

In contrast:
```bash
activate EnvA
activate -b EnvB
activate -p EnvC
```
Would setup something like this:
- Env
  - binB:binA
  - PythonA
  - PkgA1
  - PkgA2
  - PkgC1
  - PkgC2

Or even weird as:
```bash
activate EnvC
activate -b EnvA
activate -b EnvC
```
Would setup something like this (to make sure that the order of search for packages would be preserved as needed):
- Env
  - binC:binA:binC
  - PythonC
  - PkgC1
  - PkgC2

Regarding deactivate - by default it will deactivate the last activate.
There will be also additional switch to make a specific deactivation of some environment.
And additionally a way to deactivate all environments.

This will allow to write strange scripts like this one:
```bash
activate EnvA
   do_only for_A
   activate -b EnvB
      do_for_A_and_B
   deactivate
   activate -p EnvC
      do_for_A_and_C

deactivate -all
do_something_else
``` 
I'm just thinking that without decent definition of atomic operations within activate - there is no way to stack the environments properly.

**Comment by mingwandroid** [comment]
I contend there's little value to this. Conda envs are cheap to create and destroy and we shouldn't complicate things with this stuff. I stand by my 3 and 3 only.

**Comment by thoth291** [comment]
Again, just like @njalerikson said [here](https://github.com/conda/conda/issues/3580#issuecomment-252082291): introducing stacking might move activate/deactivate closer to lmod behavior and, who knows, may be there is a need to think about integration some of the conda stuff with lmod...

**Comment by groutr** [comment]
@mingwandroid is right in my opinion.  Conda environments, in almost all cases, are incredibly cheap in terms of overhead and weight.  The size limit on PATH is also another factor.  Having separate environments means now you have to maintain many more conda environments.  Packages in every environment now have to be maintained and updated.  Environments are sure to overlap and shadow each other.  You now need to track binaries and libraries in each environment. On top of that, order of activation would be incredibly important.

If using conda environments requires you to be a power-user, I think the subtle issues that could arise from stacking environments would be far beyond a power-user.  Not only would you have to understand environments, but you would have to understand how environments interact with each other.

**Comment by mingwandroid** [comment]
I've had to read about `lmod` just now, and I don't think being like `lmod` is a design goal for `conda` nor do I think `lmod` has the same constraints as `conda`.

**Comment by asmeurer** [comment]
Something that hasn't been addressed (if it has I missed it). Why can't you just install all the packages you need into a single environment? Installing the same package into multiple environments is extremely cheap, since conda uses hard linking.

**Comment by abretaud** [comment]
I agree, creating environments is cheap and is the *right* way.

But we have *many* users, and some software already available in the described way (and not enough time to port them to conda in a reasonable time frame).
So if we begin to use conda the default way, people will have to deal with 2 logics: some softs can be stacked, others not... I expect a deluge of support requests if we do this (and we're thinking about using conda to save us time, so...).

On the other hand, currently we use the described behavior with our local tools, and we get very few user requests of people having problems.

Again I perfectly understand that this should not be the default behavior, and that it should only be activated by people who are ready to assume the consequences (ie, teach impacted users how to create their own env).

**Comment by abretaud** [comment]
I don't know if you have all seen it: I opened the #3924 PR for this, your feedback is welcome!

**Comment by asmeurer** [comment]
What do you mean by "some softs can be stacked, others not"?

**Comment by doomsbuster** [comment]
We have a similar requirement. We provide our customers a platform that is multi-tenant with ability to host their data science models on our clusters. We would like to provision these environments through automation agents running on the target machines in the cluster.

So if a customer A came first and submitted their application, the daemon would start off and activate a conda environment for the App A. If after this a customer B comes and tries deploying their apps, will it de-activate the previous conda environment?

Is there a way the automation agent that runs on the target machine in the cluster have two active conda environments?

**Comment by abalter** [comment]
I'm chiming in here because I think both conda and computing have evolved quite a bit since 2016. This would be my use case:

**Some envs:**
* r-plotting (ggplot, pheatmaps, ggbeeswarm, plotly, many others as well...)
* python-plotting (matplotlib, seaborn, bokeh, plotly, etc...)
* python-notebooks (jupyter, jupyterlab, jupytext, extensions, ...)
* r-notebooks (rmarkdown, knitr, r-irkernel, ...)
* r-stats
* python-stats

**Use cases:**
If I was going to do some general exploratory analysis in Rmd, I could stack r-notebooks and r-plotting. If I am doing some advanced stats in a jupyter notebook in R I could stack python-notebooks, r-notebooks, r-stats, r-plotting. If I'm doing a python stats and plotting in a jupyter notebook, stack python-stats, python-plotting, python-notebooks.

**Advantages:**
I have close to a dozen R plotting packages I use (additions to ggplot, making plot grids, etc.), and as many stats packages. Sometimes I use r and python together in notebooks, sometimes not. When I use jupyter, I use jupyterlab, jupytext, lots of extensions, etc. It's not just jupyer anymore! Creating environments with a lot of packages requires a lot of typing. It makes to encapsulate purpose-specific collections and mix as needed.
