### ISSUE TITLE
Question: openness of Anaconda Server or local repository tools

### ISSUE THREAD

**Issue by GaelVaroquaux** [conda/conda#3583]
Hi Conda devs,

This is maybe the wrong place to ask the question, but I couldn't find a better place. In particular, my question seems related to information in the [2-years-old blog post on binstar](https://www.continuum.io/blog/developer/binstar-out-beta-now-available-everyone), but it's been siting for 10 days in moderation in the continuum blog.

So, I am trying to understand how different aspects of the conda ecosystem plug together. I've been reading the binstar blog post, which was outlining the technology and aspects of the business model, I wonder how much it is outdated with the conda-forge evolution.

My specific question is: Am I right in thinking that anaconda-server is not open source, as implied in the earlier blog post? If so, what is the roadmap / vision with regards to the open-source ambitions of conda and the community-building behind conda-forge to fill in this specific niche? Are there any recommendation for people who want to have local repositories or mirrors to use conda on them?

Local repositories are described in the [docs on anaconda-repository](https://docs.continuum.io/anaconda-repository/install#start-and-log-on-to-anaconda-server) but it seems to me that they point to non open components of the ecosystem. Mirroring is [also described using these tools](https://docs.continuum.io/anaconda-repository/mirrors-anaconda-repository).

So, is it that these documentations are outdated and there are open ways to replace the central server that conda talks too, or is the recommended way to use the closed anaconda-server? Sorry if I am asking a stupid question, I am trying to get some big picture, and it is a bit hard for me to follow something that is evolving so fast.

**Comment by GaelVaroquaux** [comment]
I am a bit disappointed not to have an answer. I would have thought that it was an important topic for the conda community. PyPI (and hence pip) has a variety of open source servers that can be deployed locally, because it matters to people.

For instance, my lab is located in a building of the CEA, the French atomic energy commission. For Ubuntu packages, they have a local mirror, which they supposedly audit.

**Comment by kalefranz** [comment]
Thanks Gael for your questions, and apologies that it's taken a few days to respond. I'm not sure who does Disqus moderation, but this is probably a better place for your questions anyway.

I only started working full-time on Conda as a Continuum employee on January 1, but I think I can address your questions fairly accurately.  Actually perhaps more accurately than most, because I was a conda user (and outsider) before I started working for Continuum, so I have both perspectives.

> I wonder how much it [(2-years-old blog post on binstar)[https://www.continuum.io/blog/developer/binstar-out-beta-now-available-everyone]] is outdated

The blog post has a "What you can pay for" section, which is somewhat outdated.  We still do charge a nominal fee for things like private packages, but this is most definitely not a revenue source for Continuum--it doesn't even really cover associated costs.  Between repo.continuuum.io and anaconda.org, outbound bandwidth served was nearly 200 TB for September, with Continuum covering all associated costs gratis.  (We're actually exploring options with CDN providers now to make the delivery even better.)  Selling various types of "space" on anaconda.org is definitely not part of Continuum's current business model.

> Am I right in thinking that anaconda-server is not open source, as implied in the earlier blog post?

You're correct that the code driving anaconda.org is closed source.  We *do* sell on-premise versions of this, and that offering is currently part of the [Anaconda Workgroup subscription](https://www.continuum.io/anaconda-subscriptions).  The anaconda.org repository and on-prem versions have capabilities far beyond a simple repository mirror.  For examples, it serves *dynamic* repodata.json and associated packages based on user and credentials.

These capabilities are built to work well with conda--rather than the other way around. And conda is the open-source, free, non-corporate, not-for-profit, not evil piece of software that I think your questions are primarily aimed at.

> What is the roadmap / vision with regards to the open-source ambitions of conda and the community-building behind conda-forge to fill in this specific niche?

Let's start by acknowledging that there are several years of history (and evolution) to conda already--and the associated communit(y/ies).  It all had to have a starting point though, a seed, and that starting point was and still is repo.continuum.io.  That's why repo.continuum.io is hard-coded in conda as the "default" repository.  While Continuum continues to expand and further overload the Anaconda brand, the most relevant piece to this discussion we now refer to as the Anaconda Distribution.  Right now, this is effectively the Anaconda Installer along with all of repo.continuum.io.  A very real part of Continuum's business model is selling an "enterprise" grade license to this software, which right now is marketed as [Anaconda Pro](https://www.continuum.io/anaconda-subscriptions).  It's exactly the same software; just with additional gaurantees like support and corporate indemnification.  It's also all COMPLETELY transparent and you can build it all yourself.  Not only are all of the recipes included in the conda packages themselves (in the `info` directory), they're also at https://github.com/ContinuumIO/anaconda-recipes.

In the future, there will likely also be evolution on this front. The 'default' conda repository, whether it's repo.continuum.io or repo.anaconda.org or whatever else, we'd like to make much more community-driven.  In effect, much more like conda-forge, bioconda, etc. In turn, we'll further beef-up the "enterprise-grade" repository with extra guarantees important to corporate customers. It will likely be a separate and paid-subscription-only repository, but it would be stictly *downstream* from the default community repository.  The Continuum package maintainers would still contribute upstream to the 'default' community repository.


> Are there any recommendation for people who want to have local repositories or mirrors to use conda on them?

[The specification for a valid conda repository](http://conda.pydata.org/docs/spec.html#repository-structure-and-index) is incredibly trivial.  You definitely *do not* need the software powering anaconda.org to host your own repository.  Any generic static host will do, even a NFS mount, an FTP server, or an s3 bucket in `s3://` mode or [`http://` mode](http://docs.aws.amazon.com/gettingstarted/latest/swh/website-hosting-intro.html).  In effect, take a directory of conda packages (i.e. of `.tar.bz2` tarballs) and run `conda index` on it.

Mirroring a repository is similarly trivial.  See for example [a script](https://gist.github.com/kalefranz/e56e8ffc53662a1724dd) I threw together well-before I started working for Continuum.

> Sorry if I am asking a stupid question

Not stupid questions at all!  Continuum's messaging hasn't always been clear in the past; I know because I've been right where you are.

Do those answers help? Are there things I've missed?

**Comment by teoliphant** [comment]
Thanks for the questions, Gael!  It's great to hear from you.   Kale's descriptions are completely on point.    We've strived to make conda open-source friendly and able to be used by an entire community and not *just* us.     We haven't always succeeded, but we appreciate hearing about how we are not doing a good job so we can make improvements where needed.

Our biggest limitation is time, and it has always made it difficult to respond in a timely way and to message well about what we are doing and how open source connects to our business model and necessary revenue streams that make what we do sustainable.   We have tried to be transparent about how we make money as well so that it is clear what is open-source and community-driven.   

A big reason we started Continuum was to promote the creation and maintenance of more open-source software.   One of the things that I'm very happy about is that we have been able to create and fund a growing Community Innovation group at Continuum whose purpose is to build communities around open-source software.   

This is the group that produces and supports bokeh, numba, blaze (including odo), datashape (including libndtypes), dask, datashader, textadapter (previously iopro), conda, holoviews, datashader, spyder, jupyterlab, phosphorjs. 

Thank you, Kale, for your answer.    Thanks for engaging Gael, and apologies for taking a bit of time to get back with you.

**Comment by msarahan** [comment]
I would only add that the ```conda index``` command that @kalefranz referenced is part of conda-build.  Conda-installing conda-build may be necessary for that to work.

A small detail is that I'm not sure that these custom-indexed URLs add the subfolders for particular platforms.  You may need to do more work to index each subfolder, and manage channels more individually (including the platform subfolder in your URL).

**Comment by GaelVaroquaux** [comment]
Hi everybody. Thank you for the answers. I haven't had time to read them properly, as I have been traveling the last week.

Just to stress: I don't believe in "evil". I believe in incentives and benefits. I have my own interests when I do open source software. I have a "revenue model", it's citations and software to build my "products" upon. I wasn't implying any evil in conda.

**Comment by kalefranz** [comment]
Seems like discussion has slowed here.  I'm going to close the issue.  Feel free to keep discussing though.
