### ISSUE TITLE
Problems with binary incompatibility when combining multiple channels

### ISSUE THREAD

**Issue by johanneskoester** [conda/conda#3721]
This issue recently arised in the bioconda channel (pull request bioconda/bioconda-recipes#2569). To streamline the discussion, I thought I'd move it to an appropriate place.
# Problem

When combining multiple channels that are not disjoint in terms of packages, it can happen that conda pulls, even pinned, dependencies from a different channel than the one used for building. This can lead to problems when binary incompatibilities occur that are not reflected in the package versions (e.g. different compiler flags).
# Example

The bioconda channel depends on the anaconda, r and conda-forge channels. Both conda-forge and r use only anaconda during building. Now, there is a libgd version in anaconda and one in conda-forge. During dependency resolution, it can happen that e.g. the one from conda-forge is pulled for a package from the r channel (which was however built against the anaconda version). Apparently, the two libgd versions are not binary compatible, leading to errors (see pull request bioconda/bioconda-recipes#2569).
# Possible solutions
## Channel dependencies

Make conda aware of channel dependencies. A package coming from a certain channel may only pull dependencies from the same channel or channels it was built against. The downside is that people cannot use channels to replace a certain package in a dependency tree.
## Pinning beyond plain versions

Find a way to pin to something like used compiler flags or an md5 hash of a binary. Downside: this would probably involve a lot of changes in the way conda discovers and manages package versions.
## Ensure binary compatibility case-by-case

Have an agreement between conda-forge, r and anaconda about using the same compiler flags for duplicate packages.

---

This is a pressing issue for us, and I believe this will sooner or later also occur to the users of other channels. Any help, pointers and opinions are much appreciated!

ping @croth1, @bgruening, @daler, @jakirkham, @mingwandroid, @msarahan, @csoja, @teoliphant and @pelson.

**Comment by johanneskoester** [comment]
My personal feeling is that channel dependencies would be the best solution. Given that this ensures consistency and solves a lot of problems, the price of being a little less flexible in terms of replacing package sources is acceptable I think. Further, it will be possible again to install packages ad-hoc from channels with complex dependencies (without specifying all dependent channels manually).

**Comment by kalefranz** [comment]
@msarahan is doing a lot of work here.  He's created https://github.com/conda/conda-build/issues/1142 for me to implement in 4.3 to help the effort along.

**Comment by johanneskoester** [comment]
Does this mean that conda/conda-build#1142 will support pinning beyond versions and basically solve our issue here? Or would it need additional work to solve the problem we see here?

**Comment by johanneskoester** [comment]
Dear all, we have a Bioconda hackathon in the next two days, and there are plenty of people involved who could maybe help with this issue. Hence, I'd like to ask whether you have some additional thoughts/plans regarding such issue.
Or maybe somebody has an answer to my questions above?

We would really like to help fixing this. Thank you!

**Comment by msarahan** [comment]
@johanneskoester, thanks for your potential offer of help!  Tell me more about "pinning beyond versions" - the point of https://github.com/conda/conda-build/issues/1142 is to try to figure out how to encode all of that information, and how to make each facet configurable.  Hashes are good fingerprints, but I'm not sure of their utility in actually selecting a package.  HashDist is an interesting model, but quite a bit less flexible than what we have now - you only get exact matches.

For the Bioconda hackathon, I'd be thrilled to have any of your time in moving https://github.com/conda/conda-build/issues/1142 forward.  Please take a look at that issue.  Does it scope the problem well enough right now?  If not, what's missing?  I'm wide open to implementations.  I think that everyone involved with the history of that issue (yourself included) has given us interesting potential APIs.  I am partial to the config files proposed by @ukoethe and @stuarteberg (as opposed to solely command line flags), but open to evolution from there.

There are a few facets that I have in mind, especially regarding that conda-build PR:
1) need to develop a schema for what information gets encoded, and how.  This is especially true for non-version information, such as compiler flags.  I'm open to proposals, and have no solid ideas at the moment.
2) need an expression somehow for selecting configurations at install time, as well as at build time.  My hope was that one set of config files would serve both purposes - in other words, the same config files could be used for either purpose.  This was what I asked @kalefranz to look into with #3679.  These are "Core Dependency Trees" - CDTs.  If hashes are useful for keying builds, then also need to figure out how hashes can be derived from a CDT without actually building a package - or otherwise, we'll need a more complicated composite key of the many facets.  At install time, I think the only valid assumption is that the user will have a CDT, and not hashes based on built packages for what they want.
3) need a way to capture things that can't necessarily be installed, such as particular symbol versions or restrictively-licensed software.  Our idea right now is to make conda packages that check versions, rather than actually installing software.  This way, the dependencies can be explicit, but the actual behavior might be different from how it is now.
4) need a collection of critical system information to gather, and then the scripts or whatever to gather it.  Things like glibc version, fortran SO version, fortran symbol version, etc.  SO versions are less important, because they're often obvious.  Symbol versions are a weaker area for us right now.

https://github.com/conda/conda-build/pull/966 may have something useful in it, but don't take it as gospel.  I'll be happy to very seriously consider anything that works and moves us forward.

I'll be available to discuss these things, so if a video call helps to move things forward, let me know.

**Comment by johanneskoester** [comment]
Thanks @msarahan! I have posted my thoughts in conda/conda-build #1142.
