### ISSUE TITLE
Problems with competing libraries from different channels

### ISSUE THREAD

**Issue by RubyDrus** [conda/conda#3773]
Hey all,

just found out about conda, bioconda etc a few days ago and I was very happy to discover such a neat piece of software. Thank you for that!

First an overview of my problem:
As I got a new laptop last week, I installed pretty much all software from scratch (vast majority of it with conda). However, I am having troubles to get the programs to work. As recommended, I installed the channels from bioconda: https://bioconda.github.io/ 

`conda config --add channels r`
`conda config --add channels conda-forge`
`conda config --add channels bioconda`

Amongst others, I installed R and samtools:
`conda install r r-essentials r-recommended`
`conda install samtools`

Both happen to compete over libraries from different channels and version. Now, I can start only one of them, sometimes none of them but never both. Which is annoying...

Background:
First I used samtools, didn't start, cryptic error message, fixed it with this line of code according to this issue:
`conda update -y -c r ncurses`

As far as I understand it, this basically downgrades the ncurses library from 5.9-9 and the channel **conda-forge** to 5.9-8 and the channel **r**. 

> Source: https://github.com/bioconda/bioconda-recipes/issues/1644

Now, R is not starting. Probably because I downgraded said library although the error message is a different one:
`$ R`
`dyld: Library not loaded: @rpath/libicuuc.54.dylib`
`  Referenced from: /Users/drews01/miniconda2/lib/R/lib/libR.dylib`
`  Reason: image not found`
`Trace/BPT trap: 5`

`conda info` and `conda list` in the attachment.

I do not understand enough of libraries to deal with this myself. I would be more than happy, if anyone could assist me!

Best wishes!

[conda_info.txt](https://github.com/conda/conda/files/562235/conda_info.txt)
[conda_list.txt](https://github.com/conda/conda/files/562236/conda_list.txt)

**Comment by kalefranz** [comment]
CC @msarahan

**Comment by msarahan** [comment]
One of the most important tricky parts of conda right now is "channel priority."  The way that conda works is that conda looks for packages in particular channels, and when found, those packages take priority over other channels, even if the other channels have newer packages.

Channels that you pass on the command line have the highest priority.  Otherwise, it's in descending order in condarc.

With a complicated enough system, it may not actually be possible to have a completely consistent package set.  In this case, I recommend creating conda environments for particular functionalities that can be kept separate (and consistent.)

@kalefranz can speak to future strategies for keeping these issues from arising.  One proposed solution is to be able to specify channels as part of package dependencies.  This will help, but may still lead to unsatisfiable dependencies.

**Comment by RubyDrus** [comment]
@msarahan Thank you for your answer!

I played around with environments but still some libraries seem wilfully obstructive. Changing environments for just one tool doesn't seem appealing to me. After all, I deleted samtools from conda and I am manually managing it now. The rest of conda works now. 

Cheers!
