### ISSUE TITLE
Should `conda list --export` preserve channels?

### ISSUE THREAD

**Issue by srossross** [conda/conda#383]
With binstar coming online channels and location of packages are becoming more important, a conda requirements.txt is not sufficient to reproduce an environment.

**Comment by dmopalmer** [comment]
I'd like to bump this issue.  It is annoying to have to manually remember which packages came from which channels in an environment.

**Comment by bkreider** [comment]
Is this still relevant now that we have things like `conda env export` and `conda list --explicit`?  Also the history file in $ROOT_PREFIX/conda-meta/history tracks every change made to environments.

**Comment by dmopalmer** [comment]
`conda list --explicit` fails to list the packages installed by `pip`.  (Should this be made a separate issue?  It presumably is supposed to because there is a `--no-pip` option) 

`conda env export` doesn't list the channels.

Therefore there is no programatic way to create a descriptive file that can replicate an environment.
