### ISSUE TITLE
SpecNotFound: Runtime error: Can't process without a name

### ISSUE THREAD

**Issue by jpicau** [conda/conda#3847]
jpicau@jserverpro:~> conda env create 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.3
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /Users/jpicau/miniconda2  (writable)
    default environment : /Users/jpicau/miniconda2
       envs directories : /Users/jpicau/miniconda2/envs
          package cache : /Users/jpicau/miniconda2/pkgs
           channel URLs : https://conda.anaconda.org/petsc/osx-64
                          https://conda.anaconda.org/petsc/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/jpicau/.condarc
           offline mode : False

`$ /Users/jpicau/miniconda2/bin/conda-env create`

    Traceback (most recent call last):
      File "/Users/jpicau/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/jpicau/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "/Users/jpicau/miniconda2/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    SpecNotFound: Runtime error: Can't process without a name
    Please install nbformat:
    	conda install nbformat
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

**Comment by soapy1** [comment]
It looks like you have two problems. 

First, you are missing the `nbformat` package. This can be fixed with a simple `conda install nbformat` 😸 

Next, it looks like you don't have an `environment.yml` in your current working directory. You can either [create one by hand] or [export a current environment]. Once you have that running `conda env create` should create the environment as specified in `environment.yml`

[create one by hand]: http://conda.pydata.org/docs/using/envs.html#create-environment-file-by-hand
[export a current environment]:  http://conda.pydata.org/docs/using/envs.html#export-the-environment-file

**Comment by m090009** [comment]
Wow I'm way late to the party ;however, I had an issue where I had an `environment.yml` file in the the directory, but when I ran `conda env create -f environment.yml` I got this
`Using Anaconda API: https://api.anaconda.org

SpecNotFound: Can't process without a name`

So I preceded with your advice and ran `conda env create` since I had the `environment.yml` file in my working directory. 
Do you know why `conda env create -f environment.yml` didn't work?

**Comment by mohamedabdallah1996** [comment]
@m090009 try with the absolute (complete) path of your `environment.yml` file. it worked for me

**Comment by jennxf** [comment]
I changed the name of the yml file from some_name.yml to environment.yml and it worked.

**Comment by hloniphanidube** [comment]
Thank you @jennxf. Worked for me as well.

**Comment by abhiksark** [comment]
I tried every solution mentioned over here did not work for me.
