### ISSUE TITLE
conda install dependencies

### ISSUE THREAD

**Issue by bkreider** [conda/conda#387]
Conda doesn't always install dependencies first.  It installs all packages in alphabetical order.  Rather than create a new dependency section (install dependencies), conda should install dependencies first.  

The current implementation requires naming a package as aaa_<package name> to force it to install first.

**Comment by ijstokes** [comment]
`post-link.sh` scripts may assume that the dependencies have been installed when they execute, that is why.

**Comment by bkreider** [comment]
Michael was talking a look at this when he was working on the conda scheduler and thought it was going to be trivial to install dependencies in dependency order.  I'm not sure if that is the default now or not.  

@mcg1969 ^^

**Comment by mcg1969** [comment]
No, ultimately I didn't do anything to implement this. In theory we could walk the dependency tree and assign an install order.

**Comment by groutr** [comment]
https://github.com/conda/conda/pull/1874

**Comment by mmarchetti** [comment]
If you do this, please make sure that uninstalling happens in the opposite order. We've run into issues with pre-unlink scripts too.

**Comment by ijstokes** [comment]
It seems to me that this PR #1009 by @srossross from late 2014 was meant to address this issue, but I agree with @mmarchetti that I feel like we've still seen this as a problem.  I believe that CAS-Installer installs packages alphabetically, and that is definitely problematic when `bar` is installed before `foo`, and has expectations that `foo` has already been installed with its `pre-link.sh` script having already been run.

**Comment by mingwandroid** [comment]
`conda` does install in the correct dependency order, *provided* there are no cycles in the final set of packages that would finally be installed into your environment.

When that happens, `conda` they get installed in alphabetical order. IMHO, the dependency resolution should be re-run with the restricted set of packages that are being newly installed which is generally much smaller and usually contains no cycles.

Also, in the past, when this was triggered from `conda-build`, `conda`'s warning about this used to get swallowed up. I think this has since been fixed in `conda-build` https://github.com/conda/conda/pull/4109

**Comment by kalefranz** [comment]
Conda now installs in dependency order, and uninstalls in reverse dependency order.  The latter as of conda 4.4.
