### ISSUE TITLE
Private application environments

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#3912]
In the future, we would like to offer a miniconda installer that installs conda into a *private env*, while leaving the *default user env* empty except for links of conda's executables into the default user env. It would be naive and a disservice to users to treat conda as a special case. 

Private named environments are generally useful for any "top-level application" that the prototypical user is likely to install only once on the system.  Most users, for example, wouldn't (intentionally) install multiple instances of Firefox on their systems.  Advantageously, an application may leverage explicitly pinned dependencies for its own operational safety without worrying about creating unsatisfiability in the user's broader default environment.  Examples could include Anaconda Navigator and Spyder.

The convention for a private application environment will be the application's name, prefixed and suffixed by an underscore. This distinguishes a private environment from the established use case of an environment name prefixed by underscore (prefixed only, not suffixed); the prefix-only convention allows conda to be installed in the environment without complaint.

An application may request that it be installed in a private named environment by indicating so in [non-index package metadata](https://github.com/conda/conda-build/pull/1539).  The request will be respected for conda create, install, update, and remove commands when

* the *user default env* is the active environment, and
* the user does not specify the `--name` or `--prefix` command-line flags.

Private environment preference will only be respected for packages explicitly requested by the user.  Packages installed as dependencies of a user-requested package will not be installed in private environments, but rather the environment into which the user-requested package is installed.

When a package specifies a preferred private environment, it need not be a private environment for itself.  It can instead be the private environment of another package.  For example, conda-build can indicate that its preferred private environment is the conda private environment.

When a private environment request is respected, entry points are created in the *user default environment*, linking executable-marked paths in the private prefix's `bin`/`Scripts` directory. The entry point for an `application` executable will be similar to 

```
#!/bin/bash
CONDA_ROOT="$(dirname $0).."
source "$CONDA_ROOT/bin/activate" "$CONDA_ROOT/envs/_myapp_"
exec "$CONDA_ROOT/envs/_myapp_/bin/myapp" "$@"
```

A package may limit the executables being linked by providing an explicit list of desired paths to symlink in the package's non-index metadata.

To track user-requested packages that have been installed in private environments, a file
`conda-meta/private_envs.json` is used.  It is present only in the *user default env* `conda-meta` directory.  This tracking is necessary to unlink packages (either during update or remove) that have been installed in private environments.

The issue https://github.com/conda/conda/issues/3074 discusses the more-limited conda-specific implementation.

**Comment by mingwandroid** [comment]
This breaks `application`'s idea of the current working directory. Some examples of problems this will cause problems for the user such as:

```
cd %MyDocuments%
gedit MyTODOList.txt

Error: cannot find MyTODOList.txt
```

It might be possible with stub executables or using BASH_SOURCE or something like that to avoid using `cd`, but BASH_SOURCE (or an equivalent) won't work on poor shells and stub executables are not going to be fully transparent to the caller or to the callee (going through a shell is even worse in that regard).

**Comment by kalefranz** [comment]
@mingwandroid Your only issue here is the `cd` in that entry point pseudo code that breaks current working directory for an app, is that correct?

**Comment by ilanschnell** [comment]
I don't think we should generalize the idea of "private" conda environments beyond `_conda` at this point.  This would be a much wider discussion, which would only distract from the immediate problem we are trying to solve right now, and as a result delay the release of conda 4.3 even further.

**Comment by soapy1** [comment]
To add to this spec after discussions with @kalefranz, 
- installing in a private env should only work when the root env is active, otherwise, install in the current (or specified env) 
- there should be a `conda-meta/private_envs.json` in the root env (and only in the root) that keeps track of available private envs. It should have the form
```
<package_name>: <full path to the installed private env>
```

**Comment by kalefranz** [comment]
@mingwandroid 

New "entry point" prototype to address your concern.

```
#!/bin/bash
CONDA_ROOT="$(dirname $0).."
source "$CONDA_ROOT/bin/activate $CONDA_ROOT/envs/_myapp_"
exec "$CONDA_ROOT/envs/_myapp_/bin/myapp" "$@"
```

This actually code will have a python shebang that points to the python in conda's private env.  That's the guaranteed dependency that we have.

**Comment by ijstokes** [comment]
@bkreider and I have discussed this on many occasions and I'm a big +1 on this.  I was also going to propose that this be done exactly for the two examples @kalefranz mentions: Navigator and Spyder.  The next obvious one to include is Jupyter: we have capabilities within Jupyter to swtich between different Conda environments so it is probably a good idea that for the average user we provide one stable, sand-boxed Jupyter instance on disk.  Expert users would need an avenue to try out different Jupyter versions, but that would be the exception, not the norm.

**Comment by mingwandroid** [comment]
How does such a sandboxed Spyder interact with the user's *real* conda env? If this is via having both on the PATH then that will be problematic on Windows due to the (effective) env var length limit of 8191 characters.

If it is not then how much re-engineering of Spyder (and whatever other applications we sandbox) will be required to fit this scheme?

I'm +1 for doing it for conda but would probably rather see py2exe or freezing explored as options for that first.

**Comment by bkreider** [comment]
+1 I know it is more complicated, but this gets it so close to Nix.  If you are allowed to have _conda_4.3_ and _conda_4.4_ type environments, you can have instant rollbacks if conda fails.  Right now it is very easy to make conda break itself (unrecoverable by normal means) if it unlinks python and then fails unlinking another file (bad perms), before getting the the link step. This might also  make it easier to update on windows, since you don't have to unlink the running conda process.

**Comment by mingwandroid** [comment]
Windows in particular is not very nix-friendly:

https://ternaris.com/lab/nix-on-windows.html

I agree that isolation for conda and its dependencies is a good thing (though that alone doesn't address the issues of conda needing to update the Python binaries that it runs on), but attempting to generalise this to how nix operates is a big ask since we need to support 3 OSes.

**Comment by kalefranz** [comment]
@bkreider I think you'll appreciate the 4.3 changelog
https://github.com/conda/conda/blob/4.3.x/CHANGELOG.md

**Comment by kalefranz** [comment]
@mingwandroid We don't add to and stack PATH here. The only assumption is that the root env path *stays* on path.

**Comment by mingwandroid** [comment]
Right, but if we are talking about other applications in private envs, Spyder and RStudio and ... then we add those too or not?

**Comment by kalefranz** [comment]
No. Spyder and RStudio each get their own private env.  With the root env always staying on path when you "install Anaconda," these applications installed in private envs can elect to have certain executable entry points placed into the root env that invoke the private env application.

The code right now is

```
#!/path/to/root_env/envs/_conda_/bin/python
# -*- coding: utf-8 -*-
if __name__ == '__main__':
    import os
    import sys
    # TODO: add the python-only equivalent of the activate command for this process
    os.execv(%(source_full_path)s, sys.argv)
```

already in 4.3 [here](https://github.com/conda/conda/blob/4.3.1/conda/gateways/disk/create.py#L43-L49), although nobody is exercising it yet.

The shebang `#!/path/to/root_env/envs/_conda_/bin/python` is used because that's the guaranteed runtime we'll always have in conda's ecosystem, and it works just as well as `#!/bin/bash` to `execv`.

**Comment by mingwandroid** [comment]
I don't really see how this is achieving `Private application environments`, this is just a stub executable / script isn't it?

What about icons (embedded into executables on Windows vs in an app bundle on macOS vs .desktop files on Linux) and Info.plist? Do you intend those to work with this? The stub executable cannot be made to be transparent on Windows due to how handles are managed by CreateProcess => this is due to the lack of fork, which you can use to achieve good transparency on the other OSes.

You should take a look at what I've done for RStudio for macOS (https://github.com/mingwandroid/conda-recipes/blob/master/rstudio/build.sh#L73-L80 and https://github.com/mingwandroid/conda-recipes/blob/master/rstudio/osx-post.sh) which is to have an .app bundle with an icon in $CONDA_PREFIX that has an executable which is simply a symlink to `$CONDA_PREFIX/bin/rstudio`. That functionality from the RStudio package should be moved into `menuinst` since that already does something similar for Windows.

IMHO this stuff is too OS dependent for a one-size-fits-all solution like I think you are proposing here. You'd get a lowest common denominator result from that.

**Comment by kalefranz** [comment]
Yeah my perspective is really limited to posix command line use cases. You have a much broader perspective Ray. And that's awesome. Let's figure out solutions :) I don't think these are intractable hurdles.

**Comment by kalefranz** [comment]
Actually this proposal is very similar to osx app bundles. Maybe we should discuss what it would look like to build these OS-specific GUI things in. Never hurts to brainstorm and explore.

**Comment by kalefranz** [comment]
It seems to me that these are all the same "bits" that make up an app. The bits being all of of conda packages with conda resolving dependencies and making them available to the top-level "app" package. The only difference is how those packaged bits are arranged depending on OS context.

**Comment by JeremyEnns** [comment]
+1

I think all of our enterprise products should be using a unique environment so they do not step on each others toes.  Right now we are trying to run our products out of the root environment and if that gets changed by the user or another one of our enterprise products, it could cause the tools to stop functioning.  Anaconda-Navigator, Spyder, Jupyter, AEN, Repo, etc.  The products would be way more stable if the environment that they run out of was separate from the developers workspace (standard conda environments).  They should be able to make any changes they want to their conda environment and not break the application from being usable.

**Comment by arita37** [comment]
Main  root of conda issues is:
   Conda install is not stable : files can deleted, dependencies removed,....

1st step is to make conda package secure from 3rd party interaction, pip install issues, user mis-input.

Fallback recovery from previous version.

There are many examples where conda
install is destroyed.

**Comment by kalefranz** [comment]
This feature was originally intended for conda 4.4, but ultimately wasn't ready for prime time by the time 4.4 was released.  While the new solver work in 4.4 made progress toward this feature, it remains in our backlog.

Conda-build currently has a test that is designed in support of this feature.

https://github.com/conda/conda-build/blob/193dd65db1854adc2b175f11a9594edf1d26cd27/tests/test_api_build.py#L665-L667

The test is being disabled until future notice.  It should be re-enabled before this issue is ultimately closed.

**Comment by kalefranz** [comment]
It was originally slated for conda 4.4 but didn’t make it. Right now there’s no committed ship version.

**Comment by ccordoba12** [comment]
@kalefranz, I'd like to submit a Numfocus grant proposal to implement this feature. So I'd like to know if you think it's still feasible, how difficult this could be for a newcomer to the Conda code (not me, but a capable programmer) and how much time you think it would take to implement it.

I'd really like to have a private env to keep most of Spyder deps at stable versions. This is to avoid new versions of Jedi, IPython, ipykernel, Qt, PyQt, etc, etc, or people installing packages from conda-forge or pip, to break us in one way or another.

Of course, we try to catch errors and incompatibilities with new versions through our tests and resolve them as soon as possible, or direct them upstream if necessary. But our users can be slow at updating Spyder or other maintainers can be busy and don't have time to help us with our bugs, so we end up addressing a lot of issues about past and present problems of this kind per day (about 10 issues on Github and 4 questions on StackOverflow).

That's why I consider this feature of critical importance to the maintainability of the project. Without it, our ability to innovate and add the features people expect from us is really impaired by the amount of bug reports we're getting from the community. And one way to avoid this (IMHO) is to have a private env that isolates Spyder and its dependencies from any other env in Anaconda.

By the way, the relationship between this env and the base env would be very simple for us. Since 3 months ago, we have a new, small package called `spyder-kernels` that can be installed in any env and contains the code necessary to start an IPython kernel with all the additions we need to connect it to the rest of our components. So all that we'd require is for the base env to have this package and we'd change the default Python interpreter to start our kernels to the base one (instead of the one of the private env).

**Note**: Numfocus grant proposals need to submitted next weekend, so we need a response from you as soon as possible. Sorry for the rush, and thanks for understanding.

**Comment by ccordoba12** [comment]
@kalefranz, I'd like to submit a Numfocus grant proposal to implement this feature. So I'd like to know if you think it's still feasible, how difficult this could be for a newcomer to the Conda code (not me, but a capable programmer) and how much time you think it would take to implement it.

I'd really like to have a private env to keep most of Spyder deps at stable versions. This is to avoid new versions of Jedi, IPython, ipykernel, Qt, PyQt, etc, etc, or people installing packages from conda-forge or pip, to break us in one way or another.

Of course, we try to catch errors and incompatibilities with new versions through our tests and resolve them as soon as possible, or direct them upstream if necessary. But our users can be slow at updating Spyder or other maintainers can be busy and don't have time to help us with our bugs, so we end up addressing a lot of issues about past and present problems of this kind per day (about 10 issues on Github and 4 questions on StackOverflow).

That's why I consider this feature of critical importance to the maintainability of the project. Without it, our ability to innovate and add the features people expect from us is really impaired by the amount of bug reports we're getting from the community. And one way to avoid this (IMHO) is to have a private env that isolates Spyder and its dependencies from any other env in Anaconda.

By the way, the relationship between this env and the base env would be very simple for us. Since 3 months ago, we have a new, small package called `spyder-kernels` that can be installed in any env and contains the code necessary to start an IPython kernel with all the additions we need to connect it to the rest of our components. So all that we'd require is for the base env to have this package and we'd change the default Python interpreter to start our kernels to the base one (instead of the one of the private env).

**Note**: Numfocus grant proposals need to submitted next weekend, so we need a response from you as soon as possible. Sorry for the rush, and thanks for understanding.
