### ISSUE TITLE
Custom deactivate scripts in etc/conda/deactivate.d/ cannot modify the PATH environment variable

### ISSUE THREAD

**Issue by dmaxime** [conda/conda#3915]
On Windows with conda 4.2.9, I am attempting to set environment-specific environment variables by following [this documentation](http://conda.pydata.org/docs/using/envs.html#windows).

I've set up the following custom activate/deactivate scripts in the environment folder.
In `etc/conda/activate.d/env_vars.bat`:
```
set R_HOME=C:\Local\Programs\R-3.3.2
set R_USER=C:\Users\ENCPB\Documents\
set R_LIBS_USER=C:\Local\Programs\R_libs
set PATH=C:\Local\Programs\R-3.3.2\bin:%PATH%
```

In `etc/conda/deactivate.d/env_vars.bat`:
```
set R_HOME=
set R_USER=
set R_LIBS_USER=
set PATH=%PATH:C:\Local\Programs\R-3.3.2\bin:=%
```

`R_HOME`, `R_USER`, `R_LIBS_USER` are properly set and unset, but not `PATH`. It is properly set but the deactivate script leaves `C:\Local\Programs\R-3.3.2\bin` in the PATH.

In the global Anaconda `Scripts\deactivate.bat` script, the `PATH` environment variable is actually set **after** the custom `etc/conda/deactivate.d/` scripts are run. Any change custom scripts do to `PATH` is ignored.

**Comment by njalerikson** [comment]
Well first of all in the Windows and CMD.EXE world the `PATH` is `;` delimited not `:` delimited.

So in your `etc\conda\activate.d\env_var.bat`:

```
set PATH=C:\Local\Programs\R-3.3.2\bin;%PATH%
```

And in your `etc\conda\deactivate.d\env_var.bat`:

```
set PATH=%PATH:C:\Local\Programs\R-3.3.2\bin;=%
```

**Comment by dmaxime** [comment]
True, sorry for the confusion.. 
I have corrected both `env_var.bat` scripts with your suggestions and the behavior remains identical: 
- `R_HOME`, `R_USER`, `R_LIBS_USER` are properly set and unset
- `C:\Local\Programs\R-3.3.2\bin` is not removed from `PATH` 

I have been able to correct that behavior by making the global Anaconda `Scripts\deactivate.bat` script execute the environment-specific `etc/conda/deactivate.d/` scripts at the very beginning (before the `@SETLOCAL` command. I am not sure, though, if this could trigger any undesirered side-effect. 

Here is my modified version of `Scripts\deactivate.bat` :
```
@REM @ symbols in this file indicate that output should not be printed.
@REM   Setting it this way allows us to not touch the user's echo setting.
@REM   For debugging, remove the @ on the section you need to study.

@REM First, run any deactivate scripts, it used to be at the end of the script.
@IF EXIST "%CONDA_PREFIX%\etc\conda\deactivate.d" (
    @PUSHD "%CONDA_PREFIX%\etc\conda\deactivate.d"
    @FOR %%g IN (*.bat) DO @CALL "%%g"
    @POPD
)

@SETLOCAL enabledelayedexpansion

@SET "CONDA_EXE=%~dp0\..\Scripts\conda.exe"

:: this finds either --help or -h and shows the help text
@CALL ECHO "%~1"| @%SystemRoot%\System32\find.exe /I "-h" 1>NUL
@IF NOT ERRORLEVEL 1 (
    @call "%~dp0\..\Scripts\conda.exe" ..deactivate "cmd.exe" -h
) else (
    :: reset errorlevel to 0
    cmd /c "exit /b 0"
)

@REM doesn't matter what the arg is, just that there is one.  Ideally, only the activate.bat script is ever
@REM     passing this.
@set "HOLD=%~1"

@REM Deactivate a previous activation if it is live
@IF "%CONDA_PREFIX%"=="" @GOTO NOPATH
   @REM get the activation path that would have been provided for this prefix
   @FOR /F "delims=" %%i IN ('@call "%CONDA_EXE%" ..activate "cmd.exe" "%CONDA_PREFIX%"') DO @SET "NEW_PATH=%%i"
   @REM in activate.bat, we replace a placeholder so that conda keeps its place in the PATH order
   @REM The activate.bat script passes an argument here to activate that behavior - otherwise, PATH
   @REM    is simply removed.
   @REM In both cases, we have to used delayed expansion to have the value of NEW_PATH in the replacement.
   @IF "%HOLD%" == "" (
       @CALL SET "PATH=%%PATH:!NEW_PATH!;=%%"
   ) ELSE (
       @CALL SET "PATH=%%PATH:!NEW_PATH!=CONDA_PATH_PLACEHOLDER%%"
   )
   :NOPATH

@IF "%CONDA_PS1_BACKUP%"=="" @GOTO NOPROMPT
   @SET "PROMPT=%CONDA_PS1_BACKUP%"
   @SET CONDA_PS1_BACKUP=
   :NOPROMPT

@ENDLOCAL & (
            @SET "CONDA_DEFAULT_ENV="
            @SET "CONDA_PREFIX="
            @SET "PATH=%PATH%"
            @SET "PROMPT=%PROMPT%"
           )

```

**Comment by njalerikson** [comment]
Hm...do both of your env_var.bat scripts end with a blank line? I believe DOS requires a newline character before it runs the command on a line and hence a DOS file must have at least one line after the last line of code.

Otherwise if that doesn't fix it can you manually run the two path modifying lines of code and do they modify the path as you would expect it to do? I have tested the following code on my Win 8.1 install and get the expected results.

```
set "PATH=C:\Local\Programs\R-3.3.2\bin;%PATH%"
echo %PATH%
set "PATH=%PATH:C:\Local\Programs\R-3.3.2\bin;=%"
echo %PATH%
```

Either way you should not need to change the activate/deactivate codes.

**Comment by dmaxime** [comment]
Yes, the two PATH modifying lines work fine in my console, and I have added newlines to the env_vars.bat file with no success (I also tried to move the set PATH line higher in the file)

I have added a few `echo` lines to troubleshoot, and it seems indeed that the `PATH` modified by the environment-specific bat file is ignored. 

In `deactivate.d\env_vars.bat`:
```
set PATH=foo
echo "PATH in environment script: %PATH%"
```

In `Scripts\deactivate.bat`, I added the following `echo`:
```
@REM run any deactivate scripts
@IF EXIST "%CONDA_PREFIX%\etc\conda\deactivate.d" (
    @PUSHD "%CONDA_PREFIX%\etc\conda\deactivate.d"
    @FOR %%g IN (*.bat) DO @CALL "%%g"
    @echo "PATH in deactivate.bat: %PATH%"
    @POPD
)
```

This gave:
```
(myenv) C:\Users\ENCPB>deactivate
"PATH in environment script: foo"
"PATH in deactivate.bat: C:\Local\Programs\R-3.3.2\bin;etc..."
```

which suggests the `deactivate.bat` script does not see the PATH change from `deactivate.d\env_vars.bat`. 

My system is Windows 7 SP1.

**Comment by njalerikson** [comment]
Ok yes I have completely reproduced the issue you are experiencing.

I have also reproduced a more or less similar issue with the recently refactored activate/deactivate codes. I think I understand the issue. You are correct in trying to move the code around in the deactivate.bat file.

I have just now submitted a PR to address this issue, #3987.

**Comment by kalefranz** [comment]
Resolved as part of #5044.

**Comment by beenje** [comment]
Hi,
I see this issue in conda 4.4.11 on Linux.
1. I modify the PATH in `etc/conda/activate.d/env_vars.sh` with something like:
`export PATH="/mypath:$PATH"`
2. I remove /mypath in `etc/conda/deactivate.d/env_vars.sh`:
`export PATH=$(echo $PATH | sed "s?/mypath:??")`

Running `conda activate myenv` properly adds /mypath to PATH, but `conda deactivate` doesn't remove /mypath from PATH.
Something must be modifying the PATH variable after the deactivate script is run (if I source it manually, it works fine). I think it would make sense if the custom deactivate scripts were the last thing to run.

Should I create a new issue? Or is this a known issue?

**Comment by b1es** [comment]
I also have problem with that. For one of my envs i try to change a little the path (cuda-9.1 --> cuda-8.0) and after deactivating the path is still "cuda-8.0"
 
`echo $PATH`
`/usr/local/cuda-9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/anaconda/anaconda3/bin:/snap/bin`

1. activate (etc/conda/activate.d/env_vars.sh):
`#!/bin/bash`
`backup_path=$PATH`
`export backup_path`
`ss="cuda-9.1"`
`ts="cuda-8.0"`
`PATH="${backup_path/$ss/$ts}"`
`export PATH`
After activating:
`echo $PATH`
`/home/lturchan/.conda/envs/cardio/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/anaconda/anaconda3/bin:/snap/bin`
2. deactivate (etc/conda/deactivate.d/env_vars.sh)
`#!/bin/bash`
`PATH=$backup_path`
`export PATH`
`unset backup_path`
After deactivate:
`echo $PATH`
`/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/anaconda/anaconda3/bin:/snap/bin`

**Comment by kalefranz** [comment]
Except I'd like to avoid two python subprocess calls here.  Still thinking about a solution... And the solution could probably be impacted by the timing of https://github.com/conda/conda/issues/6820

**Comment by kalefranz** [comment]
For reference, we've already flipped the order once in 4.4.x with https://github.com/conda/conda/pull/6602

**Comment by njalerikson** [comment]
Fair. Well from the quick tests I did the hack seems to work fine and doesn't appear to introduce any real slowdown. So it's an option to juggle alongside the other ideas you have.

**Comment by mbargull** [comment]
> For reference, we've already flipped the order once in 4.4.x with #6602

Yes, and, of course, we shouldn't flip that back.
> Except I'd like to avoid two python subprocess calls here.

As I see it, #6820 is not something we can do quickly due to compatibility reasons, and hence there are only two options for now:
1. Use @njalerikson's approach and run Python code twice.
2. Get and source the list of deactivate scripts in shell code and after that run the Python part.

But since the latter requires heterogeneous shell code, it would be a step backward from the previous code unification -- let's avoid that!
To counteract the added running time of the doubled Python invocation, we can
1. Speed up `conda`'s initialization generally.
2. Make that proposed `conda shell.posix deactivatepost` lightweight.

As for the first point, I did some profiling and we can reduce that time by approx. 33 % by avoiding some costly imports and unnecessary precompilations. Those only require some minimal changes -- I'll submit a PR for that.
If it's really necessary to look into the second point, we could make that a `python -m conda.activate deactivate_post args` or `python -m conda.deactivate_post args`. That way we can avoid the general initialization and have in `args` the needed information encoded that we extracted in the first, costlier `conda shell.xxx deactivate` call. Hence the `deactivate_post` step could be very simple/dumb as it only processes already prepared information.

**Comment by njalerikson** [comment]
How often are these `{de,}activate.d` scripts used in practice? I feel like it's a unique corner case of environments. I've personally never created/used these scripts outside of testing this functionality and like I mentioned thes two python calls would only apply to instances when there are `{de,}activate.d` scripts, otherwise there would only be one call. So I feel like this is a unfortunate slowdown but is a reasonable short term sacrifice until #6820 or other ideas pan out. I do consider this to be a problematic bug as it fundamentally breaks how the `{de,}activate.d` scripts work.

**Comment by mbargull** [comment]
> How often are these `{de,}activate.d` scripts used in practice?

I hope not very often, but can't tell.
>  like I mentioned thes two python calls would only apply to instances when there are `{de,}activate.d` scripts

Even only for `deactivate.d` scripts, as `activate.d` scripts are always executed last (granted, I assume they usually come in pairs.).

> So I feel like this is a unfortunate slowdown but is a reasonable short term sacrifice until #6820 or other ideas pan out. I do consider this to be a problematic bug as it fundamentally breaks how the `{de,}activate.d` scripts work.

I fully agree to that.

**Comment by mbargull** [comment]
If you have a PR for that, happy to review :wink:.

**Comment by vegerot** [comment]
Am noticing the same problem in macOS High Sierra

**Comment by albertmichaelj** [comment]
I just wanted to reiterate that this is showing up for me on Mac OS as well. It is getting in the way of our use case for conda, and I would very much appreciate a workaround. Thanks!
