### ISSUE TITLE
Missing --no-site-packages option

### ISSUE THREAD

**Issue by rgommers** [conda/conda#394]
Conda doesn't seem to have the feature provided in virtualenv by `--no-site-packages`. I'd actually expected this to be the default behavior for conda environments. Is this on purpose?

**Comment by sscherfke** [comment]
I agree with @andreas-h. Users expect conda envs to be isolated from everything so `PYTHONNOUSERSITE=1` should be the default.

**Comment by westurner** [comment]
- I noticed this issue:

```
conda env export | tee environment.yml
# why are packages from ~/.local/lib/python2.7/site-packages included?


which python
python -m path
PYTHONNOUSERSITE=1 python -m path
```

- Should ``conda install pip; pip install --user`` install packages outside of the conda env?
  - I think the answer is no (because as a user, I assume conda environments to be self-contained and thereby reproducible)
- Where should ``conda install pip; pip install --user`` install packages?
  - ``CONDA_ROOT``?
- Should conda python, by default, read packages from ``~/.local/lib/python2.7``?
  - I think the answer here is also no (for the same reason).

> python agnostic

- If reproducibility is the ultimate objective, IDK how this is relevant?
- IIUC, we are to assume that conda python is wholly independent of what else is installed on the system?

Workarounds:

- always manually set ``PYTHONUSERSITE=1``
  - impractical when directly calling things in ``${CONDA_ENV}/bin``
- virtualenvwrapper: ``echo 'export PYTHONUSERSITE=1' >> "${VIRTUAL_ENV}/bin/postactivate"``

Possible solutions:

- Patch the cpython user-site directory to a subpath of ``CONDA_ROOT``:
  - https://www.python.org/dev/peps/pep-0370/
  - https://github.com/ContinuumIO/anaconda-recipes/blob/master/python-2.7/site.patch
    - ``sitecustomize.py``?

**Comment by rgommers** [comment]
Hmm, still not fixed. I'd forgotten about this.

> Patch the cpython user-site directory to a subpath of ``CONDA_ROOT``

Why ``CONDA_ROOT``, that would still be visible from multiple conda envs for the same Python version right?

Making ``PYTHONNOUSERSITE=1`` the default sounds better to me.

**Comment by westurner** [comment]
> Why CONDA_ROOT, that would still be visible from multiple conda envs for the same Python version right?

It would (which is the purpose of the user-site directory).

> Making PYTHONNOUSERSITE=1 the default sounds better to me.

That would work too;
though then there'd still be overlap with ~/.local
(which isn't really a problem now that __pycache__ directories are unique per interpreter major.minor (instead of just <filename>.pyc)).

Two issues with the status quo:
- If there are things compiled in ~/.local, they may or may not conflict with what is supposed to be a contained environment (and that's surprising)
  - https://docs.python.org/3/c-api/stable.html
- People may believe they're working in a contained, reproducible environment when it's not (because ~/.local is first in sys.path)
