### ISSUE TITLE
Consider conversion to UNC paths on Windows

### ISSUE THREAD

**Issue by treetoc** [conda/conda#3944]
conda has a limit on path length.
It seems this is linked to the windows limit of 260 char. See "Maximum Path Length Limitation" on 
[MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)
conda should use UNC paths to avoid that issue.

This is becoming a problem as Anaconda and Miniconda install themselves in C:\User\UserName\AppData\local\Continuum\Anaconda2 (previously was in C:\Anaconda2) so the path are now longer by default causing some packages to fail to install.

How to reproduce:
> conda build --no-anaconda-upload conda-bld ./conda_test_pack

[conda_test_pack.zip](https://github.com/conda/conda/files/611046/conda_test_pack.zip)

**Comment by mingwandroid** [comment]
Use --croot <PATH> --no-build-id.

I attempted to use UNC paths in a party of conda and the results were disastrous. You couldn't replace a hardlinked file referenced via a UNC path while using a normal path you could.

So while I agree in principle that it would be better, we'd need to figure a way around this issue.

For that reason I'm not going to close this, I'll leave that up to @kalefranz.

**Comment by kalefranz** [comment]
I definitely trust @mingwandroid on avoiding UNC paths.  We went down the road of a full implementation a few months ago, and then we had to back it out.  At this point UNC paths seem to be out, unless I can listen to a technical conversation with @mingwandroid and someone with ideas that can address all of the issues we've just experienced.  Given @mingwandroid expertise on Windows, that seems unlikely (I'm open to being proven wrong).

Using conda-build on windows, I can see that it's possibly you'll often--or always?--need to use `--croot` and/or `--no-build-id`.  It's possible this needs to be made clearer in the documentation?  Or maybe we can enhance conda-build somehow to take this into account on Windows? Tagging @msarahan if he has any additional input.

`C:\User\UserName\AppData\local\Continuum\Anaconda2\` is +/-52 characters, leaving +/-208 user-usable characters. (The +/- part is 'actual username length' minus 9.)  The `C:\User\UserName\` portion seems like a reasonable requirement for single-user installs.  `AppData\local\Continuum\Anaconda2` is I'm sure Windows convention, and widely considered the "correct place" to install to.  [`appdirs`](https://github.com/ActiveState/appdirs) is my typical reference here, and it actually looks like we're not following the standard.  Looking now, for Windows 7, I see

```
>>> appname = "SuperApp"
>>> appauthor = "Acme"
>>> user_data_dir(appname, appauthor)
'C:\\Users\\trentm\\AppData\\Local\\Acme\\SuperApp'
```

Since local windows paths are case-insensitive, I guess this is consistent.

However... I'm not unsympathetic to the issue you raise @treetoc.  As a calibration point, I just looked at the longest file path for the django package, which can nest files fairly deep.

```
lib/python3.4/site-packages/django/contrib/auth/migrations/__pycache__/0007_alter_validators_add_error_messages.cpython-34.pyc
```

It's 126 characters.  Granted this is on unix, but at least it's a ballpark number.  In this case that leaves 134 characters left over for the `CONDA_PREFIX` it's being installed into.  The conventional location for named environments on Windows would be `C:\User\UserName\AppData\local\Continuum\Anaconda2\envs\`, 57 characters, so that leaves 77 characters remaining for the env name in this case.  That length seems reasonable to me.

If there are other specific examples you have, let's discuss them.  Given java's language conventions, I can envision a possible problem there.  We haven't really thought through what conda packages for java means, and the implications.  I haven't anyway.  Especially what type of prefix replacement is required to make the package portable, or if prefix replacement is even relevant.
