### ISSUE TITLE
Initial Install from Pip Doesn't Work

### ISSUE THREAD

**Issue by Miserlou** [conda/conda#3961]
Just tried an initial install of `conda` from `pip`, and it doesn't work, looks like it could be a dependency/packaging error.

```
$ pip install conda
Collecting conda
  Downloading conda-4.2.7.tar.gz (235kB)
    100% |████████████████████████████████| 235kB 2.5MB/s 
Building wheels for collected packages: conda
  Running setup.py bdist_wheel for conda ... done
  Stored in directory: /Users/rjones/Library/Caches/pip/wheels/aa/94/d8/a845fe13112e0e3bdc3f907702a06c0b3ba66d90903060e467
Successfully built conda
Installing collected packages: conda
Successfully installed conda-4.2.7
$ conda list
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 7, in <module>
    from conda.cli.main import main
  File "/usr/local/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/usr/local/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/usr/local/lib/python2.7/site-packages/conda/base/context.py", line 18, in <module>
    from ..common.configuration import (Configuration, MapParameter, PrimitiveParameter,
  File "/usr/local/lib/python2.7/site-packages/conda/common/configuration.py", line 40, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named ruamel.yaml.comments
```

😿

**Comment by kalefranz** [comment]
We haven't really maintained conda installs from pip.  I'm going to fix this (sort of) in the next release.  But when installing from pip, we're not going to be making the entry points and related support executables.  That is, pip installs will only support `import conda` from python and not conda as an executable.

The reason is that pip (or more accurately distutils, setuptools, and wheels) doesn't give us the tools we need.  (This was actually one of the reasons for starting the conda project in the first place.)  The tools we'd need specifically from pip would be to install all of conda's dependencies (including python) and the ability to put files at any arbitrary path relative to the installed-python's `sys.prefix`.

The best way to install conda (right now) is to use the [miniconda installer](http://conda.pydata.org/miniconda.html).  The `.sh` installers are self-extracting executables that bootstrap python into the environment.  They're made with [conda/constructor](https://github.com/conda/constructor).

In the hopefully near feature, we'll have officially-supported rpm and deb packages.  A homebrew recipe would be fairly trivial as well.

**Comment by Miserlou** [comment]
Ah, gotcha. Okay, thanks! And thank you for the swift reply.
