### ISSUE TITLE
Activate conda env by a path to the env

### ISSUE THREAD

**Issue by traff** [conda/conda#3992]
Hi. I am a PyCharm developer.

We already have support for conda in our IDE. Now we are doing automated activation of conda env in the terminal inside the IDE. And struggling with that.
Currently, at least as far as I see from the documentation, it is possible to activate an env by it's name. For automation purposes sometimes it is very inconvenient because what we have sometimes is only a path to the env and there is no reliable way to get a name from the path.

There is no such problem with virtualenv, which activates the same env where activate script belongs, which is not the case with conda.

Could you please provide a way to activate a conda env by it's path or point me to such feature if it already exists?

**Comment by kalefranz** [comment]
Thanks for PyCharm! It's the IDE I use :)

The `-p` / `--prefix` option should work with activate to use a full path instead of a name. If it's not, then it's a bug.

**Comment by kalefranz** [comment]
BTW conda is useful for more than just pycharm. Conda environments are language agnostic.

**Comment by njalerikson** [comment]
@kalefranz `-p`/`--prefix`? `activate` did not previously nor does it support such a flag now...so am I missing something...?

@traff by default the `activate` scripts already activates names of environments or paths. No extra parameters are necessary as the scripts check to see if the environment to `activate` contains a "/" and in which case processes the environment as a path, otherwise it assumes it is a name and processes accordingly.

**Comment by wulmer** [comment]
AFAIK there are (were?) three ways to use the activate scripts:
* `activate <named_env_name>` would activate a named environment
* `activate <path_to_prefix_env>` would activate a prefix environment
* `/path/to/prefix/bin/activate` activates the environment in `/path/to/prefix`.

Although I only used the first two (as we are still using Anaconda 2.1), I remember that @msarahan was heavily relying on the third option to create shortcut links on Windows (for starting programs like Spyder in a specific environment).

**Comment by njalerikson** [comment]
I would say that only the first two styles you listed are "safe".

The third is risky because of how they are made. On Linux those are symlinks to the root activate/deactivate scripts. On Windows those are redirect scripts. Either way those scripts are generated by conda upon activation of the environment, they are left around after that but are dangerous to rely on (also because @kalefranz wants to get rid of them completely, which is an entire relatively unrelated discussion).

**Comment by njalerikson** [comment]
Actually I'm VERY sure the last method is not at all possible anymore.

**Comment by mcg1969** [comment]
I do think @kalefranz got it wrong above. @wulmer is on track. I agree that the third one isn't a safe option in general, and they will certainly be deprecated, as we seek to isolate `conda` from its surrounding environments (including the default environment) to give it better resilience.

**Comment by mcg1969** [comment]
So in short: no need for a `-p` or `--prefix` keyword. Just supply the full path to the environment.

It raises a question: what should the behavior be with _relative_ paths? The problem, of course, is that `activate `_name_, when _name_ is both an environment name and the name of a subdirectory, will be ambiguous. And yet, I think relative paths would be useful.

I'm honestly not sure what the current behavior is, but I would suggest the following: if the argument to `activate` starts _or ends_ with a slash, it should indicate a path-based environment selection.

**Comment by kalefranz** [comment]
Yeah I was wrong.  I thought there was both `--name` and `--prefix` for the `activate` command.  There *should* be!! We'll get that sorted in the future.  But I think we have the answer for now.  Thanks everyone for correcting me.

**Comment by traff** [comment]
Thanks for the answers!
I can confirm that the third option doesn't work anymore, though I would consider it the most obvious.
The second option works for me. There is a tiny inconvenience that in that case you have a full path to your env instead of it's name as a shell prompt. While it is ok, looks a bit cumbersome and can lead to misinterpretation: the same env look differently when opened with different arguments.

**Comment by karuppaiya** [comment]
above three options is not work for me. is there any way?
