### ISSUE TITLE
terminal instructions after creation of env should be more specific as to location of env

### ISSUE THREAD

**Issue by pleabargain** [conda/conda#4221]
create an env 
conda says start it 
BUT conda does NOT say WHERE to start it...
one extra string of instructions e.g. the LOCATION of WHERE to start the env would be very helpful
--------------------------
dennis@dennis-HP-Compaq-tc4400-EN356UT-ABA ~/D/O/e/P/TweetsByMonth> conda create -n ob node
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/dennis/anaconda3/envs/ob:

The following NEW packages will be INSTALLED:

    node: 0.8.7-0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|############################################################################| 100%
#
# To activate this environment, use:
# > source activate ob
################################################
# To activate this environment, go to the anaconda directory open the new env direactory and use:
# > source activate ob
#
# To deactivate this environment, use:
# > source deactivate ob
#

dennis@dennis-HP-Compaq-tc4400-EN356UT-ABA ~/D/O/e/P/TweetsByMonth> source activate ob
source: Error encountered while sourcing file “activate”:
source: No such file or directory

**Comment by njalerikson** [comment]
Hm the error message you see `source: Error encountered while sourcing file “activate”` suggests that something else is wrong. If you are using `bash` then running `source activate ob` is sufficient.

So what shell are you using? My guess is that you are using `fish` in which case here are the usage instructions:

```
# INSTALL
#
#     Source this file from the fish shell to enable activate / deactivate functions.
#     In order to automatically load these functions on fish startup, append
#
#         source (conda info --root)/bin/conda.fish
#
#     to the end of your ~/.config/config.fish file.
#
# USAGE
#
#     To activate an environment (via name or path), you can use one of the following:
#
#         activate ENV
#         conda activate ENV
#
#     To deactivate an environment, use one of:
#
#         deactivate
#         conda deactivate
#
#     To make the env name appear on the left side, set an environment variable:
#
#         set -gx CONDA_LEFT_PROMPT 1
#
#     To go back to making the env name appear on the right, erase that variable:
#
#         set -e CONDA_LEFT_PROMPT
```

**Comment by phejimlin** [comment]
I follow your method and still not working on Ubuntu.

After downloading conda.fish from [here](https://gist.github.com/jiffyclub/9679788), and mv it to anaconda3/bin/.

Add "source /home/phejimlin/anaconda3/bin/conda.fish" at the end of ~/.config/fish/config.fish.

>conda activate spark_env
Traceback (most recent call last):
  File "/home/phejimlin/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/phejimlin/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 161, in main
    raise CommandNotFoundError(argv1, message)
TypeError: __init__() takes 2 positional arguments but 3 were given

or

>activate spark_env
Error: activate must be sourced. Run 'source activate envname'
instead of 'activate envname'.

Do I miss something?
