### ISSUE TITLE
Why is conda-env still added implicitly to Specs?

### ISSUE THREAD

**Issue by sscherfke** [conda/conda#4229]
conda-env has been merged into conda but you still require it as a dependency (and conda forge even has an empty package for it).  Also it is implicitly added as spec when installing something (https://github.com/conda/conda/blob/master/conda/plan.py#L735).

What's the reasoning behind this? Why not just remove all of this?

**Comment by mcg1969** [comment]
The reason is that conda doesn't yet have the notion of an "obsolete" package. So if someone has an older version of conda installed---one that depends on a _separate_ conda-env---and then they upgrade, there's no way for conda to _remove_ the conda-env package, since it's no longer needed.

So what we're doing instead is upgrading the user in that case to conda-env 2.6.0, which is an "empty" package.

We're actively working on a way to instruct conda that package A "obsoletes" package B; and when that happens, we'll provide a path to removing this unnecessary package.

**Comment by sscherfke** [comment]
Ah, cool. Thanks for the explanation.
