### ISSUE TITLE
python setup.py doesn't overwrite {de,}activate shell scripts.

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#4251]
I am having to manually copy them. It might be because of: https://github.com/conda/conda/commit/41316e4eab0fc5c00e50070e02df106bad846127

The log says:

```
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'tests'
warning: no previously-included files matching '*' found under directory 'shell'
```

**Comment by kalefranz** [comment]
`setup.py` no longer contains entry point creation.  This is so that people pip installing conda somehow (for various reasons, often legitimate) don't clobber the real conda entry points.

There is also a warning message now that explains this printed when you use `setup.py`.  You may have missed it.

What you want is `python utils/setup-testing.py install`.

**Comment by mingwandroid** [comment]
Any chance of adding that to the WARNING?

**Comment by kalefranz** [comment]
sure: https://github.com/conda/conda/pull/4258

**Comment by kalefranz** [comment]
Didn't mean to close it this time Ray. I'll let you do that.

**Comment by mingwandroid** [comment]
Thanks.
