### ISSUE TITLE
Conda does not fall back to using soft links

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#4253]
Let me describe a scenario. 

There is a company, called `marvelcomics` and inside that, is a team called `avengers`.  Two members of this team are:

```bash
[shield@earth ~]$ id thor
uid=1004(thor) gid=1002(avengers) groups=1002(avengers)
[shield@earth ~]$ id loki
uid=1003(loki) gid=1002(avengers) groups=1002(avengers)
```

Now, there is a playground called `asgard` where these two guys can play:
```bash
[shield@earth ~]$ ls -ld /asgard
drwxrwxrwt. 4 root root 4096 Jan 10 11:24 /asgard/
[shield@earth ~]$ getfacl /asgard
getfacl: Removing leading '/' from absolute path names
# file: asgard/
# owner: root
# group: root
# flags: --t
user::rwx
group::rwx
other::rwx
[shield@earth ~]$ mount | grep /asgard
/dev/sdb1 on /asgard type ext4 (rw,relatime,seclabel,data=ordered)
```

The user `thor` creates a conda environment on `earth`, inside the playground using conda and installs his favourite tool: `curl`.
```bash
[thor@earth ~]$ wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
[thor@earth ~]$ chmod +x Miniconda2-latest-Linux-x86_64.sh 
[thor@earth ~]$ ./Miniconda2-latest-Linux-x86_64.sh -b -p /asgard/kingdom
[thor@earth ~]$ source /asgard/kingdom/bin/activate
(root) [thor@earth ~]$ conda install curl
```

The user `loki` tries to steal this kingdom:
```bash
[loki@earth ~]$ source /asgard/kingdom/bin/activate 
(root) [loki@earth ~]$ conda config --add envs_dirs /asgard/loki
(root) [loki@earth ~]$ conda create -n stealth curl
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /asgard/loki/stealth:

The following NEW packages will be INSTALLED:

    curl:    7.49.0-1
    openssl: 1.0.2j-0 (soft-link)
    zlib:    1.2.8-3  (soft-link)

Proceed ([y]/n)? y

Linking packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]


CondaOSError: OS error: failed to link (src=u'/asgard/kingdom/pkgs/curl-7.49.0-1/bin/curl', dst=u'/asgard/loki/stealth/bin/curl', type=1, error=OSError(1, 'Operation not permitted'))
``` 
Why did `loki` think that he could steal that easily? Because, he had read in conda's docs:

> When allow_softlinks is True, conda uses hard-links when possible, and soft-links (symlinks) when hard-links are not possible, such as when installing on a different filesystem than the one that the package cache is on.

... and he had double checked:

```bash
(root) [loki@earth ~]$ conda config --show | grep allow_softlinks
allow_softlinks: True
```

That's weird. Let's see if `shield` has added any protection mechanisms:
```bash
[shield@earth ~]$ sudo cat /proc/sys/fs/protected_hardlinks 
1
```

Of course there is one, so, unless `loki` has ownership of a file or at least `read+write` permissions on it, he can't steal it. Let's check:
```bash
[shield@earth ~]$ ls -l /asgard/kingdom/pkgs/curl-7.49.0-1/info/index.json 
-rw-rw-r--. 1 thor avengers 274 Jul 21 18:56 /shared/thor/pkgs/curl-7.49.0-1/info/index.json
```

Well, `loki` is an avenger, so he has `read+write` permissions on this file and he indeed *can* create a link to *this* file. And conda is correct till now in assuming that he can... However, the reason why he fails to steal:

```bash
[shield@earth ~]$ ls -l /asgard/kingdom/pkgs/curl-7.49.0-1/bin/curl
-rwxr-xr-x. 2 thor avengers 182238 Jul 21 18:56 /asgard/kingdom/pkgs/curl-7.49.0-1/bin/curl
```

There is no `write` permission on this `inode` for `loki`. And hence, he cannot steal blindly.

This scenario makes me raise some queries:

1.  Why does conda check only `${CONDA_PREFIX}/info/index.json` for determining whether or not it can use `LINK_HARD` for the entire package? In other words, how/why is this file the source of truth?
2.  Is there an option in conda using which I can specify that I want to prefer soft-links over hard-links, while creating new environments (using `conda create -n` or `conda env create ...`),  regardless of whether creating hard-links is possible? Why/Why not?

**Comment by kalefranz** [comment]
> Why does conda check only `${CONDA_PREFIX}/info/index.json` for determining whether or not it can use `LINK_HARD` for the entire package? In other words, how/why is this file the source of truth?

I've started making fairly extensive use of "magic files" (see https://github.com/conda/conda/blob/4.4.x/conda/base/constants.py#L108-L110).  (Hmmm even the name sort of goes a long with the theme here.)  `info/index.json` should be added to the list of constants.

The value of this pattern really solidified somewhere around conda 4.3.13, and it's really proven itself since.  We can make assumptions that these files are indicative of the state of the "unit" they represent, and we will be right the VERY VAST majority of the time.  It's only under extremely exceptional circumstances that we'll be wrong (like if a user `chmod`s a single random file for some reason somewhere), and we can then balk without too much consequence if/when that ever happens (due in large part to how rock solid the unlink-link transaction has been).

For the three magic files I linked to above, the test we're throwing at them is "are you--and the unit you represent--writable or read-only?"  Before this magic file change, conda would test permissions by just seeing if a file of a random name could be created (and then removed) in a directory.  Obviously problematic.

So is it really ok to use a single file to represent the state of a whole unit of files?  For the three examples I've been talking about so far, I think so.  If you think through how we'd handle the situation if we tested every single file in the unit of files, and found one to be abnormal compared to the others, I don't think the end result would be much different than what we're already doing now.  It's just that the path from point A to point B--the in between--might be a little different.

Now, to the `info/index.json` file specifically... You use `${CONDA_PREFIX}/info/index.json`, which is actually incorrect.  `info` directories from conda packages are left out of what is linked into a conda prefix.  More accurate is `<EXTRACTED_CONDA_PACKAGE_DIRECTORY>/info/index.json`.  We use `info/index.json` because that is absolutely guaranteed to be there for every conda package.  If a tarball does not have an `info/index.json` file, then it is not a conda package.  Easy test.  Here again for the hard-link test, I think it's safe to use this one path as a proxy for the state of the entire package.  If you think of the general flow, we download tarballs to a cache directory, and then extract them there too.  They're extracted in one go as a single unit.  Under any normal circumstance it doesn't make sense that, for example, that the package could be extracted on more than one mount point.  Similarly, on the other end, we're making the assumption that a conda prefix is all contained within a single mount point (this is probably the more tenuous assumption).

What happens if we're wrong and the file can't be hard-linked?  First, we use a procedure to figure out what the *requested* link type is when linking a package into a prefix.  https://github.com/conda/conda/blob/4.3.17/conda/core/link.py#L48-L58  That function should really be named `determine_requested_link_type()`; the result is called [`requested_link_type`](https://github.com/conda/conda/blob/4.3.17/conda/core/link.py#L401) in many other places in the code, and that's more accurate.  It's a requested link type because it's not honored in all situations.  There a few places of logic [here](https://github.com/conda/conda/blob/4.3.17/conda/core/path_actions.py#L156-L195) and [here](https://github.com/conda/conda/blob/4.3.17/conda/gateways/disk/create.py#L217-L254) where we'll override the request saying no, you can't have that.

Are there edge cases?  Probably still a few.  Much of this strategy conda has been using well before I started working on the code base.  We haven't yet encountered an edge case that presents a fatal flaw in the design.

> Is there an option in conda using which I can specify that I want to prefer soft-links over hard-links, while creating new environments (using conda create -n or conda env create ...), regardless of whether creating hard-links is possible? Why/Why not?

The short logic in [`determine_link_type()`](https://github.com/conda/conda/blob/4.3.17/conda/core/link.py#L48-L58) shows the available configuration parameters and how they're handled.  To your question directly, the answer is 'yes', and the configuration parameter is `always_softlink: yes` in a condarc file and `CONDA_ALWAYS_SOFTLINK=yes` as an environment variable.  In this case, the value `always_copy` has to be `False` (which is the default) for this to work.  These are boolean switches rather than a single enum parameter because, well, probably for the same reason conda 'features' are right now binary on-off rather than enums.  No further comments on design philosophy limitations there.  The `always_softlink` option was actually added somewhat recently.  The 'why' discussion is at https://github.com/conda/conda/issues/3308.

**Comment by nehaljwani** [comment]
Wow, thank you for the detailed reply!

With the advent of https://github.com/conda/conda/pull/5002 , Loki can now happily resume his quest, without having to further fiddle with any of the default configuration. 

```
TRACE conda.core.path_actions:execute(244): linking /asgard/kingdom/pkgs/curl-7.49.0-1/bin/curl => /asgard/loki/stealth/bin/curl
DEBUG conda.gateways.disk.create:create_link(247): **hard-link failed. falling back to copy**
  error: OSError(1, 'Operation not permitted')
  src: /asgard/kingdom/pkgs/curl-7.49.0-1/bin/curl
  dst: /asgard/loki/stealth/bin/curl
```

Feel free to close this issue.

**Comment by kalefranz** [comment]
From an email thread, and just including here so it can be referenced...

---


The big epiphanies leading up to conda 4.3.13 that finally made multi-user work were

1. Stop relying on directories to test permissions. Testing permissions on a single representative file that under normal conditions is a proxy for an entire group of paths is much more reliable. There are three "group types" that conda is generally concerned about w.r.t. permissions: prefixes, `pkgs` directories, and `envs` directories. Each has a "magic file" pointed to in conda/base/constants.py. The magic file for a conda prefix is `conda-meta/history`, and `pkgs/urls.txt` for the `pkgs` directory. In conda 4.4 I've added an `envs/catalog.json` that's the magic file for the `envs` directory (it also is now used for other meta information associated with that `envs` directory). In conda 4.3 the `envs` directory magic file piggy-backs off the parallel `pkgs/urls.txt`.

2. Stop relying on `os.stat` to test permissions. It's just not reliable across file systems and operating systems. Given use of (1), use `open(path, 'a').close()` to ultimately test for writability.
