### ISSUE TITLE
conda incompatible with local installations?

### ISSUE THREAD

**Issue by astrojuanlu** [conda/conda#448]
I normally use pip to handle all the packages in my system:

```
$ pip-2.7 install numpy --user
$ /usr/bin/python2.7 -c "import numpy; print numpy.version.version"
1.8.0
```

so they get installed in ~/.local/python2.7/site-packages. Then I wanted to give conda a try, so I did this:

```
$ ./Miniconda[...].sh
# No PYTHONPATH defined
# Prepend .anaconda to PATH: yes
$ [new shell] conda update conda
$ conda install numpy==1.7.1
$ ./.anaconda/bin/python2.7 -c "import numpy; print numpy.version.version"
1.8.0
```

I still cannot reach the 1.7.1 version installed with conda. If I remove the .local one, I can use the conda version again.

```
$ ./.anaconda/bin/python2.7 -c "import sys; from pprint import pprint as p; p(sys.path)"
['',
 '/home/juanlu/.anaconda/lib/python27.zip',
 '/home/juanlu/.anaconda/lib/python2.7',
 '/home/juanlu/.anaconda/lib/python2.7/plat-linux2',
 '/home/juanlu/.anaconda/lib/python2.7/lib-tk',
 '/home/juanlu/.anaconda/lib/python2.7/lib-old',
 '/home/juanlu/.anaconda/lib/python2.7/lib-dynload',
 '/home/juanlu/.local/lib/python2.7/site-packages',
 '/home/juanlu/.anaconda/lib/python2.7/site-packages']
```

It seems the path is not correctly handled.

```
>>> import sys
>>> sys.path.append(sys.path.pop(-2))
>>> p(sys.path)
['',
 '/home/juanlu/.anaconda/lib/python27.zip',
 '/home/juanlu/.anaconda/lib/python2.7',
 '/home/juanlu/.anaconda/lib/python2.7/plat-linux2',
 '/home/juanlu/.anaconda/lib/python2.7/lib-tk',
 '/home/juanlu/.anaconda/lib/python2.7/lib-old',
 '/home/juanlu/.anaconda/lib/python2.7/lib-dynload',
 '/home/juanlu/.anaconda/lib/python2.7/site-packages',
 '/home/juanlu/.local/lib/python2.7/site-packages']
>>> import numpy; numpy.version.version
'1.7.1'
```

Notice that the only entry that matters is `site-packages`.

**Comment by orbeckst** [comment]
As a possible workaround if someone wants to keep their `~/.local` user site around: When working with `conda`, set the environment variable `PYTHONNOUSERSITE` to something:
```
export PYTHONNOUSERSITE=True
```
and then the local user site is ignored.

**Comment by ruizengalways** [comment]
mark

**Comment by ebolyen** [comment]
Hello, I've stumbled upon this with @jjhelmus's help. I noticed this situation happening with R's .libPaths() and then confirmed it also happens with Python's sys.path. (You can trace the backreferences from the conda-forge/python-feedstock above)

I think the argument for root installations potentially needing user site-packages makes sense, however I was wondering if the position had evolved at all over time? It seems like conda is emphasizing reproducible deployments fairly heavily over system administration (thought that is useful as well). 

Given that  [PEP 405](https://www.python.org/dev/peps/pep-0405/) specifically calls out how it interacts with PEP 370 in [this section](https://www.python.org/dev/peps/pep-0405/#isolation-from-system-site-packages), it does seem like conda should behave similarly. Additionally it looks (from the outside at least) like pip intends to move its default to `--user` (to avoid `sudo pip install`) which will make things appear very strange to beginner users when using conda. 

Imagine for example a user that copy-pastes pip-install instructions from the internet before they really have a chance/need to learn about virtualized environments. I see this pretty consistently in R via `install.packages()` (usually in RStudio), and it's not exactly obvious where and why things break. I would hate to see this happen to beginner Python users as well.

Thanks for reading!

**Comment by mingwandroid** [comment]
`install.packages()` is tricky. A large part of the point of `Anaconda Distribution` is to build binary packages for you that are well tested and known to work (as well as being secure and of high performance).

Using `install.packages()` cannot guarantee any of that; rather, on Linux, it puts you at the mercy of your system package manager and the compilers you have on your `PATH` and the compatibility of those with software compiled with the `Anaconda Distribution` compilers. On OSes other than Linux, replace "system package manager and the compilers you have on your `PATH`" with "binaries available on CRAN".

I've been tempted to re-route `install.packages()` through `conda`, perhaps for now hidden behind an env. var that'd be disabled by default but I'm not sure. One thing I have done is to make R 3.4.3 depend upon our compilers so that `install.packages()` has a better chance of success.

In general, regarding user package dirs for R and Python, maybe we should consider and env. var that controls whether this is used or not? Not sure whether we'd used the same one for both ecosystems or not?

**Comment by ebolyen** [comment]
> In general, regarding user package dirs for R and Python, maybe we should consider and env. var that controls whether this is used or not? Not sure whether we'd used the same one for both ecosystems or not?

That would be really useful I think. The main issue as I see it isn't so much corralling things like `install.packages` and `pip` to use conda, but rather to make it so that if someone *did* use that in the past, they aren't stuck with a seemingly broken installation of conda because the user-directories that `install.packages` and `pip` used have masked the conda packages in a binary-incompatible way. It's really a precedence issue honestly, if the user-packages were last in the import/library order, then this wouldn't really be an issue either.

That's basically what lands us in hot water, we distribute an `environment.yaml` file to our users, which is *amazing*, however if they use R or Python on their own (especially R) they end up with user package installs which mask our environment, and there's not a easy way to remedy that (for a long time, we had users write an `.Rprofile` file to modify `.libPaths()` as that was the best solution we knew for a while, and that was only after we realized our packages weren't the things that were broken). Requesting that they never use R/Python outside of conda is also not a realistic requirement for most.
