### ISSUE TITLE
gcc cannot be installed

### ISSUE THREAD

**Issue by joachimwolff** [conda/conda#4544]
If you try to install gcc with conda on a system which is not having gcc it quits the installation with the following error:

```
Couldn't locate crtXXX.o in default library search paths. You may not have it  at all. It is usually packaged in libc6-dev/glibc-devel packages. We will try  to locate crtXXX.o with system installed gcc...
There is no /usr/bin/gcc
*** Can't install the gcc package unless your system has crtXXX.o. ***


LinkError: Link error: Error: post-link failed for: gcc-4.8.5-7 

```

1. To get this library I need to install e.g. on Ubuntu 16.04 with apt the libc6-dev. Which contradicts the idea of conda to install software without root rights. But it does not help to install it. I am still getting the same error message.
2. To quote the error message: ```We will try  to locate crtXXX.o with system installed gcc...``` Well this seems a very bad idea on a system which is not having gcc! 
3. Only solution so far is to install gcc with apt which needs root rights. And if I can install it with apt I really do not need gcc from conda.

**Comment by mingwandroid** [comment]
Conda's `gcc` package exists so that packages that use some C++11 can be built on systems with very old compilers (CentOS5 and CentOS6) and so that those packages can be run on a vast range of Linux systems (provided the libgcc run dependency is  added). It was never intended to be free-standing and requires a system linker.

I don't think I will spend time rebuilding it to change the message text regarding libc6-dev, but yes it's wrong and should say that you need a complete toolchain to be present.

**Comment by joachimwolff** [comment]
This does not help on some old weird system admin approved 'secure' systems. :(

**Comment by mingwandroid** [comment]
You need to ask you administrator to install GCC, sorry.

**Comment by basnijholt** [comment]
I am actually encountering this issue here https://github.com/conda-forge/fenics-feedstock/issues/32.

With installing a conda package in the Jupyter-stack [`base-notebook`](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile).

**Comment by mingwandroid** [comment]
You need to install a system GCC in your docker image.

**Comment by joachimwolff** [comment]
@basnijholt Continuum Analytics Inc made it very clear that they don't want to support a stand alone gcc installation. Which means if we want to have support for it we need to build our own gcc conda pakage and publish it in our own channels. I don't know if and how this is possible, maybe it is not that easy because if it would be I see no reason why it wasn't done in the first place.

**Comment by mingwandroid** [comment]
> Continuum Analytics Inc made it very clear that they don't want to support a stand alone gcc installation.

No, we haven't. I simply explained the motivations for and limitations of the current GCC package. You then filled in a load of blanks and ended up with something quite different.

Two Continuum Analytics Inc engineers have been working hard to provide comprehensive toolchains but I didn't really want to mention it because I didn't want anyone to wait for it and depend on it in-case for some reason it doesn't work out. Oh well.
