### ISSUE TITLE
CMake in unrelated projects pick up anaconda path

### ISSUE THREAD

**Issue by holocronweaver** [conda/conda#4552]
Not sure where to report this, so please direct me if this isn't the place.

In CMake-enabled projects having nothing to do with Anaconda I am running into the problem that CMake is picking up Anaconda include and lib directiories. This results in binaries which have their rpaths set to include the Anaconda lib directory. In most cases this causes the program to have linking errors or be non-functional since the bundled Anaconda libraries are rarely the versions needed to run the program.

I am not sure if this is a CMake or Anaconda bug. I am not sure how CMake even knows of the Anaconda paths since they aren't in my `LD_LIBRARY_PATH`. `printenv | grep anaconda` only shows `anaconda/bin` being in my `PATH`, nothing else Anaconda related.

OS: Ubuntu 16.04 x64
conda: 4.2.9
cmake: 3.5.1

**Comment by mingwandroid** [comment]
Did you add Anaconda to your PATH? It's likely pkg-config that's causing
you this trouble if so. Also since cmake has its own scripting language,
build system authors are free to rummage around your PATH (or other env
vars) looking for things if they so choose.

My opinion is that the activate and deactivate shell scripts should be used
instead of adding Anaconda to your PATH.

On Feb 7, 2017 1:51 AM, "Jesse Johnson" <notifications@github.com> wrote:

Not sure where to report this, so please direct me if this isn't the place.

In CMake-enabled projects having nothing to do with Anaconda I am running
into the problem that CMake is picking up Anaconda include and lib
directiories. This results in binaries which have their rpaths set to
include the Anaconda lib directory. In most cases this causes the program
to have linking errors or be non-functional since the bundled Anaconda
libraries are rarely the versions needed to run the program.

I am not sure if this is a CMake or Anaconda bug. I am not sure how CMake
even knows of the Anaconda paths since they aren't in my
LD_LIBRARY_PATH. printenv
| grep anaconda only shows anaconda/bin being in my PATH, nothing else
Anaconda related.

OS: Ubuntu 16.04 x64
conda: 4.2.9
cmake: 3.5.1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda/conda/issues/4552>, or mute the thread

**Comment by holocronweaver** [comment]
Yep, putting `anaconda/bin` in my `PATH` is what was causing the issues. I will use the activation shell scripts for now on. Thank you very much!

**Comment by goodloop** [comment]
@holocronweaver  you mean call `source ~/anaconda3/bin/activate env_name` before using conda, and delete `export PATH=~/anaconda3/bin:$PATH` from bashrc or zshrc. Is that right?

**Comment by holocronweaver** [comment]
@goodloop Correct!

**Comment by BJWiley233** [comment]
I remove anaconda from path and get same issue.

**Comment by hossamfadeel** [comment]
To fix this issue you need to add this line in your .bashrc file: (Based on your installed version of cmake)
sudo ln -s /opt/cmake-3.21.0-linux-x86_64/bin/cmake /usr/local/bin/cmake

This fixes my problem.

Regrads
