### ISSUE TITLE
suggestion: build should install into a clean dedicated directory

### ISSUE THREAD

**Issue by peter1000** [conda/conda#478]
this is a suggestion: the current situation that it is recommended to install into: PREFIX
see: http://docs.continuum.io/conda/build.html 
`PREFIX    build prefix where build script should install to`
is maybe not the best solution as this is also used to fetch the build dependencies into.

I would suggest to install into a clean dir: e.g. 

```
env/_build      (build PREFIX where build dependencies will be fetch into`)
env/_installdir      (build INSTALLDIR where build script should install to`)
```

the problem with the current situation is: that if one wants to compile something like e.g. make, chrpath patchelf, gcc, glibc ect  and one wants to define the same as a dependency one ends up with a mess and mostly missing bits.

```
package:
    name: "make"

requirements:
  build:
    - "make"
```

1 becauce the build dependency is first fetched into `env/_build` 
2 the resulting make is also installed into `env/_build` 
3 the final conda pkg is the difference in files
4 one ends up with nearly nothing: the info folder

because of this:  I suggest to install into a dedicated separate folder

I know there are ways around but it makes sense:
things like  calculating any differences ect fall away.

But who know I do not know conda so well inside and I might miss something: for linux I will implemented something like this in my fork

**Comment by craigyk** [comment]
I'd like to second this proposal.  The current system is both more limited and more complicated.  As far as I can tell, conda build is trying to diff the directory before and after to figure out what is new to package.  Just have it build and install to a new directory, scan for paths there, and package that up, diffing not required.  bootstrapping a package with itself is also less of a problem then.

@ilanschnell suggested that make is a pathological case, but I've found myself running into several of these cases while trying to get condo to work as a user space package manager on a cluster.  I've been compiling make, gcc, binutils, openmpi, hdf5, mpich, slurm, etc. and it has taken some gymnastics to get these compiled.

**Comment by ilanschnell** [comment]
Diffing is required because we generally have to deal with build dependencies.  When you talk about the gymnastics you had to take to get some packages compiled, what are the problems you ran into?  Are these problems related to diffing, or is it just hard to build some packages?  Conda-build is really just a framework for building (and bundling up) packages, the user still has to write the scripts which do the actual build process.

**Comment by craigyk** [comment]
@ilanschnell 

not so much figuring out to get it to build, which you are right, can be challenging, but also managing circular dependencies.  Things like gcc, binutils, make, etc.  I know the diffing is required to remove the build dependencies, but that is why I was suggesting passing an alternative to install so that diffing isn't required.

by targeting a PREFIX dir that is not the dir where the dependencies are installed it would be possible for a package to specify itself as a dependency (for gcc ie. a previous version of gcc) and make install would move all the actual new stuff to the build directory for you, no need to separate it from the dependencies.  you might have to scan for and replace two prefix placeholders though?  Anyways, just a thought.
