### ISSUE TITLE
Doc formatting is confusing

### ISSUE THREAD

**Issue by lia-simeone** [conda/conda#4852]
I'm admittedly new to conda, but I find the formatting style of the `conda env` docs to be confusing.

For example, [this page](https://conda.io/docs/commands/env/conda-env-update.html) for `conda env update`. As a new user, I wasn't sure if the right syntax was:
- ` conda - conda env update`
- _or_ ` conda-env update`
- _or_ `conda env update`

![screen shot 2017-03-10 at 6 07 03 pm](https://cloud.githubusercontent.com/assets/11477059/23816806/c6774400-05bc-11e7-9dce-80f238341081.png)

@mcg1969

**Comment by kerrywatson1** [comment]
Hi @lia-simeone, thanks for the comment. The NAME of the command is conda - conda env update, as shown in the NAME section, and the exact USAGE is shown in the "usage" section. 

Let us know if you have suggestions on improving this. You can even submit improvements of your own since this is an open source project.

**Comment by kalefranz** [comment]
I think we're sort of stuck with argparse here for a while still.  Maybe we'll update to click at some point.
