### ISSUE TITLE
conda update made conda client executable disappear

### ISSUE THREAD

**Issue by j3mdamas** [conda/conda#4899]
Hi guys,

Some weird behaviour I found the other day.

I cycled through a bunch of machines using SSH to run the command:

``` bash
conda update htmd -c acellera -y
```

And the output was normal, and everything related with updating packages and installing new ones, but after it, the conda client executable (`~/miniconda3/bin/conda`) was gone. I know it's just a wrapper, and easy to create a replacement, but still a very strange behaviour that I thought I should report.

Can't provide much more info than this, as I have already reinstalled conda on those machines.

**Comment by kalefranz** [comment]
You were using a version of conda prior to conda 4.3.  Unfortunately, conda hosed itself.  You'll need to download a new miniconda installer from https://conda.io/miniconda.html, and the run it overtop your current install.  Something like

    bash Miniconda.sh -bfp ~/miniconda3

We've completely fixed the root cause of what happened in conda 4.3.

**Comment by j3mdamas** [comment]
ok, thanks for the feedback!
