### ISSUE TITLE
Feature Request: conda develop command

### ISSUE THREAD

**Issue by paddymul** [conda/conda#498]
Is there someway to add a conda command for `conda develop`  similar to `python setup.py develop`  but with better management of .pth files, or maybe no .pth files.  

Manually editting a .pth file to get proper development behavior is onerous.

**Comment by twiecki** [comment]
Seems like `conda develop` does exactly the right thing. Good to close?

**Comment by ChrisBarker-NOAA** [comment]
well, setup.py develop already works, except for the proper linking. So conda develop really needs to do that -- at least on OS-X.

I have to run the following script in my project in order for develop mode to work:


    import os
    from subprocess import check_call, check_output
    # find the path to libcurl
    conda_info = check_output('conda info', shell=True)
    conda_path = conda_info.split("default environment :")[1].split()[0].strip()
    lib_name = 'libcurl.4.dylib'
    lib_path = os.path.join(conda_path, 'lib', lib_name)
    # install_name_tool -change libcurl.4.dylib /Users/chris.barker/anaconda/envs/py_gnome/lib/libcurl.4.dylib cy_basic_types.so
    command = "install_name_tool -change %s %s gnome/cy_gnome/cy_basic_types.so"%(lib_name, lib_path)
    check_call(command, shell=True)

In my case, I need to make sure it links against the conda libcurl -- otherwise it finds the conda one at build time, but the system one at run time.

conda build and/or conda install already has the code to do the linking right, so this shouldn't be too hard for someone already familiar with conda ( I hope...)

**Comment by asmeurer** [comment]
There are also [these](https://github.com/conda/conda/issues/498#issuecomment-38330137) TODOs still.

**Comment by ChrisBarker-NOAA** [comment]
@asmeurer:

Looks good. Now someone just needs to find the time to do it all ;-)

Also, I have not thought this out at all yet, but it seems that given that conda packages are more universal than python packages, then there may be a use-case for a non-pyton specific "develop" -- i.e. a way to put in links to a unpacked conda package, rather than installing it. That would allow folks to actively develop non-pyton stuff as well, all inside a conda-built framework.

Just a thought....

**Comment by asmeurer** [comment]
In terms of OS X, the work at https://github.com/conda/conda-build/pull/312 should make this easier (and potentially unnecessary, so long as you compile your code against the Anaconda libs).

**Comment by asmeurer** [comment]
Automatic calling of the relinking logic on OS X was implemented in https://github.com/conda/conda-build/pull/490. That should fix the main issue people have been having on OS X where install_name_tool or `DYLD_LIBRARY_PATH` is needed to work against some Anaconda libraries. I'm leaving this issue open because there are still some [other](https://github.com/conda/conda/issues/498#issuecomment-38330137) things that would be useful to have implemented.

**Comment by sandhujasmine** [comment]
Here's a PR to make the rpath an absolute path in develop mode. From my testing on CentOS, linux already does this, though I'm not sure how, so this only applies to the Mac.

See discussion here: [#652](https://github.com/conda/conda-build/pull/652)
[my understanding + motivation](https://github.com/conda/conda-build/pull/652#issuecomment-153915871)

Please weigh in if you have more thoughts on this topic. thanks!

**Comment by ChrisBarker-NOAA** [comment]
cool! this sure sounds good -- I'll need to try to test it out soon.

-CHB


On Thu, Nov 5, 2015 at 2:48 PM, jasmine <notifications@github.com> wrote:

> Here's a PR to make the rpath an absolute path in develop mode. From my
> testing on CentOS, linux already does this, though I'm not sure how, so
> this only applies to the Mac.
>
> See discussion here: #652 <https://github.com/conda/conda-build/pull/652>
> my understanding + motivation
> <https://github.com/conda/conda-build/pull/652#issuecomment-153915871>
>
> Please weigh in if you have more thoughts on this topic. thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/498#issuecomment-154220679>.
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by tetianakh** [comment]
Hello all,
Are there any updates on this issue?

 I am working on a python project with a lot of non-python dependencies. I need to install this project in a development mode from the source code, and I want to be able to change the python source code and run tests. I am new to conda and I can't figure out how to do this simple thing. 

Can someone please give an example of how to use the `conda develop` command?

**Comment by kynan** [comment]
@tetianakh It works the same way as `setup.py develop`: in the root of your source directory you do `conda develop .` to link that directory to your active environment.

**Comment by kynan** [comment]
@asmeurer handling entrypoints would be great!

**Comment by kalefranz** [comment]
`conda develop` is now a conda-build command

**Comment by ankostis** [comment]
So still (May 2019) `conda develop` does not handle entry-points, correct?
