### ISSUE TITLE
NoPackagesFoundError: Packages missing in current osx-64 channels

### ISSUE THREAD

**Issue by kentrino** [conda/conda#4994]
Hi!

I'm noob at conda. And I got this error below while doing `conda env create -f env.yml` on my own mac(10.12.2).

And my env.yml is here which is created on Amazon Linux(https://aws.amazon.com/amazon-linux-ami/2016.09-release-notes/)

https://gist.github.com/kentrino/7bd10595715fa07058c44baf1b735e4a

How can I fix it?

I'm sorry for my novice question, but does anyone help me? 

```
NoPackagesFoundError: Packages missing in current osx-64 channels:
  - dbus 1.10.10 0
  - gst-plugins-base 1.8.0 0
  - gstreamer 1.8.0 0
  - libgcc 5.2.0 0
  - libsodium 1.0.10 0
  - libxcb 1.12 1
  - opencv 3.1.0 np111py27_1
  - pycairo 1.10.0 py27_0
  - qt 5.6.2 2
  - system 5.8 2
  - zeromq 4.1.5 0
  - menpodetect 0.4.1 py27_0
```

**Comment by kalefranz** [comment]
The env.yml files aren't always completely portable across operating systems, usually because of the build numbers.  Try editing the https://gist.github.com/kentrino/7bd10595715fa07058c44baf1b735e4a file by removing all the build numbers.  For example change `bzip2=1.0.6=3` to just `'bzip2=1.0.6`.  I'd start there.  If that doesn't work, next thing I'd do is remove the version numbers too.
