### ISSUE TITLE
Anaconda Navigator doesn't launch

### ISSUE THREAD

**Issue by monicaec** [conda/conda#4995]
Hi there,

I am new to Python and everything that comes with it and I am having some problems in getting my first project moving.

I was working with Spyder and it was working perfectly until (I think this was the reason but I am not sure) I downloaded python-control-master and installed setup.py. Then Spyder wouldn't launch. 

I have tried uninstalling and installing Anaconda again but it doesn't work. I have typed conda list and conda info in cmd and in both cases it says there has been an unexpected error. 

I get this from conda list:
![conda-list](https://cloud.githubusercontent.com/assets/26897300/24652974/29838b82-1934-11e7-8b7c-bc51107a0db7.PNG)

And this from conda info:
![conda-info](https://cloud.githubusercontent.com/assets/26897300/24652986/3e6c2fae-1934-11e7-86eb-e9540cedef48.PNG)

I am quite lost at the moment and any help will be really appreciated!

Thanks

**Comment by goanpeca** [comment]
Please open this issue on the [Anaconda Issue Tracker](https://github.com/ContinuumIO/anaconda-issues/issues)

**Comment by goanpeca** [comment]
@kalefranz ?

**Comment by groutr** [comment]
@monicaec, it looks like you have a system python installed in C:\Python27 (I'm guessing it's on path, or associated somehow with .py scripts).  You should use the python installed in the conda environment (the python binary for conda should be in C:\Users\user\Anaconda2\bin\python).

Anaconda changes the sys.version string which also requires modifying the python interpreter to be able to parse it.  That's why the system python won't work.

**Comment by kalefranz** [comment]
When you start cmd.exe, make sure you use the `Anaconda Prompt` icon.  Or, when you first start cmd.exe, run `C:\Users\user\Anaconda2\Scripts\activate root`.
