### ISSUE TITLE
Minimizing package changes in the solver

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#5027]
Recently ran into a problem over at Dask, which I expect wouldn't be an issue if the solver tried to minimize the number of packages that are swapped out (e.g. upgraded, downgraded, etc.). Please see issue ( https://github.com/dask/dask/issues/2191 ) for an example of this kind of problem. I expect this is generally helpful and useful to others. Though would be curious to hear some thoughts and feedback on this suggestion.

**Comment by electronwill** [comment]
You may have seen this already but this page talks some about channel order in .condarc: https://conda.io/docs/channels.html

**Comment by kalefranz** [comment]
This is a feature request to pin packages to channels in first install into an environment.

**Comment by minrk** [comment]
My description of this feature, migrating from #6845 which has been closed, is similar to the behavior of `pip install -r requirements.txt`.

Given the example with the new `-S` flag:

```
conda create -n test zeromq=4.2.3 # latest is 4.2.5
conda install -n test -S zeromq # doesn't upgrade, yay!
conda install -n test -S zeromq zlib # upgrades zeromq to 4.2.5, but I wish it left it alone
```

I think my goal is to essentially to reduce `conda install -n test -S zeromq zlib` to the behavior of `conda install -n test -S zlib` when `zeromq` is already satisfied. I know it's a lot more complicated than that because restrictions like `zeromq=4.2` that may already be satisfied should still be applied, preventing removal of `zeromq` or installation of `zeromq=4.3`. Perhaps what would be more accurate is to give the already-installed package for a given spec a boost in the solver so that `zeromq=4.2.3+installed` scores higher than `zeromq=5.0`. That way, all other things being equal, the installed package would be kept as long as remaining constraints are satisfied. I don't know what to do with conflicts like `conda install -S A B` where:

1. I have A 1.0
2. B 2.0 requires A >= 2.0, B 1.0 requires A >= 1.0

Does the minimal-change take priority, keeping A 1.0 and installing B 1.0? Or does the fact that I'm asking for B mean I get B 2.0 and upgrade A to 2.0? Intuitively, I'd expect the latter, coming from the perspective "Install B as you would; Only upgrade A if you have to" rather than a more forceful "pin A to current unless it is in conflict with other specs".
