### ISSUE TITLE
Consider adding the ability for conda to directly install python wheels

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5202]
Stub for community discussion following closure of https://github.com/conda/conda/issues/931 and https://github.com/conda/conda/issues/1865.

**Comment by jakirkham** [comment]
Have thought a bit over the last year about how it might be nice to be able to convert between `conda` and `wheels`, which seems related to this issue as well. Finally got around to opening `conda-build` issue ( https://github.com/conda/conda-build/issues/2490 ) briefly mentioning this possibility.

**Comment by kalefranz** [comment]
The first step here, which I think @nehaljwani has expressed interest in working on, is writing a script that, as completely as possible, converts wheel metadata (I guess described in https://www.python.org/dev/peps/pep-0427) to the three metadata files that are most import for conda package installation, which are

* `info/index.json`
* `info/link.json`
* `info/paths.json`

`index.json` contains all the information from the package that gets added to the subdir's `repodata.json` file.  Information there is kept to a minimum, since the file can grow large for large collections of packages, following the rule that we only add information that is relevant to *choosing* a package (i.e. relevant to the solver).

`link.json` contains information that affects how conda installs a package.  Information that doesn't need to be known for the package to be selected by the solver, but does need to be known for conda to install the package correctly after it's been chosen by the solver.

`paths.json` is the manifest of non-metadata files contained within the conda package, along with additional information about those individual paths (like hashes, prefix rewriting instructions, etc).  I don't think we've added a formal paths.json spec to our documentation yet.  It should be pulled out of https://github.com/conda/conda-build/issues/1486.

**Comment by tribbloid** [comment]
+1 very useful feature is implemented properly

**Comment by msarahan** [comment]
While we recognize the general usefulness of expanding the packages that are available from a given package manager, it's important to recognize that this problem is hard.  Like crazy hard.  The metadata mismatch between conda and pip is large.  With compiled packages especially, installing wheels directly is likely to cause huge issues, which conda will then get blamed for, because metadata mismatch and binary incompatibility are not things that most users are accustomed to considering.  The conda developers are not especially interested in opening up that opportunity for failure right now.  If you'd like to get involved in the discussion, please see https://discuss.python.org/t/drawing-a-line-to-the-scope-of-python-packaging/883
