### ISSUE TITLE
Test and report on state of conda with proxy servers

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5220]
Start by manually setting up a local proxy server. Google "docker image squid proxy".  There are multiple ways to configure these. Choosing a specific port to attach to. Using authentication or not. Using https or not. Etc. Before you even touch stuff with conda code, plink around just with some one-off python code that uses the requests and accessing the internet through the proxy. Make sure it's working and you understand how it's working. 

Then test conda against it. Follow the documentation on conda.io about using a proxy server with conda. Test all the different scenarios that are presented. First just figure out what works and what doesn't with 4.3.latest.  Post the report back here.

From memory, specific features that need tested:

* basic proxy server use, no proxy authentication, all conda traffic going through proxy server
* proxy server that requires a user to type in a password for access
* configuration of conda's proxy use via all three of (1) condarc configs, (2) .netrc files, (3) standard proxy configuration environment variables supported by requests

**Comment by kalefranz** [comment]
Issue referencing proxy configuration environment variables: https://github.com/conda/conda/issues/3481

**Comment by tyler-thetyrant** [comment]
[WIP] Testing info. 
Using squid from [here](https://hub.docker.com/r/poklet/squid/).

```
Current conda install:

                   platform : osx-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : 2.1.9
             python version : 2.7.13.final.0
           requests version : 2.13.0
           root environment : /Users/tkim/miniconda3  (writable)
        default environment : /Users/tkim/miniconda3
           envs directories : /Users/tkim/miniconda3/envs
                          /Users/tkim/.conda/envs
              package cache : /Users/tkim/miniconda3/pkgs
                          /Users/tkim/.conda/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                config file : /Users/tkim/.condarc
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.13.0 CPython/2.7.13 Darwin/16.5.0 OSX/10.12.4
                    UID:GID : 502:20

```

- Tested and confirmed working:

  -  All conda traffic goes through basic proxy server (HTTP) use with no proxy authentication.
 
- Haven't tested yet:

  - HTTPS proxy server usage with authentication.
  - Conda usage via proxy through .netrc files 
  - Standard proxy configuration environment variables supported by requests

**Comment by DandyDev** [comment]
What's the progress of this issue? As it currently stands, I cannot install packages through an anonymous proxy over https. I've tried adding the proxy to `.condarc` and I also tried using the `HTTPS_PROXY` env var. Neither works.

**Comment by nehaljwani** [comment]
urllib3 sort of fakes a proxy server to test it's proxy handling https://github.com/shazow/urllib3/blob/master/test/with_dummyserver/test_proxy_poolmanager.py . Maybe the test suite in conda could do something like this too?

**Comment by classtag** [comment]
NO work at now.

**Comment by JoeHartshorn** [comment]
Regarding [this issue](https://github.com/requests/requests/issues/2338) with requests. Is there any hope of having conda work from behind a windows proxy that uses NTLM?

**Comment by kalefranz** [comment]
I tested it and it worked for me.

**Comment by AndreaPi** [comment]
@kalefranz what did you test exactly? Was it a proxy which requires authentication? Can you show the contents of your `.condarc` file? Also, since putting my username and password in a text file is clearly a no-no, does it still work if I don't include them? In theory, `conda` should ask me to input them. In practice, it doesn't, and anyway even when I put them in the `.condarc` file (against all good judgment) it doesn't work anyway. I understand your first post talked about a basic proxy with no authentication, but that's by far the less common use case. In the vast majority of cases, people behind a proxy are behind a proxy _with_ authentication.

PS maybe this could be related to the `conda` version, too. I'm fairly confident I have the latest one. Can you show your version? Which command do I need to show the nice output in ? comment?

**Comment by RedDevil91** [comment]
Hi!
In practice when you configure `.condarc` file to use the specific proxy but without authentication conda doesn't prompt the user for authentication. It's a problem because the company IT won't accept the solution to store the username and the password in a simple text based file like `.condarc`.
After conda update this is the output for me (on Windows 7):

Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ C:\ProgramData\Miniconda2\Scripts\conda install numpy`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Miniconda2
                 HOMEPATH=\Users\username
                     PATH=......
        PLMVIS_82_LIBPATH=C:\Program Files (x86)\SAP\FrontEnd\SAPgui\Program
             PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=not set
            SSL_CERT_FILE=not set

     active environment : None
       user config file : C:\Users\username\.condarc
 populated config files : C:\Users\username\.condarc
          conda version : 4.5.4
    conda-build version : 3.0.30
         python version : 2.7.14.final.0
       base environment : C:\ProgramData\Miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda2\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda2\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
                          C:\Users\username\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.14 Windows/7 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False


V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.


If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 authenticationrequired',)))",),)

A reportable application error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: n

**Comment by kalefranz** [comment]
Conda uses [`requests`](https://github.com/requests/requests) for its http stack.  I believe both NTLM and kerberos are additional plugins for requests. I have no idea if those additional plugins simply being installed in the environment is sufficient, or if there is additional implementation that needs to happen in the conda code (most likely the latter). If you're an enterprise customer of Anaconda, Inc. and would like to have this issue prioritized, please let your account rep or customer support know.

**Comment by nikhilnicks** [comment]
Proxy Issue still exist in Anaconda Latest Version 
Executed below options to included required package for development and get it reflected in Anaconda Navigator.
``` 
Options
1. Install package using **pip3** (pip3 install <package-name>
2. Install package using **conda** (conda install <package-name>)
```

**Option 1: Install package using **pip3****
**Command Executed:**  pip install <package-name> --proxy http://<proxy_address>:<proxy_port>

**Output:** Package got installed but Anaconda Navigator cannot refer/pick up the installed package

**Did Not Try:**
On Installing the package using pip, you can try disabling and see whether the package is available in Anaconda
```
# use pip when installing and listing packages (default True)
use_pip: False
```

**Option 2: Install package using **conda****
Got various errors on modifying .condarc or on creating new .condarc. Issue's are mentioned below

**Issue 1: Removed defaults from channels, added proxy info**
```
channels:
- binstar_username
- http://some.custom/channel
ssl_verify: False
proxy_servers:
  http_proxy: http://<proxy_address>:<proxy_port>
  https_proxy: https://<proxy_address>:<proxy_port>
```
**Error:** 
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/r/osx-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 AuthorizedOnly')))"))

**Issue 2: Added defaults to channels, modified proxy info. This prompts for UserName/Password and on entering it fails with complete stacktrace**
```
channels:
- binstar_username
- http://some.custom/channel
- defaults
ssl_verify: False
proxy_servers:
    http_proxy: <proxy_address>:<proxy_port>
    https_proxy: <proxy_address>:<proxy_port>
```
**Error**
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', BrokenPipeError(32, 'Broken pipe'))': /simple/xgboost/

**Solution:**
Use lower version of Anaconda which has Python3 support. I tried with Anaconda3-5.3.0-MacOSX-x86_64 and stuffs executed
**Command:** pip install <package-name> ( This worked on VPN)
**Command For Resolving Proxy Issue:**  pip install <package-name> --proxy http://<proxy_address>:<proxy_port> --trusted-host pypi.python.org (Corporate Network when development is happening behind firewall)

**Comment by antoxin** [comment]
Tried to set proxy by:
.condarc:
```
proxy_servers:
 http: http://domain\user:password@proxy.domain:port
 https: httpa://domain\user:password@proxy.domain:port
```
environment variables:
```
set HTTP_PROXY=http: http://domain\user:password@proxy.domain:port
set HTTPS_PROXY=https: httpa://domain\user:password@proxy.domain:port
```
Also tried without domain before username. All result in:
```
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: 00:00.197091

The credentials you have provided for this URL are invalid.

You will need to modify your conda configuration to proceed.
Use `conda config --show` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.
```
Any chances to solve that?

**Comment by Ankur-Deka** [comment]
Any solution?
