### ISSUE TITLE
conda vs conda env has too much confusion

### ISSUE THREAD

**Issue by jgmorrison** [conda/conda#5253]
Many issues have been brought up by customers using different methods we have put forward. This leads to confusion on when to use conda or conda env. 

Here are some examples of duplicate actions:

list available environments:

    conda info -e
    conda env list

The following has had failures with "conda env" and has been suggested to use the "--all" flag with conda instead, https://github.com/conda/conda/issues/3215. Two ways are confusing especially if one doesn't always work.

    conda env remove -n env_name
    conda remove -n env_name —-all

The docs suggest the following  to build identical environments, https://conda.io/docs/using/envs.html#build-identical-conda-environments

    conda list -n test —explicit > testexp.txt
    conda create -n test —file testexp.txt

But suggest sharing environments with the following, https://conda.io/docs/using/envs.html#share-an-environment

    conda env export -n env_name > environment.yml
    conda env create —file environment.yml

**Comment by JeremyEnns** [comment]
If we are no longer developing conda env should we deprecate it and consolidate our docs around the most up-to-date way?

**Comment by ijstokes** [comment]
@JeremyEnns who says that we're deprecating `conda env`? @kalefranz is that true? I use it all the time.  I think many people do.

@jgmorrison I don't disagree that it is confusing.  It was my wish that the thing that became `anaconda-project` would provide a single-system tiered-syntax that would do away with the confusion from `conda env` environments (`conda env export`) and `conda` environments (`conda list -e`), giving us just one command and one syntax.  Instead we've ended up with 3...

**Comment by kalefranz** [comment]
> who says that we're deprecating `conda env`?

Not me.

However, it hasn't gotten the attention from me that the core conda code has.  At some point this will change.  I have every intention to actually integrate them more tightly, especially now that they're in the same repo.

All of the current ways of doing things (e.g. `conda info -e` and `conda env list`) will stay functional for a long time.  We will give ample deprecation warnings before we shut anything down, and those warnings will also teach the *right* way to do things, whatever that ends up being.

I agree that confusion between conda and conda-env is still an area I'd classify as a mess that needs cleaned up.

**Comment by Kharms** [comment]
Which of those two is recommended as of now?

**Comment by jkleckner** [comment]
I have had conda environments get quite tangled and unable to recreate them from a spec-file.  Is there a recommended flow to avoid this?

**Comment by soapy1** [comment]
I hope this documentation will make this more clear https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by jkleckner** [comment]
@soapy1 Thank you.  It is useful to know that `conda env` is still expected to work and that using `pip` with that should work.  I have a suspicion that I may have updated `pip` outside of conda and that may have led to some tangling?

**Comment by mjarosie** [comment]
Another example:

```
conda create -n test
conda env create -n test
```

The second command fails with `SpecNotFound` exception:
`Invalid name, try the format: user/package`

**Comment by cipri-tom** [comment]
what issues are we expected to face when combining `conda env <cmd>` and `conda <env-related-cmd>` ? I never know which one to use and I think I'm mixing them often

**Comment by nugend** [comment]
This is currently my biggest pain point with trying to use conda. I just want to specify a configuration so I can easily share it. There's *no* documentation about how to create an even roughly reproducible conda environment that doesn't have some subtle issues if you need to do absolutely anything other than the bog standard.

Even if it amounts to: We refuse to create a file format, you must issue all commands on the shell. Just make that the official policy and I'll stop trying to use apparently half broken tools.

**Comment by 3tilley** [comment]
I think this would be a lot easier if there was a way of using `conda create` from a yaml file. I would love to just use that function as the optional arguments are a lot more useful. Even if this needs to be built out, if I understand correctly, it should just be possible to do the transformation in a scriptable way in the short term? There needs to be some regex transformation on the format of the entries, the name could be pulled out and added as a keyword arg, and the channels could be added as args as well? Is it just running pip afterwards that would be an issue?

Is there any docs on the two formats?

**Comment by dycw** [comment]
I am continually confused by this, even as a conda user of 5+ years.

**Comment by yaochx** [comment]
what's the difference in brief :<

**Comment by perlow** [comment]
I find this confusing as well. There are options to `conda create` that do not appear to be available in `conda env create`. For example, you can specify `--strict-channel-priority` to `conda create` but you can't specify that argument to `conda env create` nor does there appear to be a way to specify strict channel priority in the yml file. Or perhaps there is a way, but there is really no documentation that I can find on what is possible to specify in a yml file. All I can find are examples. 

As a principle, shouldn't the complete functionality of `conda create` be available in `conda env create`? If not, why not get rid of the latter? Otherwise, it lures teams into assuming that the yml file is a good solution and then later find they have to revisit when they find they need an option only available in the more powerful command.

**Comment by mforbes** [comment]
Also, why does `conda env remove <env_name>` not work?  From the docs, it does not seem that `conda env remove` should take any additional non-prefixed arguments, so it should just do the right thing and remove the named environment.  (I understand why `conda remove -n <env_name>` needs to the `-n` so it can be distinguished from `conda remove <pkg_name>`, but isn't that the whole point of `conda env` - to work with environments instead of packages?

**Comment by analog-cbarber** [comment]
At the very least, it seems that `env create` should be included in the online
[command reference](https://docs.conda.io/projects/conda/en/latest/commands.html).

I don't mind typing `conda env <cmd> -h`, but someone browsing that page won't know
that it exists.

**Comment by imakin** [comment]
everytime i need to make a new conda env, i have to search on the internet which one to use

**Comment by 3tilley** [comment]
`conda env create` also:

- Doesn't accept the same flags e.g. `--channels`
- Doesn't respect the same flags `-f` works differently
- Doesn't respect `#[win]` and other modifiers in the same way (as far as I understand)

I think the only reason you ever want `conda env create` is if you use a yaml file, or you want to include the name of the environment in the file. Having two is extremely confusing and a constant source of issue for new users.

Would it be that hard to have `conda create` accept yamls?

**Comment by water-e** [comment]
Our group would like to create an environment with yaml and also be able to impose strict channel order. Unless I am mistaken, the only thing that seems to do both is to use "conda create", then to set .condarc with strict order and then use "conda env update" to catch the yaml part. That is simply impossible to teach and remember. Users don't even look it up because they seem to expect something different (channel order in the yaml will be followed strictly). While I'm at it, it would be very nice if there could be an option in the yaml to perpetuate the strict channel order by putting it in the .condarc file. Our environment encounters runtime issues if the order isn't maintained later for any random extra installations the user might do.

**Comment by houtianze** [comment]
Yes, I'm still utterly confused why there are 2 commands existed for a very basic operation creating an environment, and `conda env` is even not shown in `conda --help`.

**Comment by intotecho** [comment]
I have been struggling to get `conda env create -f env.yml` to work in a Dockerfile. 
It is asking me to install anaconda-client ?
That's when I noticed there are two alternatives.  Removing the 'env' helped solve this issue.
Also:

- `conda env create` doesn't support `-y` option for non-interactive.
- `conda create` doesn't support  `--experimental-solver`.

**Comment by CatChenal** [comment]
Another non-expected difference of option between `conda create` and `conda env create`: only the former has a "dry-run" option (`-d`).

**Comment by albertotb** [comment]
There is at least two operations I don't know how to do without `conda env`: create environment from YAML file and list all environments. This is confusing since as @intotecho the `env` command does not show up in the help message. However, in the web docs `conda env create -f` is mentioned as the way of creating environments from YAMLs.

**Comment by epignatelli** [comment]
Joining the confusion as a conda user 6+ years.

Why `conda create -n` but `conda env create -f` or `conda env remove -n`? 
It is very counterintuitive.

**Comment by dholth** [comment]
See also https://github.com/conda/conda/issues/11633 which is being worked on.
