### ISSUE TITLE
Conda produces PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by fdas3213** [conda/conda#5327]
Hi, I installed pyspark and tried to use the package, but I received following error in command prompt. I tried to solve the problem by using right-click as administrator, but it still fails, so I think the problem might be related to conda, so could anyone help me figure out what I should do? Thank you!

```
c:\spark>pyspark
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "C:\spark\bin\..\python\pyspark\shell.py", line 38, in <module>
    SparkContext._ensure_initialized()
  File "C:\spark\python\pyspark\context.py", line 259, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "C:\spark\python\pyspark\java_gateway.py", line 80, in launch_gateway
    proc = Popen(command, stdin=PIPE, env=env)
  File "C:\Users\shuzhe\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\shuzhe\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied
```

**Comment by kalefranz** [comment]
There is nothing in your stack trace that implies something going on with conda.  If the pyspark application code needs write permissions to the installed prefix, you'll need to install it into a conda environment that the user you run the process with has write access to.

**Comment by leeyuiwah-sl** [comment]
Hi I ran into the same problem. I ditched the SPARK_HOME folder (which in my case was C:\spark-2.4.3-bin-hadoop2.7) that I created previously using cygwin tar and tried unpacking the folder again (from spark-2.4.3-bin-hadoop2.7.tgz), but this time using 7zip instead of cygwin tar and then problem went away. Note that with 7zip the unpacking is done in two step, first extract the ...tar from ...tgz, and then extract the whole directory tree from ...tar

Some other discussion on the Internet (e.g. https://stackoverflow.com/a/43958577/1168041) suggested that the problem was due to cygwin tar got some permission wrong. This explanation is consistent with what I tested and experienced above.
