### ISSUE TITLE
duplicate log messages

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5378]
Adding code

```python
class DbgViewHandler(logging.Handler):
    def emit(self, record):
        print("DbgViewHandler: %s" % record)

logger = logging.getLogger("logging_test")
logger.setLevel(logging.DEBUG)
logger.propagate = False
stream_handler = logging.StreamHandler()
stream_handler.setLevel(logging.WARNING)  # all going to stderr
dbgview = DbgViewHandler()  # all going to stdout
dbgview.setLevel(logging.DEBUG)
logger.addHandler(dbgview)
logger.addHandler(stream_handler)

logger.info("Hello there")
logger.warn("Whoa there")
```

To the bottom of conda/gateways/logging.py outputs too many copies of messages.

**Comment by mbargull** [comment]
I believe there wasn't any issue of duplicate log messages at all. The expected output of your code above should be one output for `"Hello there"` from `dbgview` and two output for `"Whoa there"`, one from `stream_handler` and the other from `dbgview`. This happens since both those handler get triggered due to their levels `WARNING` and `DEBUG` being `<= WARNING` (level for `"Whoa there"`). There also shouldn't be anymore output since `logger.propagate = False` prevents the record to be handled by any ancestral logger. 
Hence #5379 doesn't fix this supposedly non-existent issue but is helpful nonetheless as you correctly stated yourself:
> But we also don't need to call it here.
