### ISSUE TITLE
Don't think features are working properly for nomkl and packages from other channels

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5383]
I don't have time to fully investigate right now, but I think you get surprisingly different results from:

```
conda create -n nomkl_cf -c conda-forge nomkl numpy scipy pandas jupyter
```

vs.

```
conda create -n nomkl_defaults nomkl numpy scipy pandas jupyter
```

My expectation is that I'd get the nomkl versions in both cases.  Maybe conda-forge numpy **is** a nomkl version, I'm just realizing.  Which then makes me think that maybe we need to reverse the feature logic and have our no-feature numpy look like conda-forge numpy (that seems reasonable to me), in which case our MKL version of numpy should have the [mkl] feature label...

**Comment by mcg1969** [comment]
Yeah, the problem really is the different conventions that conda and conda-forge adopts. There's frankly no way that our nomkl flag can affect how conda-forge's packages are selected, because they don't use our feature sets.

I'm not sure if the Anaconda folks are going to be keen to rework their MKL/nomkl conventions. That's going to require a fair amount of metadata hotfixing.

**Comment by kalefranz** [comment]
Ohhhh features.

**Comment by kalefranz** [comment]
Features need to be key/value, not binary present/not present. So mkl=true would be fine.  Default value could always be false/not present.  But then gpu=nvidia would also be fine.

**Comment by ijstokes** [comment]
OK, I think I understand what is going on now.  Do the conda-forge folks use MKL for their numpy, out of curiosity?  I came across this issue literally minutes before standing in the Intel booth to present on Anaconda + MKL and was worried that I was going to have totally the wrong conda environments and bogus benchmarks to talk about, but it worked out OK for me.

I'm closing the issue because I don't think there is anything to do.  I've taken the liberty of self-labeling the resolution as "Invalid", because the problem I thought existed didn't exist (in terms of features not working properly), but there is the meta-issue that it appears @kalefranz is aware of: features are a tricky thing.  It is weird to have a conda-package that is just a feature.  Maybe a fix/refactor of features in conda v5?  And the question of whether or not specifying "mkl" or "nomkl" has the expected effect (or any effect) when the MKL-associated packages come from anywhere other than the "default" channel... (ie. come from conda-forge).

**Comment by jakirkham** [comment]
Totally a fan of key/value with features, @kalefranz. We tried to do something like this with our `blas` package, but I don't think it totally fixes the issue. Expect some enhancements on the `conda`/`conda-build` front should be able to though.

<hr>

As for `mkl`...

We don't really have a way to include `mkl` in conda-forge ATM. This would require development packages and such, which we don't have. However it does seem Intel has made an effort to put these in their channel recently.

The other issue is this indemnification clause in Intel's license agreement. As an open source project with no funds, conda-forge can't really promise to pay Intel's legal fees in case someone tries to sue them for some issues caused by some package(s) we might build with `mkl`. There is the other question of whether we would even want to be in that situation if we did have funds to cover such a thing.

As it stands, we have tended to shy away from including `mkl` in conda-forge. This seems to be a typical response of other OSS projects distributing binaries. For instance NumPy and SciPy go to great lengths to not use `mkl` or Intel compilers when it comes to their wheels for Windows. If Intel was willing to drop this indemnification clause for open source projects, I think it would help adoption of `mkl` in a larger arena. Though I get the impression this is unlikely to happen.

That said, if someone either does not install or uninstalls our `blas` package, it appears to revert back to `mkl` packages from `defaults`. So this seems to be sufficient for those packages in `defaults`. I guess those not in `defaults` that could be built with `mkl` could be rebuilt and added to `defaults` if there is sufficient demand.

**Comment by ijstokes** [comment]
I'm not going to jump to re-open this but I think I've just seen this same issue manifest itself with the Intel Python, where the `[intel]` feature gets superceded by more recent non-`[intel]` feature packages.  I think this is exactly what Intel does not want to happen.  Once you're using the `[intel]` feature for a package then I **think** you (and Intel) want to always stay on the `[intel]` feature branch, even if it means you fall behind in versions.

@csoja @teoliphant one of you may wish to re-open this, or perhaps create a new issue with a bent towards the Intel specific case.

```bash

$ conda update --all
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/ijstokes/intelpython3:

The following NEW packages will be INSTALLED:

    asn1crypto:   0.22.0-py35_0            
    packaging:    16.8-py35_0              

The following packages will be UPDATED:

    conda:        4.3.16-py35_intel_1 intel [intel] --> 4.3.18-py35_0         
    cryptography: 1.7.1-py35_intel_0  intel [intel] --> 1.8.1-py35_0          
    idna:         2.2-py35_intel_0    intel [intel] --> 2.5-py35_0            
    intelpython:  2017.0.3-3          intel --> 2017.0.3-4       intel
    mkl:          2017.0.3-intel_5    intel [intel] --> 2017.0.3-intel_6 intel [intel]
    openmp:       2017.0.3-intel_4    intel --> 2017.0.3-intel_5 intel
    pyopenssl:    16.2.0-py35_intel_0 intel [intel] --> 17.0.0-py35_0         

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env:    2.6.0-0             intel --> 2.6.0-0               
    pyasn1:       0.2.3-py35_intel_0  intel [intel] --> 0.2.3-py35_0
```

and then for background:

```bash
(root) ijstokes@0194-ijstokes bin $ which python
/Users/ijstokes/intelpython3/bin/python

(root) ijstokes@0194-ijstokes bin $ python -V
Python 3.5.3 :: Intel Corporation

(root) ijstokes@0194-ijstokes bin $ conda info -a
Current conda install:

               platform : osx-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /Users/ijstokes/intelpython3  (writable)
    default environment : /Users/ijstokes/intelpython3
       envs directories : /Users/ijstokes/intelpython3/envs
                          /Users/ijstokes/.conda/envs
          package cache : /Users/ijstokes/intelpython3/pkgs
                          /Users/ijstokes/.conda/pkgs
           channel URLs : https://conda.anaconda.org/intel/osx-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/intelpython3/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.3 Darwin/16.6.0 OSX/10.12.5
                UID:GID : 502:20

# conda environments:
#
root                  *  /Users/ijstokes/intelpython3

sys.version: 3.5.3 |Intel Corporation| (default, Apr ...
sys.prefix: /Users/ijstokes/intelpython3
sys.executable: /Users/ijstokes/intelpython3/bin/python
conda location: /Users/ijstokes/intelpython3/lib/python3.5/site-packages/conda
conda-build: None
conda-env: /Users/ijstokes/intelpython3/bin/conda-env
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: root
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /Users/ijstokes/intelpython3/bin:/Users/ijstokes/intelpython3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

(root) ijstokes@0194-ijstokes bin $ cat /Users/ijstokes/intelpython3/.condarc
channels:
  - intel
  - defaults
```

**Comment by jakirkham** [comment]
Based on that description. Minimizing solver changes may be relevant. ( https://github.com/conda/conda/issues/5027 ) Also tracking requested packages may be relevant. ( https://github.com/conda/conda/issues/3968 )

**Comment by kalefranz** [comment]
I've also just been digging through solver-related code that looks really problematic for environments supporting multiple features.  That could be related.  I know there are open issues related to problems with multiple features, and now I'm not surprised.

**Comment by ijstokes** [comment]
@kalefranz FWIW in this instance, although both the `[intel]` and `[mkl]` features are tied to Intel as a company the traces above from me were happening in two completely distinct Anaconda installations, so I never had, TTBOMK, more than one feature "active" at a time in an environment or in the installation in general.

The issue was opened because of behavior I saw with my standard Anaconda and the use of `[nomkl]` (in order to benchmark non-MKL numpy).  The most recent comment today was from a fresh Intel Python installation which is Anaconda but put together by Intel and with the `[intel]` feature set from initial install time, and `intel` listed as the first/preferred package source channel.
