### ISSUE TITLE
Purpose of .conda directory

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#5388]
I'm trying to understand the purpose of the `.conda` directory. Is this something that is still needed for some purpose? If so, what is it? Also, assuming it is needed, is there a way to relocate this out of the home directory to somewhere else (perhaps `conda`'s install location)? Thanks.

**Comment by kalefranz** [comment]
The `~/.conda` directory is no longer used on Windows, only unix.  Conda's install location is not guaranteed to be user-writable.  Conda always needs at least one user-writable location for the package cache (`pkgs` directory) and the `envs` directory where new named environments are created.  The default location for these directories is `~/.conda` on unix, and on Windows we use [appdirs](https://github.com/ActiveState/appdirs).  The `~/.conda` directory has been used for years on unix for this purpose.

When conda's install location is user-writable, then that's the location chosen as "first writable" for these two directories.  When conda's install location is not writable by the current user, then conda uses the `~/.conda` directory as the writable location, but is still able to use the install location for a read-only package cache and named environments.  Compare output of `conda config --show` for the two different cases.

The locations of these directories can be overrode by configuration using the `envs_dirs` and `pkgs_dirs` configuration parameters, or `CONDA_ENVS_DIRS` and `CONDA_PKGS_DIRS` environment variables.

Given that the `~/.conda` directory has been used for this purpose for multiple years, moving it would be a major change that would require discussion and general community buy-in.  Moving it could end up confusing people or pissing them off if conda leaves GB worth of old packages around.

**Comment by jakirkham** [comment]
I see. Thanks for the insight.

Was mainly looking to see if we could move it somehow or remove it without harm. Not suggesting to change `conda`'s behavior in a breaking way.

We also saw an `environments.txt` file in there. Is that needed? What is the significance of it?

**Comment by kalefranz** [comment]
> Was mainly looking to see if we could move it somehow or remove it without harm.

You can actually, by overriding the `envs_dirs` and `pkgs_dirs` default values.

> We also saw an environments.txt file in there. Is that needed? What is the significance of it?

That one, I had no idea existed.  Turns out it does, and still does.  https://github.com/conda/conda/blob/4.3.21/conda/misc.py#L199  I don't think it's actually used anywhere though.  I'm guessing it was meant to be an environment manifest file, but never got fully baked.  Conda 4.4 is going to have a more structured json file for the same purpose, at `envs/catalog.json` in each `envs` directory.

**Comment by brechtm** [comment]
The `pkgs_dirs` config variable isn't recognized:

```
$ conda config --add pkgs_dirs /my/path
CondaValueError: Value error: key must be one of channels, disallow, create_default_packages, track_features, envs_dirs, default_channels, not 'pkgs_dirs'

$ conda config --set pkgs_dirs /my/path
CondaValueError: Value error: Error key must be one of always_softlink, add_anaconda_token, shortcuts, add_pip_as_python_dependency, binstar_upload, use_pip, add_binstar_token, always_copy, always_yes, client_ssl_cert, channel_alias, changeps1, channel_priority, show_channel_urls, update_dependencies, client_ssl_cert_key, allow_softlinks, default_python, anaconda_upload, offline, allow_other_channels, auto_update_conda, not pkgs_dirs
```

**Comment by kalefranz** [comment]
You can manually edit your `~/.condarc` file and it’ll be respected.

**Comment by MInner** [comment]
Is it possible to somehow disable this behavior or notify user that the default env folder is not writable and therefore conda is going to use `~/.conda` instead? On clusters home directories is often mounted over the network, are limited in size and have very slow io speed. On multiple occasions I figured out that for some reason all packages were installed in my home and because of that package installation took forever.

**Comment by diallobakary4** [comment]
@MInner  is it possible to move the ~/.conda  directory. 
my ~/.conda directory has reached the cluster allocated quota and would like to move it to a different directory.  And then define that new directory with:
`conda config --add pkgs_dirs`
