### ISSUE TITLE
conda install --revision x deleted rather than reverted

### ISSUE THREAD

**Issue by JamesOwers** [conda/conda#5435]
First time using revisions so may have misunderstood behaviour. However...

Wanted to undo an upgrade of a couple of packages (namely numpy and pandas). State at the start:

```
$ conda list --revisions
2017-01-11 13:23:00  (rev 0)
...
2017-03-07 10:52:22  (rev 3)
...
     numpy  {1.11.1 -> 1.12.0}
...
     pandas  {0.18.1 -> 0.19.2}
...
2017-05-03 14:27:31  (rev 5)
    +tqdm-4.11.2

2017-05-12 15:16:17  (rev 6)
     matplotlib  {2.0.0 -> 2.0.2}

2017-05-25 15:24:49  (rev 7)
     numpy  {1.12.0 -> 1.12.1}
     pandas  {0.19.2 -> 0.20.1}
```

so, I executed:

```
$ conda install --revision 6
Fetching package metadata ...........

Package plan for installation in environment /home/james/anaconda2/envs/mus:

The following packages will be REMOVED:

    numpy:  1.12.1-py27_0     
    pandas: 0.20.1-np112py27_0

Proceed ([y]/n)? y
```
I said yes to remove, as thought that would downgrade...but, state after:

```
$ conda list pandas
# packages in environment at /home/james/anaconda2/envs/mus:
#
$ conda list numpy
# packages in environment at /home/james/anaconda2/envs/mus:
#
gnumpy                    0.2                       <pip>
numpy                     1.12.0                    <pip>
numpydoc                  0.6.0                    py27_0  
$ conda list --revisions
2017-01-11 13:23:00  (rev 0)
...
2017-05-25 15:24:49  (rev 7)
     numpy  {1.12.0 -> 1.12.1}
     pandas  {0.19.2 -> 0.20.1}

2017-05-26 09:22:27  (rev 8)
    -numpy-1.12.1
    -pandas-0.20.1
```

You can see `pandas` and `numpy` are indeed removed and not, as I had expected, downgraded.

Is this expected behaviour?

conda info
===
```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : 2.1.15
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/james/anaconda2  (writable)
    default environment : /home/james/anaconda2/envs/mus
       envs directories : /home/james/anaconda2/envs
                          /home/james/.conda/envs
          package cache : /home/james/anaconda2/pkgs
                          /home/james/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/linux-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/james/.condarc
           offline mode : False
             user-agent : conda/4.3.18 requests/2.14.2 CPython/2.7.13 Linux/3.16.0-38-generic debian/jessie/sid glibc/2.19    
                UID:GID : 1000:1000
```

**Comment by dynamicsoar** [comment]
I met exactly the same problem today. After
`$ conda update anaconda`
I noticed matplotlib or pandas or like were updated with some drastic changes, which I don't want at the very moment. So I wanted to revert and... lost even the conda itself. I was using python 3 version on the OS X El Capitan.

I'm also a beginner and not sure if this was the expected behaviour, but probably not.

By the way, I found two posts which seem to be similar and might be related to this problem:
- https://groups.google.com/a/continuum.io/forum/#!msg/conda/fE3NOtSgbuM/SMo6UMdIBAAJ
- https://github.com/conda/conda/issues/4909

**Comment by zwn** [comment]
While trying to recover from a bad update of conda on #5036 I end up without any version conda :worried: 

So, how to get eaten up by a second bug while trying to recover from the first one.

**Comment by Andarin** [comment]
+1  

Tried to resolve a problem with cv2 (https://github.com/conda-forge/opencv-feedstock/issues/43#issuecomment-310668118), used revision for the first time, now everything disappeared - no conda, no pandas... See attachment for logs.

Nevertheless, Anaconda works like a charm 99% of the time, so thank you for your dedication !

**Comment by cbienpourtoi** [comment]
+1
I though it would revert to previous version, it removed packages including conda :(

**Comment by cbienpourtoi** [comment]
@zwn How did you recover from this? Did you reinstall all anaconda from scratch?

**Comment by NicWayand** [comment]
Same issue. I had to reinstall from scratch.

**Comment by zwn** [comment]
@cbienpourtoi Yes, reinstall.

**Comment by arita37** [comment]
same issue here, please solve it

**Comment by dwervin** [comment]
wow, what a big mess.  I just tried to revert back to a previous revision and now nothing.

**Comment by arita37** [comment]
This is a MAJOR Bug.

Can we try to put conda package in a safe zone (cannot be deleted / update is no destructive).



On 5 Aug 2017, at 15:22, dwervin <notifications@github.com> wrote:

wow, what a big mess. I just tried to revert back to a previous revision and now nothing.

―

**Comment by dwervin** [comment]
I does not appear that the Anaconda installer for windows will do a repair and it refuses to reinstall over the top since it already sees files there.  

This is a bad design.

**Comment by zhouyifan901205** [comment]
Same issue here, had to delete and install for downgrading a package.

**Comment by eskemojoe007** [comment]
Same issue.  Reverted using `conda install --revision ##` and removed all my packages and conda itself.

**Comment by pavoljuhas** [comment]
Here is a patch that seems to fix the `conda install --revision` bug for conda 4.3.24.
The `dists` variable is looped over twice in the `ensure_linked_actions`, but if it were a generator the second loop is empty.  This fix turns it to a tuple which iterates in the same way every time.

```patch
diff --git a/conda/plan.py b/conda/plan.py
index 306eaf61..b5bdb08b 100644
--- a/conda/plan.py
+++ b/conda/plan.py
@@ -805,7 +805,7 @@ def revert_actions(prefix, revision=-1, index=None):
     if state == curr:
         return {}
 
-    dists = (Dist(s) for s in state)
+    dists = tuple(Dist(s) for s in state)
     actions = ensure_linked_actions(dists, prefix)
     for dist in curr - state:
         add_unlink(actions, Dist(dist))
```

**Comment by arita37** [comment]
Thank you for the patch.

Isn't a way to put a mechanism so that conda package is protected from :
     deletetion.
     Roll Back if new conda version has issue.
(like storing into zip file the conda files at each install/update).


Because when conda is corrupted nothing can be done afterwards....

The only solution was to install miniconda somewhere and copy paste the 
files in the corrupted directory....





Pavol Juhas wrote:

**Comment by pavoljuhas** [comment]
> Isn't a way to put a mechanism so that conda package is protected from deletetion.

I checked the development version of conda and that one seems to have the `--revision` bug fixed. Hopefully this won't be happening in future releases.

> The only solution was to install miniconda somewhere and copy paste the files in the corrupted directory....

It is also possible to recover files from the `pkgs/` directory of your conda installation:

```sh
cd /to/anaconda/pkgs/conda-4.3.24-py27_0
rsync -avH --link-dest=$PWD ./ /to/anaconda/
```

This may however produce inconsistent package metadata so it should really be just an action of last-resort.

**Comment by arita37** [comment]
My experience with conda:

It gets regularly corrupted through
pip install or other packages or by conda itself.



If there is a mechanism to protect
from conda config to be deleted/
recovered from zip,
It would be bullet proof to any kind of future bug (unknown one) and also API breaks).

What would you think ?


To prevent this, I put myself a batch scheduler zipping Conda folder on a daily basis....
(Recovery is consistent).







On 23 Aug 2017, at 04:09, Pavol Juhas <notifications@github.com> wrote:

Isn't a way to put a mechanism so that conda package is protected from deletetion.

I checked the development version of conda and that one seems to have the --revision bug fixed. Hopefully this won't be happening in future releases.

The only solution was to install miniconda somewhere and copy paste the files in the corrupted directory....

It is also possible to recover files from the pkgs/ directory of your conda installation:

cd /to/anaconda/pkgs/conda-4.3.24-py27_0
rsync -avH --link-dest=$PWD ./ /to/anaconda/
This may however produce inconsistent package metadata so it should really be just an action of last-resort.

―

**Comment by greentreeys** [comment]
This is the third time this month that I have to reinstall anaconda from scratch because of this bug in the conda install revision command, which removed conda lib itself.  The install revision command just removes everything that is installed or updated recently, instead of revert back to the previous version. I should really stick a note on my computer from calling this disaster command.

**Comment by arita37** [comment]
Best solution:
  Implement a Roll Back on conda:
    Zip all the conda files.
    Install whatever update, packages.....

   If conda is corrupted, do command line:

   python RecoverRollBack.py AnacondaFolder









On 25 Aug 2017, at 11:53, greentreeys <notifications@github.com> wrote:

This is the third time this month that I have to reinstall anaconda from scratch because of this bug in the conda install revision command, which removed conda lib itself. The install revision command just removes everything that is installed or updated recently, instead of revert back to the previous version. I should really stick a note on my computer from calling this disaster command.

―

**Comment by cbienpourtoi** [comment]
Is there a way to avoid reinstalling Anaconda after this? How did you cope with it? Did you reinstall everyting? I'd like to avoid reinstalling all Anaconda, if possible (I have a complex installation with many different environments used by different people).

**Comment by arita37** [comment]
Best is daily disk backup of conda folder....

Safest solution I found...
until conda has bullet proof mechanism....






On 9 Oct 2017, at 18:43, Loïc Le Tiran <notifications@github.com> wrote:

Is there a way to avoid reinstalling Anaconda after this? How did you cope with it? Did you reinstall everyting? I'd like to avoid reinstalling all Anaconda, if possible (I have a complex installation with many different environments used by different people).

**Comment by chaunceychason** [comment]
just got hit with this bug. now instead of getting my work done I am trying to get conda reuploaded.

**Comment by kalefranz** [comment]
#6719 solves this issue. In the next 4.3 release
