### ISSUE TITLE
LookupError: unknown encoding: cp65001

### ISSUE THREAD

**Issue by hx2A** [conda/conda#5448]
I get an unexpected error creating a conda environment on my machine. The error message asked me to report the issue.

Traceback (most recent call last):
  File "C:\Users\Jim\Anaconda2\envs\datacourse\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Users\Jim\Anaconda2\envs\datacourse\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\Jim\Anaconda2\envs\datacourse\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\Jim\Anaconda2\envs\datacourse\lib\site-packages\pip\download.py", line 37, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "C:\Users\Jim\Anaconda2\envs\datacourse\lib\site-packages\pip\utils\ui.py", line 57, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "C:\Users\Jim\Anaconda2\envs\datacourse\lib\site-packages\pip\utils\ui.py", line 50, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
An unexpected error has occurred.

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\Jim\Anaconda2  (writable)
    default environment : C:\Users\Jim\Anaconda2
       envs directories : C:\Users\Jim\Anaconda2\envs
                          C:\Users\Jim\AppData\Local\conda\conda\envs
                          C:\Users\Jim\.conda\envs
          package cache : C:\Users\Jim\Anaconda2\pkgs
                          C:\Users\Jim\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393
          administrator : False

`$ C:\Users\Jim\Anaconda2\Scripts\conda-env-script.py create -f environment.yml`

    Traceback (most recent call last):
      File "C:\Users\Jim\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Jim\Anaconda2\lib\site-packages\conda_env\cli\main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "C:\Users\Jim\Anaconda2\lib\site-packages\conda_env\installers\pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "C:\Users\Jim\Anaconda2\lib\site-packages\conda_env\pip_util.py", line 32, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "C:\Users\Jim\Anaconda2\lib\subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    CalledProcessError: Command '[u'C:\\Users\\Jim\\Anaconda2\\envs\\datacourse\\python.exe', u'C:\\Users\\Jim\\Anaconda2\\envs\\datacourse\\Scripts\\pip-script.py', '-V']' returned non-zero exit status 1

**Comment by hx2A** [comment]
It seems I can fix this with this command first:

set PYTHONIOENCODING=UTF-8

Answer on stackoverflow. I'll go sit in the corner now.

**Comment by kalefranz** [comment]
That's supposed to be set for you in `activate.bat` [here](https://github.com/conda/conda/blob/4.3.21/shell/activate.bat#L6).  I'm not exactly sure what happened in your case.

**Comment by hx2A** [comment]
This error was when creating the environment, not later when activating it for the first time.

My machine is Windows 10. I can confirm that one of my students with Windows also had the same problem.

**Comment by kalefranz** [comment]
How are you first interacting with conda?  Are you using the "Anaconda Prompt" that automatically activates the root environment for you?  Or just using plain `cmd.exe`?  Or some other shell?

**Comment by hx2A** [comment]
From the plain Windows `cmd.exe` prompt I type `conda env create -f environment.yml`.

**Comment by kalefranz** [comment]
Ok that makes sense then.  If you've just got conda on PATH, you're not using the Anaconda Prompt, and not running `activate root` as a first step after opening `cmd.exe`, the conda activate script wouldn't have the opportunity to set `PYTHONIOENCODING` for you.

**Comment by hx2A** [comment]
I see! I will make a note of that for future classes.

**Comment by paknorton** [comment]
I am setting up a virtual environment on Windows 10 with the latest Anaconda (conda version : 4.3.21) and python 2.7 using an environment file and also ran into this problem. I did activate the root environment prior to creating the new environment. 

Looking at the environment variables in the root environment I noticed that PYTHONIOENCODING was missing. After manually setting this variable equal to the codepage currently used by the cmd shell (in this case it was 1252) I was able to successfully create the new environment. When I started up the new environment it threw the same codepage error (LookupError: unknown encoding: cp65001) until I manually set the PYTHONIOENCODING environment variable.

I took a look at the activate.bat script and noticed the PYTHONIOENCODING variable was not persisted to the interactive cmd shell environment. I added the following line at line 83 in activate.bat:
    @SET "PYTHONIOENCODING=%PYTHONIOENCODING%"

I closed down my virtual environments and restarted them and everything started working as expected. I then removed my new virtual environment and tried re-creating it from the root environment and it worked as expected. The newly created virtual environment worked without error.

Was persisting the PYTHONIOENCODING environment variable to the interactive shell inadvertently left out of the activate.bat script? Or is there a reason for not including it? Without this line in activate.bat I am unable to properly create or use python 2.7  virtual environments on Windows 10. I am writing instructions for non-technical users to perform this setup and I would prefer not to require them to edit the activate.bat script. At this point using python 3 for the virtual environment is not an option because one of the libraries that will be installed has not been updated to work correctly with python 3.

Any help/insight you could provide would be greatly appreciated.

**Comment by hx2A** [comment]
After installing Anaconda on Windows there is an Anaconda shell you can use. You should be able to find it in your Start menu. Does using that fix this problem? I think this special Anaconda shell is available on Windows specifically to set the necessary environment variables that do not get set using the CMD.exe prompt.

**Comment by paknorton** [comment]
I am using the Anaconda shell to start the root environment instead of executing cmd.exe directly. The activate.bat script has a section to persist certain environment variables for the shell, but for some reason the PYTHONIOENCODING variable was not included. Once I added code that the Anaconda environments started behaving correctly.
