### ISSUE TITLE
Commands to run inside/outside virtual environments

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [conda/conda#5514]
I don't have a clear understanding of what commands one is supposed to run inside and outside a virtual to maintain "everything" (e.g. my packages and the conda package manager) up-to-date.

For example, given that I _always_ work inside a virtual environment, which of the following commands am I supposed to run inside/outside of my virtual env?

* `conda update conda`
* `conda update conda-env`
* `conda update anaconda`
* `conda update -all`

Also are the versions of `conda` and `anaconda` supposed to match? For example, `conda -V` returns `conda 4.3.21`. Is it fair to say that this is also my current version of my anaconda installation?  When I do `anaconda -V` I get: anaconda Command line client (version 1.6.3)`, which is odd, because `anaconda` is currently on version `4.4.0`.

-----

I ask this question partly because I sometimes run into the problem below. If I try to update `anaconda` **within** a virtual environment (or simply do `conda update --all`) I get what you see below. If instead I try to do it outside, I simply get a message saying that `4.4.0` is already installed. 

I know `anaconda` is of course the package distribution, so in my mind it should only be installed/updated outside of the virtual environment, but I am surprised I was able to foot myself in the foot as I show below, unless I am missing something trivial here.

```
$ conda update anaconda
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/amelio/anaconda3/envs/py36:

The following packages will be UPDATED:

    anaconda: custom-py36_0 --> 4.4.0-np112py36_0

The following packages will be DOWNGRADED:

    ipython:  6.1.0-py36_0  --> 5.3.0-py36_0
    pyqt:     5.6.0-py36_2  --> 5.6.0-py36_1

Proceed ([y]/n)? n
```

**Comment by kalefranz** [comment]
More details on the anaconda package at https://github.com/ContinuumIO/anaconda-issues/issues/4298.  Having that issue resolved would address the root cause of your problems in the second half of your question.

Conda is the package manager.  So `conda update -n root conda` makes sure conda (the package manager) is up-to-date in your base environment.

Anaconda, and the `anaconda` metapackage, is a collection of the most-commonly used python packages for data scientists.  You should only have the `conda` package installed in your base environment.  The `anaconda` metepackage can be installed in any environments you create.
