### ISSUE TITLE
Install-time dependence genertion

### ISSUE THREAD

**Issue by msarahan** [conda/conda#5608]
@anton-malakhov commented on [Mon Jun 26 2017](https://github.com/conda/conda-build/issues/2125)

There is TBB module for Python in Intel Distro, it has the native part (the TBB run-time) and the Python part. We might want to decouple it into two packages accordingly and make interdependent, so whenever the `tbb` package installed, the `tbb4py` is installed as well. But somebody might actually say that they don't want the Python part if there is no Python in their environment. On the other hand, having Python counterparts is pretty important for us when these libraries are being installed along with the Python. Another example is OpenMP runtime which ideally needs some fixes/integration on the Python side when installed next to Python. Do you have some existing mechanism which would do that for me? Otherwise, please consider this as a feature request.

I could think of some triggers in meta.yaml, e.g.:
```
   - tbb4py # [python]
```
Or/and some script executed at install time which outputs additional dependencies as necessary:
```
requirements:
  install-time-script: python install.py --list-requirements
```

Another usage for this thing is to optimize size of packages to install for particular platforms. E.g. install-time dependency can decide whether to install `SSE4.2`, `AVX2`, or `AVX-512` runtime for a package.

Triggers might be preferable in order to support scenarios when tbb/openmp are installed ahead of python, and when the python is added to the environment, the triggers would schedule Python modules to be installed

**Comment by msarahan** [comment]
This needs to start on the conda side of things.  Call it "conditional installation" or something.  When conda supports the notion of it, we can talk about how conda-build should provide metadata in packages.

**Comment by msarahan** [comment]
cc @anton-malakhov

**Comment by anton-malakhov** [comment]
Thanks for considering this!

**Comment by anton-malakhov** [comment]
Do you plan implementing it in any near enough future? My struggles with separation of tbb package into multiple component packages become actual and with specific deadline. Thanks!

**Comment by msarahan** [comment]
@kalefranz run_constrained requires conda 4.4, right?  @anton-malakhov are you able to test conda 4.4 from the conda-canary channel?

With conda 4.4 still in prerelease, I think it would probably be unwise for you to depend too much on this feature being available.  Is there another way to achieve what you need to do?  Maybe for now you just need to install everything.  It's not nice, but having things working is better than having things nice.

**Comment by anton-malakhov** [comment]
Well, it might be possible to work it around or just document as a bug (Todd might say more specifically). The deadline is not that close yet, we have a month or two in order to move to new conda-build. I also see that using this section does not result in any error while generating empty dependence `  "depends": [],`. I'm not sure how solver would select between two _py27 _py36 versions though without requiring python in the environment..

**Comment by kalefranz** [comment]
> run_constrained requires conda 4.4, right?

Yes, it does. Conda 4.3 just doesn't see it; doesn't know to look.

**Comment by anton-malakhov** [comment]
On the second thought, it looks like `run_constrained` will not help me implementing ` - tbb4py [python]`. Because even if `tbb4py` does not have strong run dependency on python, there will still be multiple `tbb4py` packages for different python versions, which will prevent solver from silently settling on one of them if there is no python in the environment. Is it correct assumption?
