### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict:

### ISSUE THREAD

**Issue by ZhengZou353** [conda/conda#5697]
I tried to install vnpy, during one step, in CMD it shows

conda install -c quantopian ta-lib=0.4.9

UnsatisfiableError: The following specifications were found to be in conflict:
-matplotlib
-navigator -updater 
-ta-lib 0.4.9*
Use conda info <package> to see the dependencies for each package.

Does anyone know what shall I do to fix this?

I typed conda info ta-lib, it shows no such package. But I have the other 2 packages. Don't understand.

**Comment by dukeyc138** [comment]
I have the same problem

**Comment by fxuehit** [comment]
anyone got solution on this

**Comment by hiericzhu** [comment]
I have the same problem, I spent a day trying to solve this silly problem!!! 
## And I'm a fresh-hand in Anaconda -I start to use it this Monday since I want to learn vnpy :)  So please correct me if I made mistake, or you have better a way!

My understanding is below (I use Anaconda winows32 for py2.7):
\>conda` search ta-lib -c quantopian
Fetching package metadata ...............
ta-lib                       0.4.8                np18py27_0  quantopian
                             0.4.9               np110py27_0  quantopian
                             0.4.9               np110py34_0  quantopian
                             0.4.9                np19py27_0  quantopian
                             0.4.9                np19py34_0  quantopian
**This means ta-lib-0.4.9 needs numpy 1.10, or 1.9 for py2.7 (I don't care py3.x)**

Let's see why we got conflict:
\>conda list matplotlib
\# packages in environment at E:\Anaconda2:
\#
matplotlib                2.0.2               np112py27_0    defaults
**This means the matplotlib-2.0.2 needs  numpy 1.12**

\>conda list numpy
**My numpy is 1.12.1 installed default.**

**It seems Anaconda check the pkgs dependency striclty in version, So we have to downgrade the numpy to 1.10.x**

Fixed the problem as below:
Step1, remove the numpy:
\> conda remove numpy
Lots of pkgs depends on numpy will be removed.

Step2 install numpy 1.10.1
\> conda install numpy=1.10.1 -v
\> conda list numpy

Step3 install ta-lib
\> conda install -c quantopian ta-lib=0.4.9 -v
\> conda list ta-lib

Step4 install pkgs removed by step1  if necessary
\> conda install matplotlib=1.5.1 -v
## At Step4, CAN NOT install the latest version by default, you need to install the older version which aligns with numpy-1.10.1 (Yes, now it is something like a 'baseline', stupid anaconda), I'm crazy, I need to find which version is compatible for each pkg. So if you have better way, please tell me.

**Comment by kalefranz** [comment]
Use conda environments when you get conflicts.

    conda create -n myenv -c quantopian ta-lib=0.4.9
    conda activate myenv
