### ISSUE TITLE
conda install --file conditionals

### ISSUE THREAD

**Issue by joachimwolff** [conda/conda#5699]
Is it possible to define in a `requirements` file which I can use for a `conda install --file requirements` conditionals like 'Install dependency foo only if python = 2.7'? Something like this is already possible in a recipe file (`# [py27] `) and would be useful during the development process of a new software. The issue is that some packages are already part of Python 3.X but they need to be installed as a separate package in Python 2.7. Cover this with two `requirement` files is leading to redundancies what is always bad. 

Thanks for considering!

**Comment by tyler-thetyrant** [comment]
We don't have the `pip install -r requirements.txt` equivalent in conda because conda takes care all the requirements when installing a package. For example, when installing scikit-learn, conda installs [all the dependency](https://github.com/conda-forge/scikit-learn-feedstock/blob/master/recipe/meta.yaml#L24) for scikit-learn so that the package works properly without breaking your system/environment.

**Comment by joachimwolff** [comment]
@tyler-thetyrant 
Thanks for your answer but I don't think we talk about the same thing. I am talking about a way to define dependencies which are only need for a specific python version. E.g.:
```
numpy
scipy
configparser # [py27]
```

This would make sense because configparser is built-in for python 3.5 but not for python 2.7. Nothing will break here...
