### ISSUE TITLE
activate and deactivate script paths on Windows

### ISSUE THREAD

**Issue by cmbant** [conda/conda#5731]
When changing environments the activate and deactivate scripts generated on Windows do not include the path in quotes, so you have things like

    #!/usr/bin/env bash 
    source C:\Users\My Name\Anaconda2\Scripts\activate "$@"

and neither command works. It works OK using the .bat files, but not used "source activate" etc when used from e.g. MingW.

**Comment by mingwandroid** [comment]
You are not supposed to install `Anaconda` or `Miniconda` into a path with spaces (on any OS), also, those slashes will act as escape characters anyway. Running `conda` like this is currently not *really* supported.

However @kalefranz does have interest in making this stuff work so pinging him.

**Comment by cmbant** [comment]
OK thanks, though actually everything else seems to work just fine.

**Comment by mingwandroid** [comment]
Yes, it works just fine until it doesn't. Since Anaconda Distribution provides a large amount of software you may eventually install something that doesn't handle spaces correctly. GNU make is one example.

**Comment by kalefranz** [comment]
The contents of `activate.d` and `deactivate.d` scripts is really a packaging issue.  I think over time we've been doing better with proper quoting in these shell scripts.

In general, issue https://github.com/conda/conda/issues/6820 should give conda more control over stuff like this.  So that we can fix these problems with a code change to conda rather than changes that need to be made across a bunch of already-built packages.
