### ISSUE TITLE
Conda installs wrong version of a package when multiple builds with same build number but different hash exist

### ISSUE THREAD

**Issue by kuepe-sl** [conda/conda#5770]
Due to changed dependencies, one of our packages was rebuilt.
So now I have two packages with the same version/build number, but with different conda hashes. (The old package has hash d003050, the new one's hash is 5335936.)

When I try to install the package now, it will install the *old* version (hash d003050), because conda seems to sort packages with same version/build number by their file name and/or hash.

/cc @msarahan

**Comment by msarahan** [comment]
I think this is covered by https://github.com/conda/conda/issues/5708

I owe @kalefranz a couple of test packages for his fix. Thanks for the
reminder.

**Comment by msarahan** [comment]
@kalefranz my proposed test packages are the two following index.json files:

```
{
  "arch": null,
  "build": "pyh1234567_0",
  "build_number": 0,
  "depends": [
    "python"
  ],
  "name": "test_timestamp_sort",
  "noarch": "python",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 2,
  "version": "1.0"
}
```

```
{
  "arch": null,
  "build": "pyh7654321_0",
  "build_number": 0,
  "depends": [
    "python"
  ],
  "name": "test_timestamp_sort",
  "noarch": "python",
  "platform": null,
  "subdir": "noarch",
  "timestamp": 1,
  "version": "1.0"
}
```

There are two test cases:

``conda install test_timestamp_sort`` should pick pyh1234567_0, because the timestamp is newer, although it is lexicographically sorted earlier.  This test should fail before your fix in https://github.com/conda/conda/pull/5733
``conda install test_timestamp_sort=1.0=pyh7654321_0`` should pick pyh7654321_0 because it is explicitly specified.

Does this cover the situation in your opinion?  If so, where should these test cases be written?  I am concerned though, because I can't reproduce the failure of the first test on conda 4.3.23.

I have test packages up on the conda-test anaconda.org channel: https://anaconda.org/conda-test/test_timestamp_sort

**Comment by kuepe-sl** [comment]
I can confirm that these test cases cover our issue and that #5733 indeed fixes it.

**Comment by kalefranz** [comment]
I believe we've resolved this issue and it can now be closed.
