### ISSUE TITLE
activate leaving the root environment on the PATH

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#5806]
```
~$ echo $PATH
/Users/aaronmeurer/anaconda3/bin:...
~$ source activate test
test~$ echo $PATH
/Users/aaronmeurer/anaconda3/envs/test/bin:/Users/aaronmeurer/anaconda3/bin:...
```

I thought maybe this was because I have a symlink `~/anaconda` pointing to `~/anaconda3`, which has caused this issue in the past, but I removed the symlink and it still happens.  

```
test~$conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : 3.0.3
         python version : 3.5.3.final.0
       requests version : 2.18.1
       root environment : /Users/aaronmeurer/anaconda3  (writable)
    default environment : /Users/aaronmeurer/anaconda3/envs/test
       envs directories : /Users/aaronmeurer/anaconda3/envs
                          /Users/aaronmeurer/.conda/envs
          package cache : /Users/aaronmeurer/anaconda3/pkgs
                          /Users/aaronmeurer/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/asmeurer/osx-64
                          https://conda.anaconda.org/asmeurer/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/pyne/osx-64
                          https://conda.anaconda.org/pyne/noarch
            config file : /Users/aaronmeurer/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.24 requests/2.18.1 CPython/3.5.3 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
```

**Comment by wulmer** [comment]
This issue was already discussed in https://github.com/conda/conda/pull/3175#issuecomment-261211663 but I lost track of that discussion and only noticed later after the PR got merged that the root env actually always stays on the PATH. I am still against this behaviour as it is totally confusing for the the user in case he runs `ipython` in an activated venv which doesn't have `ipython` installed. In that case, `ipython` is used from the root env where other packages (for which the venv had been created) are missing.
However I fear there is no way back, ...

**Comment by asmeurer** [comment]
This used to be the behavior a long time ago and we changed it because it's wrong (I'm sure we could dig up the discussion). 

I don't see why there can't be a way back. The behavior was broken (a long time ago), then it got fixed. Now it is broken again, and it can get fixed again.

**Comment by nouiz** [comment]
We also got hit by this problem. I also think we should not keep the root bin in the path when we activate an env.

**Comment by kalefranz** [comment]
This has been the behavior at least since #1727 included in conda 4.1.  I guess it's shifted back-and-forth over time. Conda 4.4 maintains the behavior, with a default value for the configuration parameter `max_shlvl` of `2`.  Since this is a configuration parameter, it can certainly be set to `1`.

Conda 4.4 does implement environment stacking for the PATH environment variable (although not others, including PYTHONPATH).  That decision was made to maintain behavior unix users have had for at least the last couple years.  As a future enhancement, we should implement an alternate mode where environments are not stacked on PATH, and instead only one environment is active at a time, but we still have a CONDA_SHLVL stacking that can be pushed and popped.

**Comment by asmeurer** [comment]
Good lord I hope you're not saying that activate sets PYTHONPATH now. 

I don't think environment stacking is a good idea (I think I've outlined my reasons on another issue a long time ago). The main problem being that environments don't inherently "mix" with one another. The main reason why the root environment was always removed is so that you don't accidentally run a command from root because you forgot to install it in the environment (usually `ipython`). That sort of thing in general is why stacking doesn't work IMO. 

If you want to do stacking, you should just merge all packages from the stacked environments into a new environment. Conda makes this trivial, so long as the packages are compatible with one another (which seems like a fine prerequisite to me). This can be coded in a high level way. 

I'm curious, who is using "stacking". Even if you are able to make it work somehow, it seems like it would be an advanced feature. The most common use case is a single environment at a time. In that case, the "I activated my `python2` environment but `ipython` still starts Python 3" user error (because ipython is still from `root`) seems like it would be a *very* common misstep, orders of magnitude more common than the number of people using "stacking".

**Comment by asmeurer** [comment]
Also what is `max_shlvl`? It doesn't show up when I search the docs site.

**Comment by kalefranz** [comment]
> Good lord I hope you're not saying that activate sets PYTHONPATH now.

No, it doesn't.

> Also what is `max_shlvl`? It doesn't show up when I search the docs site. 

`conda config --describe max_shlvl`

I thought I had long ago at least created an issue. Can't track it down though.  So https://github.com/conda/conda-docs/issues/557

**Comment by asmeurer** [comment]
Why is it shlvl? Are you doing the subshell thing?

**Comment by msarahan** [comment]
conda-build is one thing that uses the stacking.  We separate build and host environments, and we activate both of them (for the sake of setting env vars).  Prior to the availability of this functionality, we hacked it by resetting conda's env var, so that it though it wasn't activated yet.

I don't think the stacking is in common use.

**Comment by choldgraf** [comment]
My two cents as a user: stacking environments is *extremely confusing* for interfaces like Jupyter Notebook / Lab. People often do the following:

1. Install conda, which comes with the notebook/lab pre-installed
2. Create an environment, forgetting to explicitly install the notebook/lab in that environment.

**What happens**
When they type `jupyter notebook` the notebook loads just fine, but *it is linked against a different environment*. This means some packages may be installed, others not, others the wrong version. this confuses the heck out of people because they say "hey, I know my packages are installed, why doesn't the notebook say they're installed???"

**What should happen** (IMO)
Users type `jupyter notebook` and they get an error saying it isn't installed. They install it, and frustration is minimized.

to quote a relative bit from the zen of python:

```
Explicit is better than implicit.
Simple is better than complex.
Flat is better than nested.
```

I'd argue that having environments purely separable and non-nested is _more explicit, simpler, and flatter_. I think that should be the default behavior of conda.

**Comment by mingwandroid** [comment]
I would also prefer that stacking be disabled by default and expert users (like `conda-build`) should enable it when necessary.

**Comment by ckaros** [comment]
Is there a way to disable this behavior in windows? Still not clear to me.

**Comment by mingwandroid** [comment]
@ckaros, did you run: `conda config --describe max_shlvl`

**Comment by ckaros** [comment]
Yes, this is the response I get

```conda-script.py: error: unrecognized arguments: max_shlvl```

**Comment by mingwandroid** [comment]
conda update conda then please.

**Comment by ckaros** [comment]
so running conda install conda=4.5 solved the unrecognized arguments error (for some reason  ```conda update conda ``` just wants to install 4.3.34).

However, even after setting max_shlvl to 1 (verified with ```conda config --show``` and looking at my .condarc file), I still see references to the miniconda3 root env in my path and I can still import packages that are not installed in the active env but exist in the base env.

It should be noted that although my .condarc file and  ```conda config --show``` show max_shlvl=1,  ```conda config --describe max_shlvl``` produces the following:
 ```
# max_shlvl (int)
#   The maximum number of stacked active conda environments.
#
# max_shlvl: 2
 ```

**Comment by kalefranz** [comment]
See https://github.com/conda/conda/issues/2502#issuecomment-395490219, #7194, and related.
