### ISSUE TITLE
Change default value for 'allow_softlinks' from True to False

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5834]
The `allow_softlinks` configuration parameter can be dangerous.  Softlinks into prefixes directly from the package cache will often lead to environment corruption.  It was an oversight that the default value for `allow_softlinks` is set to `True`.  In conda 4.4, we should definitely change the default value to `False`.  We should also consider it even for the next 4.3.x release.

**Comment by bkreider** [comment]
Can you expand on this?  It seems like a major change since this is the fall back behavior for everyone that is using multiple filesystems.  Luckily i spotted this change, because I've been telling customers for a LONG time about how conda uses symlinks (and the relationship to speed and eating up inodes).

**Comment by kalefranz** [comment]
There's discussion littered all around with references back to this ticket I think. There's also a lot of discussion in https://github.com/ContinuumIO/aen-issues/issues/949, which is unfortunately a private repo, but you have access to it @bkreider
