### ISSUE TITLE
Deprecate 'conda env attach' and 'conda env upload'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5842]
These two commands are outside the scope and spirit of conda.  The first requires knowledge of a "notebook," which is not one of conda's fundamental units of work.  The second requires knowledge of the Anaconda API, which is the purview of anaconda-client, not conda.

Deprecation warnings will be given in conda 4.4, with the command scheduled for removal in conda 4.5.

**Comment by jbednar** [comment]
Could the functionality from `conda env attach` be made available as a separate command, not part of conda, that uses the public interface of conda to do the same thing?  Could be part of jupyter, or just some standalone utility? The ability to have a notebook store its environment isn't something that I've used often, but it does seem like an important way a notebook could be made reproducible.

**Comment by rjshaver** [comment]
Since these commands are deprecated, the documentation and tutorials should provide a link or comment to use the appropriate anaconda command.  I was just going through the Anaconda tutorials and found the 'conda env upload' command listed as the way to upload to the Anaconda Cloud web site.  Could someone look into this and request the change to be made on the Anaconda web site tutorials/documentation?  I would do it, but I am just trying to learn here.  Thanks.
