### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict:

### ISSUE THREAD

**Issue by tobiashofmann88** [conda/conda#5903]
It seems that conda packages, which used to install without problems are now causing this error (on my mac pro):

in:
```
$ conda install -c bioconda secapr
```
out:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - secapr -> cogent -> python 2.7* -> openssl 1.0.1*
Use "conda info <package>" to see the dependencies for each package.

```
I understand that it has something to do with different versions of conda packages being called by different dependencies (I found similar issues in this repo, but the solutions require manual dependency alterations by the users), but in the past (e.g. two weeks ago) this used to work without problems. It would be great to find a fix on the developer side rather than having the user solve package specifications. What can I do to update secapr in order to avoid this issue?
Btw, I got a different error message when trying to install this package on a linux system:

in:
```
$ conda install -c bioconda secapr
```
out:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - bottleneck
  - phyluce
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by kalefranz** [comment]
Unlink pip, conda won't let you install packages into the same environment that it knows to be incompatible. Pip will go ahead and install things for you, only for you to find a couple days or weeks later that your environment is incredibly broken, and by that time, there's no real way to connect the problem back to the root cause.

For problems with satisfiability, by far the easiest way is to create a new environment that specific to the individual task.

In your case, `conda create -n working-env -c bioconda secapr`
