### ISSUE TITLE
Concurrent writes to the same package cache

### ISSUE THREAD

**Issue by eferreira** [conda/conda#5997]
This issue concerns this bit from the release notes for 4.3.0:

> Locking has never been fully effective in conda, and it often created a false sense of security. In this release, multi-user package cache support has been implemented for improved safety by hard-linking packages in read-only caches to the user's primary user package cache. Still, users are cautioned that undefined behavior can result when conda is running in multiple process and operating on the same package caches and/or environments.

Now, I understand why concurrent writes to the same environment are essentially impossible to support. There's just too many ways in which an environment can be mutated. But package caches are another story. My understanding is that the only way they are mutated is that tarballs get downloaded/copied into them, and then those tarballs get unpacked. (And there's also conda clean, I guess). And we should be able to assume that if two processes are trying to download/unpack a particular package at the same time, neither of them care which one of the two "succeeds". So it seems like it should be quite feasible to use atomic filesystem operations to fully support concurrent writes to the same package cache as a guaranteed feature. The basic approach would be to unpack the tarball under a temporary name, then do an os.rename to the final name, which is guaranteed to fail if the destination already exists. So the first process to create the directory would "win", which is exactly what we want because it guarantees that no one creates hardlinks to a package which is then overwritten by another process unpacking the same package.

Is conda already doing anything like this? If not, are there any major difficulties with this sort of thing that I'm missing?

For context, my team is considering a multi-user setup where users all have their own environments (and perhaps where temporary environments are routinely created and torn down on the fly), but we are hoping to keep disk usage under control by having a global package cache that is writable to everyone. But if a shared writable package cache is undefined behavior, then clearly this sort of setup would not work.

**Comment by kalefranz** [comment]
* https://github.com/conda/conda/pull/5937 Is potentially relevant here, and likely coming in conda 4.4. Conda 4.3 and prior has a *ton* of churn in package caches, especially when switching between "full ecosystem" channels like `defaults` and `conda-forge`. That churn makes the global package cache concept pretty much unworkable. The #5937 PR should at least make the situation workable, and if we add an additional hash to file names as proposed in a comment, make the shared package cache concept solid (maybe with some of the safeguards you've proposed).

* If you're worried about disk space and want to use a shared package cache, *make sure* the package cache is on the same device mount as where your environments will be, so that hardlinks can be created between the cache and the environment. (It's obvious for people who know the technical details here, but worth repeating for those who don't.)

* Pre-link scripts mutate a package after it's extracted into a package cache, but before the package is linked into an environment. They are an abomination and should be outlawed completely. Actually I could add aconfiguration parameter that prevents them from running. The most noticeable hit would be the old-style python noarch packages.

* We'll be adding back some type of locking to prevent multiple conda processes from operating on an environment at the same time. I think it's necessary, and with changes in conda 4.4 it's also now technically possible to do correctly. Operating on an environment means you have write permissions to it, so locking the environment shouldn't be a problem. No so for the general case of package caches, which by design are allowed to be read-only. I don't know of any good/feasible technical way to lock a tree of files that are read-only. Other than having a separate, long-running agent process to coordinate the lock.

**Comment by eferreira** [comment]
Yeah, #5937 looks pretty relevant. In an ideal world, there would be some way of referring to a package which is globally unique and immutable (like a hash of the content). Then the package cache could offer some very nice guarantees: if the package you want is there already, you can be sure that it's fine to use it; and if it's not, multiple processes can try creating it at the same time and it doesn't matter which one gets there first.

More generally, this idea of a unique, immutable naming scheme for packages would be really valuable for reproducibility. You could get a unique, immutable description for an environment by listing out all its installed packages. And then from that description you could reliably reproduce the environment anywhere that has access to the same set of channels.

It seems like conda isn't that far from offering this sort of functionality as is. There's just the problem that multiple channels can offer the same package but with different contents. (And maybe a single channel can also republish the same package with different contents, I guess?)

Actually, now that I think about it more, maybe it's not that infeasible to just use the package md5 as the unique naming scheme. Channels already publish the md5 of all their packages, right? It should be cheap to map an md5 to the corresponding package given that it exists in any of our known channels, making it possible to do things like passing the md5 of a package to conda install. You might lose some user-friendliness when browsing the package cache, but that seems like a minor annoyance (most of the time, a simple find command will be enough to locate the package directory that you're looking for). But the determinism and reproducibility that you would get in return is, in my opinion, a really valuable feature in an environment manager. At least as far as my use case is concerned, I would definitely take that trade-off.

**Comment by kalefranz** [comment]
Check out the changelog for conda 4.4. I think there's mention in there about referring to packages *only* by md5.

**Comment by eferreira** [comment]
Oh, cool. Yeah, I think what I want then really just comes down to what you said in the comment on #5937: use the md5 hash of the package as part of the filepath within the package cache. And then, as I said, make use of atomic directory renames to deal with concurrent writes. Even 'conda clean' can be made atomic by having it first rename the directory to a temporary name, then proceed in deleting the files inside it. This ensures that the package cache is never in an inconsistent state at any instant of time. And if conda clean removes a package while another process is in the middle of linking the package to an environment, that other process can detect that this happened and go back and redownload the same package again.

**Comment by kalefranz** [comment]
Tracking locking via https://github.com/conda/conda/issues/5997

**Comment by wimvanleuven-kbc** [comment]
Doesn't this break the use of conda on a continuous integration platform? 

Should we simply disable caching? Or what are best practices here to configure conda to work properly?

**Comment by jeremyjliu** [comment]
@wimvanleuven-kbc for a similar use case, I've disabled package cache by having a per-environment package cache directory and then removing the per-env directory after.

**Comment by wimvanleuven-kbc** [comment]
Tnx Jeremyjliu for the hint!

In the mean time, we are doing the same thing, but it also defeats the purpose of having a cache. We do pyspark development, so building the env with cache already takes to 5 minutes or much more in our build cycle.

**Comment by wimvanleuven-kbc** [comment]
We adjusted some of our builds to use a dedicated cache, but we are still seeing those errors where linking the files in the environment fail with errors like 'file already exists', etc 

Digging deeper ...
