### ISSUE TITLE
Sparse local package repo 

### ISSUE THREAD

**Issue by mahmoud** [conda/conda#6002]
As I mentioned in #5983 and as seems to be alluded to in #5889, the ability to create a sparse local package repo that could be passed to `conda install` as an option, especially in conjunction with `--offline`, would be an excellent feature I'd like to see added.

A clarifying use case: right now we have a base container image that our applications build on top of. The different applications have different requirements, but we'd like to put a significant subset of packages into the base image and cut down on build time length and variability (as well as reduce our load on anaconda.org infrastructure ;) ).

We do this right now with pip-installed packages right now through having a "wheelhouse", a flat directory of wheels, combined with usage of the [`--find-links` pip flag](https://pip.pypa.io/en/stable/reference/pip_wheel/#find-links). 

Being able to do the equivalent for our conda-installed would be amazing. Especially if we can specify the metadata file and avoid the minute or so spent downloading and resolving dependencies, for even the simpler conda package installs.

Let me know if there's any clarification I can provide, and thanks again!

**Comment by kalefranz** [comment]
Check out #5933 and #5937.  With another tweak or two this might get pretty darn close.  The proposal is effectively turning a package cache into a "view" of channels.  In fact, this might be exactly your proposal here, just in different words.

**Comment by kalefranz** [comment]
I think you might already do this in conda 4.3, if you have a populated package cache you want to use.  There's an undocumented `--unknown` flag that reads in contents of package caches and makes those packages available to the solver.  Same for the `--offline` flag, although for the `--offline` flag, you won't be able to go out and get any new packages.

If that `--unknown` flag works for you right now, don't count on it not changing names at some point, especially since it's [not documented](https://github.com/conda/conda/blob/4.3.x/conda/cli/common.py#L204) even in the CLI help.  I'd probably rename it to something like `--use-cache` when we remove that SUPPRESS.

**Comment by kalefranz** [comment]
Another issue this tangentially raises is just how dog slow bz2 decompression is.  Discussion on introducing alternate compression algorithms at https://github.com/conda/conda/issues/4861

**Comment by mahmoud** [comment]
Very interesting! I'll try it out :) I hadn't suspected bz2, but I'll pay closer attention going forward.
