### ISSUE TITLE
Unsatisfiable Errors

### ISSUE THREAD

**Issue by foreignsand** [conda/conda#6038]
I get the following error when I try to update anaconda:

$ conda update anaconda
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - argcomplete -> argparse -> python 2.6*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

and the following when I try to update --all:

$ conda update --all
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - h5py
  - opencv
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

I am not super savvy and have tried a variety of fixes that were recommended on previous posts [creating a new conda environment, updating] and none have worked.

Many thanks!

**Comment by pzwang** [comment]
What version of conda are you on?  Did you try doing a "conda update conda" first?

**Comment by kalefranz** [comment]
Unsatisfiable errors mean you are trying to put packages into an environment that are inconsistent with that environment.  In this case, it looks like you have an `argparse` package in your environment, which is not compatible with python 3.6 (since argparse is *part* of python 3.6).

The likely solution is either to remove argparse, then proceed with your update.  Another option is to start using conda environments, where fewer and more purpose-specific packages mean a less likely chance for conflicts.
