### ISSUE TITLE
conda update --all does not ignore anaconda version

### ISSUE THREAD

**Issue by zhiruiwang** [conda/conda#6066]
In my previous understanding and practice, the `conda update anaconda` will update the anaconda to the newest version, and if I installed some new version of packages, they will be downgraded to the version that matches the anaconda version. On the other hand, `conda update --all` will ignore anaconda version, install the newest version of all other packages, and turn anaconda version into `custom`. That was how I updated packages previously. 
However, when I update anaconda to `5.0`, the `conda update --all` works the same as the `conda update anaconda`, it will turn my `custom` anaconda into `5.0`, and downgrade all my other packages. This happens both on my windows and osx laptop. I wonder whether it is a bug, or a new feature?

**Comment by geiragustsson** [comment]
Wondering if this is my issue. I did an `conda update --all` yesterday and my Spyder wouldn't start. After running `conda update anaconda` it would start. Spyder then notified my about an updated version of Spyder, so I **then** did a `conda update -all`. And again, it won't start.

**Comment by saaketp** [comment]
I think this is started occurring because there is no "anaconda-custom" in the new "[main](https://repo.continuum.io/pkgs/main/win-64/)" channel and the main channel is the highest priority channel. So anaconda-5.0.0 from main is an upgrade from anaconda-custom from "[free](https://repo.continuum.io/pkgs/free/win-64/)". This should be fixed by adding those custom packages in main too.

As a workaround, for conda 4.3.x (the current latest in anaconda default channels) we could modify [install.py](https://github.com/conda/conda/blob/4.3.x/conda/cli/install.py) in conda.cli at the line where action_set is created by calling install_actions_list (currently line 257). Putting specs.remove('anaconda') before that line ignores anaconda and updates everything else. Worked for me without any noticeable problems. The "master" version code is a bit different. Can't say just by looking if it is fixed in that.

**Comment by zhiruiwang** [comment]
@saaketp Thank you for your sharing. I wonder whether the maintainers could fix this problem.

**Comment by mingwandroid** [comment]
We will fix this oversight. Thanks for the detailed analysis.

**Comment by saaketp** [comment]
Thanks, this seems to be fixed now, atleast on Windows.

**Comment by mingwandroid** [comment]
This is fixed globally.

**Comment by zhiruiwang** [comment]
@mingwandroid After I upgrade conda to 4.3.31, this issue comes back again.

**Comment by MattJEM** [comment]
I am having this issue after updating to 4.4.1 (on the anaconda channel). It asks to wipe my custom anaconda version for 5.0.1 and downgrade the bulk of my packages.

**Comment by kalefranz** [comment]
related to: https://github.com/ContinuumIO/anaconda-issues/issues/4298

**Comment by zhiruiwang** [comment]
@kalefranz Thank you kale, it is really a good proposal. And the issue fixed after updating conda to 4.4.3.
