### ISSUE TITLE
How to select a framework version of Python using conda?

### ISSUE THREAD

**Issue by jaanli** [conda/conda#607]
I'm running into issues trying to use a wx-based GUI - looks like I need to select a framework version of python (running OS X Mavericks 10.9.2)

```
Python 2.7.6 |Anaconda 1.9.1 (x86_64)| (default, Jan 10 2014, 11:23:15)
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> app = wx.App()
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.
```

A solution for virtualenv is here: http://wiki.wxpython.org/wxPythonVirtualenvOnMac

and involves putting this script in the environment's bin folder:

``` #!/bin/bash

# what real Python executable to use
PYVER=2.7
PYTHON=/Library/Frameworks/Python.framework/Versions/$PYVER/bin/python$PYVER

# find the root of the virtualenv, it should be the parent of the dir this script is in
ENV=`$PYTHON -c "import os; print os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..'))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV 
exec $PYTHON "$@"
```

Thanks!

**Comment by ezatterin** [comment]
how did you solve this exactly? I am having the same problem.

**Comment by kayhan-batmanghelich** [comment]
I have the issue, @altosaar , @asmeurer could you please explain how to resolve this?

**Comment by SBelkaid** [comment]
@kayhan-batmanghelich When trying to use matplotlib in a virtual environment I changed my bashrc file as suggested [here](http://matplotlib.org/faq/virtualenv_faq.html).  To use the anaconda version of ipython you could change the path to where ipython is installed. Which is usually ~/anaconda/bin/ipython
So instead of: 

`function frameworkpython {
    if [[ ! -z "$VIRTUAL_ENV" ]]; then
        PYTHONHOME=$VIRTUAL_ENV /usr/local/bin/python "$@"
    else
        /usr/local/bin/python "$@"
    fi
}`

do the following:

`function frameworkpython {
    if [[ ! -z "$VIRTUAL_ENV" ]]; then
        PYTHONHOME=$VIRTUAL_ENV ~/anaconda/bin/ipython "$@"
    else
        ~/anaconda/bin/ipython "$@"
    fi
}`

As stated by the FAQ this is a better way to use a "framework" python in virtualenvs, this way you don't have to change it for every virtualenv seperately.

**Comment by generatz** [comment]
@asmeurer: Thanks.  pythonw did the trick for me after I installed python 2.7.14 using miniconda (conda create -n py27 python=2.7 ;  source activate py27).
