### ISSUE TITLE
no Anaconda packages for FreeBSD

### ISSUE THREAD

**Issue by zaxtax** [conda/conda#61]
The Linux package uses dynamically linked ELF binaries. Is there anyway to adapt the existing releases to run on a FreeBSD without linux-compat?

**Comment by vnitinv** [comment]
@ilanschnell link http://continuum.io/blog/raspberry say

"No articles have been added to this blog yet."

**Comment by brycepg** [comment]
@vnitinv 
[http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-armv6l.sh](http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-armv6l.sh)

**Comment by dimpase** [comment]
Why do you say it is not a conda issue? I would like to have an initial basic install of conda on FreeBSD, with at least Python. Yes, I can pick up a conda Linux installer and try to reverse-engineer it, so that the binary blobs it downloads will work for FreeBSD, but why should it be so hard?

**Comment by jayvdb** [comment]
See newer issue for OpenBSD: https://github.com/conda/conda/issues/5968

**Comment by firebitsbr** [comment]
If any software developer wishing to do an porting of the anaconda open source for FreeBSD, could it do it without problems?

**Comment by mingwandroid** [comment]
> without problems?

It would be a huge effort with lots of problems.

**Comment by kalefranz** [comment]
Bootstrapping conda would be a relatively low bar.  I think the only code change is that we'd probably have to add the bsds as hard-coded subdir options in conda to avoid having to configure them manually.  But even after bootstrapping conda, you'd need a full package buildout to get anaconda.  That's for sure a nontrivial effort.  The only way this buildout would happen from Anaconda, Inc. employees is if we had an enterprise customer interested in funding the buildout.

If anybody from the community is really serious about this, we should discuss what the subdir names should be for freebsd and openbsd, so that we can at least get those parts into conda.

**Comment by dimpase** [comment]
Perhaps FreeBSD would be willing to do such a buildout on their infrastructure?
CCing @lwhsu on this.

**Comment by kalefranz** [comment]
For the subdir part I mentioned before, subdirs separate packages in a conda channel by, loosely, OS+architecture.  So e.g. we have `linux-64`, which is for all linux on x86_64, and within that there's an assumption of glibc rather than another libc variant.  Each channel also makes an assumption, and builds packages targeted to it, of a minimum glibc version.  In https://repo.anaconda.com/pkgs/main, the assumption is the CentOS 6 glibc version.  In https://repo.anaconda.com/pkgs/free, the assumption is, for the most part, CentOS 5.  With all that as a foundation, any packages within that `linux-64` subdir should be broadly compatible.

When we establish these subdirs for the BSDs, it's a decision that becomes really sticky, so we should do it right to begin with.  In the conda world, we generally want to maximize generality and compatibility as much as possible.

Does anyone here have any guidance or advice in this context?  Do we need different subdirs for all the different BSDs?  (From the conda perspective, it would be better if we didn't.)  What should the libc target be?

**Comment by dimpase** [comment]
Most popular BSDs have switched to clang. Clang 6.0.1 for FreeBSD. On the other hand, there is need for Fortran, and I am not sure whether Conda switched to flang, or still uses gfortran. Both would be OK for FreeBSD, but there is a need to pin the version.

**Comment by firebitsbr** [comment]
I used conda on Linux and now I'm on a FreeBSD workstation and I have to install each package manually and I'm thinking of creating a jails or something more rudimentary, since I do not have another option for FreeBSD yet. But I would really like to have the conda for the BSDs and I think there will be a lot of user in the future, just see the initiative of Nvidia to have a native Freebsd video driver (https://www.nvidia.com/object/freebsd -x64-archive.html), which all leads to believe that they are also betting on Data Science and AI for BSD world. That's the tip.

**Comment by mingwandroid** [comment]
I don't believe for one that there's much commercial demand for freebsd anaconda and every hour we put into improving freebsd for 10 people is an hour we could've spent on a relevant platform with a huge user base. Sorry.

**Comment by dimpase** [comment]
On Thu, Oct 4, 2018 at 11:10 AM Ray Donnelly <notifications@github.com>
wrote:

> I don't believe for one that there's much commercial demand for freebsd
> anaconda and every hour we put into improving freebsd for 10 people is an
> hour we could've spent on a relevant platform with a huge user base. Sorry.
>

Sorry, do you mean to say that "relevant"=="profitable for Anaconda Inc"?
Just wondering whether the huge community of volunteers helping to improve
conda ought to start sending you bills...  OK, sorry for flaming.

On the technical side of things, I cannot believe it would take it more
than a handful of man-hours at Anaconda to get it in a reasonable shape.
It has everything there, and it might help you to iron out clang-related
kinks out of conda. (Oh, and flang is ported to FreeBSD, too, by the way)

**Comment by mingwandroid** [comment]
On Sun, Oct 7, 2018 at 12:47 PM Dima Pasechnik <notifications@github.com>
wrote:

> On Thu, Oct 4, 2018 at 11:10 AM Ray Donnelly <notifications@github.com>
> wrote:
>
> > I don't believe for one that there's much commercial demand for freebsd
> > anaconda and every hour we put into improving freebsd for 10 people is an
> > hour we could've spent on a relevant platform with a huge user base.
> Sorry.
> >
>
> Sorry, do you mean to say that "relevant"=="profitable for Anaconda Inc"?
> Just wondering whether the huge community of volunteers helping to improve
> conda ought to start sending you bills... OK, sorry for flaming.
>

You have posted to the anaconda mailing list where we talk about Anaconda
Distribution, there's little incentive for us as a company to support
FreeBSD as far as I can tell. If you want to propose FreeBSD to conda-forge
then by all means do so. There'd need to be some support added to things
like conda and maybe conda-build but PRs would be thoughtfully reviewed and
if done cleanly I cannot see that we'd object. On the infrastructure side
(e.g. anaconda.org) I am less knowledgable but core support in conda and
conda-build would need to come first obviously. This is not and official
statement though.


>
> On the technical side of things, I cannot believe it would take it more
> than a handful of man-hours at Anaconda to get it in a reasonable shape.
> It has everything there, and it might help you to iron out clang-related
> kinks out of conda. (Oh, and flang is ported to FreeBSD, too, by the way)
>

Fixing, building, making installers and QAing, about 1500 packages for a
single platform takes a absolutely massive effort. Even if you automate
everything (which we're always moving towards) you still need to try to fix
every issue or bug that crops up.

Isn't there some way to run Linux binaries on FreeBSD? I've never ran any
BSD (well, maybe in some embedded thing or other!)

**Comment by mingwandroid** [comment]
> Sorry, do you mean to say that "relevant"=="profitable for Anaconda Inc"?
Just wondering whether the huge community of volunteers helping to improve
conda ought to start sending you bills... OK, sorry for flaming

Please cut out the snark, Anaconda Inc, and conda-forge have a highly
symbiotic relationship and always have. We tackle a lot of the most
difficult fixes for recipe build problems and provide the core package
manger, build tools, compilers and infrastructure for them at no cost. They
provide upstream maintainers (for some packages), recipe updates and fixes
but we also provide them same back to them via git pull requests. I also do
not believe you'll find many in conda-forge who care for BSD.

**Comment by mingwandroid** [comment]
On Sun, Oct 7, 2018 at 8:20 PM Dima Pasechnik <notifications@github.com>
wrote:

> On Sun, 7 Oct 2018, 13:06 Ray Donnelly, <notifications@github.com> wrote:
>
> > > Sorry, do you mean to say that "relevant"=="profitable for Anaconda
> Inc"?
> > Just wondering whether the huge community of volunteers helping to
> improve
> > conda ought to start sending you bills... OK, sorry for flaming
> >
> > Please cut out the snark, Anaconda Inc, and conda-forge have a highly
> > symbiotic relationship and always have. We tackle a lot of the most
> > difficult fixes for recipe build problems and provide the core package
> > manger, build tools, compilers and infrastructure for them at no cost.
> They
> > provide upstream maintainers (for some packages), recipe updates and
> fixes
> > but we also provide them same back to them via git pull requests. I also
> do
> > not believe you'll find many in conda-forge who care for BSD.
> >
>
> You might consider polling conda-forge volunteers, whether they would want
> to see a conda support for *BSD.
>

If BSD is *your* itch then it is you who should do the work, or at least
try setup a group of interested parties. For this to fly you'd need to
setup the infrastructure to support it, pick your FreeBSD version to build
against for ABI compat with any system libs you may need, build out
compiler activation scripts, find a CI system that runs it and can be
plugged into conda-forge's CI setup, make PRs to conda to add FreeBSD
subdir support.. But before going to all this effort, by all means see if
conda-forge in general care for FreeBSD support or not (they may take a
vote, I don't know, ask them, this mailing list is regarding the Anaconda
Distribution, and not conda-forge specifically).

Who knows, maybe there's lots of conda-forge people who'd like this?


> They (and you too) sure care for OSX, which is a *BSD clone.
> In fact a FreeBSD port helped us to improve OSX support on a number of
> occasions.
>

OSX is a very distant relative of BSD, very far from a clone at this point.
I really don't see the relevance.

**Comment by dimpase** [comment]
> OSX is a very distant relative of BSD, very far from a clone at this point. I really don't see the relevance.

OSX, as most *BSDs, is built natively with clang. That's why an "OSX-only" bug may be reproducible on a *BSD. (An extra argument for *BSD is that doing CI on them, unlike OSX,  does not cost a foot and a leg.)

Perhaps @lwhsu could help  getting Python FreeBSD people involved.

PS. Thanks for constructive responses, I certainly did not mean to start a flame-war. Apologies once again.

**Comment by mingwandroid** [comment]
On Mon, Oct 8, 2018 at 9:52 AM Dima Pasechnik <notifications@github.com>
wrote:

> OSX is a very distant relative of BSD, very far from a clone at this
> point. I really don't see the relevance.
>
> OSX, as most *BSDs, is built natively with clang. That's why an "OSX-only"
> bug may be reproducible on a *BSD. (An extra argument for *BSD is that
> doing CI on them, unlike OSX, does not cost a foot and a leg.)
>
> Perhaps @lwhsu <https://github.com/lwhsu> could help getting Python
> FreeBSD people involved.
>
> PS. Thanks for constructive responses, I certainly did not mean to start a
> flame-war. Apologies once again.
>

No problem! Good luck on your mission, I am not against having it at all
FWIW (in conda-forge or as a separate project) I just question if it's
value versus other tasks *I* have to or can do, and when releasing a
software distro you always want your work to be as impactful as possible
which means sometimes ignoring less popular OSes. However, it's entirely
possible to build your own locally stack too, even including installers (at
least to prove that it can be done) one of our employees singlehandedly
(AFAIK) maintains BerryConda for the RaspberryPI for example

I would also caution you not to underestimate the scope of this task, it is
huge!

I asked it before, but does *BSD not have the ability to run Linux binaries
these days?

**Comment by SylvainCorlay** [comment]
Hello world. I came across this issue as I am also looking into freebsd (long story short I am looking into jupyterhub on jails with a jupyterhub jail spawner for individual containers), and was looking if anyone built a miniconda for freebsd, and would have worked on the packages that I need...

The way conda-forge has been adding new infrastructures (Power8, ARM) has been working well and may be efficient to support new platforms.

In any case (along the lines of what @mingwandroid was saying) this would not be funded work for QuantStack as well.

**Comment by SylvainCorlay** [comment]
Note: I opened an issue in Miniforge about this: https://github.com/conda/conda/issues/61

**Comment by danieldjewell** [comment]
@mingwandroid 
> I don't believe that there's much commercial demand for freebsd anaconda 

It might be worth double-checking and or re-evaluating this for today. And not just for FreeBSD but perhaps also for other major commerical *NIXes (I don't use commercial *NIXes...  but AIX, Solaris, HP-UX, etc. are definitely out there and current.) Also, I wonder to what degree equipment/platform selection is based on the fact that Anaconda/Conda/Miniconda isn't available for these platforms (e.g. "Oh, we're not going to buy an IBM AIX POWER system because we can't install Conda on it so we'll buy an Intel system instead"). That's not Anaconda, Inc.'s responsibility at all (but it does make for an interesting case for IBM/Oracle possibly helping to fund the costs...) 

I guess, at a very high/general level, it would be nice to see the return of a more complete platform/architecture independent software design philosophy. In other words, in days of yore, software written for a POSIX-compliant (or mostly compliant) system would compile and work - regardless of the OS, CPU architecture, etc. Linux? Yup. FreeBSD? Yup. AIX? Yup. Intel? Yup. ppc64? Yup. aarch64? Yup. SPARC? Yup.

Just from my personal observations, it seems like the larger Python community (Anaconda included) really has shifted mindsets away from the elegant beauty of using cross-platform/cross-architecture standards and towards a more narrow platform-specific approach. (You can see this somewhat with the way PyPi works - there isn't really anything *ensuring* or *enforcing* that PyPi packages don't contain binaries or that source dists actually contain source - I've come across way too many packages that include a pre-compiled binary [usually a shared object / .so] compiled for x86_64 even though I'm trying to install on aarch64.) 

And I guess I kinda reject the idea that supporting multiple architectures/platforms is impossible - if the design of a system is setup in such a way that it is cross-platform/cross-architecture aware (which is the bulk of the cost/time), then - usually - adding additional architectures is a small incremental cost. (Debian supports a bunch of architectures ... and of course NetBSD is just nuts. Want to run NetBSD 9.0 (released in 2020) on your Macintosh IIcx? [Yes, a Macintosh IIcx is supported by NetBSD 9.0](https://wiki.netbsd.org/ports/mac68k/).)

Ok ```</soapbox>```

**Comment by mingwandroid** [comment]
Anaconda is moving towards genericism at every available opportunity from a packaging perspective.

Our packages can be fully architecture and os specific or they can be labeled as noarch python or as noarch generic. All packages that can be generic are made as generic as possible. R packages without compiled code are noarch generic for example and have been for a long time. These are very deliberate actions by the anaconda distribution team.

That some Linux distros also work on bsd isn't really of much interest to me in terms of providing a yardstick for the difficulties that would be involved in a bsd port of our ecosystem. We use significantly different build systems and compilers etc.

Of course there will be a market for such a port but we still must balance engineering costs vs benefits and here I strongly believe I can add more value to our users by focusing on the demonstrably much larger markets instead.

Of course there's always conda forge. They are our upstream and already provide ports that we do not. If you want bsd I think you'd need to engage conda forge and be prepared for a lot of work.

The changes needed to conda and conda build are very minimal so this isn't the forum to discuss this work.

**Comment by ykla** [comment]
I would like anaconda to support FreeBSD, which is a very good operating system.

**Comment by jtwalraven** [comment]
+1

**Comment by rajhlinux** [comment]
Oh god, I guess its folks like me who need to look into these git projects and port them into FreeBSD... However I hate python with a passion, so does talented and low level devs from FreeBSD, we are extremely happy with C/C++, hence why FreeBSD devs does not spend the time to port this python related stuff to FreeBSD (its better that why in my opinion, hence why I do not use Linux/WIndows). However in this day and age with the given user base of python users, not sure if its worth infecting FreeBSD with loads of python stuff in the long run... I'll be annoyed seeing FreeBSD ports with loads of apps done in python rather than c/c++.

**Comment by jamespolly** [comment]
I'm glad that the comments are still open here! Please keep this available for folks discovering the need to use conda on BSD.

@kalefranz wrote:

> Bootstrapping conda would be a relatively low bar. I think the only code change is that we'd probably have to add the bsds as hard-coded subdir options in conda to avoid having to configure them manually. But even after bootstrapping conda, you'd need a full package buildout to get anaconda. That's for sure a nontrivial effort. 

When you say "full package build out to get anaconda" does this mean that there is a lower bar for miniconda? I suspect a lack of my  anconda-understanding is in full effect.
