### ISSUE TITLE
provide a way to update packages installed with pip

### ISSUE THREAD

**Issue by david-gang** [conda/conda#6110]
As known there are packages not hosted in conda. These are installed by pip. On the other hand there is no known way to update them easily. conda update --all does not do the job.

Is there a better way then described at https://stackoverflow.com/questions/33187676/update-all-pip-packages-that-dont-come-from-conda ?

**Comment by kalefranz** [comment]
What you're discussing here I think is a combination of two concepts.  The first if for conda to be able to install wheels directly, which is #5202.  The second is for a concept we call "shadow packages," which would allow conda to work more intelligently with pip and other package managers. That issue is https://github.com/conda/conda/issues/6156.

I'm going to close this issue now, with both aspects being tracked elsewhere.
