### ISSUE TITLE
pywin32 module after update to 4.3.27 not found

### ISSUE THREAD

**Issue by Nyquis** [conda/conda#6127]
Today conda got updated on one of my working PCs on Win10 to 4.3.27. Anaconda was installed for the user with the path option checked. The auto_update was set to false. 

The update of all packages via conda update --all rendered several of my scripts completely useless since the win32com module could no longer be found from pywin32. The installation of Anaconda 5.0.0 after running anaconda-clean did not help. Only a downgrade to 4.3.25 rendered the module visible again. Running the script via environment did not help.

Have there been drastic changes to how conda operates? At least 4 of my machines on different windows have shown very high impact issues. All have the same installation procedure.

**Comment by mingwandroid** [comment]
I cannot reproduce this, can you give me the exact steps and/or share your script(s)?

Here's what I tried; it will install to %TEMP% and does not modify your system so should be safe for you to try. Note, I did *not* add to `PATH` as this is strongly discouraged. Adding to `PATH` adds `Anaconda` to the user `PATH` and the system `PATH` is searched in before that so we have no control of which DLLs get loaded which means we cannot be sure that our DLLs are running, in most cases of issues like this that turns out to be the root cause).

```
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/archive/Anaconda3-5.0.0.1-Windows-x86_64.exe', 'ac3.exe') }"
start /wait "" ac3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%TEMP%\ac3
%TEMP%\ac3\Scripts\activate.bat
python -c "import win32com"
echo %ErrorLevel%
0
```

**Comment by Nyquis** [comment]
Hello thank you for answering. I will run the script when I have some free time. Currently these issues crop on pretty clean systems with minimal load out.

I must disagree with the issue being the PATH since when downgrading to 4.3.25 from anaconda makes it work consistenly. There must be another reason afoot.

**Comment by mingwandroid** [comment]
> I must disagree with the issue being the PATH since when downgrading to 4.3.25 from anaconda makes it work consistenly

It could be that the pywin32 library (and its dependencies) around 4.3.25 are compatible with some DLLs on your system `PATH` whereas the pywin32 library (and its dependencies) around 4.3.27 are not compatible with those same DLLs. If that is the case then this is beyond our control.
