### ISSUE TITLE
Disoriented new contributor.

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda#6160]
Hi,

I tried to follow the instruction on README to setup a development environment. But it gives me 'Entry point not found' error:

```
Traceback (most recent call last):
  File "/home/yfeng1/anaconda3/mini/bin/conda", line 11, in <module>
    load_entry_point('conda', 'console_scripts', 'conda')()
  File "/home/yfeng1/anaconda3/mini/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/yfeng1/anaconda3/mini/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2750, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'conda') not found
```

I followed exactly the steps:

1. Download and install a miniconda environment
2. git clone the repo and get latest master branch
3. $CONDA/bin/python setup.py develop
4. activate the enrinvonment : and I see this error.

The README file mentioned setup-testing.py. So I tried that one. No luck neither. 

I am poking around a solution to #6104 -- but unable to get a working development environment has been quite frustrating ... I assume this is something extremely trivial -- looks like README may be out of date -- could someone clarify this?

**Comment by kalefranz** [comment]
Part of the problem here is that there are so many ways to do this, and everybody is going to have their own personal favorite.  Mine is to just use `python -m conda`, avoiding the entry point entirely, and just make sure my current working directory is the root of the cloned repo.

Another option is using the `install_conda_dev` function in `utils/functions.sh`, https://github.com/conda/conda/blob/b503fd216e487ef67ad4ae9f99a0b9e52f8a16da/utils/functions.sh#L227, or just going through what it's doing an executing it yourself.

Contributor docs are *definitely* an area of conda that can be improved :)

**Comment by rainwoodman** [comment]
Thanks. The python -m conda method worked the best for me -- except it doesn't allow using pdb.
