### ISSUE TITLE
Conda update behavior changed from 4.3.29->4.3.30

### ISSUE THREAD

**Issue by FuriouslyCurious** [conda/conda#6206]
I am installing Miniconda latest (same issue reproducible with Anaconda 5.0.0.1 as well) and running following sequence of commands:

```
conda config --set channel_priority false 
conda config --append channels conda-forge
conda update conda
# Install full Anaconda and some convenience packages
conda install --no-channel-priority anaconda joblib tqdm termcolor snakeviz seaborn \
                      pylama jupyterlab jupyter_kernel_gateway 
```

**Previously:**
conda version 4.3.29 was installing Anaconda 5.0.0.1 and upgrading all packages

**Now:**
conda version 4.3.30 is downgrading the whole set up to Anaconda 4.4.0.

### Request:
_conda update_ or _conda install_ should print a list of packages that are causing downgrades.   Alternatively, we can print packages that are causing a downgrade only to the critical components like Python or Anaconda meta-package.  

**Why this is a good idea:** Academic and research users like me install a lot of packages "just in case I need it someday".  This information will help user make the right decisions whether to remove a convenience package that is causing a major downgrade across the board.

**Comment by mingwandroid** [comment]
> Academic and research users like me install a lot of packages

Installing a lot of packages into the same environment "just in case" is not a good idea. Packages declare constraints on other packages and when there are a large number of packages this leaves the solver with little 'wriggle room' for the packages you actually need.

Instead you should use conda's comprehensive isolation support provided by conda [environments](https://conda.io/docs/using/envs.html).

**Comment by FuriouslyCurious** [comment]
If you visit Keras forums or PyTorch forums, 30-50% of posts are about mis-configured packages and dependencies, because best-practices are no match for "environmental pollution" with junk packages over time. 

Most research I work with try to implement 1-2 Arxiv papers everyday, so the best-practice of creating new Docker builds with 30 minute-long installs of full anaconda + new packages twice a day seems like a recommendation from an ivory tower 😣 


What do you think of following two suggestions?
1) Conda solver can print a list of package responsible for downgrade in Python-lang / Anaconda-meta, OR
2) Perhaps providing a switch "--no-downgrade", which prevents any downgrades to Anaconda-meta and Python-lang

**Comment by mingwandroid** [comment]
I dislike the idea of any special treatment of either Python or the Anaconda metapackage because special treatment means hacks and hacks bring technical debt and with it bugs.

Environments are our way of avoiding environmental pollution. You should use them for that purpose. They are a good bit faster than using Anaconda with docker, but then again Miniconda would work out much faster than Anaconda on docker anyway (though you can create docker images pre baked with whatever software you need of course). Installing only what you need is a great way to save time, and with regards to environments, installing into those only what you need for your specific workload is a great way to avoid pollution.

Implementing Arxiv papers seem unrelated to to topic at hand, I guess you are trying to say you have better things to do than worry about software installation and conflicts? I recommend minimalism through miniconda and environments then. Each env can have its own condarc too which is very powerful for avoiding conflicts between channels (and it seems to me that what you are *really* facing is a conflict between defaults and conda-forge).

**Comment by FuriouslyCurious** [comment]
@mingwandroid  Thanks Ray, I will use environments more to conduct experiments.  

Final question: when I look at the conda-forge repo (e.g., PyDICOM: https://github.com/conda-forge/pydicom-feedstock), how can I figure out its dependency restrictions?  Are dependencies and versions defined in recipes/meta.yaml file?

**Comment by mingwandroid** [comment]
> Are dependencies and versions defined in recipes/meta.yaml file

Generally speaking yes, but in the past conda-build introduced its own default pinnings (which could be overridden by env vars such as CONDA_PYTHON=3.6 or on the command line via --python=3.6). Conda-build 3 introduces a -m flag to allow specifying a build matrix which is a lot more powerful, flexible and explicit.

Another way to see the dependencies is: `conda info pydicom`
