### ISSUE TITLE
conda update conda failing on appveyor

### ISSUE THREAD

**Issue by ngoldbaum** [conda/conda#6251]
See https://ci.appveyor.com/project/ngoldbaum/yt-1nc0i/build/job/ygjhxe7u15yft5j7

The relevant output and error message is:

```
conda update -q --yes conda
Fetching package metadata: ....
Solving package specifications: 
Error: Could not find some dependencies for conda: vc 9.*, vc 10.*, vc 14.*
You can search for this package on anaconda.org with
    anaconda search -t conda vc 14.*
 (and similarly for the other packages)
You may need to install the anaconda-client command line client with
    conda install anaconda-client
Command exited with code 1
```

The associated appveyor configuration for this project is here: https://github.com/yt-project/yt/blob/master/appveyor.yml

I don't have easy access to a windows box so I can't reproduce outside of appveyor.

**Comment by dalcinl** [comment]
Same thing here: https://ci.appveyor.com/project/mpi4py/mpi4py/build/master-257, but only for Python 3 builds.

**Comment by ngoldbaum** [comment]
ping @msarahan. Is there some way we can get the attention of someone at anaconda inc?

**Comment by msarahan** [comment]
I'm looking into it.  Sorry this isn't faster.

**Comment by ngoldbaum** [comment]
No worries, just hadn't heard anything. Thanks for your tireless help!

**Comment by msarahan** [comment]
according to appveyor's descriptions of their environment (https://www.appveyor.com/docs/build-environment/#miniconda), you should point your Appveyor script at one of the newer miniconda installations.  The one you have is conda 3.16.0 - kind of amazing it has worked as long as it has for you.  If you change https://github.com/yt-project/yt/blob/master/appveyor.yml#L7 to use C:\Miniconda36-x64 things should work better.

I'll leave it up to ya'll whether you think Appveyor should point C:\Miniconda3 at whatever the current version is.  I think it should, but I also see arguments for keeping it stable.

**Comment by ngoldbaum** [comment]
That seems to have fixed things, thank you for pointing out what the real issue is.

Is it a problem that a relatively old version of miniconda can no longer update itself? Or does conda and the anaconda service not try to keep compatibility with older versions?

If Appveyor are opposed to keeping the base miniconda images pointing at a relatively recent version, if would be nice if they could provide a Miniconda-latest installation that gets continually updated. As is, the Miniconda3 installation they're providing has been made pretty much useless since the `conda` it comes with can't update itself.

**Comment by AndrewAnnex** [comment]
I am having this issue specifically with the 3.4 miniconda on appveyor

**Comment by AndrewAnnex** [comment]
oh I see @msarahan. Well I would like to continue to support 3.4 for my package, and I hit this issue when I attempt to update conda to >= 4.3.30

**Comment by ngoldbaum** [comment]
@AndrewAnnex you should still be able to create a python3.4 environment using the 3.6 miniconda base image. That's what we do for py2 in our appveyor config:

https://github.com/yt-project/yt/blob/530393ccf8fe8a556bf4db6d6b9540c716a6b3e9/appveyor.yml#L24-L33

**Comment by AndrewAnnex** [comment]
@ngoldbaum thanks I will give that a try

**Comment by msarahan** [comment]
I haven't raised this with appveyor yet.  I don't know what their opinion is.

This problem ultimately originates with an index change we needed to make.  The old ``features`` and ``track_features`` ended up causing some huge problems when more than one package in an environment used ``track_features`` on related ``features``.  For example, python used track_features for a given vc version.  RStudio also used track_features, for a different vc version.  Rather than excluding RStudio from being installed into that python environment, it became ambiguous which feature to pay attention to, and things broke horribly.  Adding the vc package dependency was the answer.

Now as for this error: The vc package that is available has version numbers with no ``.`` in them (9, 10, 14).  I have a theory that ancient conda just doesn't understand that.  The ``.*`` in specs is generally a good idea (it is what lets conda not match exactly), but an exact match here might be all that old conda supports 

We're going to try something with the index generation so that hopefully fewer code changes are necessary on your end, but in general, we can't support conda (or python) this old, and Appveyor will need to do something about this.

**Comment by msarahan** [comment]
I have removed the ``.*`` from the vc dependency specs in our index.  That should resolve this issue.  I'm closing it for now, but I'm happy to reopen it if anyone is still seeing problems.

**Comment by msarahan** [comment]
Reported to appveyor at https://github.com/appveyor/ci/issues/1897

**Comment by AndrewAnnex** [comment]
I think this issue happened again late on the 3rd or 4th for my project just fyi.
