### ISSUE TITLE
scipy - ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by abikutn** [conda/conda#6396]
Trying to figure out what's going wrong here. Tried to update all by conda update --all and also using the conda package manager through navigator. Downgraded to Python 3.5.4 (conda automatically downgrades dependent packages that goes with 3.5.4, atleast this is what I believe happens) - dint work. Upgraded back to 3.6.3 and still doesn't work. Trying to find out:

1.  What could be the real issue here and how to tackle it
2. Do a complete clean uninstall of entire conda and reinstall for a fresh start.

```
(C:\Users\abhil\Anaconda3) C:\Users\abhil>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.5.4.final.0
       requests version : 2.18.4
       root environment : C:\Users\abhil\Anaconda3  (writable)
    default environment : C:\Users\abhil\Anaconda3
       envs directories : C:\Users\abhil\Anaconda3\envs
                          C:\Users\abhil\AppData\Local\conda\conda\envs
                          C:\Users\abhil\.conda\envs
          package cache : C:\Users\abhil\Anaconda3\pkgs
                          C:\Users\abhil\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\abhil\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.5.4 Windows/10 Windows/10.0.16299
          administrator : False

(C:\Users\abhil\Anaconda3) C:\Users\abhil>
```

sample code to check scipy:

```
import numpy as np
from scipy.optimize import minimize


def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0 * (x[1:] - x[:-1] ** 2.0) ** 2.0 + (1 - x[:-1]) ** 2.0)


x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='nelder-mead',
               options={'xtol': 1e-8, 'disp': True})

print(res.x)
```

output:

```
Traceback (most recent call last):
  File "C:/Users/abhil/PycharmProjects/CISC-601-ScientificComputing2-Py3/_modules/_scipy_optimize_test.py", line 2, in <module>
    from scipy.optimize import minimize
  File "C:\Users\abhil\Anaconda3\lib\site-packages\scipy\optimize\__init__.py", line 240, in <module>
    from .optimize import *
  File "C:\Users\abhil\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Users\abhil\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1
```

**Comment by ekarademir** [comment]
I have similar issue with numpy and scipy in the conda repos. It happens while loading precompiled libs. In my case they are lapack_lite and _umath_linalg. If I uninstall conda versions and use pip versions it works ok.

**Comment by ekarademir** [comment]
Also I think this problem is repeated every time there is a wave of python package releases as there are similar issues that goes back.

**Comment by kalefranz** [comment]
No way of telling how you got into the hole you're in from the information you provided.  Sometimes the easiest thing to do is just to blow it all away and start over with a new installer.  Actually, mixing up DLLs between pip-installed and conda-installed stuff can do this.  Stick with conda to avoid that problem.

**Comment by ekarademir** [comment]
I've came across this issue after updating conda with `conda update`, so I stuck with conda all the way. Maybe conda needs to test crucial packages better before releasing?

**Comment by mingwandroid** [comment]
All of our packages are tested extensively before releasing. You have run into DLL-hell hell because you have elected for software to modify your path and/or installed badly written software that puts DLLs into C:\Windows\System32.

**Comment by ekarademir** [comment]
Why do you assume that I've done all of that? I just said this happened after `conda update`, and before that everything was managed by conda. I might have invoked a fringe case but I've made sure everything was in the path. Especially the dll's scipy was trying to find. I've uninstalled and reinstalled entire conda. I've even created a new user and did a fresh install with that user. This error was a pity, because I'm also using conda to manage the packages needed for another software that I'm maintaining.

**Comment by mingwandroid** [comment]
Just because a `conda update` triggered a problem for you does not strictly lead to it being a fact that there is a problem with any of the newly installed conda packages. It just means that the amalgamation of that new software and your existing system environment are now not compatible.

In other words it can mean that an updated DLL has become incompatible with a DLL loaded from outside of the `Anaconda Distribution` due to DLL-hell.

How did you install `Anaconda`? `Just Me` or `All Users`? Did you elect to add it `PATH` or not?

How do you launch `scipy`? Do you use the `Anaconda Prompt`? Which OS are you even using? Your prompt beginning `$>` does not *look* like Windows. You haven't shown either `conda info` nor `conda list --show-channel-urls` nor the value of `$PATH`/`%PATH%. Without these details we can only guess at what's going on.

.. but my main point is that contrary to your suggestion:

> Maybe conda needs to test crucial packages better before releasing?

.. I can guarantee that we *do* test our software *extensively*, each and every package.

**Comment by ekarademir** [comment]
> How did you install Anaconda? Just Me or All Users? Did you elect to add it PATH or not?
Just me. Also, I'm using Miniconda.

> How do you launch scipy?
I'm just importing the signal processing module like:
`from scipy.signal import savgol_filter, medfilt`

> Which OS are you even using?
Windows 7.

> $> does not look like Windows.
I was just trying to help the person who started the thread. I didn't just copy and paste the commands. So `$>` is a placeholder for the prompt.

> You haven't shown either conda info nor conda list --show-channel-urls nor the value of $PATH/%PATH%. Without these details we can only guess at what's going on.
As you might have noticed I was just trying to help by sharing what worked for me. I've searched all over the place for the problem and similar problems pop up everywhere. Error outputs change but similar problems.

As I said, it might be a fringe problem, but I've tested the problem against every case. I've even created a new user and installed from scratch. Everything boiled down to scipy v1 package through conda repos. That's why I suggested to use pip version, as they didn't have that problem. Even installed together with conda packages.

**Comment by mingwandroid** [comment]
> I've even created a new user and installed from scratch

New users still use files in `C:\Windows\System32` and still use the `system PATH` (the same way as they still use programs installed in `/usr/bin` on Linux or macOS). The only way to truly clean things out is to re-install from scratch. I am not suggesting you do that, but without the information I asked for I can't really help further.

**Comment by ekarademir** [comment]
> New users still use files in C:\Windows\System32 and still use the system PATH (the same way as they still use programs installed in /usr/bin on Linux or macOS). The only way to truly clean things out is to re-install from scratch. I am not suggesting you do that, but 

Above I said I've reinstalled it. And believe me uninstalling conda doesn't wipe out all related system parameters. I've also gone through the registry and deleted all things related to conda and anaconda and miniconda.

> without the information I asked for I can't really help further.

There is no point in giving you this information after I've changed so much since the bug. But currently here are the outputs:

`$> conda info`
`Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\Ertugrul.Karademir\Miniconda3  (writable)
    default environment : C:\Users\Ertugrul.Karademir\Miniconda3
       envs directories : C:\Users\Ertugrul.Karademir\Miniconda3\envs
                          C:\Users\Ertugrul.Karademir\AppData\Local\conda\conda\envs
                          C:\Users\Ertugrul.Karademir\.conda\envs
          package cache : C:\Users\Ertugrul.Karademir\Miniconda3\pkgs
                          C:\Users\Ertugrul.Karademir\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/7 Windows/6.1.7601
          administrator : False`


You won't see scipy below because after this incident I truly learned the value of virtualenvs and encapsulated everything scipy related to its own environment.

`$> conda list --show-channel-urls`
`# packages in environment at C:\Users\Ertugrul.Karademir\Miniconda3:
#
asn1crypto                0.23.0           py36h546eea3_0    defaults
attrs                     17.3.0                    <pip>
ca-certificates           2017.08.26           h94faf87_0    defaults
certifi                   2017.11.5        py36hb8ac631_0    defaults
cffi                      1.11.2           py36h829d1a5_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
conda                     4.3.30           py36h7e176b0_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.1.4            py36he1d7878_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
decorator                 4.1.2            py36he63a57b_0    defaults
docutils                  0.14                      <pip>
entrypoints               0.2.3            py36hfd66bb0_2    defaults
flake8                    3.5.0                     <pip>
freetype                  2.8                  h51f8f2c_1    defaults
html5lib                  1.0.1            py36h047fa9f_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.6              py36h148d497_1    defaults
intel-openmp              2018.0.0             hd92c6cd_8    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
jedi                      0.11.0                   py36_2    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jupyter_core              4.4.0            py36h56e9d50_0    defaults
Kivy                      1.10.0                    <pip>
Kivy-examples             1.10.0                    <pip>
Kivy-Garden               0.1.4                     <pip>
kivy.deps.glew            0.1.9                     <pip>
kivy.deps.gstreamer       0.1.12                    <pip>
kivy.deps.sdl2            0.1.17                    <pip>
libpng                    1.6.32               h140d38e_4    defaults
markupsafe                1.0              py36h0e26971_1    defaults
menuinst                  1.4.10           py36h42196fb_0    defaults
mistune                   0.8.1            py36h007b88b_0    defaults
mkl                       2018.0.1             h2108138_4    defaults
numpy                     1.13.3           py36ha320f96_0    defaults
openssl                   1.0.2n               h74b6da3_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py36h3ef6317_1    defaults
parso                     0.1.1            py36hae3edee_0    defaults
pip                       9.0.1            py36h226ae91_4    defaults
pluggy                    0.6.0                     <pip>
py                        1.5.2                     <pip>
pycodestyle               2.3.1                     <pip>
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pyflakes                  1.6.0                     <pip>
Pygments                  2.2.0                     <pip>
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pyparsing                 2.2.0            py36h785a196_1    defaults
pypiwin32                 220                       <pip>
pyqt                      5.6.0            py36hb5ed885_5    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
python                    3.6.3                h3b118a2_4    defaults
python-dateutil           2.6.1            py36h509ddcb_1    defaults
pytz                      2017.3           py36h1d3fa6b_0    defaults
pywin32                   221              py36h9c10281_0    defaults
pyzmq                     16.0.3           py36he714bf5_0    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
requests                  2.18.4           py36h4371aae_1    defaults
ruamel_yaml               0.11.14          py36h9b16331_2    defaults
setuptools                36.5.0           py36h65f9e6e_0    defaults
setuptools                38.4.0                    <pip>
sip                       4.18.1           py36h9c25514_2    defaults
six                       1.11.0           py36h4db2310_1    defaults
sqlite                    3.20.1               h9eeafa9_2    defaults
testpath                  0.3.1            py36h2698cfe_0    defaults
tornado                   4.5.2            py36h57f6048_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_2    defaults
vs2015_runtime            14.0.25123           hd4c4e62_2    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
wheel                     0.30.0           py36h6c3ec14_1    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
xlrd                      1.1.0                     <pip>
yaml                      0.1.7                hc54c509_2    defaults
zlib                      1.2.11               h8395fce_2    defaults`

And finally path 
`$> $Env:PATH`
`C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\ImageMagick-7.0.6-Q16;C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\ProgramData\Oracle\Java\javapath;C:\windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys;C:\Progr am Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64;C:\Program Files\Microsoft Windows Performance Toolkit;C:\Program Files (x86)\CineForm\Tools;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files\Keysight\IO Libraries Suite\bin;C:\Program Files\IVI Foundation\VISA\Win64\ktvisa;C:\Program Files (x86)\Keysight\IO Libraries Suite\bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\ktvisa;C:\Program Files (x86 )\IVI Foundation\IVI\bin;C:\Program Files\IVI Foundation\IVI\bin;C:\Program Files (x86)\IVI Foundation\VISA\winnt\agvisa;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common  Files\Intel\WirelessCommon\;C:\Program Files\Thorlabs\Kinesis;C:\Users\Ertugrul.Karademir\Miniconda3;C:\Users\Ertugrul.Karademir\Miniconda3\Library\mingw-w64\bin;C:\Users\Ertugrul.Karademir\Miniconda3\Library \usr\bin;C:\Users\Ertugrul.Karademir\Miniconda3\Library\bin;C:\Users\Ertugrul.Karademir\Miniconda3\Scripts;C:\Users\Ertugrul.Karademir\.cargo\bin;C:\Users\Ertugrul.Karademir\AppData\Local\Pandoc\;C:\Users\Ertu grul.Karademir\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\Ertugrul.Karademir\AppData\Local\Yarn\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\ ;C:\Users\Ertugrul.Karademir\AppData\Local\atom\bin`

**Comment by mingwandroid** [comment]
You said:

>>  I've uninstalled and reinstalled entire conda.

then:

> Above I said I've reinstalled it

I believe you reinstalled Miniconda and added a new user because you believed that would reset your operating system back to a completely clean slate? This is not the case, nothing short of reinstalling you OS will do that.

I think you are using Powershell here considering how you've printed out your `PATH`, but I'm not sure, even though I asked you explicitly:

> How do you launch scipy? Do you use the `Anaconda Prompt`?

We do not currently support `Powershell`.

In your `PATH` I see no mention of any entries from the `Anaconda Distribution` which leads me to believe you have not activated your environment correctly (or at all). Even once you do these things you may still have trouble, but it will be a step in the right direction.

So, the next steps for getting to the bottom of this are:

1. Use `The Anaconda Prompt` and not `Powershell`. If you don't have `The Anaconda Prompt` then activate your env correctly from `cmd.exe` by running `C:\Users\Ertugrul.Karademir\Miniconda3\Scripts\activate`, then try `scipy`.

2. If that fails, then do the same, but before running the `activate` batch file, set your `PATH` to a minimal one to get rid of all those potentially harmful entries via `set PATH=%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\`

3. If that fails then ensure you have neither `PYTHONHOME` nor `PYTHONPATH` env vars set and try again.

4. If that fails, use something like `procmon` to try to figure out which DLLs that should be getting found in your `C:\Users\Ertugrul.Karademir\Miniconda3` are instead getting found in `C:\Windows\System32`.

I will say that this is more work than it needs to be, but the root cause is the design of how Windows looks for DLLs. I have been thinking of ways to make this diagnosis easier, but I don't have time to implement anything at present.

**Comment by mbargull** [comment]
That `PATH` does not look sane at all. A general problem with having that many entries in `PATH` is that there is a very high probability that you'll have incompatible DLLs being mixed up, like @mingwandroid already said:
> You have run into DLL-hell hell because you have elected for software to modify your path

Also that `PATH` variable is 1841 characters long! You'll hit some practical limitations with that when you add a few more characters, i.e., activate a Conda environment, see
https://superuser.com/questions/1070272/why-does-windows-have-a-limit-on-environment-variables-at-all/1070354
https://software.intel.com/en-us/articles/limitation-to-the-length-of-the-system-path-variable

**Comment by mingwandroid** [comment]
Update, I was incorrect when I said:

> In your `PATH` I see no mention of any entries from the Anaconda Distribution

.. rather they were buried somewhere towards the end of it:

`C:\Users\Ertugrul.Karademir\Miniconda3;C:\Users\Ertugrul.Karademir\Miniconda3\Library\mingw-w64\bin;C:\Users\Ertugrul.Karademir\Miniconda3\Library \usr\bin;C:\Users\Ertugrul.Karademir\Miniconda3\Library\bin;C:\Users\Ertugrul.Karademir\Miniconda3\Scripts;`

This means that the DLLs that software from the `Anaconda Distribution` needs are looked for in the `Anaconda Distribution` *only* after first looking in:

```
C:\Windows\System32
C:\Program Files\ConEmu\ConEmu\Scripts
C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu
C:\Program Files\ImageMagick-7.0.6-Q16
C:\windows
C:\windows\system32\wbem
C:\ProgramData\Oracle\Java\javapath
C:\windows\System32\WindowsPowerShell\v1.0
C:\Program Files\Intel\WiFi\bin
C:\Program Files\Common Files\Intel\WirelessCommon
C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys
C:\Progr am Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64 ***
C:\Program Files\Microsoft Windows Performance Toolkit
C:\Program Files (x86)\CineForm\Tools
C:\Program Files\Git\cmd
C:\Program Files\nodejs\
C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\
C:\Program Files\IVI Foundation\VISA\Win64\Bin\
C:\Program Files\Keysight\IO Libraries Suite\bin
C:\Program Files\IVI Foundation\VISA\Win64\ktvisa
C:\Program Files (x86)\Keysight\IO Libraries Suite\bin
C:\Program Files (x86)\IVI Foundation\VISA\WinNT\ktvisa
C:\Program Files (x86 )\IVI Foundation\IVI\bin
C:\Program Files\IVI Foundation\IVI\bin
C:\Program Files (x86)\IVI Foundation\VISA\winnt\agvisa
C:\Program Files (x86)\Yarn\bin
C:\Program Files\Intel\WiFi\bin\
C:\Program Files\Common Files\Intel\WirelessCommon\
C:\Program Files\Thorlabs\Kinesis
```

.. so it is not surprising in the least that you are having issues. Did you need see the *very* explicit warning about adding Anaconda to your PATH when you installed it? If you did, did you ignore that warning? If you ignored that warning do you think it's reasonable to ask:

> Maybe conda needs to test crucial packages better before releasing?

 .. after running into issues?

**Comment by mingwandroid** [comment]
Barely none of those PATH entries are related to VISA instruments. You can setup batch files to set your PATH before launching applications according to each specific workload. This is what the `Anaconda Prompt` does.

I take exception to being called out for releasing bad untested software when the problem is very obviously a case of [DLL-hell](https://en.wikipedia.org/wiki/DLL_Hell), something it is the user's responsibility to avoid when using Windows.

**Comment by ekarademir** [comment]
I know you are testing thoroughly. I'm not saying that conda is badly tested. I've just said you might have missed something. Apologies, if you haven't. I've already said that this might be a fringe case. You keep repeating DLL hell. But that's a hell I have to work with. 

> Barely none of those PATH entries are related to VISA instruments.

Just look at the paths. Several of them has VISA written in them.

Anyway. I'm muting the thread. Thanks for the work you've already put into conda. I was loving it until this happened. I would have avoided it but I have to use this system in particular. So I've fixed the problem for this particular fringe case. I'd still advise people use anaconda, but not for every case.

**Comment by mingwandroid** [comment]
OK, you'll not read this but on a final note, if you can launch the session in which you need to use Anaconda software from the Anaconda Prompt you will avoid nearly all of these issues. You can launch Powershell from that if you prefer that. And for anyone still reading, *do not add Anaconda to your PATH*, when doing a Just Me install we have elected to add it to the User PATH to be a good Windows citizen but this choice leaves us at the mercy of things on your System PATH and then things like this happen.

**Comment by ekarademir** [comment]
You response popped as I was going through the thread again. I'm also using python through node.thread spawned by an electron application. So the reason I'm using the PS directly is that that part of the software assumes conda is already in the PATH. As you've advised, maybe a better way was to insert those paths to spawned thread's environment.

**Comment by mingwandroid** [comment]
I would still recommend you to figure out a way of having batch files to set PATH for each of your tasks and avoid modifying the Windows-Registry-stored PATH env vars altogether (I accept in *some* rare cases that not possible), but I'm happy you are now thinking in these terms.

**Comment by Irene-GM** [comment]
Just faced the same DLL error on a fresh installation of conda in a brand new computer, but in my case the module failing to be imported is `scipy.special` (which is called from `import seaborn`). The fix recommended in https://github.com/conda/conda/issues/6396#issuecomment-350254762 works.

**Comment by williamratcliff** [comment]
I will mentioned that I had the same problem and the fix recommended in [#6396 (comment)](https://github.com/conda/conda/issues/6396#issuecomment-350254762) works

**Comment by sbhle** [comment]
Also had the same problem and the fix recommended in [#6396](https://github.com/conda/conda/issues/6396#issuecomment-350254762) also works. Since I don't wanted to install the package with pip instead of conda I noticed that scipy in version 1.0.0 works fine without the recommended fix. All other 0.19.x versions of scipy needed the fix to work in my (Python 2.7) environment. Maybe this information helps to get to the root of the problem.

**Comment by sindux** [comment]
I had same problem after upgrading my anaconda to latest version. Similar to @Irene-GM comment above, I got the error when `seaborn` is trying to `import scipy.special`.
I solved it by reinstalling `icc_rt` package:
```
conda remove icc_rt --force
conda install icc_rt --no-deps
```
See [here](https://stackoverflow.com/a/51537436/4424209) for detail on how I investigated it.

**Comment by mrslezak** [comment]
Had the same issue in Python 3.5.5 |Anaconda, Inc.| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)] with SciPy although: `from scipy.stats import norm` generated the `ImportError: DLL load failed` error - the problem was fixed by:

conda remove scipy --force
pip install scipy

No more errors.  Like ekarademir's answer but didn't need to touch NumPy (which by default is built against MKL in Anaconda, SciPy rests on top of it, so why mess with NumPy you'll slow computations down).  Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] had no issues with from `scipy.stats import norm` straight from Anaconda.

**Comment by AdrienMau** [comment]
Had same Issue with Spyder-Python3.6 without Anaconda. This happened after manually installing wheels for tifffile, numpy and imagecodecs.
Fixed it by doing a manual install of last scipy wheel : https://pypi.org/project/scipy/

**Comment by dorwalp** [comment]
Was facing the same issue. Resolved by downgrading Python to 3.6.1 version(previously using 3.6.8)

**Comment by xorxx** [comment]
This looks very similar to the error I was struggling with today:
> output:
> 
> ```
> Traceback (most recent call last):
>   File "C:/Users/abhil/PycharmProjects/CISC-601-ScientificComputing2-Py3/_modules/_scipy_optimize_test.py", line 2, in <module>
>     from scipy.optimize import minimize
>   File "C:\Users\abhil\Anaconda3\lib\site-packages\scipy\optimize\__init__.py", line 240, in <module>
>     from .optimize import *
>   File "C:\Users\abhil\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
>     from .linesearch import (line_search_wolfe1, line_search_wolfe2,
>   File "C:\Users\abhil\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
>     from scipy.optimize import minpack2
> ImportError: DLL load failed: The specified module could not be found.
> 
> Process finished with exit code 1
> ```

I figured out, that this problem was caused in my case by changing the current directory the python interpreter was executed in from windows drive C: to another drive. I guess that the problem is caused by a DLL access path that is relative to the current drive but does not incorporate the drive letter itself. As long as scipy is on the current drive the problem does not occur.

I hope this information helps to fix the bug. I am using windows 7 64 bit with 32-Bit python.

**Comment by JackDartford-wq** [comment]
This worked for me! Thank you so much.

**Comment by xorxx** [comment]
> No way of telling how you got into the hole you're in from the information you provided. Sometimes the easiest thing to do is just to blow it all away and start over with a new installer. Actually, mixing up DLLs between pip-installed and conda-installed stuff can do this. Stick with conda to avoid that problem.

@kalefranz: I may be wrong, but it looks to me like there are a few hints what could still be wrong with this issue further down. At least the drive letter issue I reported [above](https://github.com/conda/conda/issues/6396#issuecomment-635370435) would be easy to fix. It may be a good idea to reopen this issue.

**Comment by lpanichi** [comment]
Got this error when importing scipy.optimize and scipy.interpolate with win10 and pyhon 3.8.
```
conda remove scipy, numpy 
pip3 install numpy, scipy
```
 did not work
But
`conda install mkl`
worked

**Comment by euricocovas** [comment]
I have a similar problem, I uninstalled python from my windows 10 PC, by removing anaconda totally, then rebooted, then run Anaconda3-2020.11-Windows-x86_64.exe, then did

	conda activate

	conda install -c conda-forge spacy --yes 
	conda install -c conda-forge cupy --yes  
        conda update -c conda-forge --all --yes

the update did this (among many other things):

scipy               pkgs/main::scipy-1.5.2-py38h14eb087_0 --> conda-forge::scipy-1.6.2-py38he847743_0

then 
```

   import scipy
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\_distributor_init.py", line 59, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\ProgramData\Anaconda3\lib\site-packages\scipy\.libs\libbanded5x.3OIBJ6VWWPY6GDLEMSTXSIPCHHWASXGT.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

fixed by

pip install scipy --force-reinstall

the 

conda install scipy --force-reinstall 

did not fixed it.

**Comment by RichardScottOZ** [comment]
Just hit this today on a fresh environment too.

**Comment by RichardScottOZ** [comment]
the conda uninstall and pip install did seem to fix it, but will need repeating if you add things

**Comment by GF-Huang** [comment]
Why still happen at 2021?

**Comment by GF-Huang** [comment]
> I have similar issue with numpy and scipy in the conda repos. It happens while loading precompiled libs. In my case they are lapack_lite and _umath_linalg. If I uninstall conda versions and use pip versions it works ok.
> 
> As an interim solution:
> 
> ```
> $> conda remove --force numpy, scipy
> $> pip install numpy, scipy
> ```
> 
> works but each new package who needs these two will install conda version again due to attached patch version at the end of the repos, unless you want to manually install all dependencies with avoiding these two.

ERROR: Invalid requirement: 'numpy,'

**Comment by andrew404** [comment]
This is sort of infuriating, that this problem hasn't been addressed in the default conda channel
