### ISSUE TITLE
conda activate does not change CONDA_SUBDIR

### ISSUE THREAD

**Issue by thibaudruelle** [conda/conda#6405]
I am running Anaconda on Windows 64 bits (conda version: 4.3.30). I need to get a 32 bits python environment for compatibility with 32 bits dlls. I followed suggestions in [this closed issue](https://github.com/conda/conda/issues/1744) and ran the following:
```
conda activate root
conda info
set CONDA_SUBDIR=win-32
conda create -n newenv_win32
conda activate new_env_win32
conda info
conda activate root
conda info
```

The platform returned by the `conda info` calls was win-64, then win-32, then win-32. 

Is this intended ? Am I supposed to change CONDA_SUBDIR manually, or are there better ways to create 32 bits environments ?

**Comment by MWorksGH** [comment]
I've been trying to use CONDA_SUBDIR too, on ubuntu gnome 16.04.3, yet using conda info it always returns linux 64 bits, and no change on my python too, tried with python 2.7, 3.5 and 3.6. Any help would be appreciated!.

**Comment by kalefranz** [comment]
The `conda activate` command only works for conda version >=4.4, and then only when propetly initialized for most shells. However the cmd.exe shell on windows should work with no additional configuration once conda is upgraded.

**Comment by kalefranz** [comment]
For the issue you’re encountering with the CONDA_SUBDIR environment variable, please show your full shell session, so that I can reproduce it myself. Make sure calling `conda info` at least once is part of your shell session.

**Comment by MWorksGH** [comment]
Hello Kalefranz, and thank you for your fast response. 
According to this: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/gbGH54qOC-A I can't install a 32 bit python if my root is 64 bit, am I right? then, I think that was the problem. For the steps, I followed thibaudruelle's steps in his first comment, with no luck as I said. If it is possible can you give me the right steps to do it? ...I ended up going to windows and installing python 32 bits there, since I had nothing installed, it went smoothly, but I would like to work on linux. Here is my pastebin: https://pastebin.com/5g3p5dJL

**Comment by kalefranz** [comment]
No, you can't run 32 bit binaries on 64 bit linux.

**Comment by JimAmuro** [comment]
Sorry for replying to this closed issue.
I think the OP was asking if the value of `platform` returned by `conda info` is literally the value of the env var `CONDA_SUBDIR` (if set) instead of something inherent in the active conda environment. I can reproduce this, I even used some random word for `CONDA_SUBDIR` and `platform` and `channel URLS` show the same random word... So this is not even inherent in `conda`...
So my question is, if I want to install a 32-bit env/software on a 64-bit conda, I just change `CONDA_SUBDIR` to `xxx-32`, then run the same install commands as for `xxx-64`, then close the session, and in the future sessions I still install 64-bit softwares, am I right? Thank you very much!

**Comment by mfansler** [comment]
For completeness, note that setting the `subdir` configuration variable for the env makes it so you don't have to set the environment variable. I.e.,

    conda activate new_env_win32
    conda config --env --set subdir win-32

This will automatically then be set whenever the env is activated.
