### ISSUE TITLE
deactivate sets `CONDA_PREFIX` to the wrong value.

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#6592]
Deactivating an env. into which the new compilers have been installed leads to:

```
ERROR: This cross-compiler package contains no program /opt/conda/bin/x86_64-conda_cos6-linux-gnu-cc
```

This comes from [here](https://github.com/AnacondaRecipes/aggregate/blob/master/ctng-compilers-activation-feedstock/recipe/deactivate-gcc.sh#L58)

It seems that `CONDA_PREFIX` has been set to the prefix of the new environment instead of that of the old environment.

It doesn't seem to matter whether the legacy activate scripts or the conda shell function are used here, both exhibit the same problem.

**Comment by kalefranz** [comment]
> It seems that `CONDA_PREFIX` has been set to the prefix of the new environment instead of that of the old environment.

It's my understanding that `CONDA_PREFIX` has always been the path to the current active prefix.  At least back to the #1727 days or so.  Then again, I could be completely mis-remembering, and I've added pieces of code over time that made that assumption, because I can't find any reference to `CONDA_PREFIX` in the 4.3.x code concerning activate.

**Comment by kalefranz** [comment]
Oh, right.  I was only looking in the code, not the shell wrappers.

https://github.com/conda/conda/blob/4.3.31/shell/activate#L88-L92
