### ISSUE TITLE
activate does not work.

### ISSUE THREAD

**Issue by yunyundong** [conda/conda#6713]
when i perform the activate commad line, there are hints, but not work!
此时不应有 \Anaconda2\Library\bin\..\..\Scripts\conda.exe""。

C:\Users\username>    @SET "_CONDA_EXE="C:\Program Files (x86)\Anaconda2\Library\bin\..\..\Scripts\conda.exe""

"此时不应有 " it means: here they do not should eixst.

besides, my OS is Win10, 64bit.

**Comment by mingwandroid** [comment]
Python 2 on Windows is incapable of being installed in a location (or handling PATH entries) containing any non-ASCII characters.

You need to use Python 3 or change those things.

**Comment by yunyundong** [comment]
Sorry, I dont know you very much. Can you write more details?
when I perform the `where conda` in dos window, it prints as follows:
`C:\Program Files (x86)\Anaconda2\Scripts\conda.exe 

C:\Program Files (x86)\Anaconda2\Library\bin\conda.bat`
when I perform the `where python` in dos window, it prints as follows:
`C:\Program Files (x86)\Anaconda2\python.exe`

In fact, previously,  the `activatate` command can work well.

**Comment by mbargull** [comment]
@mingwandroid / @kalefranz: only the error message was in Chinese, not the path. Also Python wasn't launched yet, only the batch files.
The problem is that in
```bat
 @set "_CONDA_EXE="C:\Program Files (x86)\Anaconda2\Library\bin....\Scripts\conda.exe""
```
there are some `\` missing as it should read
```bat
 @set "_CONDA_EXE="C:\Program Files (x86)\Anaconda2\Library\bin\..\..\Scripts\conda.exe""
```
. I don't know how that happened, though.

**Comment by kalefranz** [comment]
@yunyundong Can you please give us the output of `conda info`?

**Comment by yunyundong** [comment]
when I perform `conda info` in dos window, it prints as follows:

     active environment : None
       user config file : C:\Users\yydong\.condarc
 populated config files :
          conda version : 4.4.7
    conda-build version : 3.0.8
         python version : 2.7.12.final.0
       base environment : C:\Program Files (x86)\Anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Program Files (x86)\Anaconda2\pkgs
                          C:\Users\yydong\AppData\Local\conda\conda\pkgs
       envs directories : C:\Program Files (x86)\Anaconda2\envs
                          C:\Users\yydong\AppData\Local\conda\conda\envs
                          C:\Users\yydong\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.13.0 CPython/2.7.12 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False

**Comment by yunyundong** [comment]
Besides the `activate` command does not work ,when I perform the command in cell of Jupyter notebook, there are the same hints. Such as , when I input the command `!conda list`, there are the same output as follows:
C:\06Codes_From_Jupyter\ISPRS>    @SET "_CONDA_EXE="C:\Program Files (x86)\Anaconda2\Library\bin\..\..\Scripts\conda.exe""
此时不应有 \Anaconda2\Library\bin\..\..\Scripts\conda.exe""。

**Comment by mingwandroid** [comment]
Can you try installing to a PATH that does not contain any `(` or `)` characters and let us know if that works for you? If it does we need to fix `(` and `)` handling somewhere.

Also, presumably things worked fine until you updated to `4.4.*`?

**Comment by yunyundong** [comment]
@mingwandroid 
Sorry, I dont know your meaning. when I perform `conda install` in dos window, it can install some packages successfully. Maybe after I uptade conda, the issue occured. and befor update conda ,all the thing is ok.

**Comment by mbargull** [comment]
@mingwandroid is right about the parenthesis being the problem -- PR incoming..
(The missing `\` I mentioned earlier are likely just due to Markdown rendering..)

**Comment by yunyundong** [comment]
@mingwandroid  How can I fix the problem?

**Comment by mingwandroid** [comment]
Try a different folder please, e.g. from cmd.exe run:

```
cd %UserProfile%
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe', 'mc3.exe') }"
start /wait "" mc3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=0 /S /D=%UserProfile%\anaconda3
%UserProfile%\anaconda3\Scripts\activate.bat
conda install -y anaconda=5.0.1 conda-build _ipyw_jlab_nb_ext_conf
```

**Comment by yunyundong** [comment]
@mingwandroid  In my computer, there are many conda.exe, because I have many virutal environments. the `conda inifo --envs` will print the following information:
base                  *  C:\Program Files (x86)\Anaconda2
cs231n                   C:\Program Files (x86)\Anaconda2\envs\cs231n
py27                     C:\Program Files (x86)\Anaconda2\envs\py27
py35                     C:\Program Files (x86)\Anaconda2\envs\py35
py36                     C:\Program Files (x86)\Anaconda2\envs\py36

when I `cd` to the path including the `conda.exe`, the `activate` command also does not work.

**Comment by mingwandroid** [comment]
You need to clean up your old installations of Anaconda or Miniconda and in future elect not to add Anaconda to your PATH. You should install for Just Me, and should avoid paths with spaces, `(` or `)`.

First uninstall any Anaconda you have installed from the Control Panel.

Then from cmd.exe, run:

`where python.exe`

Then, for each one, remove the entry from your PATH environment variable and also remove any other PATH entries that are clearly for Anaconda.

**Comment by yunyundong** [comment]
hmm, but previously, conda and activate works well!

**Comment by mingwandroid** [comment]
I believe this is a bug introduced in `conda 4.4.*` but it is a bug you can probably avoid if you are careful and follow my instructions.

**Comment by yunyundong** [comment]
I see. uninstall my anaconda is a hard work. can I uninstall conda ,then roll back to lower version of conda, such as `conda 4.3`?

**Comment by mingwandroid** [comment]
You could force reinstall the latest Miniconda (4.3.31) on top of your existing installation then from the `Anaconda Prompt` run:

`conda config --set auto_update_conda False`

**Comment by mbargull** [comment]
You could copy your
`C:\Program Files (x86)\Anaconda2\Library\bin\conda.bat`
to
`C:\Program Files (x86)\Anaconda2\Library\bin\conda-yunyundong.bat`,
apply the changes I proposed in #6722 to that `conda-yunyundong.bat` and run
`conda-yunyundong activate`/`conda-yunyundong install`/... instead of just using `conda` until the changes are incorporated into `conda`.
Note that this is unintended usage though, thus you can't expect further support for that one..

Otherwise, I'd assume the issue is likely to get fixed in some future update.

**Comment by yunyundong** [comment]
@mbargull  Thank you! I get it.

**Comment by Philtard** [comment]
Just wanted to add a remark, that an anaconda installation done and managed by the visual studio 2017 installer results in the same error message, because the default directories the visual studio 2017 installer sets python up to default to:

```Powershell
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts>conda info

     active environment : base
    active env location : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64
       user config file : C:\Users\phili\.condarc
 populated config files : C:\Users\phili\.condarc
          conda version : 4.4.7
    conda-build version : 0+unknown
         python version : 3.6.4.final.0
       base environment : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\pkgs
                          C:\Users\phili\AppData\Local\conda\conda\pkgs
       envs directories : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs
                          C:\Users\phili\AppData\Local\conda\conda\envs
                          C:\Users\phili\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False
```

Since the Fix for 4.4.8 will get rid of the problem, I'm just wondering if there will rise any problems updating from 4.4.7 to 4.4.8. I'm no expert in how Visual Studio handles the actual update of their 3rd party libs, but if the Installer just executes `conda update conda` finding conda.exe through the $PATH and not by first setting the current working directory to the one conda.exe is in, same error comes (plus the line '\Microsoft was unexpected at this time.'):

```Powershell
F:\>conda update conda
\Microsoft was unexpected at this time.

F:\>    @SET "_CONDA_EXE="C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Library\bin\..\..\Scripts\conda.exe""

F:\>
```

... also Anaconda Navigator isn't happy about it, suggesting update and restart of itself but failing silently.

**Comment by mamafanfan** [comment]
I encountered exactly the same issue as @Philtard did. 
 
>C:\Users\twoce\OneDrive\Documents>conda list
\Microsoft was unexpected at this time.

>C:\Users\twoce\OneDrive\Documents>    @SET "_CONDA_EXE="C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Library\bin\..\..\Scripts\conda.exe""

It seems like a **path** problem but I do not know how to fix it. I have to manually changed to the ..\Scripts\ directory and execute conda and everything seems to be working alright.

How to change `@SET`? Is it through `conda config`? I think this is where the problem comes from.

I installed anaconda in Visual Studio 2017 on Windows 10 64-bit (latest).

**Comment by Philtard** [comment]
Ah, i guess i caused more confusion, then help. Workaround for now (4.4.7), just manually do what the pull request's supposed to replace which comes with the 4.4.8 release:
1. click here: [[https://github.com/conda/conda/commit/cc54f5b5ca84cbe10224f57800202e7aee70e161](https://github.com/conda/conda/commit/cc54f5b5ca84cbe10224f57800202e7aee70e161)]
2. manualy change the file as shown and voilá, `conda <whatever>` from the prompt should work again.

The concern I was having was, whether or not people will run into problems upgrading from 4.4.7 to 4.4.8, ... just raising the question i guess, I'm not very familiar with any of the involved technologies.

Since this issue is closed, contains a fix coming with 4.4.8 and you (an I) got 4.4.7 running right now, should just take a deep breath and remove 2x2 '"' characters from that batch file and let go of this issue.

**Comment by kalefranz** [comment]
I'm pushing conda 4.4.8 to `defaults` right now.  It was released into `conda-canary` earlier today.

**Comment by mamafanfan** [comment]
thanks. taking out the double quotes works!!

**Comment by CatChenal** [comment]
I used Anaconda3-5.2.0-Windows-x86_64.exe on my new Windows 10 laptop to install anaconda.
The file Scripts\activate.bat is missing, therefore cannot be run.

I would like to know the contents of this file in order to recreate it locally.
Where is this file in the repo?

Thanks for your help.
