### ISSUE TITLE
Conda (4.4): 'No such file or directory' in a new environment using non-shell process

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#6810]
**I'm submitting a...** (I don't know whether it is a bug or feature)
  - [x] bug report
  - [x] feature request

### Steps to Reproduce

Create an environment, 'test' using Conda 4.4, open a new tab and directly activate that environment. Now try to invoke conda commands using any non shell program (lua/python/java/....) it will error out saying `conda: command not found` or `No such file or directory` since they can't `exec()` that.

## Expected Behavior

The program invoking conda should not error out, or should have a way to figure out where the conda  program resides, so that it can exec the full `/path/to/conda`. Currently the only thing close to this is `$_CONDA_EXE`, but it is not documented, and also not exported, so not available to child processes and no guarantee whether it will be available in future releases.

The current work around is to first activate the base environment and then activate the non-base environment in the same shell session, which for whatever reason, retains the root environment's bin directory in the PATH.

**Comment by kalefranz** [comment]
In conda 4.4, posix shells should be initialized via `. <CONDA_BASE_PREFIX>/etc/profile.d/conda.sh` in a `~/.bashrc` file, etc.

**Comment by nehaljwani** [comment]
One way to do this right now, is to exec():

```
os.environ['CONDA_PYTHON_EXE'] -m conda <conda arguments>
```

**Comment by kalefranz** [comment]
I think we just need to add a `CONDA_EXE` environment variable alongside the `CONDA_PYTHON_EXE` environment variable management in `conda/activate.py`.

**Comment by mbargull** [comment]
I didn't get at first, what was requested, but essentially it's the following difference:
```bash
$ (. etc/profile.d/conda.sh && conda activate base && conda --version)
conda 4.4.9
$ (. etc/profile.d/conda.sh && conda activate env && conda --version)
conda 4.4.9
$ (. etc/profile.d/conda.sh && conda activate base && bash -c 'conda --version')
conda 4.4.9
$ (. etc/profile.d/conda.sh && conda activate env && bash -c 'conda --version')
bash: conda: command not found
```
In the last case the `base` environment (and thus `conda`) isn't on `PATH` (which is a nice `4.4` feature, IMHO!) and we're not trying to run `conda` in a `bash` instance that has the `conda` shell function available; i.e. that `bash -c` represents one arbitrary program that tries to run `conda`.

To me it would make sense to have a `$PREFIX/bin/conda` script in each environment which would `exec` the `base` `conda`. Those scripts could be made into a package, e.g., called something like `conda-launcher`/`conda-scripts`/???. The problem with that would be that, as of know, non-`base` environment have (on their own) no knowledge of the `base` prefix. So you'd either have to use that `CONDA_PYTHON_EXE` workaround with something like:
```bash
#!/bin/bash
exec "$CONDA_PYTHON_EXE" -m conda "${@}"
```
or hardcode the base prefix at install time. As for the former, I don't think there are guarantees that `CONDA_PYTHON_EXE` must be available (and I would rather have `conda` be called instead of that "Python implementation detail"). For the latter, I don't think the base prefix is exposed to post-link scripts or the like.
A third possibility would to always put some directory from `base` on `PATH` that contains some `conda` even if a non-`base` environment is activated. Preferably (to retain that `4.4` feature) this wouldn't be `$CONDA_ROOT/bin` so that only `conda` but nothing else pollutes `PATH`.
In any case (and if I'm not mistaken -- which could very well be) I think a change `conda` would be needed for this feature.

**Comment by mbargull** [comment]
> I think we just need to add a `CONDA_EXE` environment variable 

That would be much preferred in lieu of `CONDA_PYTHON_EXE`, yes!

**Comment by kalefranz** [comment]
> To me it would make sense to have a $PREFIX/bin/conda script in each environment which would exec the base conda.

I hadn't thought of that option.  I'm going to think more about it.

> A third possibility would to always put some directory from base on PATH that contains some conda even if a non-base environment is activated.

I *had* thought of that option.  And was thinking about implementing it as part of https://github.com/conda/conda/pull/6518

**Comment by mingwandroid** [comment]
> A third possibility would to always put some directory from base on PATH that contains some conda even if a non-base environment is activated

Please, no.

**Comment by kalefranz** [comment]
I think having a smart conda executable in every conda environment probably makes the most sense.  I think we're going to run into unanticipated problems with that though too.

For example, I had a problem with `os.execv()` on Windows.  See https://github.com/conda/conda/issues/6607

**Comment by kalefranz** [comment]
I guess one edge case would be users expecting to have `conda activate` available when hitting this executable, which it wouldn't be, because we're hitting the executable rather than the shell function.  We probably just need to have clear messaging there explaining the problem.

**Comment by mbargull** [comment]
> because we're hitting the executable rather than the shell function

At least in `bash` I think the shell function takes precedence.

**Comment by kalefranz** [comment]
The way to implement this is to create a new `PathAction` that creates this stub executable if it doesn't exist.  We need to watch out for a gotcha with the `reverse()` method, because something that triggers `reverse()` on `conda create` should remove the file, while something that triggers `reverse()` on `conda install` probably shouldn't.

Basically, we need a flag in the `execute()` method to indicate whether the file was created, or whether it already existed.  If it was newly created, `reverse()` should just remove it.

**Comment by kalefranz** [comment]
> At least in bash I think the shell function takes precedence.

I think it always does for all shells I know of that support functions and aliases.  The problem will be encountered when you're not interacting with conda through a shell though.

**Comment by kalefranz** [comment]
If all we're doing is adding a new environment variable to be managed alongside `CONDA_PYTHON_EXE`, I consider that an enhancement, which can go into any patch release.  If we're adding a new `PathAction`, I consider that a feature which will need to wait for a feature release.

**Comment by mbargull** [comment]
> The problem will be encountered when you're not interacting with conda through a shell though.

Since `conda activate`'s job is to modify the shell's environment in currently runs in, a user should expect anything if they run it in a non-shell context 😉 -- but outputting an appropriate error message never hurts.

**Comment by mbargull** [comment]
> If we're adding a new `PathAction`, I consider that a feature which will need to wait for a feature release.

Yes, please. If such a change will be added at some time, I'll have to remember to ping @bgruening about this; in Bioconda, for each package a Docker [Biocontainer](https://biocontainers.pro/) is created -- so this would be a use case where we would want such a launcher.

**Comment by mbargull** [comment]
Well, I think I'm already too much in the `4.4.x` mindset and only now realize/remember that with `4.3.x` we have
```bash
$ . bin/activate 
(root) $ conda --version
conda 4.3.34
(root) $ conda create -qynempty
 

Package plan for installation in environment /home/maba/code/conda/conda-forge/envs/empty:


(root) $ ls -la envs/empty/bin/
total 8
drwx------ 2 maba maba 4096 Feb 14 20:00 .
drwx------ 4 maba maba 4096 Feb 14 20:00 ..
lrwxrwxrwx 1 maba maba   46 Feb 14 20:00 activate -> /home/maba/code/conda/conda-forge/bin/activate
lrwxrwxrwx 1 maba maba   43 Feb 14 20:00 conda -> /home/maba/code/conda/conda-forge/bin/conda
lrwxrwxrwx 1 maba maba   48 Feb 14 20:00 deactivate -> /home/maba/code/conda/conda-forge/bin/deactivate
```
. So bringing back the `conda` symlink wouldn't be such an unexpected thing. Some could even categorize its absence as a regression in 4.4, I guess.

**Comment by kalefranz** [comment]
I think I favor a specific directory that we add to PATH when we first initialize the shell (e.g. source `conda.sh`), rather than making some type of brittle pointer to where conda is supposed to live in the environment at environment creation time.  However I know Ray prefers the latter.

**Comment by kalefranz** [comment]
Another thing to be aware of here... Conda 4.4 lifted the restriction that conda could only be installed in the base environment.  That restriction came about because of the symlinking behavior on activate, and now that we're not doing that, we also don't need the restriction.  Since there's been a strong driver for conda to be both an *application* and a *library* (with the push to have stable internal APIs), lifting the restriction makes sense.

As a future improvement, it might make sense for conda *not* to include the `bin/conda` entry point when conda isn't installed into the base environment, to further enforce it's use as a library in non-base envs.

**Comment by nehaljwani** [comment]
The only solution I like so far:
>I think we just need to add a CONDA_EXE environment variable

I can't think of any any downsides with it.
