### ISSUE TITLE
stack trace with `conda clone` if package doesn't exist

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#685]
I have a bundle with an `info/index.json` file that contains this entry in its `depends` list:
```
    "fiona 1.1.2 py27_0",
```

When I use `conda clone` to re-create this, I get a KeyError from `conda.plan`:

![screenshot 2014-04-24 11 24 12](https://cloud.githubusercontent.com/assets/293525/2791380/33983a14-cbc6-11e3-95f6-93f5ab51915a.png)

https://www.dropbox.com/s/2ztva1zekiv6jj0/Screenshot%202014-04-24%2011.24.12.png

I'm using conda 3.4.2 on Wakari.

This error appears to be because `fiona 1.1.2` does not exist in the default conda repositories, in particular it is not here:

http://repo.continuum.io/pkgs/free/linux-64/

1.1.3 and 1.1.4 are there, which makes it look a little like 1.1.2 may have been there once upon a time (when the bundle was created) but has since been removed. (is that possible? if so, that isn't so good!)

In any case, the stack trace shouldn't be handed back to the user, and since it is quite reasonable that some arbitrary dependency list is not necessarily going to specify packages that some subsequent user can "see", this condition should be handled more gracefully.  Maybe conda options to mask/ignore part (or all) of a package spec versioning would be nice: `--ignore-patch`  `--ignore-minor` `--ignore-major`.

**Comment by kyleabeauchamp** [comment]
FWIW, I get the exact same stack trace when trying to clone an enviroment that contains locally-built packages (`conda install --use-local`).

**Comment by ijstokes** [comment]
@mcg1969 believes that recent updates to conda and the "clone" mechanics should have solved these problems, but I'm leaving this open until someone more "in the know" can say they think this issue is resolved.

**Comment by mcg1969** [comment]
To be clear, I don't think we should ever promise `--clone` to work for packages whose source no longer exists. So for example, if you build a package locally, install it, and then _remove_ the package from your build directory, `--clone` may eventually fail.

I say "eventually" because when a local package is installed, the tarball is copied into the package cache and tagged with its `file://` URL. As long as that package cache entry still exists, it should still be cloneable. But if anything happens to the cache, and it needs to retrieve that tarball again, it will expect it to exist in its original location.

**Comment by kalefranz** [comment]
Should be fixed with #2428 and 4.1.0rc2.

    conda config --add channels conda-team
    conda update conda conda-env

**Comment by kalefranz** [comment]
Also, agree with @mcg1969.  If the package cache has been cleared with `conda clean` or otherwise corrupted, the various combinations of `--use-local --offline --copy` will necessarily fail to clone without access to the remote repos.
