### ISSUE TITLE
Consider tuning solver package count minimization passes

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6890]
From @mingwandroid via https://github.com/conda-forge/pygridgen-feedstock/issues/10#issuecomment-365983589:

> We call these packages 'Core Dependency Tree' packages and they are never installed at runtime (only ever at build-time).
>
> @kalefranz, any comment on the solver issue? From what I know, I really dislike this minimize number of packages (or is it minimize change of number of packages?) heuristic as it naturally prefers less well split up package sets and static libraries over shared ones.

**Comment by kalefranz** [comment]
CC @mcg1969

**Comment by mingwandroid** [comment]
This [link](https://github.com/conda-forge/pygridgen-feedstock/issues/10#issuecomment-365973363) is probably most relevant.

**Comment by mcg1969** [comment]
I can’t accept the explanation offered in the linked issue without further evidence. Yes, conda favors fewer packages, but it favors higher versions and higher channel priorities more.

That said, I do have one idea that may help. Right now we do two “version” passes: one for the requested packages and one for everything else. I would suggest that more levels may be warranted; e.g.

1. Requested packages
2. Any other package that has ever been requested
3. The top level dependencies of any of the packages in 1 & 2
4. Any other dependencies

Layer 4 might even have multiple levels, a sort of breadth-first search in the dependency tree.

The point is that the lower level the dependency is, the less important it’s version maximization ought to be considered. Or put the other way, the higher up the tree we go, the more important its version should be.

**Comment by mcg1969** [comment]
And I will say again: if a conda recipe results in a non-functioning environment, it is never the fault of the optimization passes. It is always the fault of the dependency metadata.

The optimization passes may not do the best job at picking the best set of packages, but it _must_ be able to assume that all of the choices available to it are functioning.

**Comment by kalefranz** [comment]
> The point is that the lower level the dependency is, the less important it’s version maximization ought to be considered. Or put the other way, the higher up the tree we go, the more important its version should be.

I'm not sure this is true.  I definitely want python 3.6.4 instead of python 3.6.1.  I definitely want the latest openssl.

**Comment by mbargull** [comment]
I'm with @mcg1969 on this.
> I can’t accept the explanation offered in the linked issue without further evidence. Yes, conda favors fewer packages, but it favors higher versions and higher channel priorities more.

If they still see that behavior, I could imagine they rather hit a feature-requiring package (like, e.g., a `numpy` dependency that will rather be fulfilled by `defaults` since `conda-forge`'s uses the `openblas` feature) than one with fewer dependencies. The other less likely possibility would be that something was preferred due to inducing less *updates*, not packages in general with https://github.com/conda/conda/blob/4.3.10/conda/resolve.py#L908-L917.

>  I definitely want python 3.6.4 instead of python 3.6.1. I definitely want the latest openssl.

Would you not then either have
* requested that `python` directly in that transaction (proposed level "1. Requested packages"), or
* `python` explicitly installed before (proposed level "2. Any other package that has ever been requested"), or
* `python`/`openssl` in `aggressive_update_packages`?

If none of the three above is true, why would one assume you want the latest version of that package? (I think the sole indication would be -- if one would know semver applies -- that you want patch releases; that source of information isn't available yet, though..)

**Comment by mingwandroid** [comment]
My attempts to reproduce this failed. I am able to create an env with conda-forge's qt using:

`conda create -n pygridgen python=3 pygridgen`

.. so long as I have `conda-forge` above `defaults` in my `~/.condarc` and also if I have no `~/.condarc` and instead use:

`conda create -n pygridgen python=3 pygridgen -c conda-forge`

Sorry for the noise. I will add this exact same comment (apart from this line) over at the original issue report.

**Comment by mcg1969** [comment]
> I'm not sure this is true. I definitely want python 3.6.4 instead of python 3.6.1. I definitely want the latest openssl.

Honestly, I'm not as worried about details like this. Packages that are properly designed are not going to be pinned to x.x.x releases of a piece of software _unless there is good reason for them to be_.

So for instance, supposed I have a package `foo` and version 1.0 is tied to `python 3.6`, and version 2.0 is tied to `python 3.6.1`. Let's assume the package maintainer knows what he's doing here---there was a reason why it was important to pin to that version of Python. Well, If I do `conda install foo`, I _expect_ Python to get pinned to 3.6.1 as part of that transaction. I do not want it deciding that I should accept `foo 1.0` just so I can get the latest version of Python.

So that's just a 2-level version optimization consideration. But I think the thinking maps to multiple levels quite nicely.
