### ISSUE TITLE
Excessive INFO output on activate/deactivate

### ISSUE THREAD

**Issue by oscarbranson** [conda/conda#6945]
**I'm submitting a...**
  - [X] bug report
  - [X] feature request

## Current Behavior
After upgrading to `conda 4.4.7` on Linux, there is excessive `INFO` output to terminal when using `source activate`/`deactivate`.

Output is generated by:
- `L151-152:` miniconda3/pkgs/gcc_linux-64-7.2.0-25/etc/conda/activate.d/activate-gcc_linux-64.sh
- `L109-110:` miniconda3/pkgs/binutils_linux-64-7.2.0-25/etc/conda/activate.d/activate-binutils_linux-64.sh
- `L114-115:` miniconda3/pkgs/gxx_linux-64-7.2.0-25/etc/conda/activate.d/activate-gxx_linux-64.sh

### Steps to Reproduce
Use `source activate env` or `source deactivate`. Output of `source activate env`:
```
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2
+CPP=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og
+GCC_AR=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_NM=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC_RANLIB=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+HOST=x86_64-conda_cos6-linux-gnu
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
+_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu

INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-gprof
+LD_GOLD=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+LD=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-ld
+NM=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-strip

INFO: activate-gxx_linux-64.sh made the following environmental changes:
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CXX=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-c++
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
+GXX=[miniconda/path]/envs/env/bin/x86_64-conda_cos6-linux-gnu-g++
```

## Expected Behavior
I don't need this information *every* time I use `activate` or `deactivate`. This output should be optional, rather than default behaviour?

Temporary workaround by commenting out the offending lines, but this isn't very satisfactory.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /home/[user]/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /home/[user]/miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/[user]/miniconda3/pkgs
                          /home/[user]/.conda/pkgs
       envs directories : /home/[user]/miniconda3/envs
                          /home/[user]/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.4 Linux/4.15.3-1-ARCH arch/rolling glibc/2.26
                UID:GID : 1000:100
             netrc file : None
           offline mode : False


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
[no output]
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
[no output]
```
</p></details>

**Comment by kalefranz** [comment]
@mingwandroid Any thoughts here either way?

**Comment by kalefranz** [comment]
I mean, I can write output to `/dev/null` if there's not a `-v` flag passed on activate, for example.  But swallowing everything could also have unintended consequences.

**Comment by mingwandroid** [comment]
This info is important so as not to surprise people who suddenly find their system compilers not getting used. We could implement some log level variable but I would want this text to appear by default.

**Comment by mingwandroid** [comment]
I also like that we are giving people exposure to a set of secure and fast compilation flags.

**Comment by mbargull** [comment]
>  But swallowing everything could also have unintended consequences.

Yes, that would be a breaking/unexpected change.
But I think it would be sensible to suppress (`>/dev/null`) the output if `context.quiet` is set (for now only possible with `CONDA_QUIET=1 conda activate` as we currently don't allow any additional arguments to `conda activate`).

**Comment by oscarbranson** [comment]
Did something change in `4.4.7`? I'm puzzled, because previous versions didn't print out all this info, and yet you're talking about it as if it's essential.

FYI, I 'fixed' this in a more elegant way by using a `CONDA_QUIET=1` environmental variable in my .bashrc, as per @mbargull's suggestion. I wrapped each of the offending `echo` statements in:

```bash
if [ "${CONDA_QUIET}" = "0" ]; then
  echo "INFO: $(_get_sourced_filename) made the following environmental changes:"
  diff -U 0 -rN /tmp/old-env-$$.txt /tmp/new-env-$$.txt | tail -n +4 | grep "^-.*\|^+.*" | grep -v "CONDA_BACKUP_" | sort
fi
```

Could this be a (semi)-permanent fix? Happy to implement, if you guys are busy with more important things.

**Comment by mbargull** [comment]
No, it's not something that changed in newer versions of `conda`. It is not `conda` itself that outputs those messages but the compiler's activate script. So you didn't see those messages before simply because you hadn't installed one of the newer compiler packages.

**Comment by oscarbranson** [comment]
What do you folks reckon to my solution above? Shall I implement this, or leave it to you guys? If yes, could you point me towards where the activate scripts live?

**Comment by ozancaglayan** [comment]
This is absolutely disturbing. I was just trying to create a fresh python environment to install a library. At some point  - i dont know why - , conda started to tell me that I need to use conda activate and I need to remove the old way of PATH exporting. I don't remember installing any compiler package today into my root environment. But maybe I did it before and the messages got triggered once I switched to the new way of activating environments?

Now everytime I launch a tmux window - which is something that I want very frequently on the cluster - I see 100s of those lines flowing in front of me.

**Comment by kalefranz** [comment]
> Now everytime I launch a tmux window ... I see 100s of those lines flowing in front of me.

I can see how that would be quite annoying.

**Comment by mbargull** [comment]
@oscarbranson, as a workaround you could
* remove that `conda activate ...` in your shell init script,
* just remove those packages from the environment that gets automatically activated,
* replace that `conda activate ...` in your shell init script with `conda activate ... >/dev/null`,

**Comment by krinsman** [comment]
Just wanted to mention that this type of output also occurs (at least on my system) for clang and gfortran, not just gcc, and that maybe a one-line warning like: 

```
Note: Environment is using different compilers than system default. Check the output of <automatically generated log file> for details.
```

might be less distracting for some users, while not making the important information inaccessible.

**Comment by matrs** [comment]
I just installed miniconda, and then I created a new environment where I installed the full anaconda meta-package. I expect anaconda using its own compilers because that guarantees all the installed packages will work as anaconda expects, which is good. So why I need to see all this information every time I activate/deactivate an environment? this should be optional. These Aren't errors, so I don't know why are printed to stdout by default. We are not debugging.

By the way, conda says it
https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html

**Comment by mingwandroid** [comment]
> These Aren't errors, so I don't know why are printed to stdout by default

Errors get printed to stderr, I even prefix them all with `INFO` to clear up any confusion. I am informing people so they are not surprised when their system compilers are not used.

The compilers are not dependencies of the `anaconda` meta-package though, only some runtime parts and none of those emit anything to stdout (or stderr).

**Comment by matrs** [comment]
Stop giving information to users if they didn't  ask for it.  If libgcc-ng or libfortran are part of anaconda, it's ok, we expect to anaconda make changes when we use its packages. Give information to the users who asked for it. Print errors by default, that was my point. 
I said "these aren't errors " so why are you printing them by default?. That was my point. **Why are you printing information to stdout by default** without using a `info` or a `verbose` flag?

**Comment by mingwandroid** [comment]
I am not opposed to having some verbosity level for conda activation FWIW, but since we do not have anything I am of the opinion that these prints should remain until we do.

**Comment by matrs** [comment]
I didn't add my new miniconda installation to my path. I created a new environment and that environment only has the anaconda meta-package installed, nothing else. Now, every time I activate that environment, I'm seeing dozens of lines telling me that dozens of variables like `CXXFILT`, `GFORTRAN`  plus a bunch of compilers flags are being set. All those variables point to the environment path, which is expected. Why do i need to see that everytime? 

So do you think that the number of people in this thread is related to the number of people annoyed by this bunch of information? it's simple to avoid, you just redirect the output, so you do that. Still, you don't see why every tool in Unix doesn't print this kind of `info` by default without the explicit use of an option to print information?

**Comment by mingwandroid** [comment]
Sorry, but you *have* got compilers installed, conda list will show you that. I'm more concerned about bugs affecting people and them wasting significant amounts of time because we set some env vars they didn't expect than other people seeing some text they have a hard time ignoring.

But I'm also happy to have a verbosity level option. Until then I do not wish to change this.

If you want to contribute this verbosity level feature to conda to expedite "fixing" this "problem" then please go ahead.

**Comment by matrs** [comment]
I'm aware that this is an open source project and everybody can try to contribute to it, i never tried to make you or other specific person to fix it. I just expected something like, "we will work on it when we can", but i found that, at least for you, it isn't a problem, which is surprising but It's ok for me.

Now i'm redirecting the output, why to spend the time to "fix" this "problem" ;)

**Comment by mbargull** [comment]
I was a bit startled as to why a "non-developer" user would end up with the compiler packages being installed. Then I remembered @mingwandroid's comment at https://github.com/conda/conda-build/pull/2686#issuecomment-366997040. So... I guess it's not that unlikely that users (the R-using kind) experience this:
```
$ conda info r-base=3.4.3                                                                                                                                                                                                                                          

r-base 3.4.3 h290ecf8_0
-----------------------
file name   : r-base-3.4.3-h290ecf8_0.tar.bz2
name        : r-base
version     : 3.4.3
build string: h290ecf8_0
build number: 0
channel     : https://repo.anaconda.com/pkgs/r/linux-64
size        : 41.1 MB
arch        : x86_64
constrains  : ()
license     : GPL-3.0
license_family: GPL
md5         : aab40b43659333d0c68ab7bafeb19bba
platform    : linux
subdir      : linux-64
timestamp   : 1519519447397
url         : https://repo.anaconda.com/pkgs/r/linux-64/r-base-3.4.3-h290ecf8_0.tar.bz2
dependencies:
    _r-mutex 1.* anacondar_1
    bwidget
    bzip2 >=1.0.6,<2.0a0
    cairo >=1.14.12,<2.0a0
    curl
    gcc_linux-64
    gfortran_linux-64
    glib >=2.53.6,<2.54.0a0
    gsl
    gxx_linux-64
    icu >=58.2,<59.0a0
    jpeg >=9b,<10a
    krb5 1.14.*
    krb5 >=1.14.2,<1.15.0a0
    libcurl
    libcurl >=7.58.0,<8.0a0
    libgcc-ng >=7.2.0
    libgfortran-ng >=7,<8.0a0
    libopenblas >=0.2.20,<0.2.21.0a0
    libpng >=1.6.34,<1.7.0a0
    libssh2 1.*
    libssh2 >=1.8.0,<2.0a0
    libstdcxx-ng >=7.2.0
    libtiff >=4.0.9,<5.0a0
    libxml2 >=2.9.7,<2.10.0a0
    ncurses 6.0.*
    ncurses >=6.0,<7.0a0
    pango 1.*
    pcre
    readline 7.*
    readline >=7.0,<8.0a0
    tk 8.6.*
    tk >=8.6.7,<8.7.0a0
    tktable
    xz >=5.2.3,<6.0a0
    zlib >=1.2.11,<1.3.0a0
```

**Comment by mingwandroid** [comment]
Yes, for sure, R users will get this because I got tired of people having too old, broken or no compilers and trying to install R packages from the REPL, and I agree that's a *little* unfortunate for users of R who never build their own packages.

Thing is @matrs said these messages appear with nothing more than Miniconda and the anaconda meta-package installed and that should not be the case. I asked for `conda list` but that's not been provided either.

Anyway, we need to carefully balance these conflicting requirements and I still feel that printing this stuff is better than not printing it. It's just text, and while I appreciate that it may be annoying for some, for those who spot it and pay heed to it, I believe it could save them a lot more than just some annoyance (I am talking table flipping levels of annoyance for hours spent debugging issues and the final result of "what the heck are you idiots doing *silently* changing the compiler that's being used here?")

**Comment by kalefranz** [comment]
> what the heck are you idiots doing silently changing the compiler that's being used here?

Do you want anything added to `conda info`?  Information you can demand as a baseline for starting to debug somebody's problem?

**Comment by mingwandroid** [comment]
Well the packages will show up in conda list and we always ask for that anyway so I think we're good.

Having an activate verbosity feature that the scripts can query would be great though.

**Comment by mileserickson** [comment]
This is happening to me after upgrading to OS X High Sierra. Very obnoxious. Did the default log level change in `clang` or something?

**Comment by cwwalter** [comment]
I just wanted to point out that this doesn't just show up on explicit activate/deactivate commands.  I also see it when I do (for example) 'conda update anaconda' when I am in an environment with the compilers.  In this case conda seems to be deactivating and activating the (non base) environment.  This makes the system really hard to use as (for example) the one line

# All requested packages already installed.

is then followed by ~100 lines of environment variable info log lines.

**Comment by fperez** [comment]
Just to add a note that I think this amount of verbose info is causing serious usability issues in every day practice (and it's hitting fairly vanilla use patterns beyond developers, as any installation of the base R package will lead to this).

There are really two problems with the current mode:

- the amount of verbosity is enough to become seriously annoying when switching environments frequently.

- it's very easy for all this to drown another relevant message, especially since having this much info come out on every activation is basically training my brain to simply ignore *anything* that gets printed.

Absent a controllable verbosity flag right now, I think a simple compromise solution could be to print a single line that says:

```
Your compiler defaults have changed, for more see: /path/to/info/file.txt
```

A *single* file can be generated on env activation with all this stuff somewhere inside the env. 

I bet this would eliminate the issue for most users, and for anyone who actually needs to read that information, it's actually easier to type

```
grep CPPFLAGS  /path/to/info/file.txt
```

than to scan in terminal output.

I hope this is useful - I can't contribute to conda at this time, but I think the above solution could be implemented relativel easily, without needing the system to support a verbosity flag throughout. I had a look at the activate scripts, and it would be a matter of redirecting their diff output to a file. 

HTH!

**Comment by kalefranz** [comment]
@mingwandroid I think we’re going to have to find a solution here. Conda does “reactivate” after install/update/remove, so I can see how this could start to create a situation where people start ignoring all conda output, and we definitely don’t want that.

**Comment by mingwandroid** [comment]
Yeah, I agree, we just haven't had time yet to implement anything here. We need some verbosity flag passed to the activation scripts here.

We also see this when conda does no-ops though (attempting to install things already installed, attempting to remove things that are not installed), and in those situations I don't think we should be running any activate scripts.

I'll remove it since enough people are complaining, but I guarantee as soon as I do I will get loads of bugs reported about people using R and their system compilers not being used :-(

**Comment by Dubrzr** [comment]
Any update on this?

**Comment by mingwandroid** [comment]
I've not had any time to look at it yet, sorry.

**Comment by mingwandroid** [comment]
The compilers only echo this info now when `CONDA_BUILD` is set to `1`.

**Comment by fperez** [comment]
Just here to say thanks conda team for not ignoring these - I know you have a lot on your plate, but attention to these UI details is much appreciated.

**Comment by oscarbranson** [comment]
I agree. Thanks very much for listening to the feedback, and making this change.

**Comment by mingwandroid** [comment]
No problem! Because I am pedantic, I need to clarify that I am on the `Anaconda Distribution` team handling package building, package quality and low level security end to end (so compilers up to entire sub-ecosystem rebuilds and sometimes construction of final installers) primarily.

The conda team is a sub team of that, more or less, handling conda and conda-build. I contribute to the latter a good amount but not so much the former.

Cheers.

**Comment by kalefranz** [comment]
Someday we’ll get around to adding color to the conda UI too 🌈 :)

**Comment by aavanian** [comment]
I think the `CONDA_BUILD` set to `1` has only been implemented in the activate script, not the deactivate one (at least for gfortran).

version: `gfortran_osx-64                4.8.5                h22b1bf0_4 `

**Comment by gattia** [comment]
Any update on this?

**Comment by msarahan** [comment]
All of the activate and deactivate scripts are here:

Linux: https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-activation-feedstock/recipe
mac: https://github.com/AnacondaRecipes/aggregate/tree/master/gfortran-feedstock/recipe

as far as I can see, they all have logic to only show the output either when CONDA_BUILD is set, or when an error occurs:

https://github.com/AnacondaRecipes/aggregate/blob/master/gfortran-feedstock/recipe/deactivate-gfortran.sh#L113-L126

**Comment by daynefiler** [comment]
Can we get some more clarity on this? I have set CONDA_BUILD=0:

    conda env config vars set CONDA_BUILD=0

and I am still getting all of the change messages.

**Comment by luederm** [comment]
I am also still having this issue. 
It is more than an aesthetics thing. My analysis pipeline broke because it writes the info to files I am creating with the 'conda run' command.
