### ISSUE TITLE
Consider 'conda activate' should be able to activate virtualenv-created environments

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6984]
No reason we can't do this.  And could be a UX improvement for python users.

**Comment by mbargull** [comment]
I'm not so sure about this one. Could also be confusing for the user...
1. "Why doesn't `conda activate myvenv` work?"
   -> because `conda activate` needs env names or paths, i.e., `conda activate ./myvenv` should've been used.
2. "Why doesn't `conda activate ./myvenv && conda install pkg` install `pkg` into `myvenv`?"
   -> because you didn't activate a Conda environment; `pkg` might also have been installed into the underlying activated Conda environment or into `base`.

So, *if* that functionality would be added, we should have an information/warning message à la
```
Activating virtualenv './myenv' ...
Note that 'conda' commands will still be applied to the
Conda environment 'env' (/'base')!
```

An alternative would be to just detect that the user wants to activate an `virtualenv` environment and only prompt them with
```
Looks like you are trying to activate a virtualenv-created environment at './myenv'.
Please run << shell-specific activate, e.g., 'source ./myvenv/bin/activate' >> instead.
If you do so, please note that 'conda' commands will still be applied to the
Conda environment 'env' (/'base')!
```

**Comment by mbargull** [comment]
Oh and regarding 1. above, we could generally for a `conda activate $SOME_ENV` do
```
if $SOME_ENV contains `os.path.sep`
    activate $SOME_ENV
else
    if $SOME_ENV is a namend env
        activate $SOME_ENV
    else
        if ./$SOME_ENV/conda-meta exists
            activate ./$SOME_ENV
            or prompt the user to use "conda activate ./$SOME_ENV" instead
        else
            output the usual
                Could not find conda environment: $SOME_ENV
                You can list all discoverable environments with `conda info --envs`.
```
If you think that makes sense, we can create a separate issue to track that.
