### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict:   - contextlib2  - pygame Use "conda info <package>" to see the dependencies for each package.

### ISSUE THREAD

**Issue by goswami-rahul** [conda/conda#7015]
I found the following the error while installing pygame library. I am using Python 3.6 , Ubuntu.
After I uninstalled `contextlib2` to resolve the issue, now its with `lxml`.
What is happening?!
```bash
conda install -c cogsci pygame 
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - lxml
  - pygame
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by myakin** [comment]
i have the same issue on mac wit El Capitan.

UnsatisfiableError: The following specifications were found to be in conflict:
  - pygame
  - xlwings
Use "conda info <package>" to see the dependencies for each package.

Don't know what to do. Any ideas?

**Comment by goswami-rahul** [comment]
I created a new conda environment and installed pygame in it. It worked for me .

**Comment by mbargull** [comment]
You are right, using multiple environments should be the solution of choice.
The fact that `UnsatisfiableError` doesn't really show which package is the root cause of the conflict is tracked by some issue with the `solver-messaging` label:
https://github.com/conda/conda/issues?q=is%3Aopen+is%3Aissue+label%3Atag%3Asolver-messaging
