### ISSUE TITLE
In conda 4.6, change default value of max_shlvl to 0

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7194]
Conda 4.4 reworked shell environment activation, and unified sometimes differentiated behavior across shells and platforms.  Prior to conda 4.4, one particular behavior difference was that environments could effectively be "stacked" on unix/posix shells, whereas only a single environment at a time could be active in the cmd.exe shell.  Conda 4.4 unified the behavior, opting to keep effective behavior the same for unix shells, allowing cmd.exe to also have environments "stacked" on PATH.

The ideal situation is that, while a stack of active environments should be available to push onto and pop off of, only a single environment should be able to be active at any given time.

The purpose of this issue is to track introduction of a setting for `max_shlvl` of `0`.  The effect would be to have only one environment active at a time.  The proposal is to also make `0` the default value for `max_shlvl`.  Users are free to configure `max_shlvl` to `2` or more so that environments can be stacked on PATH as in conda 4.4 and 4.5.

**Comment by mingwandroid** [comment]
> The ideal situation is that, while a stack of active environments should be available to push onto and pop off of, only a single environment should be able to be active at any given time.

Could we think of providing `conda push env` and `conda pop env` and `conda stack env` and `conda unstack env` in the future to make these different modalities explicit?

**Comment by kalefranz** [comment]
Not a bad idea at all.  Although I don't think we necessarily need to introduce four new verbs in addition to the `activate` and `deactivate` we already have.  My preference would be to have `push` and `pop` just be the `activate` and `deactivate` we already have, and then add `stack` and `unstack`.

The logic might get kind of twisted.  Or the state a user can twist themselves into.  We'd have to work through that pretty carefully.

**Comment by kalefranz** [comment]
Or... Maybe the easiest way to help users not get into a tangled mess is to have on `activate`, `stack`, and `deactivate`.  Both `activate` and `stack` push onto the history stack, and have the difference of whether `PATH` is stacked or not.  In all cases `deactivate` pops one off the history stack and removes the top-most active environment from PATH.

I think it all just simplifies down to adding `stack`.

**Comment by mingwandroid** [comment]
SGTM. activate stack and push would be very confusing; I confused myself with them already!

**Comment by kalefranz** [comment]
Rather than add a new conda command, #7195 now just implements a `--stack` flag on `conda activate`.

**Comment by tjd2002** [comment]
Testing this on canary (4.6.0a2), and it appears that now: there is no stacking of PATHs, but there is an (unlimited) stack of envs, with no way to limit this stacking (since 'max_shlvl' is no longer a supported config option). 

This does not seem to be the behavior described in this issue, or in comments by @kalefranz at: https://github.com/conda/conda/issues/2502#issuecomment-395490219

```
$ conda activate env1 && echo $CONDA_SHLVL
1
(env1)$ conda activate env2 && echo $CONDA_SHLVL
2
(env2)$ conda activate env3 && echo $CONDA_SHLVL
3
(env3)$ conda deactivate && echo $CONDA_SHLVL
2
(env2)$ conda deactivate && echo $CONDA_SHLVL
1
(env1)$ conda deactivate && echo $CONDA_SHLVL
0
$  conda config --set max_shlvl 0
CondaValueError: Key 'max_shlvl' is not a known primitive parameter.
$ conda config --show|grep shlvl
$
```

**Comment by tjd2002** [comment]
Scratch that, I see that this is the desired behavior described above:
> The ideal situation is that, while a stack of active environments should be available to push onto and pop off of, only a single environment should be able to be active at any given time.

However, now that there's no stacking of PATHs, I don't quite see the value of maintaining this separate queue. I think there is something satisfying and intuitive about `conda activate env` being used to switch to a specific env, and `conda deactivate` actually *deactivating* conda (not just popping an env off the stack).

Could the default behavior in 4.6 to be equivalent to the old max_shlvl=1 behavior, instead?

I can see it being quite confusing for a user who may have switched back and forth between several environments while trying things out:

```
$ conda activate env1
(env1)$ conda activate env2
(env2)$ conda activate env3
(env3)$ conda activate env1
(env1)$ conda activate env2
(env2)$ conda activate env3
(env3)$ echo $CONDA_SHLVL
6
(env3)$ conda deactivate
(env2)$ conda deactivate
(env1)$ conda deactivate
(env3)$ conda deactivate
(env2)$ conda deactivate
(env1)$ conda deactivate
$
```
(There seems to be some special logic which treats a request to activate the most-recently active env as a pop, rather than a push, but it doesn't help in the general case).

Lastly, is there any way to inspect the stack?

**Comment by tjd2002** [comment]
Opened a new issue #7474
