### ISSUE TITLE
Conda's usage of ~/.conda is problematic

### ISSUE THREAD

**Issue by jkeller-miovision** [conda/conda#7392]
**I'm submitting a...**
  - [x] bug report
  - [x] feature request

## Current Behavior
During a recent upgrade from the conda 4.3.* series to 4.5.* I've noticed a change of behavior that causes environment isolation problems for our setup.  We use conda extensively to create multiple isolated conda installations for the same unix user.  The version of conda, and its configuration is a part of these environments, and we keep them isolated on the filesystem and in $PATH.  It appears that starting in conda 4.4.* environments listed in ~/.conda/environments.txt are listed when doing "conda env list", although they cannot be entered or deleted unless they were created by the conda installation in use.  Essentially I need to have multiple conda installations for the same user, and the use of a centralized config location per-user is causing inter-dependencies & wrecking havoc.  I'm not even sure if multiple conda installations interact with ~/.conda/ contents in a concurrency safe manner?

```

```

## Expected Behavior
Since conda is primarily concerned with providing isolated environments, I would expect there to be a way for conda itself to be limited to an environment or filesystem location.  If not the default, I would hope that this would at least be possible via some installation/base-environment specific setting.

Gotta keep 'em separated.

**Comment by kalefranz** [comment]
> It appears that starting in conda 4.4.* environments listed in ~/.conda/environments.txt are listed when doing "conda env list"

Yes, this is true.

> although they cannot be entered or deleted unless they were created by the conda installation in use

I don't believe this to be true.  Especially when you have multiple versions of conda floating around, it's important to think of environments having *locations* rather than environments just having *names*.  The implication is that, when addressing an environment, use the `-p` / `--prefix` flag rather than the `-n` / `--name` flag, or in the case of `conda activate`, use the full path to the environment.  The first column of `conda env list` (or `conda info -e`) is the environment *name*, whereas the second column is the *location*.  If an environment name isn't listed, it'll have to be referenced using the environment location.

> I'm not even sure if multiple conda installations interact with ~/.conda/ contents in a concurrency safe manner?

We don't have any locking in conda right now.  So accessing `~/.conda/environments.txt` is the least of my worries for having multiple conda processes running at the same time.  Tracking issue for that is https://github.com/conda/conda/issues/6742.

> Since conda is primarily concerned with providing isolated environments, I would expect there to be a way for conda itself to be limited to an environment or filesystem location. If not the default, I would hope that this would at least be possible via some installation/base-environment specific setting.

You didn't include the output of `conda config --show-sources` (or an exemplary output in your case).  Are you using default configuration across the board?  If so, and if the package cache directory and envs directory in the base environment aren't writable, conda by default will fall back to the `~/.conda` directory for both of those as well.

I don't think I've yet fully appreciated all your concerns here, but I'd like to.  So let's keep the dialogue going.

I do want to point out the *reason* for us recording environment location in `~/.conda/environments.txt`, and the reason (at least so far) we haven't made that configurable.  Running `conda info --envs` as UID 0 will list *every* known conda environment on your system.  It'll use `/etc/passwd` to get home directories for users, and then check for the `~/.conda/environments.txt` file.  Extending that further, running something like `conda search --envs 'openssl<1.0.2o'` will show every outdated conda-installed version of opennssl on the whole system, and the environment location of the environment it's installed in.

**Comment by jkeller-miovision** [comment]
Thanks for such a quick & thorough response @kalefranz !  I really appreciate it.  Up until now I have been creating/delete-ing/entering/exiting conda environments by name only - both manually and when scripting conda.  I have verified that my previous statement:

> they cannot be entered or deleted unless they were created by the conda installation in use

is not true - as you point out.   You can not manipulate those environments by name, but by location it does indeed work.  Good to know.

I believe that if I switch to using location/prefix in all my conda invocations, it will fix all of my current problems.

I do remain concerned that conda is unable to be configured to fully operate within the confines of conda's install location.  I like being able to be sure that when I install an environment & wipe it out that nothing else on the system has been modified.  For example,  if I have a CI/build machine that installs conda and bootstraps an environment, and then does not use conda to remove the environment, but rather wipes out the workspace, now there are stale/dangling references in ~/.conda/environments.txt.   I see on several of my machines that ~/.conda/environments.txt is full of non-existing entries due to conditions like this.

 I do understand your 'system-wide-search' use case, but it seems to place some forwards-compatibility constraints on how conda evolves in addition to increasing potential conda 'cross-talk' issues.

Again, I think my immediate problems are solved by switching away from using environment names.

Thanks!

**Comment by kalefranz** [comment]
> now there are stale/dangling references in ~/.conda/environments.txt

Yeah, that's true.  However, the next time you run `conda env list` / `conda info -e`, all those stale references should be cleaned up (if the file is writable), and in no case should `conda env list` ever report an environment that doesn't exist.

**Comment by kalefranz** [comment]
> I do understand your 'system-wide-search' use case, but it seems to place some forwards-compatibility constraints on how conda evolves in addition to increasing potential conda 'cross-talk' issues.

I'm actually not seeing how what we've implemented so far is limiting for us.  That doesn't mean it isn't; just that I don't see it.  Could you elaborate a bit more?

**Comment by jkeller-miovision** [comment]
> I'm actually not seeing how what we've implemented so far is limiting for us. That doesn't mean it isn't; just that I don't see it. Could you elaborate a bit more?

It may sound a little contrived, but consider the scenario where a newer conda, lets say conda 6, changes the way an environment works, for example maybe the entry mechanism is changed like the recent "conda activate" change.  Now conda6's environments are listed in environments.txt, and are thus visible to other conda installations using the same user (or UID 0).  Now if conda 4.5.x sees that conda6 environment, maybe it can not work correctly with it.  In order for this to work correctly all the time, environments created with future conda's must always be able to be 'used' by older condas -> especially since conda may not be in the environment itself.   This is what I mean by forwards-compatibility.

**Comment by kalefranz** [comment]
What you describe in that example is more what I would call *backward incompatibility*, which I would say is fair game for--and actually the reason for--major version bumps.  That is, a conda environment created with a newer version of conda may crash an older version of conda when that old version tries to operate on it.  Conda environments created with older versions of conda should *absolutely* be able to be operated on with newer versions of conda.  Always.

Taking a step back from what your current implementation and conda usage... If I were designing a system for multiple conda users on the same machine from scratch, I'd probably only have a single conda executable on the whole system.  Maybe just a basic miniconda environment at `/opt/conda`, and then symlink `/opt/conda/bin/conda` to `/usr/local/bin/conda`.  That environment is obviously read-only for non-privileged users, but still executable.  In this case, there's really no "default user environment" right now, and that's actually something we might need to fix.  Conda is available as a command, but `conda install` without creating/activating an environment first will fail with a permissions error.  In this setup, the default user-writable package cache is at `~/.conda/pkgs_dirs` and the default user-writable envs directory is at ` ~/.conda/envs`.  Of course those can both be configured to other places.

Speaking of configuration, conda has fairly advanced capabilities here.  You'll probably be interested to read the blog post at https://www.anaconda.com/blog/developer-blog/conda-configuration-engine-power-users/.

**Comment by nick-youngblut** [comment]
My research group has been running into this issue ever since the major changes implemented in conda v4.4. At the time, we couldn't update conda due to some issues with certain software installed via conda. Now we are all still using conda <4.4, which is resulting in it's own issues. All of the members of the group do not want to make the sudden major switch to conda >4.4, so we would like to transition to the newest version of conda. Thus, we currently have 2 conda installs (one version <4.4 and one is v4.5.9). Besides this, we also have a "developer" conda install that just for creating conda environments used to develop software. Having these 3 conda installs results in issues such as listing conda environments.
