### ISSUE TITLE
Documentation describes non-existent option

### ISSUE THREAD

**Issue by Bezier89** [conda/conda#7469]
It looks like the "allow_other_channels" option was removed (replaced by "whitelist_channels"?). However, there are still multiple places in the documentation that refer to and describe this feature, which is leads to confusion when one wonders why it's not working...

https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#allow-other-channels-allow-other-channels
https://conda.io/projects/conda/en/latest/user-guide/configuration/admin-multi-user-install.html#system-configuration-file

-----

To Do

- [X] Check if allow_other_channels and allowlist_channels are the same option (they aren't quite. allow_other_channels is a Boolean, while allowlist_channels is a list. allow_other_channels seems to have been completely removed from the .condarc, however)
- ~[ ] If so, add allow_other_channels to the alias list for allowlist_channels~
- [ ] Update doc pages listed above

**Comment by habemus-papadum** [comment]
I also had the same issue.    I was trying to use this option to create an "isolated as possible/reproducible" conda that prevented the user config from changing channel priorities.

**Comment by pdelaage** [comment]
This problem is still present in conda version 4.10.3 (conda -V or conda info) and current online documentation (by the 2021, 16 of November) here : https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#allow-other-channels-allow-other-channels.

Loading "allow_other_channels" flag from .condarc leads to "unknown key allow_other_channels" error message.

> more ~/.condarc
show_channel_urls: true
channels:
  - defaults
  - conda-forge

allow_other_channels: false

....
> **conda config --get
unknown key allow_other_channels**

Please, could the documentation state :
 1/  whether allow_other_channels flag IS or IS NOT still relevant ? if yes, there is an operational pb; if no, there is only a documentation consistency problem
and 2/ clearly describe how an admin can prevent non-admin users from using "other channels" than those defined in a system-wide .condarc file ? My guess is that "override_channels_enabled: False" should be sufficient for that.
NB: I do not want to prevent users from creating environments or from installing packages in their own envs, I just want to prevent the use of "non-admin-approved" channels.

Thanks for the job on that very useful product,
Yours sincerely,
Pierre
