### ISSUE TITLE
BUG: different numpy version than requested

### ISSUE THREAD

**Issue by GaelVaroquaux** [conda/conda#7481]
When requesting numpy 1.11, numpy-base 1.14 is pulled in, and the imported numpy is then 1.14 ( the problem happens in our continuous integration  https://travis-ci.org/nilearn/nilearn/jobs/399527033 ).

### Steps to Reproduce

1. Install a clean miniconda environment: 
```
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
bash Miniconda-latest-Linux-x86_64.sh
```

Request the following conda packages:
```
conda install numpy=1.11 scikit-learn=0.17 scipy=0.17
```
(the bug happens when the 3 packages are requested together)

We get the wrong numpy version:
```
python -c "import numpy; print(numpy.__version__)"
```
prints '1.14.3'

I suspect that this is happening because the dependencies cannot be satisfied, but in this case, the lack of clear error is a problem. Also, this seems to be a regression. It was not happening until recently.

**Comment by msarahan** [comment]
Thanks for the report.  We'll look into it and see what we need to do to fix it.  We are working on providing a better way of choosing between MKL and openblas (or other blas implementations), and there have been some growing pains.

As a workaround for the time being, I recommend specifying ``numpy-base=1.11`` instead of or in addition to ``numpy=1.11``.

For a bit of back-story, numpy-base is a construct that was added to help remove a circular dependency with mkl_fft and mkl_random.  The numpy package in modern builds is a metapackage depending on numpy-base, mkl_fft and mkl_random.  However, because mkl_random and mkl_fft also depend on numpy, we needed to break that cycle.

**Comment by GaelVaroquaux** [comment]
> For a bit of back-story, numpy-base is a construct that was added to help
> remove a circular dependency with mkl_fft and mkl_random.

As a long time debian user, I was suspecting something like that. These
are challenging problems! Thanks for the support.

**Comment by stuarteberg** [comment]
I don't think this is related to the problem, but it's worth noting that you are using an outdated link for the Miniconda installation script.  The current versions specify the major Python version in the name (Miniconda2 or Miniconda3).  The version you're using installs `conda 4.0.5` by default, not the latest version of conda.  (I notice that your CI script immediately updates conda, so that's probably not the issue.  But your example above does not, FWIW.)

The proper link is:

```
wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
```

**Comment by kalefranz** [comment]
There's a lot of backstory on that miniconda link too.  We've debated killing `Miniconda-latest` off entirely, and even tried it once, but it just broke too many people.  Maybe it's time to try again though.

It has several problems.  First, it brings in python2, not python 3.  Just switching it to python3 would also be a surprise that will probably break people.  Additionally, while the primary purpose of Miniconda is to bootstrap *conda* onto a system, people also use it to get python.  So there's a bit of a conflation there.  It's very possible that at some point in the future, `Miniconda-latest` doesn't even give you a usable python in the base conda environment, and would solely be used for bootstrapping conda onto a system.

So, lot's of challenges there.  And we obviously still haven't figured out the best way to unwind it all yet.

**Comment by GaelVaroquaux** [comment]
> I don't think this is related to the problem, but it's worth noting that you are using an outdated link for the Miniconda installation script.

Thanks. I added an issue on our tracker.
