### ISSUE TITLE
No such file or directory for env

### ISSUE THREAD

**Issue by domoritz** [conda/conda#7569]
```
$ conda create --name space               
Solving environment: done

## Package Plan ##

  environment location: ~/anaconda3/envs/space


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate space
#
# To deactivate an active environment, use
#
#     $ conda deactivate

> conda activate space                                                                                                                                      set: Warning: $PATH entry "~/anaconda3/envs/space/bin" is not valid (No such file or directory)
```

**Comment by domoritz** [comment]
Could be the same as #7555 but I'll leave this open until the issue is confirmed.

**Comment by mingwandroid** [comment]
Why are you creating envs with nothing in them?

**Comment by domoritz** [comment]
> Why are you creating envs with nothing in them?

Am I? I thought conda create makes an environment based on the base env?

**Comment by kalefranz** [comment]
> I thought conda create makes an environment based on the base env?

No, it never has.

> It transfers some version information across for overlapping packages between the two

Doesn't even do that.

@domoritz You've opened several issues lately where you've not given all the information requested in the issue template.  We request that information up front so that we don't have to have several rounds of back-and-forth interaction that end up taking quite a bit of our time.  We often just close tickets that don't have sufficient information in them, as stated in the issue template.  In the future, when opening issues in this repository and as a courtesy to us, please use the issue template, and please make sure the issue is something that a change to code *within this repository* can address.

**Comment by domoritz** [comment]
Thank you for getting back to me. 

> In the future, when opening issues in this repository and as a courtesy to us, please use the issue template

👍 will do

> please make sure the issue is something that a change to code within this repository can address.

This is a bit harder because as a user I don't know what issues can be addressed here and which ones cannot. Moreover, for the specific issue above isn't the easiest fix to just create an empty directory at `.../bin`?
