### ISSUE TITLE
Corda navigator is not a proper app on OSX

### ISSUE THREAD

**Issue by domoritz** [conda/conda#7571]
Conda Navigator does not show up in Spotlight.

**Comment by domoritz** [comment]
If there is a different repo where this should be filed, I can move the issue.

**Comment by mingwandroid** [comment]
I don't think we care for supporting spotlight. It requires putting applications in preset locations and that's the opposite of what we want to do.

**Comment by domoritz** [comment]
Thank you for the quick response. Since there wasn't an issue about this before, could you elaborate why placing the app in a particular location is the opposite of what you want to do? I wonder because the link is placed there anyway.

**Comment by mingwandroid** [comment]
conda installs its software under your installation prefix (or often in an env subfolder of that).

Touching files outside of that isn't something we *generally* want to do. Yes there's an app there but we do not register our app bundles with the system because you could have many copies of the same app bundle and it would be a mess.
