### ISSUE TITLE
conda remove/uninstall wants to delete additional packages (but I want to keep them!)

### ISSUE THREAD

**Issue by NiklasDL** [conda/conda#7576]
Hello,

I have a conda env with tensorflow, theano and keras (and a few more obviously...)

When I try to delete theano, conda says it will delete keras as well:

```
The following packages will be REMOVED:

    keras:  2.0.9-py35_1         conda-forge
    theano: 1.0.2-py35he980bc4_0
```

But I need keras. In particular, I need keras 2.0.9. If I delete theano (and consequently keras) and reinstall keras, conda automatically installs theano as well with it. Why is that? I need a clean env without theano.

**Comment by mingwandroid** [comment]
theano is a dependency of keras so what you are attempting is not possible.

**Comment by NiklasDL** [comment]
No, theano is no dependency of keras.

**Comment by msarahan** [comment]
It is an optional dependency of keras.  Keras supports theano and tensorflow as backends.  Because conda does not have support for optional dependencies right now, the pattern is generally to include all dependencies of interest.  theano is a dependency of our keras package, even if it is only an optional dependency of the upstream keras package.

You should be able to configure Keras to not use the theano backend, and that's a better way than trying to fight the dependency stuff.

**Comment by NiklasDL** [comment]
Okay thank you, I was just wondering because my advisor wanted me to keep the env as clean as possible.
