### ISSUE TITLE
Conda CLA (Action Required)

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7605]
To the honorable, honored group below: your contributions make up conda. Anaconda needs to obtain contributor signatures from all of you, so that we can offer Conda to our customers under different indemnification terms.

Please read and sign at

--> https://conda.io/docs/contributing.html#conda-contributor-license-agreement <--

If you have already signed the CLA for conda-build, it unfortunately doesn't count due to our inability to rely on CLAHub as a trusted source of data (see https://github.com/conda/conda/issues/7573). The good news is that the document we are now asking you to sign covers *all* projects under the Conda Code Organization (i.e. https://github.com/conda).  This includes conda, conda-build, constructor, and all other related projects under https://github.com/conda.

In case you're new to CLAs, this is rather standard procedure for larger projects. [Django](https://www.djangoproject.com/foundation/cla/) and even [Python](https://www.python.org/psf/contrib/contrib-form/) itself both use something similar.

Best regards, and my admiration to all of you for helping to get conda where it is today.

@akanehira
@amelio-vazquez-reina
@anntzer
@ARF1
@AvdN
@bchapman
@blake-nicholson
@daineseh
@dfroger
@edwardreed81
@eliteraspberries
@immerrr
@jakirkham
@jharriman
@jimm-domingo
@josham
@jrjohansson
@kurtwheeler
@lambdalisue
@Maggie-M
@makbigc
@mguillau
@mjuric
@NixonK
@peter1000
@ramseydsilva
@rvianello
@tpn

**Comment by mjuric** [comment]
Hi @kalefranz,

Is there an institutional version of this CLA? I'm a prof at the U. Washington, and any code that I (and our postdocs, students, etc.) I produce while on grant or state funding is generally owned by the University.

If there's an institutional CLA, our legal tells me they probably wouldn't be able to sign it as-is, because of the patent clause. The concern is that by contributing code someone in (say) Astronomy may be inadvertently giving away a patent invented in (say) the med school. If the patent clause can be limited to the patents individually owned by the researcher (like in the ECL -- https://opensource.org/licenses/ECL-2.0), it may be possible. Big research universities don't fit the traditional monolithic corporate model -- they're more like loose conglomerates of individual departments/groups. I suspect you may have similar problems with other higher-ed institutions?

FWIW: We're generally allowed to license what we produce under BSD or MIT (assuming the grant allows it -- they generally do). But not GPLv3 or Apache 2 (or a CLA such as this one); the patent grant clauses are seen as too broad for the University.

**Comment by kalefranz** [comment]
@mjuric Good questions. I will track down answers and probably contact you directly.
