### ISSUE TITLE
Fallback to conda-static

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7723]
Would be nice to have `conda` fallback to [conda-static]( https://conda-static.anaconda.org/ ) when installing packages from [anaconda.org]( https://anaconda.org/ ) doesn't work. It may still make sense to warn about the fallback and send an error report in this case anyways.

**Comment by kalefranz** [comment]
At the moment, conda-static.anaconda.org/conda-forge is very different from conda.anaconda.org/conda-forge.  It has metadata corrections, as we've been discussing.  "Falling back" means flipping back and forth between different states of metadata.  It seems that would create far more headaches than what we've experienced with these couple bumps of service outage over the last 24 hours.  It's better to have a hard fail, fail early, than get intermixing metadata, in my view.

I understand the problem, which is reliable delivery of conda-forge.  I don't think this hard-coded fallback mechanism is the right solution.  It could also complicate our rollout mechanism for going live with what conda-static is now.  In effect, go live means making the current conda.anaconda.org/conda-forge automagically use conda-static.anaconda.org/conda-forge.  The plan is to use Cloudflare Service Workers rather than 302 redirects, so it all *really is* completely transparent to end-users.
