### ISSUE TITLE
Add expansion of environment variables in `channels` config key

### ISSUE THREAD

**Issue by teake** [conda/conda#7805]
As per https://github.com/conda/conda/issues/1156#issuecomment-299913430, can we get expansion of environment variables in the `channels` config key? This would be useful for me, as I can then add the following lines to my `.condarc` file:

```
channels:
  - https://${USERNAME}:${PASSWORD}@my.private.conda.channel
```

**Comment by teake** [comment]
Come to think of it, if environment variables will be expanded in `channels`, they should probably also be expanded in all other channel-related config keys, such as `custom_channels`, `custom_multichannels`, `default_channels`, `migrated_custom_channels`, and `whitelist_channels`.

**Comment by teake** [comment]
@kalefranz If you give your thumbs up I'd be happy to put in a PR in case you're pressed for time. I couldn't find a precedent for expanding non-path variables in the codebase though -- so I'm a bit unsure whether this is a sane thing to do.

**Comment by kalefranz** [comment]
Yeah I say go for it.  I especially see the value for `${PASSWORD}` in the example you give.

Here are my thoughts right now.  Buckle your seatbelt 😜

We need to set clear standards for usage requirements.  Do we support `$PASSWORD`, `${PASSWORD}`, and/or `%PASSWORD%`? Note that `os.path.expandvars` has different behavior on different platforms.  The notes for the `ntpath.py` version are

```
# Expand paths containing shell variable substitutions.
# The following rules apply:
#       - no expansion within single quotes
#       - '$$' is translated into '$'
#       - '%%' is translated into '%' if '%%' are not seen in %var1%%var2%
#       - ${varname} is accepted.
#       - $varname is accepted.
#       - %varname% is accepted.
#       - varnames can be made out of letters, digits and the characters '_-'
#         (though is not verified in the ${varname} and %varname% cases)
# XXX With COMMAND.COM you can use any characters in a variable name,
# XXX except '^|<>='.

Expand shell variables of the forms $var, ${var} and %var%. Unknown variables are left unchanged.
```

The notes for the `posixpath.py` version are

```
Expand shell variables of form $var and ${var}.  Unknown variables are left unchanged.
```

How do we handle non-ascii characters?  In the variable name itself?  In the value/contents of the environment variable?

Besides config parameters that deal with channels, other parameters we should probably have env var expansion in are `ssl_verify`, `client_ssl_cert`, `client_ssl_cert_key`, `proxy_servers`, `envs_dirs`, `pkgs_dirs`.  I think some, most, maybe all of these might already be happening.  We should take this opportunity to be sure though.

How do we handle merges of channels lists where different parts of a channel specification are given in different places?  A url that represents a channel is cut up into the following components

- `scheme`
- `auth`
- `channel_location`
- `token`
- `channel_name`
- `subdir`
- `package_filename`

When we merge channels, either with `context.channels` or with `conda.models.channel.prioritize_channels()` and `conda.models.channel.all_channel_urls()`, if we are given one channel URL that contains auth and one that doesn't, do we keep the auth information intact regardless of order?  What happens if the auth information conflicts?  What happens if one url only provides the username component, but a second provides both username and password?  Same questions for `scheme`, `channel_location`, `token`, and `subdir`.  The "primary key" in this situation should always be `channel_name`.

Given all these thoughts and questions, `tests/models/test_channel.py` probably needs a lot more work.

**Comment by teake** [comment]
Good catch on the platform discrepancies. The existing path expansions have these baked-in, so I'd say we keep relying `os.path.expandvars` and propagate the discrepancies to the to-be expanded config parameters. It would be strange to recommend `${VAR}` on Windows or `%VAR%` on Linux, wouldn't it?

What about false-positive expansions? The chances of having a`VAR` environment variable defined _and_ an unrelated `%VAR%` string in your URL are pretty slim, but still. Same goes for the `${VAR}` syntax since `$` is a valid URL character. Since these collisions can also exist for paths I think we can ignore them. 

As for the non-ASCII characters, I'm not sure. If these were problematic, wouldn't issues have crept up in other places (regardless of variable expansion)? Or nobody is using non-ASCII chars ... Either way, I'm not sure that's necessarily inside the scope of this issue.

I'm also inclined to not consider the merging of the channels. If variables get expanded early enough  I'd say it's outside of the scope of this issue. Not sure this is feasible though.

I'll have a look at the other config parameters you mentioned, to be sure they're also expanded.
