### ISSUE TITLE
Conda too slow, Unable to setup R env

### ISSUE THREAD

**Issue by kunaldhariwal** [conda/conda#7921]
I have been trying to setup R Environment in Anaconda but it's taking forever to get it done. 
I've tried using both anaconda prompt and anaconda navigator but none of it seems to work.
How do i create a R Environment now?

**Comment by michaelkarlcoleman** [comment]
Not a great answer, but you could just wait.  This command, in a Miniconda I installed a few weeks ago (?), completed in 985 minutes on a fast server.
```
conda create --name r -c anaconda r r-essentials
```

**Comment by msarahan** [comment]
There is a known issue with R in particular where conda has trouble choosing between the two implementations (mro vs more standard R).  That's why our docs advise you to specify one or the other explicitly: https://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language/

conda create -n r-env r-base r-essentials

We're working on the solver issue in the meantime, but it has been elusive.  The workaround is easy enough, but the problem is annoying.

**Comment by michaelkarlcoleman** [comment]
Thanks.  I've actually been playing with variants based on that link, but so far they all seem quite slow (hours or days).  I did read just now that specifying `-c anaconda` is actually not advised either.

I'm currently running this command
```
conda create --name r-mro mro-base r-essentials jupyter
```
and it's been going for at least 45m.  (100% CPU with no I/O, so presumably the solver crunching.)

It feels like something's happened with either the available packages or conda itself that's causing it to blow up.  I'm relatively new to conda, though, so perhaps these cases have always been present.

**Comment by mingwandroid** [comment]
@michaelkarlcoleman If you wouldn't mind sharing the output of `conda info` that would be great.

For me, on a Linux VM, the following:

```
pushd /tmp
curl -SLO https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ./Miniconda3-latest-Linux-x86_64.sh -bfp $PWD/mc
. mc/bin/activate
time conda create -y --name r-mro mro-base r-essentials jupyter
```

.. gives:
```
..
real    7m36.825s
..
```

.. a lot of this is actually download time. The following (subsequent) command:

```
time conda create -y --name r-mro-2 mro-base r-essentials jupyter
```

gives:

```
real    0m30.595s
```

.. pretty good.

**Comment by mingwandroid** [comment]
```
pushd %TEMP%
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe', 'mc.exe') }"
start /wait "" mc.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%TEMP%\mc
mc\Scripts\activate.bat
powershell -command "Measure-Command {conda create -y --name r-mro mro-base r-essentials jupyter}"
```
.. gives:

```
Days              : 0
Hours             : 0
Minutes           : 8
Seconds           : 2
Milliseconds      : 892
```

.. again, download time .. Followed by:

```
powershell -command "Measure-Command {conda create -y --name r-mro-2 mro-base r-essentials jupyter}"
```

.. gives:

```
Days              : 0
Hours             : 0
Minutes           : 3
Seconds           : 3
Milliseconds      : 828
```

.. a lot worse, but still bearable.

**Comment by michaelkarlcoleman** [comment]
@mingwandroid : Argh--this was an error on my part.  We have multiple conda installs here, via our system account and environment modules, and I hadn't quite realized that others were dropping things in `~/.condarc`.  In addition, I was under the impression that `--channel` effectively entailed `--override-channels`.  So the problem was that multiple channels were being searched.  For completeness, here's the list
```
channels:
  - glotzer
  - bioconda
  - conda-forge
  - defaults
  - r
```

Beyond that, there's a file `~/.conda/environments.txt` that's being shared between our various conda installs.  No idea what it's actually supposed to do, but so far it seems only to be adding extra junk to the output of `conda env list`.

Thanks very much for your help!
