### ISSUE TITLE
Conda hangs when using python 3.7 and conda-forge channel

### ISSUE THREAD

**Issue by jmelo11** [conda/conda#7953]
Hi all, i'm having trouble using conda-forge channel and python 3.7 while trying to install some libraries. I don't know if the problem is in the conda files or in the channel, but i belive the problem is related to the python version. I created a env using python 3.6 and tried to install some libraries and it works but when i use the 3.7 version it hangs for a long time showing "solving enviroment":

3.6
![image](https://user-images.githubusercontent.com/30101675/48318735-78185e80-e5e3-11e8-8512-8ddcf4cba5e9.png)

3.7
![image](https://user-images.githubusercontent.com/30101675/48318729-5b7c2680-e5e3-11e8-9ff9-81c584e799e2.png)

**Comment by jamessong** [comment]
same thing here ...  just hanging forever   - i think the python community is a mess

**Comment by jamessong** [comment]
not only it hangs, but also it crashed ... ctl+c won't quit!

**Comment by Corneliuscob** [comment]
I am having this issue as well !

**Comment by soapy1** [comment]
@jmelo11 is this still an issue for you?

@Corneliuscob what exactly is the issue, what commands are you running, what are they returning and what is the output for `conda info`

**Comment by masariello** [comment]
we run the following
```
conda env create -f path\to\a.tml -p path\to\new\env
```

Conda solves and downloads everything, and then it hangs right after creating the Start menu shortcuts

I have actually attached the debugger and the last python.exe child process spawned by the command appears stuck waiting for messages on a queue (multiprocessing?)

This is creating huge headaches. We just can't automate any deployments because of this problem. I've seen conda 4.7.x, 4.8.2 and 4.8.3

It doesn't happen always. Some users are immune. Must most will be hit.

**Comment by mingwandroid** [comment]
Do you have 64+ thread CPU?

**Comment by masariello** [comment]
yes, all the deployments are on 64bits
