### ISSUE TITLE
Better Powershell activate and deactivate

### ISSUE THREAD

**Issue by giuliofoletto** [conda/conda#8394]
Although conda 4.6 introduced Powershell support, I feel the implementation is still lackluster. I focus mostly on activation and deactivation of environments, which is a fundamental part of the conda workflow. 

Currently, an instance of python runs at startup of any Powershell process querying for the active environment, and its name is printed at the beginning of the prompt. This does not seem optimal because it slows down the loading of the shell even if the user is not interested in actually working with conda. 

The implementation in cmd seems to be better because conda runs only when actively requested by the user (via `conda activate`) and information about the environment disappears when no longer needed (`deactivate`). Shouldn't it behave in the same way in Powershell?

**Comment by dennispg** [comment]
You can accomplish this pretty easily by modifying your $PROFILE and changing it to this:

```
$Env:_CONDA_ROOT = "path to your conda installation"
$Env:CONDA_EXE = "$Env:_CONDA_ROOT\Scripts\conda.exe"
$Env:_CONDA_EXE = "$Env:CONDA_EXE"

Import-Module "$Env:_CONDA_ROOT/shell/condabin/Conda.psm1"
```

Now it will only take effect if you type `conda activate`.

**Comment by giuliofoletto** [comment]
Thank you, this seems to work quite well. Would you care to explain what these lines do?

By the way, for those interested in using this with cmder, you can use the above lines from @dennispg and the suggestion posted [here](https://github.com/BCSharp/PSCondaEnvs) by the original creator of `PSCondaEnvs`. In practice: edit `CMDER_ROOT\config\user_profile.ps1` and add
```
$Env:_CONDA_ROOT = "path to your conda installation"
$Env:CONDA_EXE = "$Env:_CONDA_ROOT\Scripts\conda.exe"
$Env:_CONDA_EXE = "$Env:CONDA_EXE"

Import-Module "$Env:_CONDA_ROOT/shell/condabin/Conda.psm1"

[ScriptBlock]$PrePrompt = {
    if ($Env:CONDA_DEFAULT_ENV) {
        return "($Env:CONDA_DEFAULT_ENV) "
    }
}
```

**Comment by dennispg** [comment]
I basically just pulled that from conda_hook.ps1, which is used by the new PowerShell implementation in Conda 4.6.x. The first three lines set up some environment variables which point to your conda installation and how to find conda.exe, those are used inside the Conda.psm1 module.

That module is also part of the new implementation, and wraps all the conda commands to become available in PowerShell.

Specifically regarding cmder, what you've provided will work but the current PowerShell implementation does some mangling of its own to the prompt function which can potentially interfere with cmder.

I've got a pull request that should allow you to disable that using `conda config --set changeps1 false` in #8213.

**Comment by musm** [comment]
I'm not sure why you need to pull in all that stuff for example


Using https://github.com/nickcox/pure-pwsh
```
$PrePromptConda = {if ($Env:CONDA_DEFAULT_ENV -ne "base") {
        "($Env:CONDA_DEFAULT_ENV) "
    } else {}}

$pure.PrePrompt = {
    param ($cwd, $git, $slow)
    "$($myColors.DeepSkyBlue3)$([Environment]::UserName) $cwd $git`n" + (& $PrePromptConda)
}
```


works

**Comment by musm** [comment]
However the whole powershell script and it's handling is rather broken and not robust

**Comment by msarahan** [comment]
It sounds like you know much more about powershell than us.  PRs to improve our scripts would be most welcome.

**Comment by dennispg** [comment]
Could you expand on what exactly is broken and not robust? Are you talking about the PowerShell functionality in conda 4.6.x or are you talking about pure-pwsh?

**Comment by musm** [comment]
No conda functionality with activate /deactivate  is not working

Reproducible case
```

$PrePromptConda = {if ($Env:CONDA_DEFAULT_ENV -ne "base") {
        "($Env:CONDA_DEFAULT_ENV) "
    } else {""}}

function prompt {
    $prompt = ""
    $prompt += Write-Prompt (& $PrePromptConda)
    $prompt
}
```
In new shell run
```
![image](https://user-images.githubusercontent.com/4319522/56181501-c7701a00-5fdb-11e9-9548-82a65fee1ede.png)

``

**Comment by dennispg** [comment]
If I had to take a guess, I would say the issue is with the ampersand you have in:
`$prompt += Write-Prompt (& $PrePromptConda)`

You should read about what the ampersand does in PowerShell here:
https://ss64.com/ps/call.html

Btw what version of conda are you using? You can use `conda -V` to find out.

You probably would have better luck if you update conda as well.

**Comment by musm** [comment]
```
> conda -V
conda 4.6.12
```

**Comment by dennispg** [comment]
The ampersand means you are trying to execute the value of `$PrePromptConda` as a command and get back its value as a parameter to pass to Write-Prompt. That not correct since $PrePromptConda is just the string you are trying to append. Remove the ampersand and see what happens..

The error messages youre getting indicate out of memory issues, which I'm not sure are the fault of anything on conda, and are more likely due to trying to execute that string as a command.

**Comment by musm** [comment]
Without the ampersand the prompt just prints out 

```
$PrePromptConda = {if ($Env:CONDA_DEFAULT_ENV -ne "base") {
        "($Env:CONDA_DEFAULT_ENV) "
    } else {"base"}}

```

The ampersand should be needed to execute the script block ?

**Comment by dennispg** [comment]
I apologize, I see that now and you are correct.

Still, from the error message it looks like it is saying that conda.exe was not able to run because of a out of memory issue, and so then the rest of the chain of commands for `conda deactivate` also fail.

**Comment by musm** [comment]
conda deactivate is doing something very strange to lead to such an error.

**Comment by musm** [comment]
where are the powershell scripts that handle the activate/deactivate logic?

**Comment by dennispg** [comment]
I just did a test of running `conda deactivate` repeatedly in PowerShell 5.1, and there are no issues.

Then I tried the same test in PowerShell 6 and it started giving me this:
```
PS C:\> conda deactivate
Environment variable name or value is too long.
Parameter name: value
At C:\Users\dennispg\Miniconda3\shell\condabin\Conda.psm1:128 char:9
+         $Env:PATH = $OldPath;
+         ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], ArgumentException
+ FullyQualifiedErrorId : ProviderContentWriteError
```

The logic is handled by a mix of `Conda.psm1` located in `<conda location>/shell/condabin`, which passes the commands on to` conda.exe`. You can find the source for it here:
https://github.com/conda/conda/blob/master/conda/activate.py

**Comment by musm** [comment]
Can you please test again by running `conda deactivate` at least 5 times

**Comment by musm** [comment]
The problem is that   Enter-CondaEnvironment keeps appending to path and if you run it enough times it will  append way too many strings to the path causing the error

**Comment by mingwandroid** [comment]
It's always best to prefix such statements with "I think" or "It appears", because, as in this case this is only a part of the story. It is essential that those parts get added, and conda is aware of them and removes them again. You should look for bugs in that side of things if you want to try to fix this.

**Comment by dennispg** [comment]
@mingwandroid That said, I can confirm that this did not occur for me with 4.6.8, and does occur for me after upgrading to 4.6.12.

Can I ask why `Add-Sys-Prefix-To-Path` was added in:
https://github.com/conda/conda/commit/3dfd8fbfd9ceb46e722379fb48e934652f67ed20#diff-fb6e0f65bb56d2f95db85b32a592f571

Is it a new requirement that the PATH has to be modified before you can execute `conda.exe`

**Comment by msarahan** [comment]
because conda.exe and thus python.exe have no intrinsic idea of the Library/bin folder, and that folder is where essential things like openssl live.  Python's "DLLs" folder is strictly for python's stuff, while the Library/bin folder is more general purpose, for any and all of our libraries and some executables.  Because Windows lacks any kind of RPATH support, the PATH hack is what we have to do.  We're trying to develop better, less hacky ways (stub DLLs that reference paths to other DLLs), but that will take time.

Take a look at our issue tracker for all of the HTTPError messages.  It's a big problem, and it's recent because of at least 2 things that we know of:

1. conda is no longer stacking environments by default.  When you activate an env, the only part of the base env that is left on PATH is condabin.  This is good, because you won't accidentally "fall through" to software in your base env.  It's also bad, because conda in the root env won't find its libraries anymore (without the PATH hack)
2. We removed a patch to python that was always adding Library/bin to PATH.  This was showing up everywhere and causing problems reasoning about the true value of PATH.

**Comment by mingwandroid** [comment]
Conda 4.6 has yet to work correctly on powershell.

> Is it a new requirement that the PATH has to be modified before you can execute conda.exe

No it is a requirement that has existed forever.

**Comment by msarahan** [comment]
> No it is a requirement that has existed forever.

This isn't quite true.  Yes, Library/bin has ALWAYS needed to be on PATH.  This has been exposed more lately, and we're working on ways to not require the user to know about it.  This is especially true for cases like calling conda with another python env active, where that python env may have incompatible libraries.  The "always add PATH" approach that @dennispg is asking about helps us make sure that the correct libraries are available to conda and to the python interpreter behind the scenes.

**Comment by musm** [comment]
It seems to me that a 'simple' solution here is to add a global variable that signals whether the path has been modified or not and then to reset the state to ensure the path doesn't continuously get appended leading to the error

**Comment by mingwandroid** [comment]
Feel free to look around more of the code. get_initial_path_list is implicated in this stuff.

The complications are:

1. We have two ways of activating, both need to work.
2. People will add things to PATH to make  things 'work'. They may add the wrong stuff and or in the wrong order. 
3. We have many shells, particularly on Windows.

**Comment by msarahan** [comment]
See some work at #8564 - we had a few issues on multiple shells.  I think I have just now sorted out powershell.  If anyone is feeling helpful, we'd appreciate your feedback and testing.  You should be able to just copy Conda.psm1 into your $PREFIX/shell/condabin folder to test the powershell fix.

**Comment by dennispg** [comment]
Thanks for this! 👍 

I tested and can confirm the changes in https://github.com/conda/conda/pull/8564 do fix the `$Env:Path` issue.

**Comment by musm** [comment]
I'm the canary channel, is there anyway to track  when the changes will land? Thanks for the improvements
