### ISSUE TITLE
The system cannot find the path specified after downgrading from 4.6 to 4.5

### ISSUE THREAD

**Issue by kylekeppler** [conda/conda#8421]
When downgrading from conda 4.6 to 4.5, `HKCU\Software\Microsoft\Command Processor\AutoRun` remains set to run `conda_hook.bat` and causes "The system cannot find the path specified" in all `cmd.exe` prompts.

Edit: also leaves code in `C:\Users\kkeppler3\Documents\WindowsPowerShell\profile.ps1`.

## Current Behavior

"The system cannot find the path specified" in all cmd.exe prompts.

and 
```
Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At C:\Users\kkeppler3\Documents\WindowsPowerShell\profile.ps1:4 char:80
+ ... onda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:PSObject) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo
   keExpressionCommand
```

### Steps to Reproduce

Downgrade conda 4.6 to 4.5, run cmd.exe and powershell.

## Expected Behavior

No error.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : C:\miniconda3
    active env location : C:\miniconda3
            shell level : 1
       user config file : H:\.condarc
 populated config files : H:\.condarc
          conda version : 4.5.13
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : <local hosted channels>
          package cache : C:\Miniconda3\pkgs
                          C:\Users\kkeppler3\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\kkeppler3\AppData\Local\conda\conda\envs
                          H:\.conda\envs
               platform : win-64
             user-agent : conda/4.5.13 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by msarahan** [comment]
``conda init`` is the command that sets that registry key.  There's a reverse command added in #7594 but that's still going to require you to run it before reverting to 4.5.x.  This is definitely not pretty, but I'm afraid other problems related more to helping people move forwards, not backwards, are higher priority for us.

**Comment by kylekeppler** [comment]
@msarahan, understandable, perhaps a warning is in order when uninstalling, suggesting the user to run conda init --reverse first?

**Comment by dektoud** [comment]
This also seems to affect reinstallation of an Anaconda distribution if target paths between installs are different, since the registry key somehow breaks the final pythonw call in the anaconda installer. 

If the key is not removed and the reinstall is to a different folder, uninstall + reboot + reinstall results in a supposedly successful anaconda install that is missing several critical tools in the Scripts/ folder, things like conda.exe and activate are just missing with no indication that anything has gone wrong - a very very confusing scenario.

To reproduce, I'm using Anaconda 5.2.0 b/c of py3.6: 

Install Anaconda 5.2.0 to C:\Anaconda3\
conda update conda
conda init powershell (I'm on windows)
Uninstall anaconda

Install Anaconda 5.2.0 to C:\<user>\Anaconda3\
conda update conda 
No conda exists???

**Comment by dektoud** [comment]
I made an error - what I have described only occurs when the command `conda init` (without powershell) is used in that process. I'm guessing that the bare init defaults to cmd?

I think the fix is to just use the new conda. Which has me looking at constructor to provide a py3.6 installer with an updated conda.

**Comment by tyszya** [comment]
THANKS a lot! That solved my problem!
