### ISSUE TITLE
Spurious activation warning

### ISSUE THREAD

**Issue by ofek** [conda/conda#8424]
First off, an obligatory thank you for this great piece of software 🙇 

So, today I upgraded Conda 4.5.x (Python 3.6) to 4.6.8 (Python 3.7) by doing:

```console
$ conda update conda
$ conda update python
```

Everything went smoothly, however now whenever I run Python I get:

```
$ python
Python 3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>>
```

I never use Conda environments and have never seen this warning before.

Is there a way to disable it? If not, I'll probably just install the official Python distribution.

**Comment by mingwandroid** [comment]
Why would you have such an extreme reaction to a line of text put into our python interpreter to help you to avoid running into problems? Did you read the link?

**Comment by ofek** [comment]
@mingwandroid I don't think I had a "reaction", more so an inquiry 🙂 

I did read the link and am fully aware of the rationale behind the warning. My question, however, is how to disable it.

**Comment by mingwandroid** [comment]
Great! And in that case I am astonished that someone would elect to run some software in which the environment in which it was designed to operate has not been setup correctly.

Anaconda Distribution's recipes are based on forks of conda-forge, but our python recipes have diverged a bit. If you make a PR to add an env var such as "CONDA_I_WISH_TO_IGNORE_ANACONDA_INCS_ADVICE_AND_PROMISE_NEVER_TO_FILE_BUGS_RELATED_TO_THE_CONDA_ECOSYSTEM` to disable this message then we would consider it (I would argue against it though), but we're not going to do any work here to allow getting rid of a message that's trying to prevent problems for our users.

**Comment by mingwandroid** [comment]
The Anaconda Distribution does *not* support running its software outside of using `conda activate` or its legacy deprecated versions: `. <conda_prefix>/bin/activate` or, on Windows, `call <conda_prefix>\Scripts\activate`.

While your software may work today, we need to be free to assume that we can use package activation scripts in new versions of that software, so your installation could break due to an update. Activation tends to do little more than setting env vars but sometimes it can do more.

**Comment by mingwandroid** [comment]
> I never use Conda environments and have never seen this warning before.

You do, everyone who uses conda uses conda environments. The default one is called `base`.

**Comment by ofek** [comment]
Up until the upgrade this warning never occurred. Do you know why?

**Comment by mingwandroid** [comment]
Because we added it to python recently. We did this because we get far too many bug reports due to people ignoring the requirement to activate any and all conda environments, including `base`.

It is called process.

**Comment by ofek** [comment]
@mingwandroid Can you please tell me a way to remove the warning without activating `base`?

**Comment by mingwandroid** [comment]
There is no way. Please explain the problem this warming is causing you.

**Comment by ofek** [comment]
The problem is it is annoying, especially since my paths are already set up to use `base`.

Is an env var what removes the warning?

**Comment by mingwandroid** [comment]
> The problem is it is annoying, especially since my paths are already set up to use base.

Please read the link in the error message again and also most of my comments to you, carefully. If you wont then please at least be aware that activation can and often does involve more than adding entries to PATH, there's no way to avoid this warning at present, we have no plans to add something for that at present, you are welcome to try to contribute such a 'feature' but I will do my best to argue against it within the anaconda team.

The warning is there

No, correct activation is the only thing that removes this warning.

**Comment by ofek** [comment]
@mingwandroid Why are you being so combative?

I doubt the warning is there "exactly for people such as" me. I literally only use Conda for the ability to install specific versions of Python easily for testing. Otherwise I use `base` as a global/system-wide Python. I use pip for package management and hatch (virtualenv) for environment management. This is all well-supported by Conda and everyone knows using standard Python tools with Conda is super common.

Again, I've read the documentation. Are you basically telling me to read the source code to figure out what exactly triggers the warning?

**Comment by mingwandroid** [comment]
I'm not being combatative, I am somewhat exasperated though.

First,  please understand we take a *huge* amount of pride in the Anaconda Distribution and seek to solve for the greatest good. Time our engineers spend responding on github often works against that because we'd otherwise spend it improving the Anaconda Distribution.

You called a deliberate change that we made spurious when it isn't (if I could have all the hours back I've spent hunting down and trying to reproduce issues on github where the actual problem turned out to be because the reporter refused or neglected to activate then I would spend them making lots of things a little better instead). You *threatened* to uninstall our software - we give it away for free,  much as we give away our time on issues such as this. And all this in the first post - yes you added a compliment, thanks - but things went downhill from there.

You claim to have read the linked to text then still insist that it's fine to ignore our operating instructions and that there must be done mechanism to remove our warning.  First because you don't use environments (you do,  everyone does) then after I pointed out the error in that statement, second that adding some entries to path is just as good. It is not.

In future we'll probably remove any mention of adding anything to PATH from the installers. Quite simply,  our PATH entries are an internal implementation detail that you shouldn't care about or even be aware of (unless technical details are your thing). The one and only correct way to run Anaconda software is through activation. 

But you are right, your usage of conda seems minimal, you are probably gaining very little advantage from it and your proposed course of action that would make it less annoying for you is not a global minimum for annoyance, far from it. I would hope that you understand that we thought long and hard about this. You keep repeating the untrue claim that activation is synonymous with adding some entries to path so please, go ahead and use an interpreter without this warning (or an ecosystem too primitive to support activation). 

You are also welcome to look through my patch to try and find a hack that disables this message.  For my part, if I find any such hacks I will do my very best to remove them because the warning is there for a reason and providing a way to remove it lessens its effectiveness.

**Comment by mingwandroid** [comment]
> I doubt the warning is there "exactly for people such as" me

Despite all this written I am still of this opinion.

We could release tomorrow an opening package that requires OPENSSL_DIR to be set. If we did that we'd have broken toe workflow. I'd you'd seen a warning maybe you would correlate those two things and try activation. If you did that then hopefully you'd be happy to accept that you need to activate, then you'd not file an issue.

**Comment by ofek** [comment]
Ah, I see what happened here. I didn't intend to come across as threatening, it was more a stream of consciousness type thing. Sorry about that.

Anyway, it would be nice to know exactly what Conda looks for to detect activation.

**Comment by mingwandroid** [comment]
OK great. We'll that's not information I'd like spread around and I hope you understand my reasons for that but feel free to poke around for yourself.

**Comment by supersaiyan73** [comment]
This error pops up even after activating the virtual environment. Is that supposed to happen?
"Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated. Libraries may fail to load.  To activate this environment
please see https://conda.io/activation"
I am using the standard environment activation method.
" conda activate myenv "

**Comment by msarahan** [comment]
How are you activating the environment? Conda environments are not the same
thing as virtualen/venv/pipenv/poetry envs. Their activation scripts are
very different.

**Comment by pradyunsg** [comment]
@ofek Curious cat question: what's the reason that you don't want to activate the conda environment?

**Comment by ofek** [comment]
I was using `base` as a global/system Python only and use other tools for environment management

**Comment by pradyunsg** [comment]
Ah!  Another curious cat question: What's the reason to avoid running `conda activate base` as suggested by the conda developers?


AFAICT, for Python packaging tooling (and the relatted environment management tooling) like pip/venv/virtualenv/pipenv/poetry etc; see activated conda's environments exactly like a system Python. So, I *think* they'd still work as expected even if you activate the environment. I feel like I'm missing something here, but I'm not sure what that is.

**Comment by ofek** [comment]
I'm on Windows where there's not a standard way to run shell start-up commands like dumping stuff in a `~/.bashrc`. I'm satisfied with my new solution to this though

**Comment by mingwandroid** [comment]
> I'm on Windows where there's not a standard way to run shell start-up commands like dumping stuff in a ~/.bashrc. I'm satisfied with my new solution to this though

There _are_ standard ways. For `cmd.exe` it's `doskey`, and for `PowerShell` there are initialization scripts.

I don't use `PowerShell` (I use `cmd.exe` and the `MSYS2 bash prompt` with `conda` on `Windows`, so you'd have to look that up for yourself, but for `cmd.exe`, `conda init cmd.exe` will install the former into your *Windows registry* such that `conda` runs from any command prompt (you still then might need to activate your base env via `conda activate` depending on the `conda` config variable `conda_auto_activate_base`.

Cheers!

**Comment by mingwandroid** [comment]
Great, one last thing while I'm here though it's  been covered already .. avoiding correct activiation on `Windows` will not end well. It is essential that 6 paths entries get added to `PATH`, in the correct order. To some extent, avoiding activation on `Unix` is workable since `Linux` and `macOS` have more comprehensive dynamic library loaders and we take advantage of the features needed so that the exes find their dynamic libraries just fine, but we cannot do that on Windows, outside of manipulating `PATH`.

But there's the other consideration, on all platforms, of the execution environment of the software. If `GDAL` needs to use `GDAL_ROOT` and the maintainers of the conda package decide that activation scripts are the appropriate place to set that, and if someone then avoids activation, `GDAL` will not work correctly. To me, since I added this warning to our interpreter, I spend a lot less time dealing with issues that turn out to be due to lack of activation. Of course I cannot know this to be true!

**Comment by mingwandroid** [comment]
Ah, oops, one more! .. the really cool thing about `conda`'s support for various shells is that we aim, where possible to allow using any shell on any OS. The code backing the shells is largely platform independent, so you can, for example, use `conda` on `PowerShell` on `Unix`, if that's something you want to do. I would love for `WSL` to gain first-class support too.
