### ISSUE TITLE
Anaconda Prompt Access Denied: Missing Temp Files

### ISSUE THREAD

**Issue by jonathanrsmjtk** [conda/conda#8510]
Hello
I was tried to launch Anaconda Prompt but this error occured after updated to 4.6.11
![image](https://user-images.githubusercontent.com/49324622/55656830-8c732700-5822-11e9-9f19-efbd65a70520.png)

**Note:** My Anaconda3 installed on C:/ProgramData

**Comment by msarahan** [comment]
There is a bug in our code regarding handling of spaces in temporary paths. We'll look into it. In the meantime, you can possibly work around this by setting the TMP and TEMP environment variables to a path without spaces that you have write permissions for. Making something like c:\conda_tmp for this purpose might be good.

**Comment by schuelaw** [comment]
Just noting, I installed Anaconda this morning (Anaconda3-2019.03-Windows-x86_64) and this problem is still present when launching the anaconda prompt. I added the lines:
`
@REM Added by schuelaw, June 9, 2019 after clean install
@SET TMP=C:\CondaTmp
@REM Added by schuelaw, June 9, 2019 after clean install
@SET TEMP=C:\CondaTmp
`
to the file [Anaconda root]\condabin\_conda_activate.bat right after the comment:
`
@REM This method will not work if %TMP% contains any spaces.
` 
and created the folder "C:\CondaTmp"

**Comment by yandaj** [comment]
I have the same problem even though TEMP and TMP variables have no space right now. Did anyone fix it?

**Comment by datavisualytic** [comment]
> Just noting, I installed Anaconda this morning (Anaconda3-2019.03-Windows-x86_64) and this problem is still present when launching the anaconda prompt. I added the lines:
> `@REM Added by schuelaw, June 9, 2019 after clean install`
> `@SET TMP=C:\CondaTmp`
> `@REM Added by schuelaw, June 9, 2019 after clean install`
> `@SET TEMP=C:\CondaTmp`
> to the file [Anaconda root]\condabin\_conda_activate.bat right after the comment:
> `@REM This method will not work if %TMP% contains any spaces.`
> and created the folder "C:\CondaTmp"

As advised by msarahan on Apr 6 above, I was able to solve this issue by changing the temp folders in Environment Variables to a path without spaces e.g. C:\ProgramData\Temp

![Temp folders](https://user-images.githubusercontent.com/54326368/63935474-151f8780-ca90-11e9-958b-3db1f1a452a0.PNG)

**Comment by robwaat** [comment]
This issue is still relevant and has not yet been resolved in the current release, despite this issue's closed status.

I had the same problem with a fresh install via `Anaconda3-2019.07-Windows-x86_64.exe` for Windows 1903 as of the 28th of August 2019 owing to a space in my `%USERPROFILE%` path. This filename is not easily changed at an OS level.

Instead, opting to install for all users  (i.e. changing the install locaiton to `C:\ProgramData\Anaconda3`) seems to have partly resolved wider issues, while the changes to the `TEMP` environment variable suggested by [datavisualytic](https://github.com/conda/conda/issues/8510#issuecomment-526138786) acted as workaround sufficient to allow me to run Anaconda prompt.

However, this is an involved solution unlikely to be attempted by most users. 

The core issue is something I belive should be corrected during base installation.

**Comment by dedovic** [comment]
Yep, broke for me a/o 8/28 version of conda install. %USERPROFILE% name isn't easily changeable. Will try to reinstall and choose a different path

**Comment by smarkh** [comment]
I would just like to add myself to this here saying that as of today, the problem persists. I get the same error because my user folder has a space in it and because its windows, I cannot rename it.

**Comment by jasongrout** [comment]
@msarahan - was this ever fixed?

**Comment by bentalebahmed** [comment]
Same issue: space in path, hope it will be fixed soon

**Comment by Det7** [comment]
I'm encountering this issue and I don't have any spaces in my path:
C:\Users\L130763\AppData\Local\Temp

My Anaconda was working fine since I initially installed it last year until a computer crash happened last week and started to get those errors.

Any advise on this?

I did a lot of manual setup on some of the libraries I'm using so I don't want to to a fresh install of Anaconda.

What's the root cause of this issue and what else can I do about it?

**> Main Error**
> 'root_prefix'
> 
> **Traceback**
> Traceback (most recent call last):
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
>     return_value = func(*args, **kwargs)
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
>     window = run_app(splash)
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
>     window = MainWindow(splash=splash, tab_project=False)
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
>     self.api = AnacondaAPI()
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
>     ANACONDA_API = _AnacondaAPI()
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
>     self._conda_api = CondaAPI()
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
>     CONDA_API = _CondaAPI()
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
>     self.set_conda_prefix(info=get_conda_info())
>   File "C:\Users\L130763\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
>     self.ROOT_PREFIX = info['root_prefix']
> KeyError: 'root_prefix'
