### ISSUE TITLE
Support pypi/pip installed packages in `conda.api.PrefixData.iter_records`

### ISSUE THREAD

**Issue by xhochy** [conda/conda#8538]
The new API `conda.api. PrefixData.iter_records` is really helpful for inspecting conda environments and has a much better feeling than parsing `conda list --json`. At the moment, I sadly cannot replace the calls in my code with the new API as the new API only lists conda packages while `conda export` also list packages installed via `pip`. 

What would be required to bring to this on par with `conda list`? It seems that the actual implementation code already supports this but with a do-not-use-this warning.

**Comment by msarahan** [comment]
have you tried turning on ``pip_interop_enabled``?  It might show them if you do?

```
conda config --set pip_interop_enabled true
```

We don't do that by default because we found it slowed down conda too much (and people are already screaming about that).  We will work on optimizing it and enable it by default when it is fast enough.

> What would be required to bring to this on par with conda list?

A PR?  I don't see any fundamental blockers, aside from possible internal usage of that function that may need to be adjusted for pip packages possibly being present.

**Comment by quartox** [comment]
I tried turning `pip_interop_enabled` to true in my config, but it didn't work. The `conda.core.prefix_data.PrefixData.__init__` does take a `pip_interop_enabled` parameter which does return the pip installed packages but that class has a comment saying not to use the parameter. I believe it is currently being used in the logic of `conda list` but isn't available in the `conda.api` module.

**Comment by kalefranz** [comment]
A feature flag that’s ideally going away someday probably shouldn’t be added to the long-term API. Maybe there’s another place to tackle the problem?
