### ISSUE TITLE
conda powershell hook overrides all environment variables

### ISSUE THREAD

**Issue by musm** [conda/conda#8613]
The conda powershell activation,  places its own environment variables at the front of the path, which basically breaks any system environment variables if they are shared.  

Please don't add the miniconda environment variables in front of the existing path variables, only append them at the end.

**Comment by mingwandroid** [comment]
We could add the conda path entries to the end if PATH but many many people would have lots of trouble with that. The software they want to run will not run.

**Comment by musm** [comment]
Can we please not close this issue without at least a discussion? 

The current implementation caused me several hard to track problems because it ended up overriding my system configuration.

**Comment by musm** [comment]
Can we please not close this issue without at least a discussion?

The current implementation caused me several hard to track system issues because it ended up overriding my system configuration, in all powershells shells (it's installed to profile1.ps).

**Comment by msarahan** [comment]
I'm happy to not close this issue, but you're going to have to do a lot more legwork on exactly what is causing problems, and how you'd propose fixing it.  We have not willfully broken these scripts.   These details all exist for a reason.  If they conflict with stuff you have created, you might need to help us improve our scripts.  We can't cater to everyone's needs, both because we have insufficient resources, and also because we have no way of knowing exactly what everyone's needs even are.
