### ISSUE TITLE
How to activate conda environments in command prompt from within VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [conda/conda#8702]
I'm going to remove the template as this isn't a bug, but a question specific to Visual Studio Code (VSCode + Activation of Conda environments in Command prompt).

* Today our support for Conda Environments in the Python Extension for VS Code is fairly choppy, and we'd like to rectify this.
* We'd like to ensure we have great support for Conda 4.6 onwards.

**Our current solution is:**
* Identify the base conda environment and activate that using any `*.bat` files found in that directory
* Next, run the command `conda activate <....>`
    * At this point we're assuming conda is in the path, and necessary variables have been setup.

**Problems:**
* Slow - we're activating the base environment, then activating the correct user environment (two steps)
* Feels like a hack

**Question**
* Is there a `*.bat` file that we can run in the Command Prompt or similar to activate a conda environment instead of resorting to such hacks.

@msarahan /cc (creating issue as discussed at PyCon)

**Comment by mingwandroid** [comment]
Hi @DonJayamanne, one way is:

```
call <conda_base_env>\condabin\conda_hook.bat
call conda activate <env>
```

Our PowerShell ingeration is now better than our cmd.exe by the way (and the code is a lot cleaner since it's not batch script).

**Comment by DonJayamanne** [comment]
> Our PowerShell ingeration is now better than our cmd.exe

The expectation in VSC for PowerShell is simple.
User needs to have configured PowerShell for conda, and we just send the commands `conda activate ....`, that's as we send.

Hope this is an acceptable solution?

**Comment by mingwandroid** [comment]
> Hope this is an acceptable solution?

Yeah, that sounds OK [* there are caveats]

It depends how deep you want to go with conda environment curation inside VSC itself. I can definitely see the advantage of staying out of that game as it's a lot of work!

[* caveats] (and your PowerShell idea illuminates the issue here very well) .. I'm not *personally* in favour of these new global/system-wide ideas that conda has gained recently and I'd prefer if IDEs were a bit more 'savy' and avoided them for a better user experience, but it is what it is and I guess we'll never remove it. Let me explain the technical reasons behind this ..

It has always and still is possible to install multiple separate conda installations on the same computer. There's some good reasons to do this, esp. if you're a developer. Working on conda on Windows means I need 4 conda base envs on my machine at time, two pythons by 32, 64-bit *and* I want to be able to have totally different versions of conda in each one (so the envs subdirs could be subtly different, and older condas cannot manage envs that have been touched by later condas). Further, conda's environments.txt (in ~/.conda) lists environments from all envs (and even ones since deleted, so I'd ignore that stuff too and look in the envs subdir), so you may have trouble if using that list against an older conda.

**Comment by luchinsky** [comment]
A lazy guy solution. Start any anaconda shell.
Activate required environment.
Start VSC: code from the shell.

**Comment by DonJayamanne** [comment]
Closing this issue, as this is no longer a problem.
