### ISSUE TITLE
conda should not allow to dowgrade python version

### ISSUE THREAD

**Issue by hainm** [conda/conda#8718]
Hi,

I was using python 3.7 and issued below command:
```
conda install pystan pysam -c conda-forge -y
```
This downgraded my python.
```
The following packages will be DOWNGRADED:

  numpy                               1.16.3-py37h7e9f1db_0 --> 1.16.3-py27h7e9f1db_0
  numpy-base                          1.16.3-py37hde5b4d6_0 --> 1.16.3-py27hde5b4d6_0
  py-boost                            1.67.0-py37h04863e7_4 --> 1.67.0-py27h04863e7_4
  python                                   3.7.3-h0371630_0 --> 2.7.16-h9bab390_0
```
I think this is not a correct behavior. Cheers.

My conda -info
```
    active environment : None
       user config file : /home/nguyen/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 2.7.16.final.0
       base environment : /X/nguyen/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /X/nguyen/miniconda3/pkgs
                          /home/nguyen/.conda/pkgs
       envs directories : /X/nguyen/miniconda3/envs
                          /home/nguyen/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/2.7.16 Linux/3.10.0-957.5.1.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 9501:150
             netrc file : None
           offline mode : False
```

**Comment by tonyabracadabra** [comment]
agree

**Comment by tjd2002** [comment]
it appears that `pysam` is only built for Python 2.x:
```
 conda search pysam
Loading channels: done
# Name                       Version           Build  Channel
pysam                            0.6          py26_0  pkgs/free
pysam                            0.6          py27_0  pkgs/free
```

So conda is doing what you asked... 

You could, if you wanted, 'pin' python to a particular version in your env: (See: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning)

**Comment by hainm** [comment]
> So conda is doing what you asked...

I still don't know why `conda` doesn't prevent that? I did not intentionally ask conda to downgrade my python for sure. I just expect conda prevent me not doing that.

**Comment by tjd2002** [comment]
I see what you mean, and this certainly seems like an example of conda violating the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). 

But you requested that conda install a package (pysam) that is only available for python 2.7; and you had not previously pinned python to any particular version; and you used the `-y` option to suppress any user prompts; so I don't think the behavior you encountered can be considered a bug.

Note that if you had instead run:
`conda install pystan pysam 'python>=3'`, then the install would have failed:

```
$ conda install pysam 'python>=3'
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pysam -> python=2.7
  - python[version='>=3']
Use "conda search <package> --info" to see the dependencies for each package.
```

Or, if you had previously pinned python, the install would also have failed:

```
$ conda config --add pinned_packages 'python>=3' --env  # limit pin to this env
$ conda install pysam
Collecting package metadata: done
Solving environment: failed

SpecsConfigurationConflictError: Requested specs conflict with configured specs.
  requested specs:
    - pysam
  pinned specs:
    - python[version='>=3']
Use 'conda config --show-sources' to look for 'pinned_specs' and 'track_features'
configuration parameters.  Pinned specs may also be defined in the file
/Users/tjd/conda/envs/env3/conda-meta/pinned.
```

It seems that you would like Conda to treat the python package as a special case, and to default to not allowing downgrades in order to satisfy a user's install request. There is an open issue that addresses that in a specific way: #7325. 

Issue #7688 could also be relevant here, since it suggests adding a flag that would cause installs to fail if the solution results in a downgrade of **any** package.

Maybe you would like to review those issues, comment there, and close this issue if you think those existing proposals would solve your problem.

**Comment by hainm** [comment]
hi, I don't want to go deeper to the discussion because I think it's just a common sense (of course, your comments are very logical). And yes, you're right about " you would like Conda to treat the python package as a special case". My philosophy is that: make the software "just work" (this is why I like conda when it was originally released).

**Comment by kalefranz** [comment]
If you want python to stay at `=2.7`, then just make sure `python=2.7` is given as a user-requested spec via the command line in either a `conda create` or `conda install` command.

In all of the examples here, conda is behaving exactly as designed. Prior to conda 4.4, we would have indeed raised an unsatisfiable error. However we always want to present users with the best possible solution, if a solution exists. That “best possible solution” has gone through years of tweaking, and indeed one of our principles is minimizing user surprise and trying to “just make it work” most of the time. The “just make it work” part is exactly why, when you request `pysam`, we give you the changes to the environment we would have to make to give you what you’ve requested. The *only* alternative to raising `UnsatisfiableError` is downgrading python, and since you haven’t pinned python explicitly via package pinning or implicitly via a current or past user request, we present the downgrade as a possible solution.

**Comment by hainm** [comment]
> If you want python to stay at =2.7, then just make sure python=2.7 is given as a user-requested spec via the command line in either a conda create or conda install command.

Hi, I think you misunderstood the issue. I am using python 3.7 and want to stay with that, but conda downgrade my python version to 2.7.

**Comment by msarahan** [comment]
No, he's not misunderstanding it. Pysam can't work with your python 3.7 install. It's not built for that. Conda can do one of two things: keep python 3.7  and deny you pysam, it give you pysam and downgrade python. Which go you want? Conda's best guess is that you want pysam, because you have explicitly asked for that, but you may not have explicitly asked for python 3.7. explicit is better than implicit.

All this said, I think you'll find that conda 4.7 had more of your desired behavior here.

**Comment by kalefranz** [comment]
Sorry I meant `=3.7` in my comment above instead of `=2.7`. I’ve edited the comment.

**Comment by hainm** [comment]
> Conda can do one of two things: keep python 3.7 and deny you pysam, it give you pysam and downgrade python. Which go you want? Conda's best guess is that you want pysam, because you have explicitly asked for that, but you may not have explicitly asked for python 3.7. explicit is better than implicit.

Hi @msarahan, you're absolutely right here in term of treating Python just as other programs. May be my mindset is still treating python as 1st class: if the version is changed, the whole conda env is broken (vs it's not really harmful if I downgrade/upgrade numpy version).

PS: I admit that I don't review the dependencies carefully when using "conda install" because I expected conda did the work for me. :D Saying there are two approaches below:

- Do "anaconda search pysam" to see if there's any pysam for my python version. If yes, run "conda install pysam". If No, move on.
- Or another approach: "conda install ...-y", if conda's happy to download, I know there' compatible pysam with my env. If conda raises Error, I know there's not, move on. At the end of the day, I am happy because conda makes thing simple. (Of course, this's all about your or my perspective).

**Comment by hainm** [comment]
> All this said, I think you'll find that conda 4.7 had more of your desired behavior here.

thanks.
