### ISSUE TITLE
Conda 4.7.0 not in Anaconda Cloud

### ISSUE THREAD

**Issue by 6etacat** [conda/conda#8726]
### Steps to Reproduce

Install new miniconda environment.
```
conda update --all
conda --version
```

## Expected Behavior

conda should be version 4.7.0, but it is only 4.6.14, which is the previous release. The 4.7.0 release is not on Anaconda Cloud.

**Comment by msarahan** [comment]
All conda releases spend time on the conda-canary channel before they are released onto defaults.  Conda 4.7.0 had some major issues that we didn't catch because our integration tests weren't yet using the new package format.  We had some chicken/egg problems there.  Because these problems made it hard to revert to a functional installation, we removed conda 4.7.0 from the conda-canary channel.  We'll have a 4.7.1 release soon - it will be on the conda-canary channel, and maybe conda-forge.

**Comment by tydlwav** [comment]
:+1: :D

**Comment by msarahan** [comment]
4.7.1 is on the conda-canary channel now.  Please let us know how it works for you.

**Comment by kalefranz** [comment]
FWIW, some historic perspective on Conda’s release strategy is at https://www.anaconda.com/what-conda-canary/.  When we make release to the `conda-canary` channel, there’s no guarantee they’ll stay. In fact, they might be pulled if it’s clear that there’s a defect, especially if it’s breaking CI systems. Indeed the contract for the `conda-canary` channel is that we WILL pull releases if it’s clear we’re breaking CI systems. The other part of the contract is that we always release to the canary channel before we publish the release to `defaults`.

**Comment by Seanny123** [comment]
Thank you for this information on `conda` releases. I think this issue can be closed now?
