### ISSUE TITLE
Conda deletes powershell and console shortcut on update

### ISSUE THREAD

**Issue by Nathan-Furnal** [conda/conda#8855]
Hi,

When I update conda to the latest version (4.7.5) in my ``base`` env.

I get : 

```
The following packages will be REMOVED:

  console_shortcut-0.1.1-3
  powershell_shortcut-0.0.1-2
```

Which removes the shortcuts obviously,

is this intented behavior?

Thanks

P.S : I'm using miniconda on Win10, lenovo laptop.

**Comment by Huqin-China** [comment]
Bugs in conda4.7.5
Reinstall anaconda2019.03 and don't update any package for now.
Recently issue shows that conda4.7.5 breaks some mechanism.

**Comment by msarahan** [comment]
Those are being removed because the miniconda installer doesn't install them in a way that preserves them as part of the explicit install history.  You can get them back by doing:

``conda install console_shortcut powershell_shortcut``

After that, they should not disappear for you.  There's a lot more information about this issue in https://github.com/conda/conda/issues/8842

**Comment by Ingvar-Y** [comment]
`conda update --all` removed console_shortcut (and conda-env) from my environment after updating conda from 4.6.14 to 4.7.8 despite #8911

This maybe has something to do with having conda-forge above defaults in condarc file.
