### ISSUE TITLE
Change path_conflict config default to prevent

### ISSUE THREAD

**Issue by timsnyder** [conda/conda#8955]
In #4119 `path_conflict` was added with default of `clobber` and @kalefranz said the plan was for 4.5 to change the default to prevent.

Somehow, I thought this already happened but looking at `conda config --show` in my fresh 4.7.5 install says the default is still `clobber`.

Are you guys still planning to switch the default to `prevent`?  Is there any downside to setting it to `prevent` in my .condarc?

**Comment by jjhelmus** [comment]
A number of packages in `defaults` as well as other large community maintained channels like `conda-forge` and `bioconda` have packages which have conflicting paths.  Setting `path_conflict` to `prevent` will cause these packages to un-installable.  You can set the configuration value to `warn` so that conflicts show a warning when a path conflict is detected.
