### ISSUE TITLE
[Question] How to associate a conda environment with a project directory

### ISSUE THREAD

**Issue by afettouhi** [conda/conda#8956]
I have been using miniconda for a while and have set up conda environments for each for each of my projects. What I can't figure out after looking through the documentation, is there a way to bond/associate my conda environment to my project folder for that conda environment? So that when I activate a specific conda environment it moves directly into the associated project directory. This virtualenvwrapper etc. can do for example. Is conda able to this?

**Comment by timsnyder** [comment]
@afettouhi  do you have a full miniconda install for each of your projects or do you have a single miniconda install that uses 'environments'.  

There isn't a first-class feature (that I'm aware of) in conda to do this but depending on how you have things setup, it would be easy to create a package that would have this side-effect if you had it installed in your environments.

Can you add the output of `conda info` and `conda env list` to this ticket so I can see how you have things setup?

**Comment by afettouhi** [comment]
I have a single miniconda install and then I use different environments I use for each of my projects. Here is the output of `conda info`

(base) [af@andre ~]$ conda info

     active environment : base
    active env location : /home/af/Dokumenter/Programs/miniconda3
            shell level : 1
       user config file : /home/af/.condarc
 populated config files : /home/af/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : /home/af/Dokumenter/Programs/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/af/Dokumenter/Programs/miniconda3/pkgs
                          /home/af/.conda/pkgs
       envs directories : /home/af/Dokumenter/Programs/miniconda3/envs
                          /home/af/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/5.2.1-arch1-1-ARCH arch/ glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

and `conda env list`

(base) [af@andre ~]$ conda env list
# conda environments:
#
base                  *  /home/af/Dokumenter/Programs/miniconda3
demo-ml-python3          /home/af/Dokumenter/Programs/miniconda3/envs/demo-ml-python3
demo-numpy-python3       /home/af/Dokumenter/Programs/miniconda3/envs/demo-numpy-python3
demo-pandas              /home/af/Dokumenter/Programs/miniconda3/envs/demo-pandas
demo-playbook            /home/af/Dokumenter/Programs/miniconda3/envs/demo-playbook
demo-python-standard-library     /home/af/Dokumenter/Programs/miniconda3/envs/demo-python-standard-library
explore-iris             /home/af/Dokumenter/Programs/miniconda3/envs/explore-iris
hello                    /home/af/Dokumenter/Programs/miniconda3/envs/hello

**Comment by timsnyder** [comment]
What are the paths for the project directories you'd like to cd into?

**Comment by afettouhi** [comment]
Some of them are located here:

`/home/af/Dokumenter/Programs/Jupyter/demo-ml-python3/`
`/home/af/Dokumenter/Programs/Jupyter/demo-numpy-python3/`
`/home/af/Dokumenter/Programs/explore-iris/`
`/home/af/Dokumenter/Programs/hello/`

**Comment by timsnyder** [comment]
I'm assuming that you cd into your project directories using virtualenv by manually editing the activate script for the environment?  

To do the same type of thing in conda, you can put a oneline script in the environment's `etc/conda/activate.d/` directory.  Depending on what packages you have installed, the directory may not exist yet.  For example, you could create `/home/af/Dokumenter/Programs/miniconda3/envs/demo-ml-python3/etc/conda/activate.d/cd-to-project.sh` that contains

`cd /home/af/Dokumenter/Programs/Jupyter/demo-ml-python3`


**_Manually editing files in a conda environment is definitely not best practice._**  It would be much better if you created a conda package that could be installed in all of your environments and 'own' this activation script.  Ideally, you'd probably want to come up with a way to generically map your environment name to the project directory.  For example if all of your projects lived in the same toplevel directory, you could change your script to be generic:

`cd /home/af/Dokumenter/Programs/projects/$(basename "$CONDA_PREFIX")`

If you didn't want to have all projects contained in one directory (i.e. you'd like a more complex mapping), you could write a more complex script that reads a configuration file somewhere mapped an environment name to the project directory.

Currently, conda doesn't let you put user-defined info in the .condarc but it might even be worth asking for a new feature in conda where it would allow an 'extra' level in the .condarc file where you could put this mapping.  If you had that feature, you could set the project directory like this:

`conda config --env --set extra.project_dir <some directory>`

And then your activation script in your conda package could do something like:

`cd $(conda config --file $CONDA_PREFIX/.condarc --get extra.project_dir)`

I use `--file` in the activation script because I'm not sure whether you would get the value from the environment being activated without it.

**Comment by afettouhi** [comment]
I have miniconda installed in my home directory, installed from the website. Then I activate the base environment with

`eval "$(/home/af/Dokumenter/Programs/miniconda3/bin/conda shell.bash hook)"`

I activate the project environment I want to on for example:

`conda activate demo-playbook`

and then I cd into the project folder where `demo-playbook` is.

**Comment by timsnyder** [comment]
Sure.  So in this case, if you create `/home/af/Dokumenter/Programs/miniconda3/envs/demo-playbook/etc/conda/activate.d/cd_project.sh` that contains:

`cd <path to demo-playbook project>`

When you run `conda activate demo-playbook` it will cd into the `demo-playbook` project directory for you.

**Comment by afettouhi** [comment]
I just tried to do that and it doesn't work.

**Comment by afettouhi** [comment]
Ignore my last comment I got it working. I missed the conda directory before the activate.d directory

**Comment by afettouhi** [comment]
Is there a plan to add this feature to conda?

**Comment by timsnyder** [comment]
> Is there a plan to add this feature to conda?

The basic functionality of having activation scripts is already a part of conda.  It is also already possible to create a package that you can install that provides the activation script.  

What would you like to see added or changed from what you've done so far?

**Comment by afettouhi** [comment]
I guess I am asking for a feature like in virtualenv that when you activate you specific environment it reads .profile in your home directory and the location of project folders and then cd's into it.

**Comment by timsnyder** [comment]
Didn't mean to discourage you with my comment.  I'm not familiar with virtualenv and how it works.  

Looking at a bit more documentation, I can see that `mkvirtualenv` from `virtualenvwrapper` lets you pass `-a <project_path>` when creating a virtualenv and then after that when you `workon`  your project, it activates the virtualenv and cd's into the associated directory given with `-a <project path>` when you created the environment.

There isn't currently a supported highlevel feature to do this.

I'm not the right person to answer whether there are plans to add something like this but since you find this bind/associate feature of virtualenvwrapper useful, I'm glad you asked.  If you reopen the issue, one of the core developers  from Anaconda might be able to address whether this has come up before and whether they have a feature like this on the roadmap or would accept a PR for one.

**Comment by afettouhi** [comment]
You didn't discourage me at all. I just closed this issue since it was solved. Many thanks for your help and answering my questions. It could be a nice feature to have in conda plus the reason I even posted this question here was that I couldn't fins anything on it in the documentation. Everything I found in the documentation was only about activating the environment but nothing about how it links to the project directory. Again many thanks this way of making a .sh shell script in the `../etc/conda/activate.d/` directory fine for me and good to know. All the best!

**Comment by jaclu** [comment]
I expanded a bit on the suggestion from @timsnyder  and added another script so I will be put back to my previous location when I deactivate the venv. 
Note that I still use bash, for other shells you might have to remove the variable in a different way...

=== ../envs/venv_name/etc/conda/activate.d/cd-to-project.sh ===
export PRE_VENV_WD=$(pwd)
cd /foo/bar/proj_dir
-------------------------------

=== ../envs/venv_name/etc/conda/deactivate.d/cd-to-previous.sh ===
cd $PRE_VENV_WD
unset PRE_VENV_WD
-------------------------------

**Comment by siraj-samsudeen** [comment]
I tried these steps but it did not work for me. How do I know whether cd_project.sh was run? 

And here is the output conda info
```
active environment : quran-srs
    active env location : /opt/anaconda3/envs/quran-srs
            shell level : 2
       user config file : /Users/siraj/.condarc
 populated config files : /Users/siraj/.condarc
          conda version : 4.10.1
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/siraj/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/siraj/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.5 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
