### ISSUE TITLE
Add support for channel and solver arguments to conda env create

### ISSUE THREAD

**Issue by alimanfoo** [conda/conda#9065]
When creating an environment from a yaml environment definition file, I would like to be able to ensure that channel and solver options are **not** being picked up from .condarc but can be controlled explicitly. I.e., I think I would like to be able to do:

```
conda env create --file environment.yml --name example --strict-channel-priority --override-channels
```

...where `--strict-channel-priority` behaves as in the `conda create` command, and `--override-channels` ensures that channel information is pulled only from the environment.yml file.

Additionally I'd like to be confident that the order of the channels specified in the environment.yml file will be fully respected, which I'm not sure is the case (xref https://github.com/conda/conda/issues/7238). If not, I would also like to be able to use the `--channel` argument with `conda env create` so I can be sure of channel order. E.g.:

```
conda env create --file environment.yml --name example --strict-channel-priority --override-channels --channel conda-forge --channel bioconda --channel defaults
```

The rationale is to be able to be confident of reproducible environments across different systems, where users may have manually altered their .condarc and hence we want to be sure to override.

**Comment by soapy1** [comment]
Another option you have here is to have a shared/curated condarc file and specify that conda should use it using the `CONDARC` env var. Or, you can set configuration using environment variables of the form `CONDA_<config parameter name>`. e.g `CONDA_CHANNEL_PRIORITY='strict'`. 
See our docs for more info on this https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#precedence

**Comment by alimanfoo** [comment]
Thanks @soapy1, knowing about the environment variables is very useful. Just to double check, are you absolutely sure the CONDA_CHANNEL_PRIORITY environment variable will be picked up and respected by ``conda env``? I just ask because I'm aware `conda create` and `conda env create` are different code paths.

**Comment by soapy1** [comment]
They should be. If you find that it doesn't, then that is definitely a bad bag

**Comment by mforbes** [comment]
This is a major pain.  For example, on one shared system I use, the base environment has a `condarc` files with so many channels that almost any `conda` operations run out of memory.  Since conda just merges the channels from all files, there seems to be no way to stop the base channel list from spoiling the environment except `--override-channels` which [does not work with `conda env create`](https://github.com/conda/conda/issues/10498), completely destroying reproducibility (and usability).

Specifying `CONDARC` as suggested simply adds more channels - still no way of cleaning the channel list.
