### ISSUE TITLE
Update env.yml file automatically on installing new packages

### ISSUE THREAD

**Issue by janosh** [conda/conda#9118]
Would be nice if there was an `conda install` option or better yet if it could be made the default that new package installations are automatically added to the environment's `env[ironment].y[a]ml` file.

This is the default behavior for both JavaScript package managers (see [`yarn add`](https://yarnpkg.com/lang/en/docs/cli/add/) and [`npm install`](https://docs.npmjs.com/cli/install)) which automatically update `package.json`. It's also been [suggested on StackOverflow a year ago](https://stackoverflow.com/questions/52639713/update-conda-yml-file-automatically).

**Comment by eddietaylor** [comment]
that would honestly be great

**Comment by davidgilbertson** [comment]
I'm new to Conda. Is it really still the case in 2022 that there's no way to automatically track my dependencies?
I've come from npm and pipenv and would have thought this is one of the first features any package manager would implement. Am I missing something? How do people actually use Conda with a codebase shared with a team via Git?

**Comment by ilyakochik** [comment]
Hello! Is this being implemented? I see @kenodegard added this to Planning, but then bots closed it.

**Comment by imaspol** [comment]
Hi, was it implemented?

**Comment by thisdotmatt** [comment]
It's been nearly 6 years since the original stack overflow post, and it's clear that this feature won't be implemented anytime soon. Related issues can be found [here](https://github.com/conda/conda/issues/8800) and [here](https://github.com/conda/conda/issues/4205).

I wrote up a simple VSCode Extension that addresses this, called [CondaSync](https://github.com/thisdotmatt/CondaSync). It's a work-in-progress, but it's already allowed my conda workflow to mirror an npm or yarn one. I've also considered writing a conda plugin, but I'm not sure how feasible this would be. In the meantime, contributions and feedback are welcome.
