### ISSUE TITLE
Incorrectly escaped path for active_prefix

### ISSUE THREAD

**Issue by wvxvw** [conda/conda#9119]
I believe this is related to #7577

It is an Anaconda setup on MSYS2 and ZSH... I know, it isn't officially supported, but I already patched a lot of things to almost get it to work.  But, now I'm at a loss: where does this variable come from: `active_prefix`?  It is definitely broken (whether my setup is supported or not--doesn't matter) because it reads `C:\bin` and interprets it as if it was a string literal, rather than the value.  So, active prefix gets set to `Cin`.

I can sidestep some of the problems this creates by explicitly supplying `--prefix=/c/bin` or `--prefix=C:/bin` both will work, but some commands seem to ignore `--prefix` and some simply don't take this argument...

----

As an aside: `conda` seems to "remember" some environments which are not mentioned in `~/.conda/environments.txt`, and it insists on using backwards slashes... Why would you ever use backwards slashes anywhere? This is completely unnecessary... :(

**Comment by mingwandroid** [comment]
> Why would you ever use backwards slashes anywhere?

Because that is that standard slash on Windows?

**Comment by mingwandroid** [comment]
> It is an Anaconda setup on MSYS2 and ZSH... I know, it isn't officially supported, but I already patched a lot of things to almost get it to work. But, now I'm at a loss: where does this variable come from: active_prefix? It is definitely broken (whether my setup is supported or not--doesn't matter) because it reads C:\bin and interprets it as if it was a string literal, rather than the value. So, active prefix gets set to Cin.

The bash shell changes this. This is not a bug. If you are using the MSYS2 shell you are expected to pass all paths to any programs (be they MSYS2/msys2, MSYS2/mingw-w64 or MSVC-compiled) in POSIX form, so the *correct* invocation is `--prefix=/c/bin`.

**Comment by mingwandroid** [comment]
Also, this is not related to https://github.com/conda/conda/issues/7577 (which is fixed) at all.

**Comment by wvxvw** [comment]
> Because that is that standard slash on Windows?

No, it isn't. 

1. Windows or Microsoft never declared any standards wrt path formatting.
2. Forward slashes work just fine.

But, now you just made life of people wanting to work with `conda` more difficult.

It doesn't matter though.  I'm not here to lecture about path escaping. The bug in your code is that `active_prefix` is red / escaped incorrectly.  The `\b` in it should have never been interpreted as "bell", no matter the platform you are on.

**Comment by mingwandroid** [comment]
Please drop your aggressive tone. You claim to have hacked up your conda in various ways and then ask us to support and help you with that, in this way?

> It doesn't matter though. I'm not here to lecture about path escaping. The bug in your code is that active_prefix is read / escaped incorrectly. The \b in it should have never been interpreted as "bell", no matter the platform you are on.

Where to begin with such a statement? Please do not try to lecture me about path escaping. I don't wish to apeal to authority here, but trust me everything I said is true. For reference, I was the co-founder of MSYS2 (so I have a good knowledge of how it works internally => I know which program (and/or DLL) translates which paths and at which points during the execution). I also implemented both `MSYS2_ARG_CONV_EXCL` and `MSYS2_ENV_CONV_EXCL` env. vars which are hacks specifically to workaround issues with path conversion, but you're not running into any of that.

Here you have the msys2-runtime looking at your \b and escaping it, resulting in nothing. That you disbelieve that is neither here nor there. You can confirm it for yourself if you wish but I trust you already know which tools to use to do that already and don't want someone telling you things.

> No, it isn't.
>
>    Windows or Microsoft never declared any standards wrt path formatting.
>    Forward slashes work just fine.

Again, an appeal to authority but this time, not my own. From https://en.wikipedia.org/wiki/Backslash :

> but the Microsoft convention remains to use a backslash

> But, now you just made life of people wanting to work with conda more difficult.

The very next sentence on that page strongly contradicts this:

> ,and APIs that return paths use backslashes

..  so you'd require everyone else to switch their backslahes returned from the WIN32 API to forward slashes I presume?

For another indicator that perhaps, on Windows (i.e. non-POSIX emulation programs) stating the backslash to be the default is reasonable can be found at https://docs.python.org/3/library/os.html#os.sep

The ironic thing about this exchange is that conda works just fine in MSYS2 and it does that specifically because I work on both projects and have spent a lot of my time to make this work.

You also entirely failed to provide a useful reproduction which, given you felt the need to hack conda up due to your misconceptions, is hardly surprising!

If you want to start from scratch, and use conda as it's intended, yes, on MSYS2 (and with zsh if you wish but you really are pushing at the edges of what is expected to work doing that, as I can guarantee not many will run with that) and if you run into some problems then please open a proper bug report so we can investigate that.

Good luck.

**Comment by wvxvw** [comment]
You are mostly right, but ultimately provide me with useless information.
All I need to know from you is how conda gets its value for active prefix.
The code around it is extremely convoluted and repetative, so it's
difficult to understand how that happens.

You are definitely wrongs though about conda working in msys2... not even
sure how would you get this idea. One thig, for instace, that prevents
conda from working in this environment is that it emits MSDOS style line
ends to its helper commans defined in the hook loaded in the shell profile.
This has zero chance of working, and that was the part that I patched.

**Comment by mingwandroid** [comment]
I am sorry that you think it appropriate to hack up conda due to a bug / missing feature in MSYS2's port of zsh and that you think it appropriate to emit non-standard line-endings to files on Windows.

MSYS2's bash handles `\r\n` just fine. Here is the patch we use to implement that:

**Comment by mingwandroid** [comment]
And I have no interest in directly answering your question because it is the wrong question, much like your `\r\n` fix in conda is the wrong {fix, package, ecosystem}.

**Comment by mingwandroid** [comment]
If you do want to fix this likely bug in MSYS2's zsh, you could use the bash patch above as inspiration and try to contribute a patch to this folder of MSYS2: https://github.com/msys2/MSYS2-packages/tree/master/zsh

I don't know if you know C though.

**Comment by wvxvw** [comment]
I didn't touch conda to fix it... The Python code is a hellish mess, but
this isn't the real problem: the real problem is that it will get updated
any and every time the environment is updated or new packages get
installed. It would be impossible to keep up with these updates.

I changed the shell hook to filter out the bad characters produced by
conda. Luckily, this part doesn't get updated unintentionally.

This, again, has nothing to do with ZSH. It's a bug in conda's code, where
it reads some environment variables incorrectly. It's just too hard to find
where it does it, because, like I said, the code is a mess. If I had to
guess, it's the custom YAML parsing routines, but, again, I couldn't find
it, so, who knows.

**Comment by mingwandroid** [comment]
Ok, you know everything. That's fine; I won't try to help you.

**Comment by mingwandroid** [comment]
In the meantime, I will check to see if MSYS2's zsh handles `\r\n` like it should do and if not I'll at least file a bug. Fixing things in the wrong place is a poor practice because then it needs to be fixed in multiple (wrong) places.

**Comment by wvxvw** [comment]
Lol. What a drama queen :) I'm practically bursting into tears here because
you wont't help me fix a bug in your project. Look what you've done, you
monster *loud sobbing*!
