### ISSUE TITLE
Support for PEP517

### ISSUE THREAD

**Issue by Liam-Deacon** [conda/conda#9133]
Hi - I was wondering if conda supports (or could be made to support) [PEP517](https://www.python.org/dev/peps/pep-0517/)?

It would be truly awesome if conda can be specified as a build system backend for pip in instances where packages can't be built from source easily. 

There is a good example using poetry [here](https://github.com/sdispater/poetry/blob/master/poetry/masonry/api.py) which could maybe be used as a template for creating the PEP517 compliant backend build system API.

**Comment by jjhelmus** [comment]
It does not really make sense for conda to be a PEP517 backend.  A case could be made for [conda-build](https://github.com/conda/conda-build) to be a 517 frontend although the how exactly this would work are an bit unclear.

PEP 517 lays out a requirements for a Python build system.  Conda is a package and environment manager, it is not involved in building packages or wheels except that it can be used to set up an environment where a build could take place.  In this manner you might consider it similar to `virtualenv` of `venv`.  Both of these mentioned as in the PEP as choices that a build system frontend could use to create an isolated build environment and one could imaging using conda in a similar manner.

[Conda-build](https://github.com/conda/conda-build) is the tool used to create conda packages.  It uses conda to create an isolated environment and then runs the necessary commands inside this environment to create artifacts.  In most cases these artifacts are conda packages but conda-build can also output wheels if they are produced by the build steps.  In many ways this sounds like a case for `conda-build` to be a PEP 517 frontend since wheels are produced.  

The main issue is that conda-build does not create the wheels by itself.  Rather in calls other build system from inside the isolated environment to accomplish everything.  For Python packages this typically means running either `pip install ..` or `python setup.py install ...` inside the isolated environment.  So in many (most?) cases conda-build is already calling a PEP 517 frontend to call a backend which builds a wheel which the front end then installs.  

One could argue that conda-build should be a frontend itself, it could call the appropriate backend  and then install the wheel.  This would require implementing the logic to do both of these steps, which are already performed quite well by `pip`.
