### ISSUE TITLE
numpy mkl conflicting with other programs mkl

### ISSUE THREAD

**Issue by RoyLarson** [conda/conda#9244]
I have a program that interacts with a proprietary windows COM library (Bryan Research and Engineering - Promax).  The COM library is uses an intel-mkl library installed in its path.  When I install numpy with conda I get the mkl libraries with it.  Activating the environment causes the COM library to lose its reference to its mkl libraries causing it to error out.  Do you have any suggestions on a work around?  I know this is not a conda problem but am not sure where else to ask.

Thanks in advance

**Comment by mingwandroid** [comment]
You could request that Promax change their code so that they use explicit full paths to load their MKL libraries instead of relying on PATH. That's not an option for us unfortunately due to how tightly integrated MKL is into the Anconda Distribution ecosystem.

The only other option is to deactivate conda before calling Promax. Does Promax come with Python bindings though? Do you need to use Promax Python extension modules in the same Python process as Anaconda Distribution Python extension modules? That will always be problematic I'm afraid.

**Comment by RoyLarson** [comment]
Thanks for the reply. 
I will definitely contact BRE with your suggestion. 
Promax does not come with python bindings.  I am using comtypes to run and adjust the inputs to the simulations that their program runs.  This works really well for me, but now I need to run scipy.integrate.RK45 on a portion of the simulation and that is going to take numpy.

**Comment by msarahan** [comment]
It probably comes down to the PATH environment variable. That is how anaconda finds mkl. The tricky thing about it is that library loading is a per-process thing. Your promax thing might have mkl libraries next to its binary, which is ideal for not interfering with other things, but if the parent python process has already loaded mkl, you might be up a creek. Try to run promax with as much isolation as you can. Do not pass the python process env vars to any subprocess.
