### ISSUE TITLE
Fallback on Pip Install

### ISSUE THREAD

**Issue by blink1073** [conda/conda#931]
Currently if a package is not found by `conda install`, you get a nice message about binstar.  For new users (and lazy users like me), it would be nice if the default fallback behavior of `conda install` would be to use `pip install` in the current environment.  This would mean that we only use _one_ package manager for all tasks.

At the very least, Miniconda should ship with `pip`.

**Comment by jakirkham** [comment]
Also very eager to see this.

**Comment by markwhitfield** [comment]
+1

**Comment by MaxNoe** [comment]
PLEASE add this!

**Comment by jakirkham** [comment]
Just brainstorming, maybe a `pypi` pseudo-channel could be added for this case.

Also, I think this would massively cut down on the cruft that currently fills [conda/conda-recipes]( https://github.com/conda/conda-recipes ).

**Comment by dusans** [comment]
If you are using venv you can also use an environment.yml which also list all pip packages to install. Very handy.

**Comment by mayerwin** [comment]
+1

**Comment by JanSchulz** [comment]
Please not: IMO it should be an explicit step to pollute the conda environment with non-conda (e.g. pip, r,...) installed packages.

Adding an automatic step to call pip is also very problematic in the case that there is an pip package with the same name as the conda package but with different content. In cases like unavailable conda packages (e.g. for certain python versions), this means that a wrong package is installed. If this even happens for requirements, this would be really bad.

Conda is also used to install r packages. While these packages are currently easily identifiable via a `r-` prefix, it could also mean that requesting `conda install r-unavailable` would install a python package with that name. Conda can potentially be used to install more than python packages and should not gain a default fallback to only one package type.

IMO a better idea is to add an explicitly hint to pip (or other package manager) and not only to `conda search`. Another step would be a community supplied central conda channel, so that more python (and other) packages are available via conda.

**Comment by mcg1969** [comment]
> Another step would be a community supplied central conda channel, so that more python (and other) packages are available via conda.

Funny you should say that... we are working on it (as are others). Stay tuned.

**Comment by jakirkham** [comment]
Yes, funny. This sounds like a good idea. Do you have a timeline yet or is this still in the early phases?

**Comment by mcg1969** [comment]
Nothing we're ready to share yet, but it is an active effort.

**Comment by cdeepakroy** [comment]
Very eager to see this fix. Would solve the problem we are facing that is described [here](http://stackoverflow.com/questions/35802939/install-only-available-packages-using-conda-install-yes-file-requirements-t)

**Comment by dusans** [comment]
Our team has now switched to using 
environment.yml: http://conda.pydata.org/docs/using/envs.html#export-the-environment-file

This way we no longer need a fallback to pip.

**Comment by ssbarnea** [comment]
Lack of transparent solution prevents lots of people from adopting conda because it does not allow us to slowly intoduce it.

**Comment by mcg1969** [comment]
I'm with @janschulz on this one. The hazards of "slow" adoption are greater than the benefits.

**Comment by jakirkham** [comment]
This might even be something we play with on the conda-forge side. To early to say how we do this, but there is interest in doing it some way.

**Comment by mcg1969** [comment]
Continuum has experimented with auto-generation of conda packages built from pip. I believe [this](https://anaconda.org/auto) is the channel where those builds were deposited.

**Comment by aadu** [comment]
Any update on this?

**Comment by kalefranz** [comment]
There was a brief period of time where conda actually did fall back to pip, and that change was quickly reverted.  (This was several years ago.)  The fallback behavior has some pretty disastrous unintended consequences.

At this point, what's more possible would be for conda to directly install wheels from PyPI.  If there's community interest in that, I'd encourage discussion directly exactly toward that feature in a new issue.
