### ISSUE TITLE
Add system C library virtual package

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#9348]
It would be useful to have a virtual package, which tracked the type and version of system C library. This could be useful for people tracking the version GLIBC they built against on Linux. It could also be useful for other C libraries like musl. Finally this could be useful for other platforms that have their own respective system C libraries (like on macOS for example).

**Comment by jakirkham** [comment]
For reference, linking @beckermr 's PR ( https://github.com/conda/conda/pull/9349 ).

**Comment by jjhelmus** [comment]
The existing [`linux_get_libc_version` function](https://github.com/conda/conda/blob/4.7.12/conda/common/_os/linux.py#L19-L75) in conda or the standard library's [platform.libc_ver](https://docs.python.org/3.7/library/platform.html#platform.libc_ver) might be useful for implementing this virtual package.  

Do keep in mind that not all libc implementation are as backwards compatible as glibc.  A simple version comparison may not be sufficient for these libraries.

**Comment by scopatz** [comment]
PR at https://github.com/conda/conda/pull/9358

**Comment by jakirkham** [comment]
Also PR ( https://github.com/conda/conda/pull/9349 ) is adding the ability to track macOS version.

**Comment by jakirkham** [comment]
It's probably now worth thinking about how we should start to use these virtual packages in Conda recipes/packages.

**Comment by davidbrochart** [comment]
I was looking at virtual packages. Is there a conda package which e.g. depends on glibc, that could not be installable if I `export CONDA_OVERRIDE_GLIBC=0.1`?

**Comment by jakirkham** [comment]
Probably we want to add that to the compiler runtime libraries. Not sure if we already did that

cc @isuruf (who may know)

**Comment by zklaus** [comment]
I just stumbled across this issue due to conda-forge/gdal-feedstock#606. Since I think this functionality is now available, perhaps you want to close this issue.

But if you want to follow up on @jakirkham's suggestion of thinking about how to use this, it would probably be useful if a host dependency on the correct `__glibc`  version could be added automatically if the build requirements contain a non-standard sysroot.

If this is not possible or desirable to do automatically, perhaps an addition to the documentation on using different sysroots that recommends it could be considered.

**Comment by jaimergp** [comment]
This was closed by https://github.com/conda/conda/pull/9358 long ago
