### ISSUE TITLE
conda env create only installs a fraction of the packages listed in yml

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#9413]
I've got an `environment.yml` file that contains the following:

```
name: gp_tutorial

channels:
  - conda-forge

dependencies:
  - python=3.7
  - conda-forge::arviz
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - lxml
  - matplotlib
  - mkl-service
  - notebook
  - numpy=1.16
  - pandas
  - patsy
  - pip
  - pymc3
  - pydot
  - python-graphviz
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - theano
  - xlrd
```
However, when I run `conda env create`, only a small fraction are installed:

```
Downloading and Extracting Packages
matplotlib-3.1.1     | 7 KB      | ##################################### | 100% 
liblapack-3.8.0      | 10 KB     | ##################################### | 100% 
curl-7.65.3          | 125 KB    | ##################################### | 100% 
clangxx-9.0.0        | 13 KB     | ##################################### | 100% 
libopenblas-0.3.7    | 8.3 MB    | ##################################### | 100% 
libcblas-3.8.0       | 10 KB     | ##################################### | 100% 
ld64-409.12          | 1.0 MB    | ##################################### | 100% 
libblas-3.8.0        | 10 KB     | ##################################### | 100% 
libllvm9-9.0.0       | 19.7 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: \x1b[32mOK\x1b[0m\n'
```
moreover, there are no error messages suggesting anything went wrong.

Running conda 4.7.12 on macOS Catalina.

**Comment by fonnesbeck** [comment]
It appears this is because I have `conda-forge` specified in the channels section. However, I would expect some feedback to assert that not all the specified packages could be found and installed.

**Comment by soapy1** [comment]
Conda will only download packages that are not already on your computer. For example, if you already downloaded seaborn it will be in your package cache and not re-download if you try to install it into another environment. When you activate your environment can you use the `conda list` command to confirm that you have all the packages specified.

**Comment by fonnesbeck** [comment]
Many of the packages were not installed, as they could not be imported after I had activated the environment. When it was clear that things were not working as expected, I also did a `conda clean --all` which should have dealt with the package cache, yet the problem persisted. The output I posted above was actually after I cleaned everything out.

**Comment by msarahan** [comment]
conda clean --all will only remove things that aren't present in any known environment, so it's possible that the packages are still in the cache (in extracted folder format).  The only way to know for sure is to look in your install prefix's "pkgs" folder.

What did conda list show for the environment?  There's certainly something wrong here, but I'm not sure what yet.  If you can confirm any files that you know should be present are or are not present, that would help.  Perhaps `<PREFIX>/bin/jupyter` would be good, since it is in your deps, but not in the list of downloads you show.

It is possible that the package cache itself got corrupted, but I think you'd see warning messages from conda if that were the case.
