### ISSUE TITLE
Conda issue 

### ISSUE THREAD

**Issue by zahrael97** [conda/conda#9513]
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/home/zahrael97/anaconda3/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

the envir is not activated what should i do ?

**Comment by soapy1** [comment]
Please fill in the rest of the issue template

**Comment by zahrael97** [comment]
> Please fill in the rest of the issue template

sorry, but what should i fill ?

**Comment by soapy1** [comment]
Issue template:

## Current Behavior
What actually happens?


### Steps to Reproduce
 If the current behavior is a bug, please provide specific, minimal steps to independently reproduce. Include the exact conda commands that reproduce the issue and their output between the ticks below.
```

```


## Expected Behavior
 What do you think should happen?


## Environment Information
<details open><summary><code>`conda info`</code></summary><p>
```

```
</p></details>


<details open><summary><code>`conda config --show-sources`</code></summary><p>


```

```
</p></details>


<details><summary><code>`conda list --show-channel-urls`</code></summary><p>


```

```
</p></details>

**Comment by killalarm** [comment]
i meet to
