### ISSUE TITLE
Please Make Tf2.1 Installable

### ISSUE THREAD

**Issue by yourtheron** [conda/conda#9591]
Looking forward to it! Thanks!

**Comment by msarahan** [comment]
Quoting from the issue template,

Hi! Read this; it's important.

This is an issue tracker for conda -- the package manager. File feature requests
for conda here, as well as bug reports about something conda has messed up.

If your issue is a bug report for:

a specific conda package from Anaconda ('defaults' channel):
==> file at https://github.com/ContinuumIO/anaconda-issues
a specific conda package from conda-forge:
==> file at the corresponding feedstock under https://github.com/conda-forge
repo.anaconda.com access and service:
==> file at https://github.com/ContinuumIO/anaconda-issues
anaconda.org access and service:
==> file at https://anaconda.org/contact/report
commands under 'conda build':
==> file at https://github.com/conda/conda-build
commands under 'conda env':
==> please file it here!
all other conda commands that start with 'conda':
==> please file it here!
If you continue on,

please include all requested information below.

If a maintainer determines the information is required to understand
your issue, and if it is not provided, your issue may be
closed automatically.
