### ISSUE TITLE
from conda.cli import main ModuleNotFoundError: No module named 'conda'

### ISSUE THREAD

**Issue by sigurdurb** [conda/conda#9672]
## Current Behavior

After we did `conda install -c conda-forge imbalanced-learn` it updated some packages and seems to have made conda command disabled so now we always get `ModuleNotFoundError: No module named 'conda'` when trying to execute conda commands, My PATH also has `/opt/conda/bin:` and even doing `/opt/conda/bin/conda` directly fails:

```
root@jupyter:# conda
Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

I installed conda with miniconda and the python executable still loads, python updated itself while installing imbalanced-learn so maybe that did something to the conda executable? I also get a ModuleNotFoundError: for every package I try to import into Python that is currently a conda package. As you can see from the conda-meta/history log below, that shows the update that damaged conda, the version is 4.5.11

```
==> 2020-02-08 14:44:22 <==
# cmd: /opt/conda/bin/conda install -c conda-forge imbalanced-learn
# conda version: 4.5.11
-conda-forge::ca-certificates-2019.3.9-hecc5488_0
-conda-forge::certifi-2018.8.24-py35_1001
-conda-forge::openssl-1.0.2r-h14c3975_0
-conda-forge::setuptools-40.4.3-py35_0
-defaults::blas-1.0-mkl
-defaults::libgcc-ng-8.2.0-hdf63c60_1
-defaults::libstdcxx-ng-7.2.0-h7a57d05_2
-defaults::numpy-1.13.3-py35hdbf6ddf_4
-defaults::pip-8.1.2-py35_0
-defaults::python-3.5.2-0
-defaults::scikit-learn-0.19.1-py35hbf1f462_0
-defaults::scipy-1.1.0-py35hfc37229_0
-defaults::wheel-0.29.0-py35_0
+conda-forge::_libgcc_mutex-0.1-conda_forge
+conda-forge::_openmp_mutex-4.5-0_gnu
+conda-forge::blas-2.11-openblas
+conda-forge::ca-certificates-2019.11.28-hecc5488_0
+conda-forge::certifi-2019.11.28-py36_0
+conda-forge::imbalanced-learn-0.6.1-py_0
+conda-forge::joblib-0.14.1-py_0
+conda-forge::libblas-3.8.0-11_openblas
+conda-forge::libcblas-3.8.0-11_openblas
+conda-forge::libgcc-ng-9.2.0-h24d8f2e_2
+conda-forge::libgomp-9.2.0-h24d8f2e_2
+conda-forge::liblapack-3.8.0-11_openblas
+conda-forge::liblapacke-3.8.0-11_openblas
+conda-forge::libstdcxx-ng-9.2.0-hdf63c60_2
+conda-forge::ncurses-5.9-10
+conda-forge::numpy-1.18.1-py36h95a1406_0
+conda-forge::openssl-1.0.2u-h516909a_0
+conda-forge::pip-20.0.2-py_2
+conda-forge::python-3.6.3-0
+conda-forge::scikit-learn-0.22.1-py36hcdab131_1
+conda-forge::scipy-1.4.1-py36h921218d_0
+conda-forge::setuptools-45.1.0-py36_0
+conda-forge::wheel-0.34.2-py_1
+defaults::libopenblas-0.3.6-h5a2b251_2
# update specs: ['imbalanced-learn']
```

**Comment by sigurdurb** [comment]
The problem was that this install above updated to python3.6. 

I did fix this by just copying from an old python3.5, packages like ruamel-yaml and some other that were needed for conda to run into the lib/python3.6 site-packages folder inside conda. Then did conda install --revision nr. that reverted back to python3.5

**Comment by sigurdurb** [comment]
This should work:
```
pip install ruamel-yaml
pip install pycosat
```

Or you could try this, but it could end badly to mess with the environment.
```
cp -r python3.5/site-packages/ruamel_yaml python3.6/site-packages/
cp -r python3.5/site-packages/ruamel_yaml-_VERSION-py3.5.egg-info python3.6/site-packages/
cp -r python3.5/site-packages/pycosat python3.6/site-packages/
cp -r python3.5/site-packages/pycosat.cpython-35m-x86_64-linux-gnu.so python3.6/site-packages/
cp -r python3.5/site-packages/pycosat-0.6.3-py3.5.egg-info python3.6/site-packages/

```

**Comment by sigurdurb** [comment]
I would still like to find out why conda gets disabled when installing another version of python(by mistake or not) into the base environment?
So calling conda results in this error:
`ModuleNotFoundError: No module named 'conda' `

**Comment by kalefranz** [comment]
This is a bug in the conda solver. When conda switched out the python version to comply with your request to install `imbalanced-learn`, it should have changed all packages that were built for a specific version of python, or for `noarch: python` packages should have uninstalled and re-installed them.

**Comment by anderl80** [comment]
Is there a way to manually solve this if you ran into this issue?

**Comment by M-kadi** [comment]
On Windows : go to "System Properties" -> "Environment Variables" -> clear value of "PYTHONPATH"

**Comment by reallsx** [comment]
Guys I think I found a new solution to this problem. Hopefully it is not breaking anything else.

The cause of this problem is that the python version of the base environment was changed and conda only works with the previous version. Take the first post of this issue as example, we can notice the python version was changed:
```
...
-defaults::python-3.5.2-0
...
+conda-forge::python-3.6.3-0
...
```
Suppose our conda behaves the same, then in `/opt/conda/bin/` , there should be (at least) two versions of python. And `/opt/conda/bin/python` should be a symbolic link:
```
python -> python3.6
```
Where python3.6 is the new python that cannot import stuff from `conda.cli`. But if python3.5 (original version) is specified then conda should work ( like `$ /opt/conda/bin/python3.5 conda`). However, specifying older python doesn't allow us to do anything with the environment because at some point another python core is started and this time the shell is still using the newer python. So what I did was relinking  `/opt/conda/bin/python` to the older python:
```
# execute as root in /opt/conda/bin/
unlink python
ln -s python3.5 python
```

Then conda started functioning as usual. 

I am maintaining a server for research on which I don't know how conda was installed ( the person who installed conda on this machine made the change that broke conda on Friday. He never works at weekends. ). I hope my solution could help somebody else who doesn't want to reinstall conda.

**Comment by LuooChen** [comment]
Here it's the solution for avoid reinstall the conda, that works for me.
[Answer by cel](https://stackoverflow.com/questions/61153488/no-module-named-conda-after-conda-update#)
