### ISSUE TITLE
Illegal Instruction: 4 with many python packages

### ISSUE THREAD

**Issue by lucashusted** [conda/conda#9678]
Hello,

Due to some change in `conda`, my environment is broken and I'm not sure where it started. I suspect it is a compatability issue with older macbook-pro models. I get the following error, when I try to import `pandas` or `numpy` in python:

```
Illegal instruction: 4
```
which just dumps me right out of python.

I am using  A Mid-2010 Macbook Pro it has the following OS installed:
```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G10021
```

In order to reproduce the result in the most basic way possible and illustrate that this is an issue for `conda` in this particular OS, I installed just the base `miniconda` and the only thing I have installed is `conda install pandas=0.25`.

As a result, my environment is simply the following:
```
#
# Name                    Version                   Build  Channel
asn1crypto                1.2.0                    py37_0  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py37_0  
cffi                      1.13.0           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
conda                     4.8.2                    py37_0  
conda-package-handling    1.6.0            py37h1de35cc_0  
cryptography              2.8              py37ha12b0ac_0  
idna                      2.8                      py37_0  
intel-openmp              2020.0                      166  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.0.15           py37h5e564d8_0  
mkl_random                1.1.0            py37ha771720_0  
ncurses                   6.1                  h0a44026_1  
numpy                     1.18.1           py37h7241aed_0  
numpy-base                1.18.1           py37h6575580_1  
openssl                   1.1.1d               h1de35cc_4  
pandas                    0.25.3           py37h0a44026_0  
pip                       19.3.1                   py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pyopenssl                 19.0.0                   py37_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.4                h359304d_1  
python-dateutil           2.8.1                      py_0  
python.app                2                        py37_9  
pytz                      2019.3                     py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.22.0                   py37_0  
ruamel_yaml               0.15.46          py37h1de35cc_0  
setuptools                41.4.0                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.30.0               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
tqdm                      4.36.1                     py_0  
urllib3                   1.24.2                   py37_0  
wheel                     0.33.6                   py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by lucashusted** [comment]
So, just to troubleshoot and narrow the issue, I ran the following:
```
conda install mkl=2018.0.3
```
Since it seemed like `mkl` was my issue before (had some stuff pop up about it before. Now I can successfully import numpy and pandas without getting dumped, but my version of numpy is very old. Here is the new environment, which works. Would be great to figure out what package is causing the issue:

```
# Name                    Version                   Build  Channel
asn1crypto                1.2.0                    py37_0  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py37_0  
cffi                      1.13.0           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
conda                     4.8.2                    py37_0  
conda-package-handling    1.6.0            py37h1de35cc_0  
cryptography              2.8              py37ha12b0ac_0  
idna                      2.8                      py37_0  
intel-openmp              2020.0                      166  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py37hb8a8100_0  
mkl_random                1.0.1            py37h5d10147_1  
ncurses                   6.1                  h0a44026_1  
numpy                     1.15.4           py37h6a91979_0  
numpy-base                1.15.4           py37h8a80b8c_0  
openssl                   1.1.1d               h1de35cc_4  
pandas                    0.25.3           py37h0a44026_0  
pip                       19.3.1                   py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pyopenssl                 19.0.0                   py37_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.4                h359304d_1  
python-dateutil           2.8.1                      py_0  
python.app                2                        py37_9  
pytz                      2019.3                     py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.22.0                   py37_0  
ruamel_yaml               0.15.46          py37h1de35cc_0  
setuptools                41.4.0                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.30.0               ha441bb4_0  
tbb                       2020.0               h04f5b5a_0  
tbb4py                    2020.0           py37h04f5b5a_0  
tk                        8.6.8                ha441bb4_0  
tqdm                      4.36.1                     py_0  
urllib3                   1.24.2                   py37_0  
wheel                     0.33.6                   py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by wenzao** [comment]
I have the same problem with my newly updated `conda` environment on my Mac. 

> $ ipython
> Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import numpy                                                            
> Illegal instruction: 4

> $ ipython
> Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import matplotlib.pyplot                                                
> Illegal instruction: 4

**Comment by cbrnr** [comment]
Same problem here on my MacBook Pro Mid-2010. I installed `miniconda` and then `numpy`, and I get the illegal instruction error as soon as I `import numpy`. Using the package `nomkl` (which replaces MKL with OpenBLAS) has no effect either. Could it be that all conda packages are compiled with some sort of CPU flag enabled (such as e.g. AVX, which my MacBook Pro CPU doesn't have)?

Note that `pip install numpy` works.

**Comment by cbrnr** [comment]
Also, if it turns out that the issue is indeed missing AVX support this would mean that Anaconda now requires Macs at least Early-2011 or later (https://en.wikipedia.org/wiki/List_of_Macintosh_models_grouped_by_CPU_type and https://en.wikipedia.org/wiki/MacBook_Pro#Technical_specifications_2). Which is why Mid-2010 doesn't work of course (bummer).

**Comment by cbrnr** [comment]
FYI, installing everything from `conda-forge` works fine!

**Comment by lucashusted** [comment]
I can confirm that this worked for me as well. However, updating `numpy` through `conda-forge` downgraded `spyder` for some reason for me, and then upgrading `spyder` and attempting to run it caused an Import Error with 
```
ImportError: dlopen(/Users/lucas/opt/miniconda3/lib/python3.7/site-packages/PyQt5/QtWebKitWidgets.so, 2): Library not loaded: @rpath/libQt5WebKitWidgets.5.dylib
  Referenced from: /Users/lucas/opt/miniconda3/lib/python3.7/site-packages/PyQt5/QtWebKitWidgets.so
  Reason: image not found
```

**Comment by rhstanton** [comment]
I've also encountered this behavior on my work Mac Pro, which runs macOS High Sierra (and which I can't upgrade due to my video adapter), but everything works fine on my home machine and on my MacBook, both of which run Catalina. Could it be OS-version related, rather than hardware?

**Comment by cbrnr** [comment]
Re the `ImportError`, this is likely unrelated - did you create a new environment before installing everything via `conda-forge`? If not, mixing channels might cause all sorts of problems, including the one you encountered.

I'm pretty sure the illegal instruction error is not caused by the OS version - I have Catalina and get this error on my MacBook Pro 2010 (mid-2010). Can you share the model identifiers for your three machines?

**Comment by lucashusted** [comment]
Hi Clemens, for the sake of nailing this, are you sure you are using Catalina on the MB Pro mid-2010? I have this same computer, and I use High Sierra because Catalina is not supported for this hardware. Best, Lucas

**Comment by cbrnr** [comment]
Yep, I use a patched version.

**Comment by rhstanton** [comment]
Sorry,  I was only talking about the illegal instruction.

The machine that displays the problem is my office Mac Pro, Mid-2012, running High Sierra.

The two machines that work fine:

Home Mac Pro: Late 2013
MacBook Pro: 15" 2016

Both of these are running Catalina.

**Comment by rhstanton** [comment]
A further quick follow-up: My High Sierra machine seems to run fine with a fresh Anaconda installation. Problems start as soon as I run "conda update anaconda"

**Comment by cbrnr** [comment]
The Mac Pro Mid-2012 does not support AVX so this would corroborate my theory. But you can check yourself if you run `sysctl -a | grep machdep.cpu.features` and the resulting list doesn't contain `AVX` (https://apple.stackexchange.com/a/360963/257107).

The two machines that work fine both support AVX.

The fact that a fresh install works could mean that Anaconda introduced this change in an update. Interesting.

**Comment by mingwandroid** [comment]
> Yep, I use a patched version.

Unless you can guarantee and prove to me that these patches are harmless, we won't be investigating making anything work on such a patched (hacked!) machine.

As a fellow owner of a classic mac pro, you have my sympathy though.

I'm setting it up again to investigate this, but I don't plan to go beyond macOS 10.14.6 as that's all Apple supports.

**Comment by mingwandroid** [comment]
The issue is with MKL though, and for that we need to talk to Intel.

**Comment by cbrnr** [comment]
@mingwandroid of course I can't guarantee anything, but other people here have been reporting the same issue with older (supported) macOS versions.

Also, it's not an MKL issue because the problem persists after `conda install nomkl`.

**Comment by jjhelmus** [comment]
@cbrnr Do imports from the standard library work, for example `import sqlite3`?  How about other extensions modules like `psutil`?  This should answer if the is with something in the NumPy stack or something in Python.

**Comment by rhstanton** [comment]
I just tried importing various modules on my work machine:

pandas fails
matplotlib fails
numpy fails

sqlite3 succeeds
psutil succeeds

**Comment by cbrnr** [comment]
I can confirm that the problematic package seems to be `numpy`; packages that depend on `numpy` fail to import, whereas other packages not requiring `numpy` work fine.

**Comment by mingwandroid** [comment]
Great. Thanks for the help @cbrnr. Looking into it soon (if I get my cmp reinstalled ok that is)

**Comment by jarpepe** [comment]
Hello, 
I installed a new version of Anaconda3 in my MacBook Mid 2010, using High Sierra version 10.13.6. I uninstalled a previous version of Anaconda3. Something went wrong with the installation because when I tried to import matplotlib, numpy, or pandas, I got the annoying illegal instruction:  4. After trying to figure out what the problem was (before I found you), I uninstalled the Anaconda3 version that I had (2020 02) and reinstalled a previous Anaconda3 version (2019 10). Now, it seems that there is no problem when I import the libraries aforementioned. But when I run a command like help("modules") from a Jupyter notebook to list the libraries I can use with python, I got this:

-------------

Please wait a moment while I gather a list of all available modules...

/opt/anaconda3/lib/python3.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
WARNING: AstropyDeprecationWarning: astropy.utils.compat.futures is now deprecated - use concurrent.futures instead [astropy.utils.compat.futures]
/opt/anaconda3/lib/python3.7/site-packages/nltk/twitter/__init__.py:22: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  "The twython library has not been installed. "
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: bzr
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: git
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: hg
DEBUG:pip._internal.vcs.versioncontrol:Registered VCS backend: svn
/opt/anaconda3/lib/python3.7/site-packages/skimage/novice/__init__.py:103: UserWarning: The `skimage.novice` module was deprecated in version 0.14. It will be removed in 0.16.
  warnings.warn("The `skimage.novice` module was deprecated in version 0.14. "
/opt/anaconda3/lib/python3.7/site-packages/skimage/viewer/utils/core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "
/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/opt/anaconda3/lib/python3.7/site-packages/qtawesome/iconic_font.py:301: UserWarning: You need to have a running QApplication to use QtAwesome!
  warnings.warn("You need to have a running "
Crypto              brain_gi            isympy              random
Cython              brain_hashlib       itertools           re
IPython             brain_http          itsdangerous        readline
OpenSSL             brain_io            jdcal               reprlib
PIL                 brain_mechanize     jedi                requests
PyQt5               brain_multiprocessing jinja2              resource
__future__          brain_namedtuple_enum joblib              rlcompleter
_abc                brain_nose          json                rmagic
_ast                brain_numpy_core_fromnumeric json5               rope
_asyncio            brain_numpy_core_function_base jsonschema          ruamel_yaml
_bisect             brain_numpy_core_multiarray jupyter             runpy
_blake2             brain_numpy_core_numeric jupyter_client      sched
_bootlocale         brain_numpy_core_numerictypes jupyter_console     scipy
_bz2                brain_numpy_core_umath jupyter_core        scripts
_cffi_backend       brain_numpy_ndarray jupyterlab          seaborn
_codecs             brain_numpy_random_mtrand jupyterlab_server   secrets
_codecs_cn          brain_numpy_utils   keyring             select
_codecs_hk          brain_pkg_resources keyword             selectors
_codecs_iso2022     brain_pytest        kiwisolver          send2trash
_codecs_jp          brain_qt            lazy_object_proxy   setuptools
_codecs_kr          brain_random        lib2to3             shelve
_codecs_tw          brain_re            libarchive          shlex
_collections        brain_six           libfuturize         shutil
_collections_abc    brain_ssl           libpasteurize       signal
_compat_pickle      brain_subprocess    lief                simplegeneric
_compression        brain_threading     linecache           singledispatch
_contextvars        brain_typing        llvmlite            singledispatch_helpers
_crypt              brain_uuid          locale              sip
_csv                bs4                 locket              sipconfig
_ctypes             builtins            logging             sipdistutils
_ctypes_test        bz2                 lxml                site
_curses             cProfile            lzma                six
_curses_panel       calendar            macpath             skimage
_datetime           certifi             mactypes            sklearn
_dbm                cffi                mailbox             smtpd
_decimal            cgi                 mailcap             smtplib
_dummy_thread       cgitb               markupsafe          sndhdr
_elementtree        chardet             marshal             snowballstemmer
_functools          chunk               math                socket
_hashlib            click               matplotlib          socketserver
_heapq              cloudpickle         mccabe              socks
_imp                clyent              mimetypes           sockshandler
_io                 cmath               mistune             sortedcollections
_json               cmd                 mkl                 sortedcontainers
_locale             code                mkl_fft             soupsieve
_lsprof             codecs              mkl_random          sphinx
_lzma               codeop              mmap                sphinxcontrib
_markupbase         collections         mock                spyder
_md5                colorama            modulefinder        spyder_breakpoints
_multibytecodec     colorsys            more_itertools      spyder_io_dcm
_multiprocessing    compileall          mpmath              spyder_io_hdf5
_opcode             concurrent          msgpack             spyder_kernels
_operator           conda               multipledispatch    spyder_profiler
_osx_support        conda_build         multiprocessing     spyder_pylint
_pickle             conda_env           navigator_updater   sqlalchemy
_posixsubprocess    conda_package_handling nbconvert           sqlite3
_py_abc             conda_verify        nbformat            sre_compile
_pydecimal          configparser        netrc               sre_constants
_pyio               contextlib          networkx            sre_parse
_pylief             contextlib2         nis                 ssl
_pyrsistent_version contextvars         nltk                stat
_pytest             copy                nntplib             statistics
_queue              copyreg             nose                statsmodels
_random             crypt               notebook            storemagic
_scproxy            cryptography        ntpath              string
_sha1               csv                 nturl2path          stringprep
_sha256             ctypes              numba               struct
_sha3               curl                numbers             subprocess
_sha512             curses              numexpr             sunau
_signal             cycler              numpy               symbol
_sitebuiltins       cython              numpydoc            sympy
_socket             cythonmagic         olefile             sympyprinting
_sqlite3            cytoolz             opcode              symtable
_sre                dask                openpyxl            sys
_ssl                dataclasses         operator            sysconfig
_stat               datetime            optparse            syslog
_string             dateutil            os                  tables
_strptime           dbm                 osax                tabnanny
_struct             decimal             packaging           tarfile
_symtable           decorator           pandas              tblib
_sysconfigdata_i686_conda_cos6_linux_gnu defusedxml          pandocfilters       telnetlib
_sysconfigdata_m_darwin_darwin difflib             parser              tempfile
_sysconfigdata_powerpc64le_conda_cos7_linux_gnu dis                 parso               terminado
_sysconfigdata_x86_64_apple_darwin13_4_0 distributed         partd               termios
_sysconfigdata_x86_64_conda_cos6_linux_gnu distutils           past                test
_testbuffer         doctest             path                test_data
_testcapi           docutils            pathlib             test_pycosat
_testimportmultiple dummy_threading     pathlib2            testpath
_testmultiphase     easy_install        patsy               tests
_thread             email               pdb                 textwrap
_threading_local    encodings           pep8                this
_tkinter            ensurepip           pexpect             threading
_tracemalloc        entrypoints         pickle              time
_uuid               enum                pickleshare         timeit
_warnings           errno               pickletools         tkinter
_weakref            et_xmlfile          pip                 tlz
_weakrefset         fastcache           pipes               token
_xxtestfuzz         faulthandler        pkg_resources       tokenize
_yaml               fcntl               pkginfo             toolz
abc                 filecmp             pkgutil             tornado
aem                 fileinput           platform            tqdm
aifc                filelock            plistlib            trace
alabaster           flask               pluggy              traceback
anaconda_navigator  fnmatch             ply                 tracemalloc
anaconda_project    formatter           poplib              traitlets
antigravity         fractions           posix               tty
appnope             fsspec              posixpath           turtle
appscript           ftplib              pprint              turtledemo
argparse            functools           profile             types
array               future              prometheus_client   typing
asn1crypto          gc                  prompt_toolkit      unicodecsv
ast                 genericpath         pstats              unicodedata
astroid             getopt              psutil              unittest
astropy             getpass             pty                 urllib
asynchat            gettext             ptyprocess          urllib3
asyncio             gevent              pvectorc            uu
asyncore            glob                pwd                 uuid
atexit              glob2               py                  venv
atomicwrites        gmpy2               py_compile          warnings
attr                greenlet            pyclbr              wave
audioop             grp                 pycodestyle         wcwidth
autoreload          gzip                pycosat             weakref
babel               h5py                pycparser           webbrowser
backcall            hashlib             pycurl              webencodings
backports           heapdict            pydoc               werkzeug
base64              heapq               pydoc_data          wheel
bdb                 hmac                pyexpat             widgetsnbextension
binascii            html                pyflakes            wrapt
binhex              html5lib            pygments            wsgiref
binstar_client      http                pylab               wurlitzer
bisect              idlelib             pylint              xdrlib
bitarray            idna                pyodbc              xlrd
bkcharts            imageio             pyparsing           xlsxwriter
bleach              imagesize           pyrsistent          xlwings
bokeh               imaplib             pytest              xlwt
boto                imghdr              pytest_arraydiff    xml
bottleneck          imp                 pytest_doctestplus  xmlrpc
brain_argparse      importlib           pytest_openfiles    xxlimited
brain_attrs         importlib_metadata  pytest_remotedata   xxsubtype
brain_builtin_inference inspect             pytz                yaml
brain_collections   io                  pywt                zict
brain_crypt         ipaddress           pyximport           zipapp
brain_curses        ipykernel           qtawesome           zipfile
brain_dataclasses   ipykernel_launcher  qtconsole           zipimport
brain_dateutil      ipython_genutils    qtpy                zipp
brain_fstrings      ipywidgets          queue               zlib
brain_functools     isort               quopri              zmq

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".

DEBUG:matplotlib.pyplot:Loaded backend module://ipykernel.pylab.backend_inline version unknown.
/opt/anaconda3/lib/python3.7/pkgutil.py:107: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  yield from walk_packages(path, info.name+'.', onerror)

-------------
I understand that that many things in this Anaconda3 version got deprecated. The thing is that in one of my projects I need to use PythonTex within LaTeX and when I run PythonTeX, one of the python code blocks that I have in my LaTeX file source (I have 3 blocks), the one that calls matplotlib does not work. 

I also noticed that the list of channels in my anaconda navigator is empty and when I tried to add defaults and/or conda-forge, they are not saved. So, something is also wrong with this Anaconda distribution I have. I'm hesitant about reinstalling the latest Anaconda3 version because of the illegal instruction that pops up when calling some libraries. I know that Clemens said that installing everything from conda-forge works fine, but I cannot use it. I would like to use the latest Anaconda3 version, but as I said it's not working properly, even with Jupyter notebooks. I don't know coding and I don't want to mess things up. Any help?

**Comment by lucashusted** [comment]
As I mentioned, and has been discussed here, the newest distro seems to work if you downgrade numpy to version 1.15. So if that works for you then I recommend it; it is working for me currently with many other packages installed. Let me know if it works for you.

**Comment by jarpepe** [comment]
Thanks Lucas for your response. I uninstalled the latest Anaconda version and I installed Miniconda. Then I went on installing packages I needed: numpy, sympy, matplotlib, pandas, jupyterlab, anaconda-navigator, xlrd, scipy. As expected, it did not work with the numpy version 1.18 that was first installed, so I downgraded it to 1.15 and then everything worked nicely when using Jupyter notebooks for my projects not related with the PyhonTeX package. As I mentioned previously, I have a LaTeX file that has python code in it. To compile it, I have to use PythonTex together with a LaTeX compiler. I have 4 blocks with code in Python. All the blocks except for the one that contains the matplotlib library show up in the final pdf file. So, I think the problem has to do with the PythonTeX package itself. At least I was able to get my Jupyter notebooks work again!

**Comment by rhstanton** [comment]
For what it’s worth, things seem to work fine up to numpy 1.17. It’s only when I install 1.18 that I get the “illegal instruction” error.

**Comment by jarpepe** [comment]
I installed numpy 1.17 and got the "illegal instruction" error. I realized that the version installed was 1.17.0 from the conda-forge channel. So I then installed the version 1.17.4 from the default channel and then it worked again. So, I learned that it matters the choice of the channel we use. By the way, do you know how to delete a channel in conda?

**Comment by pumpkinpieter** [comment]
I am having some similar problems to the above.  I am on Mac running Sierra 10.12.6.  I updated anaconda recently and whenever I attempt to run Spyder from conda I get an illegal instruction error: 

/Users/PV/opt/anaconda3/bin/pythonw: line 3:  7768 Illegal instruction: 4  /Users/PV/opt/anaconda3/python.app/Contents/MacOS/python "$@"

I can use conda to open jupyter notebook, then begin to use it, but if I attempt to import numpy the kernel dies immediately.  However, I can import os and use it just fine.  Matplotlib and pandas are also unable to import.

**Comment by jarpepe** [comment]
Did you try to downgrade numpy to version 1.17.4 or 1.15 as @rhstanton suggested? It worked for me. To avoid potential incompatibilities issues, make sure you use the usual channel you use to install/update packages. In my case is the defaults channel.

**Comment by kdpenner** [comment]
I have a mid-2010 MacBook Pro running Sierra.  numpy 1.18 works fine in one environment; in the base environment, I get the Illegal instruction.

```
(base) bash-3.2$ conda list numpy
# packages in environment at /Users/kpenner/anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.1           py37h7241aed_0  
numpy-base                1.18.1           py37h6575580_1  
numpydoc                  0.9.2                      py_0    conda-forge
(base) bash-3.2$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Illegal instruction: 4
(base) bash-3.2$ conda activate pygmt
(pygmt) bash-3.2$ conda list numpy
# packages in environment at /Users/kpenner/anaconda3/envs/pygmt:
#
# Name                    Version                   Build  Channel
numpy                     1.18.1           py36hdc5ca10_1    conda-forge
(pygmt) bash-3.2$ python
Python 3.6.10 | packaged by conda-forge | (default, Mar  5 2020, 09:56:10) 
[GCC Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> 
```

**Comment by cbrnr** [comment]
The version on conda-forge works even for the latest numpy. This is about the default channel.

**Comment by mingwandroid** [comment]
@cbrnr, Indeed. @kdpenner, please check the channels and you'll see that the working one comes from conda-forge and the broken one from defaults.

This issue is filed in the wrong repository and should be at anaconda-issues or else at AnacondaRecipes/numpy-feedstock. I'm looking into it though.

**Comment by jarpepe** [comment]
Just wanted to add that everything seems to work fine for packages downloaded via the defaults channel until version numpy=1.17.4 for both python 3.7.6 and python 3.6.10. The problem shows up as soon as I try to upgrade numpy to version 1.18. I tried it by using both defaults and conda-forge channels and it didn't work. 

(base) pepe-macbookpro:~ jaruiz$ python --version
Python 3.7.6
(base) pepe-macbookpro:~ jaruiz$ conda list numpy
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.17.4           py37h890c691_0  
numpy-base                1.17.4           py37h6575580_0  
(base) pepe-macbookpro:~ jaruiz$ python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> 

(base) pepe-macbookpro:~ jaruiz$ conda activate py36
(py36) pepe-macbookpro:~ jaruiz$ conda list numpy
# packages in environment at /opt/miniconda3/envs/py36:
#
# Name                    Version                   Build  Channel
numpy                     1.17.4           py36h890c691_0  
numpy-base                1.17.4           py36h6575580_0  
(py36) pepe-macbookpro:~ jaruiz$ python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>>

**Comment by jarpepe** [comment]
Just wanted to add that everything seems to work fine for packages downloaded via the defaults channel until version numpy=1.17.4 for both python 3.7.6 and python 3.6.10. The problem shows up as soon as I try to upgrade numpy to version 1.18. I tried it by using both defaults and conda-forge channels and it didn't work.

```
base) pepe-macbookpro:~ jaruiz$ python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> exit()

(base) pepe-macbookpro:~ jaruiz$ conda activate py36
(py36) pepe-macbookpro:~ jaruiz$ conda list numpy
# packages in environment at /opt/miniconda3/envs/py36:
#
# Name                    Version                   Build  Channel
numpy                     1.17.4           py36h890c691_0  
numpy-base                1.17.4           py36h6575580_0  
(py36) pepe-macbookpro:~ jaruiz$ python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> exit()
```

**Comment by jarpepe** [comment]
Just wanted to add that everything seems to work fine for packages downloaded via the defaults channel until version numpy=1.17.4 for both python 3.7.6 and python 3.6.10. The problem shows up as soon as I try to upgrade numpy to version 1.18. I tried it by using both defaults and conda-forge channels and it didn't work.

```
base) pepe-macbookpro:~ jaruiz$ python --version
Python 3.7.6
(base) pepe-macbookpro:~ jaruiz$ conda list numpy
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.17.4           py37h890c691_0  
numpy-base                1.17.4           py37h6575580_0 

base) pepe-macbookpro:~ jaruiz$ python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> exit()

(base) pepe-macbookpro:~ jaruiz$ conda activate py36
(py36) pepe-macbookpro:~ jaruiz$ conda list numpy
# packages in environment at /opt/miniconda3/envs/py36:
#
# Name                    Version                   Build  Channel
numpy                     1.17.4           py36h890c691_0  
numpy-base                1.17.4           py36h6575580_0  
(py36) pepe-macbookpro:~ jaruiz$ python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> exit()
```

**Comment by pumpkinpieter** [comment]
Hi,

I attempted to downgrade to numpy 1.17.4 using the command conda install
numpy=1.17.4.  After waiting 4 hours of conda examining conflicts with
dependencies, it basically said I wasn't allowed to do it.  How did you do
the downgrade?

**Comment by cbrnr** [comment]
@pumpkinpieter try to install it in a new env.

**Comment by pumpkinpieter** [comment]
Thank you.  Just did that and it works!  In the new environment installing
numpy version 1.17.4 allows everything else (spyder, matplotlib, git,
gitpython, and a few others) to work.  Does anyone understand what the
issue is underlying this?

Pieter

**Comment by cbrnr** [comment]
@mingwandroid I created a new issue here: https://github.com/AnacondaRecipes/numpy-feedstock/issues/20

**Comment by cbrnr** [comment]
@pumpkinpieter we don't know what the issue is, currently my best bet is that numpy 1.18 was compiled with flags that enable certain CPU features (such as AVX) that are not present on older CPUs.

**Comment by mingwandroid** [comment]
Just create a new environment for each version or package set you wish to
test. Conda will attempt to tell you what's conflicting but everyone should
*always* prefer new environments for each task, workflow or experiment,
it's so much faster and comes with much less risk.

**Comment by ChristinaZhao** [comment]
@cbrnr I was having the same issue with my Mac computer and I installed the previous version of anaconda, and it works. However, when I try to install mne python by creating the mne environment and use the conda-forge channel, it fails the installation on mayavi. I then took out all the lines for pip, it manages to create the environment, but now it has the same issues as before (i.e. illegal instruction). Any pointers?

**Comment by pumpkinpieter** [comment]
Using current version of anaconda on Mac running High Sierra 10.13.6 I was
able to get everything working by:

1. Creating a new environment in Anaconda

2. Downgrading my version of numpy as in the comments above to 1.17.4.

After this, everything was working in the new environment.

**Comment by mingwandroid** [comment]
This should be fixed now. We built new macOS compilers and it seems numpy has been rebuilt with those. The build number was *not* bumped for numpy it seems though so conda reports this as a downgrade!

Works on my computer at least! I tested from my local install and also updating anaconda 2020.02 via:

```
conda install anaconda=custom
conda update --all
```

Please let me know if this works for y'all. There still are these dodgy builds around but I think conda will ignore them, or else we will come up with something to avoid them being selected for people without AVX CPUs (via virtual packages).

Cheers!

**Comment by cbrnr** [comment]
Thanks a lot @mingwandroid! The new package works on my old Mac! Great work! 🎉

**Comment by nakayama-muimu** [comment]
My iMac(late 2009) with High Sierra 10.13.6 had the same issue so I've been using numpy 1.17.4.
But now, after this update, it works fine! Thanks a lot!
