### ISSUE TITLE
Support `source conda activate env`

### ISSUE THREAD

**Issue by adrinjalali** [conda/conda#9709]
`conda` sets many environment variables, which are necessary for the environments to work they're expected to work. For instance, if the user has installed compilers in their environment, then the `conda activate env` should set the environment variables such as `CC` to the right path, which is different than the default system compiler.

That requirement can be satisfied with either a shell function (which is the status quo), or through invoking `source`. Note that it cannot be a standalone shell script (not invoked using `source`) since it'll be in its own isolated environment and wont be able to set those environment variables of the parent shell in a clean way.

#7980 is an example of a use-case for activating an environment w/o having the shell function. With that in mind, it would be nice to enable users to activate through:

    source conda activate env

**Comment by pzwang** [comment]
A few questions:

  1. Is "activation from within a shell script" the only (or primary) driver for this change?  Are there other (perhaps adjacent) needs which are also addressed by supporting `source conda ...`?

  2. How important is it for us to provide similar/congruent mechanisms across all platforms?  Shells?  If this is important, let's please enumerate the other environments and their idiosyncrasies.

  3. This really messes up the (maybe silly?) convenience of being able to cut-n-paste shell command history into a batch/shell script.  The user has to know to put `source` in front of all `conda` commands, which honestly feels a bit... off.  (Even though I understand the rationale).  As I understand it, the primary desire is to properly set environment variables in the *current* shell -- is this the only need?  If so, might we be able to accomplish this task in a more idiomatic way for shell scripting, that is outside of this `source conda activate` mechanism?

**Comment by adrinjalali** [comment]
>  1. Is "activation from within a shell script" the only (or primary) driver for this change?  Are there other (perhaps adjacent) needs which are also addressed by supporting `source conda ...`?

Other than [probably very subjective] preference, it's been only problematic working with shell scripts at least for me. I do remember spending at least half a day trying to fix a CI script issue caused by this. 
 
>  3. This really messes up the (maybe silly?) convenience of being able to cut-n-paste shell command history into a batch/shell script.  The user has to know to put `source` in front of all `conda` commands, which honestly feels a bit... off.  (Even though I understand the rationale). 

I agree. This argument to me is one in favor of having the `source conda activate env` as the default usage and not `conda activate env`.

> As I understand it, the primary desire is to properly set environment variables in the _current_ shell -- is this the only need?  If so, might we be able to accomplish this task in a more idiomatic way for shell scripting, that is outside of this `source conda activate` mechanism?

I also had this reaction/thought at first. But it appears to be challenging I suppose.

**Comment by mingwandroid** [comment]
From a chat with @jbednar:
I think conda activate makes a whole lot of sense, we need to make conda robust. My main worry is that conda is different for different people (shell script vs a python script) and that hurts us because when people say "I ran conda" I don't actually know what they mean!

From a chat with @kalefranz:
For conda to behave correctly the necessary conda entr{y/ies} for the sys_python must be prefixed onto PATH. This must happen independently of all other considerations about which env is going to be used or whatever. Simply, if we want the right DSOs to be found, we need to force the OS loader to look in the correct folders in the correct order.

That is an immutable fact, that Unix needs 1 path should, for the purposes of uniformity and reduced code hackiness be ignored here (and actually, if we had to support some poor clibrary lib ucLibc then there could end up being a need to mutliple folders since the RPATH_ORIGIN feature is/was missing there, Android/bionic also had poor DSO skills traditionally).

It is still the case _on Unix_ that if we have python 2 on our PATH and we try to run conda from a python 3, we can get in trouble, depending on details as such how the script/shebang has been written).

I really want to put to bed the idea that this is somehow "Windows" only, and we can say that even more with the excellent unification of what conda is and how to interact with it that's been done so far (but I'm keen to see pushed further so I can get on with other work one day instead of the ground-hog day that is dealing with `conda activate` - and now `conda run` - issues, both user bug reports).

So, axiom 1 is: To run conda successfully, the base env's path entries must get added to the front of PATH before the executable gets started (as that is when DSOs get loaded)

It *is* the root source of our pain here.

Inside conda's very early init code, knowing that I've been called from the correct thing (the conda function) is very important because then I can assume that the steps I think it will have taken actually have been taken, so I can undo them safely for subsequent subprocess calls. In this case, the sys_prefix path entries must be removed from the front of os.environ['PATH'] en-masse (it is more nuanced than this but for the sake of discussion we can say this).

So, my idea situation here is to have one door to conda (ok, per shell). To do that let's hide the other doors in $CONDA_PREFIX/libexec, behind deprecation-warning proxy scripts, through renaming conda.exe to conda_impl.exe and conda-script.py to conda_impl-script.py.

This can all be achieved. I've spent too long sidestepping the way things are in this area!

I also think it can be achieved with minimal collateral damage, far less than many changes we've made to conda over the years.

**Comment by mingwandroid** [comment]
FWIW, on providing support for `source conda activate`, if it can be done cleanly (and I think it can) then sure, I have no problem with it, even if I think it's a bit anti-conda :-)

**Comment by deeplook** [comment]
A bit late to comment on this, but as I feel this littly thingy might have kicked this discussion off, I feel like I should: https://github.com/deeplook/mcinstall.

There I'm trying to provide a "miniconda installer" for colleagues who know about pip but have never seen the need for conda so far (until they have to use a complex environment and before going docker...). Having it cross-platform is a must, because else they could just use the available binaries. And it also has to play nicely in CI/CD pipelines. So this is my still pretty fresh attempt at it.

I realize that the activation idea in conda is a non-trivial problem to solve in fundamentally different ways, but in my case I would like to use the installed conda binary as much as possible without any shell activation. I first thought of using a config file instead of setting env. vars. but I kind of know the disadvantages. Apparently the existing activation works quite differently on Windows (not my platform) and any solution for making even conda/pip/python _only_ work nicely would be already helpful, I think.
