### ISSUE TITLE
Conda virtual packages

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#9818]
As of conda 4.8, we have virtual packages coded by

https://github.com/conda/conda/blob/16f67cf6ef06b00fe6c5d71afc1eda81534063a7/conda/core/index.py#L155-L172

The purpose of this ticket is to enumerate and document the current needs for hardware- and system-related virtual packages.

Some potential existing sources for virtual packages are

* https://github.com/conda/conda/blob/16f67cf6ef06b00fe6c5d71afc1eda81534063a7/conda/base/context.py#L721-L729
* https://github.com/conda/conda/blob/16f67cf6ef06b00fe6c5d71afc1eda81534063a7/conda/base/context.py#L732-L753
* https://github.com/conda/conda/blob/16f67cf6ef06b00fe6c5d71afc1eda81534063a7/conda/base/context.py#L756-L760
* https://github.com/conda/conda/blob/16f67cf6ef06b00fe6c5d71afc1eda81534063a7/conda/base/context.py#L756-L760
* https://github.com/conda/conda/blob/16f67cf6ef06b00fe6c5d71afc1eda81534063a7/conda/base/context.py#L763-L766

For my current system

![image](https://user-images.githubusercontent.com/1418419/78694188-ebe69580-78c1-11ea-9d39-54fe29063cb9.png)

The value for `context.cpu_flags` is

```
>>> context.cpu_flags
['1gbpage', 'acpi', 'aes', 'apic', 'avx1.0', 'avx2', 'bmi1', 'bmi2', 'clfsh', 'cmov', 'cx16', 
'cx8', 'de', 'ds', 'dscpl', 'dtes64', 'em64t', 'erms', 'est', 'f16c', 'fma', 'fpu', 'fpu_csds', 
'fxsr', 'htt', 'ibrs', 'invpcid', 'l1df', 'lahf', 'lzcnt', 'mca', 'mce', 'mdclear', 'mmx', 'mon', 
'movbe', 'msr', 'mtrr', 'osxsave', 'pae', 'pat', 'pbe', 'pcid', 'pclmulqdq', 'pdcm', 
'pge', 'popcnt', 'pse', 'pse36', 'rdrand', 'rdtscp', 'rdwrfsgs', 'seglim64', 'sep', 
'smep', 'smx', 'ss', 'ssbd', 'sse', 'sse2', 'sse3', 'sse4.1', 'sse4.2', 'ssse3', 'stibp', 
'syscall', 'tm', 'tm2', 'tpr', 'tsc', 'tsc_thread_offset', 'tsci', 'tsctmr', 'vme', 'vmx', 
'x2apic', 'xd', 'xsave']
```

**Comment by kalefranz** [comment]
Should we have a categorical hierarchy?

So instead of having

* `__osx`
* `__windows`
* `__glibc`
* `__musl-libc`

should we standardize to

* `__os-osx`
* `__os-windows`
* `__libc-glibc`
* `__libc-musl`

?

**Comment by kalefranz** [comment]
When addressing this issue, also address the location of `_supplement_index_with_system` causing a huge import stack with `conda info`.  Specifically

```
  File "/Users/shelly/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
```

See https://github.com/conda/conda/issues/9880

**Comment by chebee7i** [comment]
Hi @kalefranz I was wondering if it might be possible to use virtual packages as a way for people to declare to conda that some package X is available but without actually having conda install the package.  The idea here would be that downstream packages are installed consistently as if this version of X were installed.

This comes up in scenarios where we cannot bring the world into conda. I mentioned this briefly in https://github.com/conda/conda-build/issues/4155 as well. Effectively, our environment is such that the vast majority of C++ stays in its own world. For Python, we are using conda, and when the two worlds intersect, it can be complicated, indeed, but realistically, it will never be an option to move everything under conda---and so we are trying to get what we can out of conda (which is quite a bit).

Some additional details: In some of these scenarios, we want consistency of package versions between the ecosystems. So for example, we want Python and C++ to both use the same underlying blosc library.  Since C++ is not in the conda world, it is made available via [modules](http://modules.sourceforge.net/).  It is very easy for us in Python to ensure that this is setup and available either before we activate a conda env or during activate.  What I'm looking for is a way to declare to the conda build system that this dependency (and only that one) has already been met and the risks/rewards for doing so are accepted.

I imagine this sort of scenario has come up in other contexts too?  Do you have any recommendations?  Maybe just a shim conda package that does nothing?
