### ISSUE TITLE
rolling back new package during conda update --all

### ISSUE THREAD

**Issue by rhaynes74** [conda/conda#9826]
Hi folks, relatively new to conda.  I upgraded scipy to 1.4.1 but now when I do a general update 

conda update --all

then it wants to roll back my scipy package

The following packages will be SUPERSEDED by a higher-priority channel:

  scipy               pkgs/main::scipy-1.4.1-py37hba666df_0 --> conda-forge::scipy-1.2.1-py37_blas_openblash486cb9f_0

How do avoid scipy being rolled back during a generate update?

**Comment by kalefranz** [comment]
`conda update --all` drops all version pinnings by definition, and conda finds the most up-to-date solution for you across the whole environment, given the channel configuration you've given it. So `update --all` often doesn't give you the results you expect, and sometimes downgrades packages you don't want to be downgraded.  If you _really_ want to run `update --all`, then just run a second `conda install scipy=1.4.1` command to snap back to that version of `scipy`.

**Comment by rhaynes74** [comment]
Thanks folks, is there a better way to update the packages installed without rolling back?

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

**Comment by kalefranz** [comment]
The problem is that sometimes certain packages have to be rolled back to be compatible with other packages being updated. Conda does the best it can, and updates the most packages that it can, but it doesn't know that the package _you_ really care about most in this situation is `scipy`. It looks like you've also reconfigured your channels, adding in `conda-forge`, and changing channel configurations can also alter solver results.
