### ISSUE TITLE
Installing from local channel with channel::package fails

### ISSUE THREAD

**Issue by davidbrochart** [conda/conda#9828]
## Current Behavior

Installing from a local channel and explicitly specifying the channel for a package fails.

### Steps to Reproduce

You can get the `channel_a` directory from https://github.com/QuantStack/mamba/tree/27f6d83cc98fa7f4481137668d703138ea55a917/test/channel_a.
```
$ conda install --override-channels -c ./test/channel_a channel_a::a
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: channel_a
  channel url: https://conda.anaconda.org/channel_a
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

## Expected Behavior

The channel URL should be `file:///path_to_channel/channel_a`, not `https://conda.anaconda.org/channel_a`.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : conda-dev
    active env location : /home/david/minimamba3/envs/conda-dev
            shell level : 2
       user config file : /home/david/.condarc
 populated config files : /home/david/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __glibc=0.1
       base environment : /home/david/minimamba3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/david/minimamba3/pkgs
                          /home/david/.conda/pkgs
       envs directories : /home/david/minimamba3/envs
                          /home/david/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.4 Linux/5.3.0-40-generic ubuntu/19.10 glibc/2.30
                UID:GID : 1000:1001
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/david/.condarc <==
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/david/minimamba3/envs/conda-dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1e               h516909a_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.4             h516909a_1002    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</p></details>

**Comment by kalefranz** [comment]
Any objection to using `-c file:///path_to_channel/channel_a` or just `file:///path_to_channel/channel_a::a` instead of a relative path? Channels have always had url scheme and channel location attached, unless we're falling back to `channel_alias`. I guess we could teach channel to infer `file://` and determine the absolute path for channel strings starting with `{'./', '.\\', '..', '~'}`, but I don't think we've considered that in the past, nor thought through the implications.

**Comment by kalefranz** [comment]
I guess we'd have to add in absolute paths and Windows UNC paths. But if we have UNC paths, then we also need to handle the `[drive_letter]:` paths. But then we'd have to decide whether the left side of the first colon split is a drive letter or a url scheme.

**Comment by davidbrochart** [comment]
But it is the combination of local path and explicit `channel::package` that fails, e.g. this fails:
```
conda install --override-channels -c file:///home/david/git/davidbrochart/mamba/test/channel_a channel_a::a
```
and this works:
```
conda install --override-channels -c file:///home/david/git/davidbrochart/mamba/test/channel_a a
```

**Comment by kalefranz** [comment]
Ah right, that first one just falls back to `channel_alias`.

```
conda install file:///home/david/git/davidbrochart/mamba/test/channel_a::a
```

should also work.

**Comment by davidbrochart** [comment]
No, same error.

**Comment by kalefranz** [comment]
Ok, I understand the issue now.

I was wrong with

```
conda install file:///home/david/git/davidbrochart/mamba/test/channel_a::a
```

actually should explicitly not work. Channels are broken up into locations and names. The channel location is allowed to move around, from server to server, without having any real affect on the environment. (For example, if you have a mirror of the `conda-forge` channel at `file:///var/mirrors/conda-forge`, then conda treats `https://conda.anaconda.org/conda-forge` and `file:///var/mirrors/conda-forge` as equivalent channels and expects them to have the same content.) The channel name is part of a package's identity. MatchSpec is conda's query language for packages. Each spec input in a `conda install` line gets parsed as MatchSpec. Doing `file:///home/test/channel_a::a` is in fact attempting to set the configuration for the location of `channel_a` while at the same time specifying package `a` should come from the channel named `channel_a`. Not going to work with the current code, and probably never going to work out well in general, because even if we did allow setting channel location through the MatchSpec mechanism, and you give conda something like 

```
conda install file:///dir1/channel_a::a file:///dir2/channel_a::b
```

then where's the location of `channel_a`?

So where we're at I think is that

```
> conda install --override-channels -c file:///home/test/channel_a a  # works
> conda install --override-channels -c file:///home/test/channel_a channel_a::a  # doesn't work, but should
```

and then as a corollary 

```
conda install --override-channels -c file:///dir1/channel_a -c file:///dir2/channel_a a
```

would need to recognize that you can only have one channel named `channel_a` (or more precisely the assumption is that both channels named `channel_a` are equivalent), and so by priority order the location of `channel_a` should be treated as `file:///dir1`. Probably also warn that multiple locations for `channel_a` were detected, and conda is moving forward with `file:///dir1` as the location.

Need to think through what kind of subtle issues this could (or already does) lead to.

That last example isn't so different from `conda install file:///dir1/channel_a::a file:///dir2/channel_a::b`, except we don't have the concept of a deterministic priority order for specs while we do for channel configuration.

**Comment by davidbrochart** [comment]
I see, it's not an easy problem. Thanks for the detailed explanation.

**Comment by kalefranz** [comment]
Ha "not an easy problem"  so often the case in this conda world where we're spanning multiple OSes, packaging ecosystems, etc. etc.

This issue for me does expose a real problem we need to resolve, which is illustrated by

```
conda install --override-channels -c file:///dir1/channel_a -c file:///dir2/channel_a a
```

from above.

**Comment by kalefranz** [comment]
The issue as originally filed I think is also valid now, after talking through the problem with you.

```
>>> from conda.models.channel import Channel
>>> vars(Channel("./test/channel_a"))
{'scheme': 'file', 'auth': None, 'location': '/Users/kfranz/continuum/conda/test', 'token': None, 'name': 'channel_a', 'platform': None, 'package_filename': None}
```

so our `Channel` class is already parsing `-c ./test/channel_a` exactly as you requested, and I think we've already handled all of the contingencies for path expansion I enumerated earlier. 

What we need to do is

1. have `-c ./test/channel_a` configure the location of `channel_a`, and
2. make sure that location is then used for `channel_a::a`.

```
conda install --override-channels -c ./test/channel_a channel_a::a
```

**Comment by pauldmccarthy** [comment]
I've recently run into what _might_ be the same issue, using conda 4.9.2, when working with internally hosted conda channels, accesed over HTTP(S), rather than via the file system.

 I am trying to use `conda env create -f env.yml` to create an environment. I originally tried putting the following into `env.yml`:

```
channels:
  - conda-forge
  - defaults
dependencies
  - numpy
  - http://localhost/my_test_channel::mypkg
```

which resulted in:

```
conda.exceptions.UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: main_channel
  channel url: https://conda.anaconda.org/main_channel
  error code: 404
```

After reading this discussion, I changed my `env.yml` to:

```
channels:
  - conda-forge
  - defaults
  - http://localhost/my_test_channel

dependencies:
  - conda-forge::numpy
  - my_test_channel::mypkg
```

but get the same error. Conda is pulling repodata from my local channel in the second scenario, but not the first. So I'm guessing this is still an open issue?

**Comment by wesleykendall** [comment]
@kalefranz to follow up on what @pauldmccarthy mentioned, I also receive the same issue on Conda 4.11.0 using a local file channel

I'm trying to explicitly specify my private channel for some of my dependencies in the environment.yml file.

Your most recent  comment at https://github.com/conda/conda/issues/9828#issuecomment-611723891 made it sound like this might be a bug that can be resolved. Mind updating if this is something that might be addressed for private Conda channels? thanks for your help
