### ISSUE TITLE
pandas version is different than listed in `conda list`

### ISSUE THREAD

**Issue by rpanai** [conda/conda#9927]
### Steps to Reproduce

```
(dashboards) baobob:~$ conda list | grep pandas
pandas                    1.0.3            py37h0da4684_0    conda-forge
(dashboards) baobob:~$ python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'0.25.0'
```

## Expected Behavior

I'd like to use the pandas version listed in `conda list`

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /home/baobob/.condarc
 populated config files : /home/baobob/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/conda  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/baobob/.conda/pkgs
       envs directories : /home/baobob/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-99-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/baobob/.condarc <==
channels:
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

** it's `conda-forge` for all of them.
</p></details>

**Comment by cjmartian** [comment]
Hello @rpanai it looks like this package was installed from conda-forge. I would encourage you to file a report in their issue tracker!
Here is where that might be found: https://github.com/conda-forge/pandas-feedstock

**Comment by rpanai** [comment]
> Hello @rpanai it looks like this package was installed from conda-forge. I would encourage you to file a report in their issue tracker!
> Here is where that might be found: https://github.com/conda-forge/pandas-feedstock

It's not a problem related to the channel but a conda environment problem. Using the console I get the right pandas version but using jupyter-lab this is not happening.

**Comment by cjmartian** [comment]
Apologies! From the steps to reproduce it looked as if the issue was that the installation of pandas from conda-forge was not reporting the same version from the python interpreter as it was from the output of `conda list` 

I have failed to reproduce that issue.

![image](https://user-images.githubusercontent.com/47338163/81741055-8a3abd80-9463-11ea-8527-4d510d2e58b4.png)


Could you provide the steps to reproduce the jupyter-lab issue that you are describing?

Thank you!

**Comment by jobirk** [comment]
In case somebody here is still interested or somebody else stumbles upon this problem:

I was able to fix it for me using the `-s` flag when running python. This tells python to ignore user-installed packages (the ones I installed globally with pip).
(Documentation: `-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE`)

I had the same problem as described above but found out that even after `conda activate myenv` python was still importing the pandas package located at `/home/airflow/.local/lib/python3.6/site-packages` instead of using the packages from `/opt/conda/envs/testenv/lib/python3.6/site-packages` as can be seen below.

```bash
(testenv) default@98c6a7ebee2d:/opt/airflow$ conda list | grep pandas
pandas                    1.0.0            py36hb3f55d8_0    conda-forge
(testenv) default@98c6a7ebee2d:/opt/airflow$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas; pandas.__version__; pandas.__file__
'1.1.5'
'/home/airflow/.local/lib/python3.6/site-packages/pandas/__init__.py'
>>>
(testenv) default@98c6a7ebee2d:/opt/airflow$ python -s
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas; pandas.__version__; pandas.__file__
'1.0.0'
'/opt/conda/envs/testenv/lib/python3.6/site-packages/pandas/__init__.py'
```
